---
permalink: a1k/install-cable.html 
sidebar: sidebar 
keywords: aff a1k, prepare installation 
summary: コントローラの管理ネットワークポートはスイッチに接続されます。HA インターコネクトポートとクラスタインターコネクトポートは、両方のコントローラでケーブル接続されます。コントローラモジュールは、注文した場合は外付けストレージに接続されています。 
---
= ハードウェアのケーブル接続- AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のストレージシステム構成に応じて、コントローラとシェルフをケーブル接続します。

.作業を開始する前に
ケーブル配線図の図矢印を参照して、ケーブルコネクタのプルタブの向きが正しいかどうかを確認します。

image::../media/drw_cable_pull_tab_direction_ieops-1699.svg[ケーブルプルタブの向きの例]

* コネクタを挿入すると、カチッという音がして所定の位置に収まります。カチッという音がしない場合は、コネクタを取り外し、ケーブルヘッドを裏返してやり直してください。
* 光ファイバをスイッチに接続する場合は、ポートにケーブル接続する前に、SFPをコントローラポートに挿入します。




== 手順 1 ：コントローラをネットワークに接続する

2ノードスイッチレスクラスタまたはスイッチクラスタとしてコントローラをネットワークにケーブル接続します。

.作業を開始する前に
ストレージシステムをスイッチに接続する方法については、ネットワーク管理者にお問い合わせください。

.このタスクについて
ここでは、一般的な設定について説明します。具体的なケーブル接続は、ご使用のストレージシステム用に注文したコンポーネントによって異なることに注意してください。設定およびスロットプライオリティの詳細については、を参照してください link:https://hwu.netapp.com["NetApp Hardware Universe の略"^]。

[role="tabbed-block"]
====
.オプション1：スイッチレスクラスタをケーブル接続する
--
スイッチレスクラスタをケーブル接続します。

.手順
. クラスタ/ HAインターコネクトケーブルを使用して、クラスタ/ HAインターコネクトポートe1aからe1aに、e7aからe7aにケーブル接続します。
+

NOTE: クラスタインターコネクトトラフィックとHAトラフィックは、同じ物理ポートを共有します。

+
.. コントローラAのポートe1aをコントローラBのポートe1aにケーブル接続します。
.. コントローラAのポートe7aをコントローラBのポートe1aにケーブル接続します。
+
*クラスタ/ HAインターコネクトケーブル*





image::../media/oie_cable_25Gb_Ethernet_SFP28_IEOPS-1069.svg[クラスタHAケーブル]

+image：：../media/drw_a1k_TNSC_cluster_cabling_ieops-1648.svg[2ノードスイッチレスクラスタのケーブル配線図、幅=500px]

+。イーサネットモジュールポートをホストネットワークにケーブル接続します。

+一般的なホストネットワークケーブル接続の例を次に示します。ご使用のシステム構成については、を参照してください link:https://hwu.netapp.com["NetApp Hardware Universe の略"^] 。

. 図に示すように、ポートe9aおよびe9bをイーサネットデータネットワークスイッチにケーブル接続します。
+

NOTE: クラスタトラフィックとHAトラフィックのシステムパフォーマンスを最大限にするためには、ホストネットワーク接続にポートe1bとe7bを使用しないことを推奨します。パフォーマンスを最大化するには、別のホストカードを使用します。

+
* 100GbEケーブル*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gbイーサネットケーブル]

+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[100Gbイーサネットネットワークへのケーブル接続]

. 10 / 25GbEホストネットワークスイッチをケーブル接続します。
+
* 10/25GbEホスト*

+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25Gbイーサネットケーブル]

+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[10 / 25Gbイーサネットネットワークへのケーブル接続]

+
.. 1000BASE-T RJ-45ケーブルを使用して、コントローラの管理（レンチ）ポートを管理ネットワークスイッチにケーブル接続します。
+
image::../media/oie_cable_rj45.svg[RJ-45ケーブル]

+
* 1000BASE-T RJ-45ケーブル*

+
image::../media/drw_a1k_management_connection_ieops-1651.svg[管理ネットワークへの接続]






IMPORTANT: まだ電源コードを接続しないでください。

--
.オプション2：スイッチクラスタをケーブル接続する
--
スイッチクラスタをケーブル接続します。

.手順
. 次のケーブル接続を行います。
+

NOTE: クラスタインターコネクトトラフィックとHAトラフィックは、同じ物理ポートを共有します。

+
.. コントローラAのポートe1aとコントローラBのポートe1aをクラスタネットワークスイッチAにケーブル接続します。
.. コントローラAのポートe7aとコントローラBのポートe7aをクラスタネットワークスイッチBにケーブル接続します。
+
* 100GbEケーブル*

+
image::../media/oie_cable100_gbe_qsfp28.svg[100Gbケーブル]

+
image::../media/drw_a1k_switched_cluster_cabling_ieops-1652.svg[クラスタネットワークへのクラスタ接続のケーブル接続]



. イーサネットモジュールポートをホストネットワークにケーブル接続します。
+
次に、一般的なホストネットワークのケーブル接続例を示します。ご使用のシステム構成については、を参照してください link:https://hwu.netapp.com["NetApp Hardware Universe の略"^] 。

+
.. 図に示すように、ポートe9aおよびe9bをイーサネットデータネットワークスイッチにケーブル接続します。
+

NOTE: クラスタトラフィックとHAトラフィックのシステムパフォーマンスを最大限にするためには、ホストネットワーク接続にポートe1bとe7bを使用しないことを推奨します。パフォーマンスを最大化するには、別のホストカードを使用します。

+
* 100GbEケーブル*

+
image::../media/oie_cable_sfp_gbe_copper.svg[100Gbイーサネットケーブル]

+
image::../media/drw_a1k_network_cabling1_ieops-1649.svg[100Gbイーサネットネットワークへのケーブル接続]

.. 10 / 25GbEホストネットワークスイッチをケーブル接続します。
+
* 4ポート、10/25GbEホスト*

+
image::../media/oie_cable_sfp_gbe_copper.svg[10/25Gbイーサネットケーブル]

+
image::../media/drw_a1k_network_cabling2_ieops-1650.svg[10 / 25Gbイーサネットネットワークへのケーブル接続]



. 1000BASE-T RJ-45ケーブルを使用して、コントローラの管理（レンチ）ポートを管理ネットワークスイッチにケーブル接続します。
+
image::../media/oie_cable_rj45.svg[RJ-45ケーブル]

+
* 1000BASE-T RJ-45ケーブル*

+
image::../media/drw_a1k_management_connection_ieops-1651.svg[管理ネットワークへの接続]




IMPORTANT: まだ電源コードを接続しないでください。

--
====


== 手順2：コントローラをシェルフにケーブル接続する

コントローラをシェルフにケーブル接続します。

ここでは、1台のシェルフと2台のシェルフにコントローラをケーブル接続する手順について説明します。最大4台のシェルフをコントローラに直接接続できます。

[role="tabbed-block"]
====
.オプション1：1台のNS224シェルフにケーブルを接続
--
各コントローラをNS224シェルフのNSMモジュールにケーブル接続します。図は、各コントローラからのケーブル接続を示しています。コントローラAのケーブル接続は青、コントローラBのケーブル接続は黄色です。

.手順
. コントローラAで、次の接続をケーブル接続します。
+
.. ポートe11aをNSM Aのポートe0aに接続します。
.. ポートe11bをポートNSM Bのポートe0bに接続します。
+
image:../media/drw_a1k_1shelf_cabling_a_ieops-1703.svg["コントローラAのe11aおよびe11bを1台のNS224シェルフに移行"]



. コントローラBで、次の接続をケーブル接続します。
+
.. ポートe11aをNSM Bのポートe0aに接続します。
.. ポートe11bをNSM Aのポートe0bに接続します。
+
image:../media/drw_a1k_1shelf_cabling_b_ieops-1704.svg["コントローラBのポートe11aおよびe11bを1台のNS224シェルフにケーブル接続"]





--
.オプション2：ケーブルで2台のNS224シェルフに接続
--
各コントローラを両方のNS224シェルフのNSMモジュールにケーブル接続します。図は、各コントローラからのケーブル接続を示しています。コントローラAのケーブル接続は青、コントローラBのケーブル接続は黄色です。

.手順
. コントローラAで、次の接続をケーブル接続します。
+
.. ポートe11aをシェルフ1のNSM Aのポートe0aに接続します。
.. ポートe11bをシェルフ2のNSM Bのポートe0bに接続します。
.. ポートe10aをシェルフ2のNSM Aのポートe0aに接続します。
.. ポートe10bをシェルフ1のNSM Aのポートe0bに接続します。
+
image:../media/drw_a1k_2shelf_cabling_a_ieops-1705.svg["コントロオラAノコントロオラ/シエルフカンノセツソク"]



. コントローラBで、次の接続をケーブル接続します。
+
.. ポートe11aをシェルフ1のNSM Bのポートe0aに接続します。
.. ポートe11bをシェルフ2のNSM Aのポートe0bに接続します。
.. ポートe10aをシェルフ2のNSM Bのポートe0aに接続します。
.. ポートe10bをシェルフ1のNSM Aのポートe0bに接続します。
+
image:../media/drw_a1k_2shelf_cabling_b_ieops-1706.svg["コントローラBのコントローラ/シェルフ間の接続"]





--
====