---
permalink: a1k/io-module-replace.html 
sidebar: sidebar 
keywords: aff a1k, replace a pcie card 
summary: PCIe カードを交換するには、カードからケーブルを外し、 SFP モジュールと QSFP モジュールをカードから取り外してから、ライザーを取り付け直し、 SFP モジュールと QSFP モジュールを取り付けてから、カードをケーブル接続する必要があります。 
---
= I/Oモジュールの交換- AFF A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害が発生したI/Oモジュールを交換するには、次の手順を実行します。

* この手順は、ストレージシステムでサポートされるすべてのバージョンのONTAPで使用できます。
* ストレージシステムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。




== 手順 1 ：障害ノードをシャットダウンします

次のいずれかのオプションを使用して、障害のあるコントローラをシャットダウンまたはテイクオーバーします。

[role="tabbed-block"]
====
.オプション 1 ：ほとんどのシステム
--
障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

.このタスクについて
ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。

.手順
. AutoSupportが有効になっている場合は、AutoSupport messageコマンドを呼び出してケースの自動作成を抑制します。 `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
次のAutoSupportコマンドは、ケースの自動作成を2時間停止します。 `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待機しています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
障害のあるコントローラを正常なコントローラから停止またはテイクオーバーします。 `storage failover takeover -ofnode _impaired_node_name_`

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
.オプション 2 ：コントローラが MetroCluster に搭載されている
--

NOTE: 2 ノード MetroCluster 構成のシステムでは、この手順を使用しないでください。

障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

* ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。
* MetroCluster 構成を使用している場合は、 MetroCluster 構成状態が構成済みで、ノードが有効かつ正常な状態であることを確認しておく必要があります（「 MetroCluster node show 」）。


.手順
. AutoSupportが有効になっている場合は、AutoSupportコマンドを呼び出してケースの自動作成を抑制します。 `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
次のAutoSupportコマンドは、ケースの自動作成を2時間停止します。 `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
障害のあるコントローラを正常なコントローラから停止またはテイクオーバーします。 `storage failover takeover -ofnode _impaired_node_name_`

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
====


== 手順2：障害が発生したI/Oモジュールを交換する

I/Oモジュールを交換するには、エンクロージャ内でI/Oモジュールの場所を確認し、特定の手順を実行します。

. 接地対策がまだの場合は、自身で適切に実施します。
. コントローラからPSUケーブルをPSUから抜きます。
+

NOTE: ストレージシステムにDC電源装置が搭載されている場合は、電源装置（PSU）から電源ケーブルブロックを外します。

. ターゲット I/O モジュールのケーブルをすべて取り外します。
. ケーブルマネジメントトレイ内部の両側にあるボタンを引いてケーブルマネジメントトレイを下に回転させ、トレイを下に回転させます。
+

NOTE: 次の図は、水平および垂直I/Oモジュールの取り外しを示しています。通常、取り外したI/Oモジュールは1つだけです。

+
image:../media/drw_a1k_io_remove_replace_ieops-1382.svg["I/Oモジュールの取り外し"]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
 a| 
I/Oカムラッチ

|===
+
元の場所がわかるように、ケーブルにラベルを付けておいてください。

. ターゲットI/Oモジュールをエンクロージャから取り外します。
+
.. ターゲットモジュールのカムボタンを押します。
+
カムボタンがエンクロージャから離れます。

.. カムラッチをできるだけ下に回転させます。水平モジュールの場合は、カムをモジュールからできるだけ離します。
.. カムレバーの開口部に指をかけ、モジュールをエンクロージャから引き出して、モジュールをエンクロージャから取り外します。
+
I/O モジュールが取り付けられていたスロットを記録しておいてください。



. I/O モジュールを脇へ置きます。
. 交換用I/Oモジュールをエンクロージャに取り付けます。
+
.. モジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. I/Oモジュールをケーブル接続します。
. PSUを再接続します。
. ケーブルマネジメントトレイを上に回転させて閉じます。




== 手順3：コントローラをリブートする

I/O モジュールを交換したら、コントローラモジュールをリブートする必要があります。


NOTE: 新しいI/Oモジュールが障害の発生したモジュールと同じモデルでない場合は、最初にBMCをリブートする必要があります。

.手順
. 交換用モジュールのモデルが古いモジュールと同じでない場合は、BMCをリブートします。
+
.. LOADERプロンプトで、advanced権限モードに切り替えます。_set privilege advanced_
.. BMCをリブートします。_sp reboot_


. LOADER プロンプトで、ノードをリブートします： bye _
+

NOTE: これにより、I/Oカードおよびその他のコンポーネントが再初期化され、ノードがリブートされます。

. ノードを通常動作に戻します。_storage failover giveback -ofnode impaired_node_name_
. 自動ギブバックが無効になっていた場合は、再度有効にします。_storage failover modify -node local -auto-giveback true_




== 手順 4 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
