---
permalink: a400/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff a400, restore and verify the system configuration, verify and set the ha state of the controller module, run system-level diagnostics 
summary: ハードウェアの交換が完了してメンテナンスモードでブートしたら、交換用コントローラの下位のシステム構成を確認し、必要に応じてシステムを再設定します。 
---
= システム構成をリストアおよび検証します - AFF A400
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの交換が完了してメンテナンスモードでブートしたら、交換用コントローラの下位のシステム構成を確認し、必要に応じてシステムを再設定します。



== 手順 1 ：コントローラを交換したあとにシステム時間を設定して確認します

[role="lead"]
交換用コントローラモジュールの日付と時刻は、 HA ペアの正常なコントローラモジュール、またはスタンドアロン構成の信頼できるタイムサーバに照らして確認する必要があります。日付と時刻が一致しない場合は、時刻の違いによるクライアントの停止を防ぐために、交換用コントローラモジュールで日付と時刻をリセットする必要があります。

これらの手順のコマンドを正しいシステムに適用することが重要です。

* replacement _node は、この手順で障害ノードと交換した新しいノードです。
* healthy_node は、 _replacement _node の HA パートナーです


.手順
. _replacement _node に LOADER プロンプトが表示されない場合は、システムを停止して LOADER プロンプトを表示します。
. 正常なノードで、システム時刻「日付」を確認します
+
日付と時刻は GMT で表示されます。

. LOADER プロンプトで、 _replacement node の日付と時刻を確認します。 'how date]
+
日付と時刻は GMT で表示されます。

. 必要に応じて、交換用ノードの日付を GMT で設定します。 'et date_mm/dd/yyyy_`
. 必要に応じて、交換用ノードの時刻を GMT で設定します。「 set time _hh ： mm ： ss_` 」
. LOADER プロンプトで、 _replacement _node の日付と時刻を確認します。 'how dat'
+
日付と時刻は GMT で表示されます。





== 手順 2 ：コントローラモジュールの HA 状態を確認して設定します

[role="lead"]
コントローラモジュールの「 HA 」状態を確認し、必要に応じてシステム構成に合わせて状態を更新する必要があります。

. 新しいコントローラモジュールのメンテナンスモードで ' すべてのコンポーネントが同じ HA 状態で表示されることを確認します
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたコントローラモジュールのシステム状態がシステム構成と一致しない場合は、コントローラモジュールの HA 状態を「 ha-config modify controller ha-state 」に設定します
+
hA-state には、次のいずれかの値を指定できます。

+
** 「 HA 」
** 「 mcc 」
** 「 mcc-2n 」
** 「 MCCIP 」
** 「 non-ha 」


. 表示されたコントローラモジュールのシステム状態がシステム構成と一致しない場合は、コントローラモジュールの HA 状態を「 ha-config modify controller ha-state 」に設定します
. 設定が変更されたことを確認します。「 ha-config show 」




== 手順 3 ：診断を実行します

[role="lead"]
システムのコンポーネントを交換したら、そのコンポーネントに対して診断テストを実行する必要があります。

診断を開始するには、システムに LOADER プロンプトが表示されている必要があります。

診断手順のコマンドは、すべてコンポーネントを交換するノードから実行します。

. 作業をするノードに LOADER プロンプトが表示されていない場合は、ノードをリブートします。「 system node halt -node node_name 」
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. LOADER プロンプトで、システムレベルの診断用に特別に設計されたドライバ「 boot_diags 」にアクセスします
. 表示されたメニューから「 * Scan System * （システムのスキャン）」を選択して、診断テストの実行を有効にします。
. 表示されたメニューから * Test system * を選択して、診断テストを実行します。
. 各種サブメニューからテストまたは一連のテストを選択します。
. 前述の手順の結果に応じて、次に進みます。
+
** テストに失敗した場合は、エラーを修正してからテストを再実行します。
** テストでエラーが報告されなかった場合は、メニューから Reboot を選択してシステムをリブートします。
+

NOTE: ブートプロセス中に、次のプロンプトが表示される場合があります。

+
*** システム ID が一致していないためにシステム ID の上書きを求める警告プロンプト。
*** HA 構成でメンテナンスモードに切り替えたときに表示される、正常なノードが停止したままであることの確認を求めるプロンプト。これらのプロンプトには「 y 」と入力できます。





