---
permalink: a70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the boot media 
summary: AFF A70またはAFF A90ストレージ システムのブート メディアを交換する前に、要件を確認してください。 
---
= 自動ブートメディアリカバリの要件 - AFF A70およびAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90ストレージ システムのブート メディアを交換する前に、クラスタ ポート機能、キー マネージャ構成、 ONTAPバージョンの互換性などの要件を確認してください。

自動ブート メディア リカバリ プロセスには、 ONTAP 9.17.1 以降が必要です。ストレージシステムが以前のバージョンのONTAPを実行している場合は、link:bootmedia-replace-workflow.html["手動ブート回復手順"] 。

次の要件を確認します。

* 障害が発生したブートメディアを、NetAppから受け取った交換用ブートメディアと交換する必要があります。
* クラスタポートは、自動ブートリカバリプロセス中に2つのコントローラ間の通信に使用されます。障害が発生したコントローラのクラスタポートが正常に動作していることを確認してください。
* OKM の場合、クラスター全体のパスフレーズとバックアップ データも必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* この手順で使用されるコントローラの用語を理解します。
+
** _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
** _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。




.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["コントローラをシャットダウン"]
