---
permalink: a70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: 障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシに交換します。 
---
= シャーシの交換準備- AFF A70およびAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシと交換する準備をします。



== 手順1：システムを特定して監視する

あとで参照できるように、コンソールセッションを開き、セッションログを保存しておき、障害のあるシャーシを特定するためにシステムの場所LEDを点灯する必要があります。

. シリアルコンソールポートに接続し、システムとのインターフェイスを確立して監視します。
. コントローラのロケーションLEDの場所を確認してオンにします。
+
.. ロケーションLEDの現在の状態を表示するには、コマンドを使用し `system controller location-led show`ます。
.. ロケーションLEDの状態を「オン」に変更します。
+
`system controller location-led modify -node _node1_ -state on`です。

+
ロケーションLEDは30分間点灯したままになります。







== 手順2：交換用コンポーネントを確認する

必要なコンポーネントを受け取ったことを確認し、パッケージから取り出して、パッケージを保存する必要があります。

. 梱包を開く前に、梱包ラベルを確認し、次のことを確認してください。
+
** コンポーネントのパーツ番号。
** パーツの説明。
** ボックス内の数量。


. 梱包から内容物を取り出し、梱包を使用して障害が発生したコンポーネントをNetAppに返送します。




== 手順3：ケーブルとコントローラモジュールにラベルを付け、自身でアースを取る

コントローラモジュールまたはシャーシからケーブルを取り外す前に、ケーブルとコントローラにラベルを付ける必要があります。

. ストレージシステムに接続されているすべてのケーブルにラベルを付けます。これは、この手順の後半でケーブルを再接続する際に役立ちます。
. コントローラモジュールにラベルを付けます。
. まだ適切な接地対策を行っていない場合は、自分で接地対策を行ってください。


.次の手順
AFF A70またはAFF A90シャーシハードウェアを交換する準備ができたら、を行う必要がありますlink:chassis-replace-shutdown.html["コントローラをシャットダウン"]。
