---
permalink: a70-90/chassis-replace-prepare.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: AFF A70またはAFF A90システムで障害のあるシャーシを交換する準備として、障害のあるシャーシを特定し、交換用コンポーネントを確認し、ケーブルとコントローラモジュールにラベルを付けます。 
---
= シャーシを交換する準備- AFF A70 and AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90システムで障害のあるシャーシを交換する準備として、障害のあるシャーシを特定し、交換用コンポーネントを確認し、ケーブルとコントローラモジュールにラベルを付けます。

.手順
. シリアルコンソールポートに接続し、システムとのインターフェイスを確立して監視します。
. コントローラーの位置 LED をオンにします。
+
.. 使用 `system controller location-led show`ロケーション LED の現在の状態を表示するコマンド。
.. ロケーション LED をオンにします。
+
`system controller location-led modify -node _node1_ -state on`

+
ロケーションLEDは30分間点灯したままになります。



. パッケージを開封する前に、パッケージのラベルを調べて、次の点を確認してください。
+
** 部品番号
** 部品の説明
** 箱の中の数量


. パッケージから内容物を取り出し、故障したコンポーネントをNetAppに返送するためにパッケージを保管してください。
. ストレージ システムに接続されているすべてのケーブルにラベルを付けます。これにより、この手順の後半で適切な再配線が確実に行われます。
. まだ接地していない場合は、自分自身を接地してください。


.次の手順
AFF A70またはAFF A90シャーシハードウェアを交換する準備ができたら、を行う必要がありますlink:chassis-replace-shutdown.html["コントローラをシャットダウン"]。
