---
permalink: a70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace the chassis 
summary: AFF A70またはAFF A90システムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、システムの他のすべてのコンポーネントが適切に動作していること、ONTAPのローカル管理者のクレデンシャル、正しい交換用シャーシ、および必要な工具があることを確認します。 
---
= シャーシの交換要件- AFF A70およびAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90システムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、システムの他のすべてのコンポーネントが適切に動作していること、ONTAPのローカル管理者のクレデンシャル、正しい交換用シャーシ、および必要な工具があることを確認します。

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。

次の要件を確認します。

* システムの他のすべてのコンポーネントが正常に機能していることを確認します。正常に機能していない場合は、に連絡してサポートを受けてください http://mysupport.netapp.com/["ネットアップサポート"^]
* ONTAPのローカル管理者のクレデンシャルがない場合は、そのクレデンシャルを取得します。
* 交換に必要な工具と機器が揃っていることを確認します。
* シャーシの交換手順は、システムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、NVMeドライブ、およびコントローラモジュールを新しいシャーシに移動することを前提としています。また、交換用シャーシはNetAppの新しいコンポーネントであることを前提としています。
* シャーシの交換手順はシステムの停止を伴います。2 ノードクラスタではサービスが完全に停止し、マルチノードクラスタでは部分的に停止します。


.次の手順
要件を確認した後、link:chassis-replace-prepare.html["シャーシを交換する準備"] 。
