---
permalink: a70-90/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: aff a70, aff a90, how to recable the system, reboot the system 
summary: AFF A70またはAFF A90システムが通常の運用を再開できるように、ストレージリソースの制御を交換用コントローラに戻します。 
---
= コントローラのギブバック- AFF A70とAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90システムが通常の運用を再開できるように、ストレージリソースの制御を交換用コントローラに戻します。返却手順は、システムで使用されている暗号化の種類（暗号化なしまたはオンボード キー マネージャー (OKM) 暗号化）によって異なります。

[role="tabbed-block"]
====
.暗号化なし
--
障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。

.手順
. Loaderプロンプトで、と入力し `boot_ontap`ます。
. コンソールメッセージが停止したら、<enter>キーを押します。
+
** _login_promptが表示されたら、このセクションの最後の次の手順に進みます。
** 「_Waiting for giveback_」と表示された場合は、<enter>キーを押してパートナーノードにログインし、このセクションの最後の次の手順に進みます。


. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。 `storage failover giveback -ofnode _impaired_node_name_`
. 自動ギブバックを無効にした場合は、再度有効にします。 `storage failover modify -node local -auto-giveback _true_`
. AutoSupportが有効になっている場合は、ケースの自動作成をリストアまたは抑制解除します。 `system node autosupport invoke -node * -type all -message MAINT=END`


--
.オンボード暗号化（OKM）
--
オンボード暗号化をリセットし、コントローラを通常動作に戻します。

.手順
. Loaderプロンプトで、と入力し `boot_ontap maint`ます。
. LoaderプロンプトからONTAPメニューを起動し `boot_ontap menu`、オプション10を選択します。
. OKMパスフレーズを入力します。
+

NOTE: パスフレーズの入力を2回求められます。

. プロンプトが表示されたら、バックアップキーのデータを入力します。
. ブートメニューで、「option for normal boot」と入力します `1`。
. 「_Waiting for giveback_」と表示されたら、<enter>キーを押します。
. パートナーノードにコンソールケーブルを接続し、としてログインします `admin`。
. CFOアグリゲート（ルートアグリゲート）のみをギブバックします。 `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** エラーが発生した場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。


. ギブバックレポートが完了してから5分待って、フェイルオーバーのステータスとギブバックのステータスを確認します（および `storage failover show-giveback`） `storage failover show`。
. キーの同期とステータスの確認を行います。
+
.. コンソールケーブルを交換用コントローラに戻します。
.. 欠落しているキーの同期： `security key-manager onboard sync`
+

NOTE: クラスタのOKMのクラスタ全体のパスフレーズを入力するように求められます。

.. キーのステータスを確認します。 `security key-manager key query -restored _false_`
+
適切に同期されている場合、出力には何の結果も表示されません。

+
出力に結果（システムの内部キーテーブルにないキーのキーID）が表示された場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。



. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。 `storage failover giveback -ofnode _impaired_node_name_`
. 自動ギブバックを無効にした場合は、再度有効にします。 `storage failover modify -node local -auto-giveback _true_`
. AutoSupportが有効になっている場合は、ケースの自動作成をリストアまたは抑制解除します。 `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.次の手順
ストレージリソースの所有権を交換用コントローラに戻したら、の手順を実行する必要がありlink:controller-replace-restore-system-rma.html["コントローラの交換後の処理"]ます。
