---
permalink: a70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff a70, aff a90, prerequisite, replace the controller module 
summary: AFF A70またはAFF A90システムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、正しい交換用シャーシの用意、システム構成のバックアップ、必要な工具やファームウェアへのアクセスが含まれます。 
---
= コントローラの交換要件- AFF A70とAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90システムのコントローラを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、適切な交換用コントローラの用意、システム構成のバックアップ、必要なツールやファームウェアへのアクセスが含まれます。

コントローラモジュールを交換するための要件を確認します。

* すべてのドライブシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールは、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* ブートデバイスはシステムの背面に取り付けられたシステム管理モジュールに配置されているため、コントローラモジュールの交換時にブートデバイスを移動する必要はありません。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。


* コントローラのコンソール出力を必ずテキストログファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。


