---
sidebar: sidebar 
permalink: a70-90/install-requirements.html 
keywords: a1a70-90k, install, setup, cautions 
summary: 必要な機器と、プラットフォームとシェルフの持ち上げに関する注意事項を確認します。 
---
= インストール要件- AFF A70およびAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70またはAFF A90のストレージシステムとストレージシェルフに必要な機器と、持ち上げに関する注意事項を確認します。



== 設置に必要な機器

AFF A70またはAFF A90ストレージシステムを設置するには、次の機器と工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* NS224ストレージシェルフIDを設定するためのペーパークリップまたはボールペン
* No.2 プラスドライバ




== 吊り上げ時の注意事項

AFF A70 / AFF A90ストレージシステムとNS224ストレージシェルフは重量があります。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== AFF A70およびAFF A90ストレージシステム

AFF A70ストレージ・システムまたはAFF A90ストレージ・システムの重量は'最大68.8 kg（151.68ポンド）になることがありますシステムを持ち上げるには、4人で作業するか、油圧リフトを使用します。

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90用]



=== NS224シェルフ

NS224ストレージシェルフの重量は最大30.29kg（66.78ポンド）です。ストレージシェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224の持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]


.次の手順
ハードウェア要件を確認したら、link:install-prepare.html["AFF A70またはAFF A90ストレージシステムを設置する準備"]
