---
permalink: a70-90/install-power-hardware.html 
sidebar: sidebar 
keywords: aff a70, a90, power controllers 
summary: 電源ケーブルを接続し、シェルフとコントローラの電源をオンにします。 
---
= ストレージ・システムの電源を入れる- AFF A70、AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ネットワークとシェルフのケーブルを接続したら、コントローラとその他のシェルフの電源をオンにすることができます。


NOTE: 外付けNS224シェルフはオプションです。



== 手順1：シェルフの電源をオンにしてシェルフIDを割り当てる

ONTAPストレージシステムでは、各NS224シェルフは一意のシェルフIDで識別されます。このIDにより、ストレージシステムの設定内でシェルフが区別されます。デフォルトでは、シェルフIDには通常「00」と「01」が割り当てられますが、ストレージシステム全体で一意になるように、これらのIDの調整が必要になる場合があります。


NOTE: コントローラシャーシのシェルフIDは「00」にハードコードされています。プラットフォームに接続されたNS224シェルフにはシェルフID「00」を使用しないでください。

.このタスクについて
* 有効なシェルフ ID は 00~99 です。
* シェルフIDを有効にするには、シェルフの電源を再投入する必要があります（両方の電源コードを取り外し、しばらく待ってから再度接続します）。


.手順
. シェルフの電源をオンにするには、まず電源コードをシェルフに接続し、電源コード固定クリップで所定の位置に固定してから、電源コードを別 々 の回路の電源に接続します。
+
シェルフを電源に接続すると、シェルフの電源が自動的にオンになり、ブートします。

. 前面プレートの後ろにあるシェルフIDボタンにアクセスするには、左側のエンドキャップを取り外します。
+
image:drw_a900_oie_change_ns224_shelf_id_ieops-836.svg["NS224のシェルフIDを変更（幅= 300px）"]

+
[cols="20%,80%"]
|===


 a| 
image:legend_icon_01.svg["番号1、幅= 20"]
 a| 
シェルフのエンドキャップ



 a| 
image:legend_icon_02.svg["番号2、幅= 20"]
 a| 
シェルフ前面プレート



 a| 
image:legend_icon_03.svg["番号3、幅= 20"]
 a| 
シェルフID番号



 a| 
image:legend_icon_04.svg["番号4、幅= 20"]
 a| 
シェルフIDアクセスボタン

|===
. シェルフ ID の最初の番号を変更します。
+
.. ペーパークリップまたは細いボールペンのまっすぐな端を小さな穴に挿入します。
.. デジタルディスプレイの 1 桁目の数字が点滅するまでボタンを押し続け、ボタンを放します。
+
点滅するまでに最大 15 秒かかる場合があります。これにより、シェルフ ID プログラミングモードがアクティブになります。

+

NOTE: ID の点滅に 15 秒以上かかる場合は、ボタンをもう一度押し続けてください。

.. 目的の番号になるまで、ボタンを押してから離します（ 0 ～ 9 ）。
+
各プレスおよびリリース時間は、 1 秒ほど短くすることができます。

+
1 桁目の数字は点滅し続けます。



. シェルフ ID の 2 番目の番号を変更します。
+
.. デジタルディスプレイの 2 桁目の数字が点滅するまで、ボタンを押し続けます。
+
数字が点滅するまでに最大 3 秒かかる場合があります。

+
デジタルディスプレイの 1 桁目の数字の点滅が停止します。

.. 目的の番号になるまで、ボタンを押してから離します（ 0 ～ 9 ）。
+
2 桁目の数字は点滅し続けます。



. 2 桁目の数字が点滅しなくなるまでボタンを押し続けて、目的の番号をロックしてプログラミングモードを終了します。
+
点滅が停止するまでに最大 3 秒かかる場合があります。

+
デジタルディスプレイの両方の番号が点滅し始め、約 5 秒後に ODP の黄色の LED が点灯して保留中のシェルフ ID がまだ有効になっていないことを警告します。

. シェルフIDを有効にするために、シェルフの電源を10秒以上再投入します。
+
.. シェルフの両方の電源装置から電源コードを抜きます。
.. 10 秒待ちます。
.. 電源コードをシェルフの電源装置に再度接続して、電源を再投入します。
+
電源コードが接続されるとすぐに、電源装置の電源がオンになります。LED が緑色に点灯します。



. 左側のエンドキャップを取り付けます。




== 手順2：コントローラの電源をオンにする

. コントローラに電源が投入されているときのブートシーケンスを監視できるように、ラップトップをシリアルコンソールポートに接続します。
+
.. ラップトップのシリアルコンソールポートを115、200ボー（N-8-1）に設定します。
+

NOTE: シリアルコンソールポートの設定手順については、ラップトップのオンラインヘルプを参照してください。

.. プラットフォームに付属のコンソールケーブルを使用して、ラップトップにコンソールケーブルを接続し、コントローラのシリアルコンソールポートを接続します。
.. ラップトップを管理サブネット上のスイッチに接続します。
+
image:drw_a1k_70-90_console_connection_ieops-1702.svg["コンソール接続"]

.. 管理サブネット上のTCP/IPアドレスを使用して、ラップトップに割り当てます。


. 電源コードをコントローラの電源装置に接続し、さらに別の回路の電源に接続します。
+
image:drw_affa1k_power_source_icon_ieops-1700.svg["一般的な電源接続図"]

+
** プラットフォームがブートを開始します。初回のブートには最大 8 分かかる場合があります。
** LEDが点滅し、ファンが起動します。これは、コントローラの電源がオンになっていることを示します。
** ファンは、最初に起動するときに大きな音がすることがあります。起動時にファンから大きな音がするのは正常です。


. 各電源装置の固定装置を使用して、電源ケーブルを固定します。

