---
permalink: a70-90/maintain-overview.html 
sidebar: sidebar 
keywords: aff a70 aff a90 maintenance, maintenance, repairing aff a70 aff a90, repairing a70 aff a90, replace a70 aff a90 components 
summary: AFF A70およびAFF A90ストレージシステムのハードウェアを保守して、長期的な信頼性と最適なパフォーマンスを確保します。ダウンタイムやデータ損失の防止に役立つため、障害のあるコンポーネントの交換などの定期的なメンテナンスタスクを実行します。 
---
= メンテナンス手順の概要- AFF A70およびAFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A70およびAFF A90ストレージシステムのハードウェアを保守して、長期的な信頼性と最適なパフォーマンスを確保します。ダウンタイムやデータ損失の防止に役立つため、障害のあるコンポーネントの交換などの定期的なメンテナンスタスクを実行します。

メンテナンス手順では、AFF A70システムとAFF A90システムがONTAP環境にストレージノードとしてすでに導入されていることを前提としています。



== システムコンホオネント

AFF A70およびAFF A90ストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["ブートメディア - 自動回復"]
 a| 
ブートメディアには、プライマリおよびセカンダリのONTAPイメージファイルセットが保存されています。ストレージシステムはこれを使用して、パートナーノードからイメージを起動し、適切なブートメニューオプションを自動的に実行して、交換用ブートメディアにブートイメージをインストールします。自動ブートメディアリカバリプロセスは、 ONTAP 9.17.1以降でのみサポートされています。ストレージシステムで以前のバージョンのONTAPを実行している場合は、 link:bootmedia-replace-workflow.html["手動ブート回復手順"] 。



 a| 
link:bootmedia-replace-workflow.html["ブートメディア - 手動リカバリ"]
 a| 
ブート メディアには、ストレージ システムが USB ドライブからイメージをブートし、パートナー ノードから構成を復元するために使用するONTAPイメージ ファイルのプライマリ セットとセカンダリ セットが保存されます。



 a| 
link:chassis-replace-workflow.html["シャーシ"]
 a| 
シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



 a| 
link:controller-replace-workflow.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAPオペレーティングシステムソフトウェアを実行します。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
デュアルインラインメモリモジュール（DIMM）は、コンピュータメモリの一種です。コントローラのマザーボードにシステムメモリを追加するために取り付けられます。



 a| 
link:drive-replace.html["ドライブ"]
 a| 
ドライブは、データに必要な物理ストレージを提供するデバイスです。



 a| 
link:fan-swap-out.html["ファン"]
 a| 
ファンがコントローラを冷却します。



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
NVRAM（Non-Volatile Random Access Memory）は、システムの電源が切れた場合にコントローラが転送中のデータを保護および保存できるようにするモジュールです。システムIDはNVRAMモジュールにあります。交換したコントローラは、交換用NVRAMモジュールの新しいシステムIDを引き継ぎます。



 a| 
link:nvdimm-battery-replace.html["NVハツテリ"]
 a| 
NVバッテリは、電力損失後に転送中のデータをフラッシュメモリにデステージしている間、NVRAMモジュールに電力を供給します。



 a| 
link:io-module-overview.html["I/O モジュール"]
 a| 
I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



 a| 
link:power-supply-replace.html["電源装置"]
 a| 
電源装置は、コントローラに冗長な電源を提供します。



 a| 
link:rtc-battery-replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。



 a| 
link:system-management-replace.html["システム管理モジュール"]
 a| 
システム管理モジュールは、コントローラまたはシステムのメンテナンスを目的として、コントローラとコンソールまたはラップトップ間のインターフェイスを提供します。システム管理モジュールにはブートメディアが格納され、システムシリアル番号（SSN）が格納されています。

|===