---
permalink: a70-90/nvram-replace.html 
sidebar: sidebar 
keywords: aff a70, aff a90, replace an nvdimm 
summary: NVRAM モジュールは、 NVRAM12 と DIMM 、 NVRAM モジュールあたり最大 2 つの NVMe SSD Flash Cache モジュール（ FlashCache またはキャッシングモジュール）で構成されます。 
---
= NVRAMの交換- AFF A70、AFF A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVRAMモジュールは、NVRAM12ハードウェアDIMMとフィールド交換可能DIMMで構成されています。障害が発生した NVRAM モジュールまたは NVRAM モジュール内の DIMM を交換できます。障害が発生したNVRAMモジュールを交換するには、シャーシからモジュールを取り外し、DIMMを交換用モジュールに移動して、交換用NVRAMモジュールをシャーシに取り付ける必要があります。

システムのその他のコンポーネントがすべて正常に動作している必要があります。正常に動作していない場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。



== 手順 1 ：障害のあるコントローラをシャットダウンします

次のいずれかのオプションを使用して、障害のあるコントローラをシャットダウンまたはテイクオーバーします。

[role="tabbed-block"]
====
.オプション 1 ：ほとんどのシステム
--
障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

.このタスクについて
* SANシステムを使用している場合は、障害コントローラのSCSIブレードのイベントメッセージを確認しておく必要があり  `cluster kernel-service show`ます）。コマンド（priv advancedモードから）を実行すると、 `cluster kernel-service show` ノード名、そのノードのクォーラムステータス、そのノードの可用性ステータス、およびそのノードの動作ステータスが表示されます。
+
各 SCSI ブレードプロセスは、クラスタ内の他のノードとクォーラムを構成している必要があります。交換を進める前に、すべての問題を解決しておく必要があります。

* ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。


.手順
. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。 `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
次のAutoSupport メッセージは、ケースの自動作成を2時間停止します。 `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
+

NOTE: 自動ギブバックを無効にしますか?_と表示されたら'y'を入力します

. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。「 storage failover takeover -ofnode impaired_node_name _

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
.オプション 2 ：コントローラが MetroCluster に搭載されている
--
障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

* ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。
* MetroCluster 構成を使用している場合は、 MetroCluster 構成状態が構成済みで、ノードが有効かつ正常な状態であることを確認しておく必要があります（「 MetroCluster node show 」）。


.手順
. AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT=number_OF_hours_downh
+
次の AutoSupport メッセージは、ケースの自動作成を 2 時間停止します。 cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。「 storage failover takeover -ofnode impaired_node_name _

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
====


== 手順 2 ： NVRAM モジュールを交換します

NVRAMモジュールを交換するには、シャーシのスロット4/5でモジュールの場所を確認し、特定の手順を実行します。

. シャーシの前面で、プラスのストッパーになるまで、親指で各ドライブをしっかりと押し込みます。これにより、ドライブがシャーシのミッドプレーンにしっかりと装着されます。
+
image::../media/drw_a800_drive_seated_IEOPS-960.svg[DRW A800ドライブがIEOPS 960に装着されました]

. シャーシの背面に移動します。接地対策がまだの場合は、自身で適切に実施します。
. 両方のPSUから電源コードを抜きます。
+

NOTE: システムにDC電源装置が搭載されている場合は、電源ケーブルブロックをPSUから取り外します。

. ケーブルマネジメントトレイの内側にあるボタンを引いて下に回転させ、ケーブルマネジメントトレイを下に回転させます。
. ターゲットの NVRAM モジュールをシャーシから取り外します。
+
.. カムラッチボタンを押します。
+
カムボタンがシャーシから離れます。

.. カムラッチを所定の位置まで回転させます。
.. カムレバーの開口部に指をかけてモジュールをシャーシから引き出し、障害のあるNVRAMモジュールをシャーシから取り外します。
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[NVRAM12モジュールとDIMMの取り外し]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
 a| 
カムロックボタン



 a| 
image:../media/legend_icon_02.svg["番号2、幅= 30px"]
 a| 
DIMMの固定ツメ

|===


. NVRAMモジュールを安定した場所に置きます。
. 障害のあるNVRAMモジュールからDIMMを1つずつ取り外し、交換用NVRAMモジュールに取り付けます。
. 交換用 NVRAM モジュールをシャーシに取り付けます。
+
.. モジュールをスロット4/5のシャーシ開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入し、カムラッチを最後まで押し上げてモジュールを所定の位置にロックします。


. PSUにケーブルを再接続します。
+

NOTE: システムにDC電源装置が搭載されている場合は、電源ケーブルブロックをPSUに再接続します。

. ケーブルマネジメントトレイを上に回転させて閉じます。




== 手順 3 ： NVRAM DIMM を交換します

NVRAMモジュールのNVRAM DIMMを交換するには、NVRAMモジュールを取り外してから、ターゲットDIMMを交換する必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. 両方のPSUから電源コードを抜きます。
+

NOTE: システムにDC電源装置が搭載されている場合は、電源ケーブルブロックをPSUから取り外します。

. ケーブルマネジメントトレイの端にあるピンをそっと引いてトレイを下に回転させ、トレイを下に回転させます。
. ターゲットの NVRAM モジュールをシャーシから取り外します。
+
.. カムボタンを押します。
+
カムボタンがシャーシから離れます。

.. カムラッチを所定の位置まで回転させます。
.. カムレバーの開口部に指をかけてモジュールをシャーシから引き出し、NVRAMモジュールをシャーシから取り外します。
+
image::../media/drw_a70-90_nvram12_remove_replace_ieops-1370.svg[NVRAM12モジュールとDIMMの取り外し]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
| カムロックボタン 


 a| 
image:../media/legend_icon_02.svg["番号2、幅= 30px"]
 a| 
DIMMの固定ツメ

|===


. NVRAMモジュールを安定した場所に置きます。
. NVRAMモジュール内で交換するDIMMの場所を確認します。
+

NOTE: NVRAMモジュールの側面にあるFRUマップラベルを参照して、DIMMスロット1および2の位置を確認します。

. DIMMの固定ツメを押し下げ、ソケットから持ち上げてDIMMを取り外します。
. DIMM をソケットに合わせ、固定ツメが所定の位置に収まるまで DIMM をそっとソケットに押し込み、交換用 DIMM を取り付けます。
. NVRAM モジュールをシャーシに取り付けます。
+
.. モジュールをスロットにそっと挿入し、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. PSUにケーブルを再接続します。
+

NOTE: システムにDC電源装置が搭載されている場合は、電源ケーブルブロックをPSUに再接続します。

. ケーブルマネジメントトレイを上に回転させて閉じます。




== 手順4：コントローラをリブートする

FRU を交換したら、コントローラモジュールをリブートする必要があります。

. LOADERプロンプトからONTAPをブートするには、_bye_と入力します。




== 手順 5 ：ディスクを再割り当てする

コントローラのブート時にシステムIDの変更を確認し、変更が実装されたことを確認する必要があります。


CAUTION: ディスクの再割り当てはNVRAMモジュールを交換する場合にのみ必要で、NVRAM DIMMの交換には該当しません。

.手順
. コントローラがメンテナンスモード（プロンプトが表示されている）の場合は `*>` 、メンテナンスモードを終了してLOADERプロンプトに移動します。_halt_
. コントローラのLOADERプロンプトからコントローラをブートし、システムIDが一致しないためにシステムIDを上書きするかどうかを尋ねられたら「_y_」と入力します。
. Waiting for giveback... 交換用モジュールを搭載したコントローラのコンソールにメッセージが表示され、正常なコントローラから新しいパートナーシステムIDが自動的に割り当てられたことを確認します。_storage failover show_
+
コマンド出力には、障害のあるコントローラでシステム ID が変更されたことを示すメッセージが表示され、正しい古い ID と新しい ID が示されます。次の例では、 node2 の交換が実施され、新しいシステム ID として 151759706 が設定されています。

+
[listing]
----
node1:> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. コントローラをギブバックします。
+
.. 正常なコントローラから、交換したコントローラのストレージをギブバックします。_storage failover giveback -ofnode replacement_node_name_
+
コントローラはストレージをテイクバックしてブートを完了します。

+
システムIDの不一致が原因でシステムIDを上書きするように求められた場合は、_y_と入力します。

+

NOTE: ギブバックが拒否されている場合は、拒否を無効にすることを検討してください。

+
詳細については、を参照してください https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted["手動ギブバックコマンド"^] 拒否を無視するトピック。

.. ギブバックの完了後、HAペアが正常でテイクオーバーが可能であることを確認します。_storage failover show_
+
「 storage failover show 」コマンドの出力に、パートナーメッセージで変更されたシステム ID は含まれません。



. ディスクが正しく割り当てられたことを確認します。「 storage disk show -ownership
+
コントローラに属するディスクに新しいシステムIDが表示されます。次の例では、node1が所有するディスクに新しいシステムID 151759706が表示されています。

+
[listing]
----
node1:> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        151759706  151759706  -       151759706 Pool0
1.0.1  aggr0_1  node1 node1           151759706  151759706  -       151759706 Pool0
.
.
.
----
. MetroCluster構成のシステムの場合は、コントローラのステータスを監視します。_ MetroCluster node show_
+
MetroCluster 構成では、交換後に通常の状態に戻るまで数分かかります。この時点で各コントローラの状態が設定済みになります。 DR ミラーリングは有効で、通常モードになります。MetroCluster node show -fields node-systemid' コマンドの出力には、 MetroCluster 設定が通常の状態に戻るまで古いシステム ID が表示されます。

. コントローラが MetroCluster 構成になっている場合は、 MetroCluster の状態に応じて、元の所有者がディザスタサイトのコントローラである場合に DR ホーム ID フィールドにディスクの元の所有者が表示されることを確認します。
+
これは、次の両方に該当する場合に必要です。

+
** MetroCluster 構成がスイッチオーバー状態である。
** コントローラがディザスタサイトのディスクの現在の所有者です。
+
を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["4 ノード MetroCluster 構成での HA テイクオーバーおよび MetroCluster スイッチオーバー中のディスク所有権の変更"] を参照してください。



. MetroCluster構成のシステムの場合は、各コントローラが設定されていることを確認します。_ MetroCluster node show -fields configuration -state_
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 各コントローラに、想定されるボリュームが存在することを確認します。 vol show -node node-name
. ストレージ暗号化が有効になっている場合は、機能をリストアする必要があります。
. リブート時の自動テイクオーバーを無効にした場合は、正常なコントローラから有効にします。_storage failover modify -node replacement -node-name -onreboot true_
. AutoSupportが有効になっている場合は、コマンドを使用してケースの自動作成をリストアまたは抑制解除し `system node autosupport invoke -node * -type all -message MAINT=END` ます。




== 手順 6 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
