---
permalink: afx-2k/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, replace the boot media 
summary: AFX 2Kストレージシステムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、正しい交換用ブートメディアを使用しているかの確認、コントローラに欠陥のあるクラスタポートがないかの確認、およびOnboard Key ManagerまたはExternal Key Managerが有効になっているかどうかの確認が含まれます。 
---
= AFX 2Kストレージシステムにおける自動ブートメディアリカバリの要件を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 2Kストレージシステムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、正しい交換用ブートメディアを使用しているかの確認、コントローラに欠陥のあるクラスタポートがないかの確認、およびOnboard Key Manager（OKM）またはExternal Key Manager（EKM）が有効になっているかどうかの確認が含まれます。

ブートメディアを交換する前に、次の要件を確認してください。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。


* 障害のあるコントローラに障害のあるクラスタポートがないことを確認します。


.次の手順
ブートメディアを交換するための要件を確認した後、link:bootmedia-shutdown.html["コントローラをシャットダウン"] 。
