---
permalink: afx-2k/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, replace the chassis 
summary: AFX 2Kストレージシステムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正しく機能していることの確認、ONTAP のローカル管理者資格情報を持っていることの確認、適切な交換用シャーシと必要な工具の準備が含まれます。 
---
= AFX 2Kシャーシを交換する前に要件を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 2Kストレージシステムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正しく機能していることの確認、ONTAP のローカル管理者資格情報を持っていることの確認、適切な交換用シャーシと必要な工具の準備が含まれます。

シャーシは、ファン、コントローラー/CPU ユニット、NVRAM12、システム管理モジュール、I/O カードとブランキング モジュール、PSU などのすべてのシステム コンポーネントを収容する物理シャーシです。

次の要件を確認します。

* システムの他のすべてのコンポーネントが正常に機能していることを確認します。正常に機能していない場合は、に連絡してサポートを受けてください http://mysupport.netapp.com/["ネットアップサポート"^]
* ONTAPのローカル管理者のクレデンシャルがない場合は、そのクレデンシャルを取得します。
* 交換に必要な工具と機器が揃っていることを確認します。
* シャーシの交換手順は、システムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、ファン、コントローラ モジュール、NVRAM12、システム管理モジュール、I/O カードとブランキング モジュール、および PSU を新しいシャーシに移動し、交換用シャーシがNetAppの新しいコンポーネントであることを前提として書かれています。


.次の手順
要件を確認した後、link:chassis-replace-prepare.html["シャーシを交換する準備をする"] 。
