---
permalink: afx-2k/controller-replace-shutdown.html 
sidebar: sidebar 
keywords: afx 2k, shut down the impaired controller 
summary: AFX 2Kストレージシステムのコントローラーに不具合が生じた場合は、コントローラーの電源を切ってください。メンテナンスや部品交換を行う前に、データ損失を防ぎ、システムの安定性を確保するために、コントローラーを安全にシャットダウンすることが非常に重要です。 
---
= 交換する前に、AFX 2Kストレージシステムの故障したコントローラーをシャットダウンしてください。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データ損失を防ぎ、コントローラー交換時のシステム安定性を確保するため、AFX 2K ストレージシステム内の障害のあるコントローラーをシャットダウンしてください。

次のいずれかのオプションを使用してコントローラモジュールをシャットダウンします。

障害のあるコントローラーを引き継いで停止し、正常なコントローラーが障害のあるコントローラーのストレージからデータを引き続き提供できるようにします。これを行うには、AutoSupportで自動ケース作成を抑制し、自動ギブバックを無効にして、障害のあるコントローラをLOADERプロンプトに切り替えます。LOADERプロンプトは、FRUを交換できる安全な停止状態です。

.このタスクについて
* 4 つ以上のノードを持つクラスターがある場合は、クォーラム内になければなりません。ノードに関するクラスター情報を表示するには、 `cluster show`指示。詳細については、 `cluster show`コマンドについては、link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["ONTAPクラスタ内のノードレベルの詳細を表示する"^] 。
* クラスターがクォーラムにない場合、または (障害のあるコントローラー以外の) コントローラーの正常性または適格性が false と表示される場合は、障害のあるコントローラーをシャットダウンする前に問題を修正する必要があります。見るlink:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^] 。


.手順
. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
次のAutoSupport メッセージは、ケースの自動作成を2時間停止します。

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 障害のあるコントローラのコンソールからの自動ギブバックを無効にします。
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: 「自動ギブバックを無効にしますか？」と表示されたら、次のように入力します。 `y` 。

. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
システムプロンプトまたはパスワードプロンプト
 a| 
正常なコントローラから障害のあるコントローラを引き継ぐか、停止します。
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

_-halt true_ パラメータは、障害のあるノードを LOADER プロンプトに表示します。

|===


.次の手順
コントローラーをシャットダウンした後、link:controller-replace-move-hardware.html["コントローラを交換"] 。
