---
permalink: afx-2k/controller-replace-requirements.html 
sidebar: sidebar 
keywords: afx 2k, prerequisite, replace the controller module 
summary: AFX 2Kストレージシステムのコントローラーを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、適切な交換用コントローラー、システム構成のバックアップ、および必要なツールとファームウェアへのアクセスが含まれます。 
---
= AFX 2Kシステムでコントローラーを交換するための要件を確認します。
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 2Kストレージシステムのコントローラーを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正しく機能していることを確認すること、正しい交換用コントローラーを使用していることを確認すること、およびコントローラーのコンソール出力をテキストログファイルに保存することが含まれます。

コントローラの交換要件を確認します。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。


* すべてのドライブシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* 障害が発生したコンポーネントは、NetAppから受け取ったField-Replaceable Unit（FRU；フィールド交換可能ユニット）と交換する必要があります。
* コントローラモジュールは、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。


.次の手順
AFX 2Kコントローラーを交換するための要件を確認した後、link:controller-replace-shutdown.html["コントローラーをオフにする"]。
