---
permalink: afx-2k/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: afx 2k, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: AFX 2Kストレージ システムにおいて、コントローラのHA構成が有効かつ正しく機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認してください。 
---
= AFX 2Kシステムでコントローラー構成を復元および検証する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 2Kストレージ システムにおいて、コントローラのHA構成が有効かつ正しく機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認してください。



[[step-1-verify-ha-config-settings]]
== 手順1：HA構成を確認する

コントローラモジュールの「 HA 」状態を確認し、必要に応じてシステム構成に合わせて状態を更新する必要があります。

. メンテナンスモードでブートします。 `boot_ontap maint`
+
.. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。



. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。




[[step-2-verify-disk-list]]
== 手順2：ディスクリストを確認する

. アダプタにすべてのディスクへのパスがリストされていることを確認します。
+
`storage show disk -p`

+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. メンテナンスモードを終了します。
+
`halt`



.次の手順
AFX 2Kストレージシステムの構成を復元および検証した後、link:controller-replace-recable-reassign-disks.html["コントローラをギブバック"]。
