---
permalink: a900/bootmedia_recovery_image.html 
sidebar: sidebar 
keywords:  
summary: 障害のあるコントローラをリカバリイメージからブートするための手順 は、システムが 2 ノード MetroCluster 構成かどうかによって異なります。 
---
= リカバリイメージ AFF A900 を起動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP イメージを USB ドライブからブートし、ファイルシステムをリストアして、環境変数を確認する必要があります。

. LOADER プロンプトから、 USB フラッシュドライブ「 boot_recovery 」からリカバリ・イメージをブートします
+
イメージが USB フラッシュドライブからダウンロードされます。

. プロンプトが表示されたら、イメージの名前を入力するか、画面に表示されたデフォルトのイメージをそのまま使用します。
. var ファイルシステムを復元します。
+
[cols="1,2"]
|===
| システムで実行しているバージョン | 作業 


 a| 
ONTAP 9.16.0 以前
 a| 
.. 障害コントローラで、次のメッセージが表示されたら_Y_を押します。 `Do you want to restore the backup configuration now?`
.. 障害コントローラで、上書きするかどうかを確認するメッセージが表示されたら_Y_を押します `/etc/ssh/ssh_host_ecdsa_key`。
.. 正常なパートナーコントローラで、障害コントローラをadvanced権限レベルに設定します。 `set -privilege admin`
.. 正常なパートナーコントローラで、restore backupコマンドを実行します `system node restore-backup -node local -target-address impaired_node_IP_address`。
+
*注：*リストアが正常に完了した以外のメッセージが表示された場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

.. 正常なパートナーコントローラで、障害のあるコントローラをadminレベルに戻します `set -privilege admin`。
.. 障害コントローラで、というメッセージが表示されたら、_y_を押します `Was the restore backup procedure successful?`。
.. 障害コントローラで、というメッセージが表示されたら、_y_を押します `...would you like to use this restored copy now?`。
.. 障害コントローラで、障害コントローラのリブートを求めるプロンプトが表示されたら_y_を押し、ブートメニューとして_Ctrl+C_を押します。
.. システムで暗号化が使用されていない場合は、_option 1 Normal Bootを選択します。使用されていない場合は、に進みます。 link:bootmedia_encryption_restore.html["キー管理ツールのリストア"]
.. パートナーコントローラにコンソールケーブルを接続します。
.. storage failover giveback -fromnode local_コマンドを使用してコントローラをギブバックします。
.. 自動ギブバックを無効にした場合は、_storage failover modify -node local-auto-giveback true_コマンドを使用してリストアします。
.. AutoSupportが有効になっている場合は、_system node AutoSupport invoke -node *-type all -message MAINT=end_commandを使用して、ケースの自動作成をリストアまたは抑制解除します。
+
*注意：*プロセスが失敗した場合は、に連絡してください https://support.netapp.com["ネットアップサポート"]。



|===

