---
permalink: a900/bootmedia_encryption_restore.html 
sidebar: sidebar 
keywords:  
summary: 環境変数を確認したら、オンボードキーマネージャ \ （ OKM \ ）、 NetApp Storage Encryption \ （ NSE\ ）、または NetApp Volume Encryption \ （ NVE \ ）が有効になっているシステムに固有の手順を実行する必要があります。 
---
= OKM 、 NSE 、および NVE - AFF A900 のブートメディア交換後の手順
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


環境変数を確認したら、オンボードキーマネージャ（ OKM ）、 NetApp Storage Encryption （ NSE ）、および NetApp Volume Encryption （ NVE ）のリストア手順を実行する必要があります。

. OKM 、 NSE 、または NVE 構成のリストアに使用するセクションを決定します。 NSE または NVE がオンボードキーマネージャとともに有効になっている場合、この手順の最初に取得した設定をリストアする必要があります。
+
** NSE または NVE が有効で、オンボードキーマネージャが有効になっている場合は、に進みます <<Restore NVE or NSE when Onboard Key Manager is enabled>>。
** ONTAP 9.6 に対して NSE または NVE が有効になっている場合は、に進みます <<Restore NSE/NVE on systems running ONTAP 9.6 and later>>。






== オンボードキーマネージャを有効にした場合は、 NVE または NSE をリストアします

. コンソールケーブルをターゲットコントローラに接続します。
. LOADER プロンプトで boot_ontap コマンドを使用してコントローラをブートします。
. コンソールの出力を確認します。
+
[cols="1,2"]
|===
| コンソールに表示される内容 | 作業 


 a| 
LOADER プロンプト
 a| 
コントローラをブートメニュー「 boot_ontap menu 」からブートします



 a| 
ギブバックを待っています
 a| 
.. プロンプトで「 Ctrl+C 」と入力します
.. というメッセージが表示された場合：このノードを halt するのではなく、 [y/n] をクリックしますか？「 y 」と入力します
.. LOADER プロンプトで「 boot_ontap menu 」コマンドを入力します。


|===
. ブート・メニューで ' 非表示のコマンド 'recover_onboard keymanager_' を入力し ' プロンプトで y と応答します
. この手順の冒頭でお客様から入手したオンボードキーマネージャのパスフレーズを入力します。
. バックアップ・データの入力を求められたら、このセクションの冒頭でキャプチャしたバックアップ・データを貼り付けます。security key-manager backup show コマンドまたは security key-manager onboard show-backup コマンドの出力を貼り付けます。
+

NOTE: このデータは 'security key-manager backup show コマンドまたは security key-manager onboard show-backup コマンドのいずれかから出力されます

+
バックアップデータの例：

+
バックアップデータを入力します。

+
====
-------------- バックアップの開始 TmV0QXBwIEISELAALAC6AALAG3ATVATLH1DBZ12piVATVZ4ATLASYFSSAJAXAJAXAZAAALAC6AALACBAALAC6AALACZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAADATAAAAADAAAAAAADADAAAAAAAAAADAAAAAAAAAAADAAAAAADAAAAAADAAAAAADAAAADAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADAAAADAAAADAAAAA。。。H4nPQM0nrDRYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

-------------- エンド・バックアップ：

====
. ブートメニューで、 Normal Boot のオプションを選択します。
+
システムがブートし、「 Waiting for giveback... 」プロンプトが表示されます。

. パートナーコントローラにコンソールケーブルを接続し、 admin としてログインします。
. storage failover show コマンドを使用して ' ターゲット・コントローラがギブバック可能な状態になっていることを確認します
. 「 storage failover giveback -fromnode local-only -cfo-aggregates true 」コマンドを使用して、 CFO アグリゲートだけをギブバックします。
+
** ディスク障害のためにコマンドが失敗した場合は、ディスクを物理的に取り外します。ただし、交換用のディスクを受け取るまでは、ディスクをスロットに残しておきます。
** CIFS セッションが開いているためにコマンドが失敗する場合は、 CIFS セッションを閉じる方法をお客様に確認します。
+

NOTE: CIFS を終了原因すると、データが失われる可能性があります。

** パートナーの準備ができていないためにコマンドが失敗した場合は、 NVRAMs が同期されるまで 5 分待ちます。
** NDMP 、 SnapMirror 、または SnapVault のプロセスが原因でコマンドが失敗する場合は、そのプロセスを無効にします。詳細については、該当するコンテンツを参照してください。


. ギブバックが完了したら、「 storage failover show 」コマンドと「 storage failover show-giveback 」コマンドを使用して、フェイルオーバーとギブバックのステータスを確認します。
+
CFO アグリゲート（ルートアグリゲートおよび CFO 形式のデータアグリゲート）のみが表示されます。

. ONTAP 9.6 以降を実行している場合は、セキュリティキー管理ツールのオンボード同期を実行します。
+
.. 「 securitykey-manager onboard sync 」コマンドを実行し、プロンプトが表示されたらパスフレーズを入力します。
.. 'security key-manager key-query' コマンドを入力して ' オンボード・キー・マネージャに格納されているすべてのキーの詳細な表示を表示し ' すべての認証キーの 'restored`column=yes/true' を確認します
+

NOTE: 「 Restored 」列が「 yes/true 」以外の場合は、カスタマサポートにお問い合わせください。

.. キーがクラスタ全体で同期されるまで 10 分待ちます。


. パートナーコントローラにコンソールケーブルを接続します。
. storage failover giveback -fromnode local コマンドを使用して、ターゲットコントローラをギブバックします。
. storage failover show コマンドを使用して ' ギブバックのステータスを確認します完了を報告してから 3 分後に確認します
+
20 分経ってもギブバックが完了しない場合は、カスタマーサポートにお問い合わせください。

. クラスタシェルプロンプトで、 net int show -is-home false コマンドを入力し、ホームコントローラとポートにない論理インターフェイスを表示します。
+
いずれかのインターフェイスが「 false 」と表示されている場合は、 net int revert コマンドを使用して、これらのインターフェイスをホームポートに戻します。

. コンソール・ケーブルをターゲット・コントローラに移動し 'version -v コマンドを実行して ONTAP のバージョンを確認します
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。




== ONTAP 9.6 以降を実行しているシステムで NSE / NVE をリストアする

. コンソールケーブルをターゲットコントローラに接続します。
. LOADER プロンプトで boot_ontap コマンドを使用してコントローラをブートします。
. コンソールの出力を確認します。
+
[cols="1,2"]
|===
| コンソールに表示される内容 | 作業 


 a| 
ログインプロンプト
 a| 
手順 7 に進みます。



 a| 
ギブバックを待っています
 a| 
.. パートナーコントローラにログインします。
.. storage failover show コマンドを使用して ' ターゲット・コントローラがギブバック可能な状態になっていることを確認します


|===
. コンソールケーブルをパートナーコントローラに移動し、 storage failover giveback -fromnode local-only -cfo-aggregates true local コマンドを使用して、ターゲットコントローラストレージをギブバックします。
+
** ディスク障害のためにコマンドが失敗した場合は、ディスクを物理的に取り外します。ただし、交換用のディスクを受け取るまでは、ディスクをスロットに残しておきます。
** CIFS セッションが開いているためにコマンドが失敗する場合は、 CIFS セッションを閉じる方法をお客様に確認してください。
+

NOTE: CIFS を終了原因すると、データが失われる可能性があります。

** パートナーの準備が完了していないためにコマンドが失敗した場合は、 NVMEM が同期されるまで 5 分待ちます。
** NDMP 、 SnapMirror 、または SnapVault のプロセスが原因でコマンドが失敗する場合は、そのプロセスを無効にします。詳細については、該当するコンテンツを参照してください。


. 3 分待ってから、 storage failover show コマンドを使用してフェイルオーバーステータスを確認します。
. クラスタシェルプロンプトで、「 net int show -is-home false 」コマンドを入力し、ホームコントローラとポートにない論理インターフェイスを表示します。
+
いずれかのインターフェイスが「 false 」と表示されている場合は、「 net int revert 」コマンドを使用して、これらのインターフェイスをホームポートに戻します。

. コンソール・ケーブルをターゲット・コントローラに移動し 'version -v コマンドを実行して ONTAP のバージョンを確認します
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。
. クラスタシェルプロンプトで「 storage encryption disk show 」を使用して出力を確認します。
. キー管理サーバに保存されている暗号化キーと認証キーを表示するには 'security key-manager key-query コマンドを使用します
+
** リストアされたカラム = 'yes/true' の場合は ' 終了し ' 交換プロセスを完了することができます
** 'Key Manager type`=external' および 'restored' カラム = が 'yes/true' 以外の場合は 'security key-manager external restore コマンドを使用して認証キーのキー ID を復元します
+

NOTE: コマンドが失敗した場合は、カスタマーサポートにお問い合わせください。

** 'Key Manager type`=onboard ' および 'restored' カラム = 'yes/true' 以外の場合は、 security key-manager onboard sync コマンドを使用して Key Manager タイプを再同期します。
+
security key-manager key-query コマンドを使用して ' すべての認証キーの Restored カラム = 'yes/true' を確認します



. パートナーコントローラにコンソールケーブルを接続します。
. storage failover giveback -fromnode local コマンドを使用してコントローラをギブバックします。
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。

