---
permalink: a900/chassis_replace_complete_system_restore_rma.html 
sidebar: sidebar 
keywords: aff a900, verify and set HA state, run diagnostics, complete the replacement process 
summary: キットに付属する RMA 指示書に従って、シャーシの HA 状態を確認し、診断を実行し、障害が発生した部品をネットアップに返却する必要があります。 
---
= 設定AFF A900を復元して確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シャーシの交換を完了するには、特定のタスクを実行する必要があります。



== 手順 1 ：シャーシの HA 状態を確認して設定します

シャーシの HA 状態を確認し、必要に応じてシステム構成に合わせて更新する必要があります。

. メンテナンスモードでは、いずれかのコントローラモジュールから、ローカルコントローラモジュールとシャーシの HA 状態を表示します。「 ha-config show 」
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は、次の手順を実行します。
+
.. シャーシの HA 状態を設定します :'ha-config modify chassis_ha-state _
+
hA-state には、次のいずれかの値を指定できます。

+
*** 高可用性
*** 非 HA




. 設定が変更されたことを確認します。「 ha-config show 」
. システムの残りのケーブルをまだ再接続していない場合は、ケーブルを再接続します。




== 手順2：システムを起動します

. 電源ケーブルをPSUに接続し直します（まだ接続していない場合）。
. ロッカーのスイッチを*オン*に切り替えてPSUをオンにし、コントローラの電源が完全にオンになるまで待ちます。
. 電源投入後、シャーシとコントローラの前面と背面に障害LEDがないかどうかを確認します。
. SSHを使用してノードのSPまたはBMCのIPアドレスに接続します。このアドレスは、ノードのシャットダウンに使用するアドレスと同じです。
. の説明に従って、追加の健全性チェックを実行します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAPでスクリプトを使用してクラスタの健全性チェックを実行する方法"^]
. AutoSupport を再度オンにします（メンテナンス時間のメッセージが終了します）。
`system node autosupport invoke -node * -type all -message MAINT=end`


[]
====

NOTE: ベストプラクティスとして、次のことを実行することを推奨します。

* いずれかを解決します https://activeiq.netapp.com/["Active IQ ウェルネスアラートとリスク"^] （Active IQ は電源投入後のAutoSupportの処理に時間がかかります。結果が遅れることが予想されます）
* を実行します https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* を使用してシステムヘルスを確認します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAPでスクリプトを使用してクラスタの健全性チェックを実行する方法"^]


====


== 手順 3 ：システムレベルの診断を実行します

新しいシャーシを設置したら、インターコネクト診断を実行する必要があります。

.作業を開始する前に
システムレベルの診断を開始するには、システムに LOADER プロンプトが表示されている必要があります。

診断手順のコマンドは、すべてコンポーネントを交換するコントローラから実行します。

. 作業をするコントローラに LOADER プロンプトが表示されていない場合は、次の手順を実行します。
+
.. 表示されたメニューからメンテナンスモードオプションを選択します。
.. コントローラが保守モードでブートしたら、コントローラを停止します
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

+

NOTE: 起動プロセス中に 'y' をプロンプトに安全に応答できます



. HA 構成の場合は、 2 台目のコントローラで同じ手順を繰り返します。
+

NOTE: インターコネクトテストを実行するには、両方のコントローラをメンテナンスモードにする必要があります。

. LOADER プロンプトで、システムレベルの診断用に特別に設計されたドライバ「 boot_diags 」にアクセスします
+
ブート・プロセス中に 'Maintenance] モードのプロンプト（ *> ）が表示されるまで 'y とプロンプトを入力しても安全です

. メンテナンスモードのプロンプトから相互接続診断テストを有効にします。 'diag device modify -dev interconnect -sel enable
+
インターコネクトテストはデフォルトでは無効になっており、実行するには有効にする必要があります。

. メンテナンスモードのプロンプトから ' 相互接続診断テストを実行します (`lddiag device run -dev interconnect `
+
インターコネクトテストは 1 台のコントローラからだけ実行します。

. シャーシの交換によってハードウェアの問題が発生していないことを確認します。 'lddiag device status -dev interconnect -llong -state failed
+
テストに失敗した場合は、プロンプトに戻ります。失敗した場合は、そのステータスがすべて表示されます。

. 前述の手順の結果に基づいて、次に進みます。


|===
| システムレベルの診断のテスト結果 | 作業 


 a| 
は失敗なしで完了しました
 a| 
. ステータスログ「 `diag device clearstatus` 」を消去します
. ログがクリアされたことを確認します。「 diag device status 」
+
次のデフォルトの応答が表示されます。

+
[listing]
----
SLDIAG: No log messages are present.
----
. 両方のコントローラで保守モードを終了します
+
LOADER プロンプトが表示されます。

+

NOTE: 続行する前に、両方のコントローラでメンテナンスモードを終了する必要があります。

. LOADER プロンプトで、両方のコントローラで「 bye 」というコマンドを入力します
. コントローラを通常動作に戻します。


|===
|===
| ONTAP を実行しているシステムの構成 | 作業 


 a| 
2 ノードのクラスタです
 a| 
問題コマンド： 'node::> cluster ha modify -configured true `node::> storage failover modify -node node0 -enabled true



 a| 
3 ノード以上のクラスタ
 a| 
問題このコマンド :`node::> storage failover modify -node node0 -enabled true ``



 a| 
スタンドアロン構成の場合
 a| 
このタスクにはこれ以上の手順はありません。これで、システムレベルの診断が完了しました。



 a| 
テストが失敗しました
 a| 
問題の原因を特定します

. 保守モードを終了します :halt
. クリーンシャットダウンを実行し、電源装置の接続を解除します。
. システムレベルの診断を実行するための考慮事項をすべて確認するとともに、ケーブルがしっかりと接続されているか、ハードウェアコンポーネントがストレージシステムに適切に取り付けられているかを確認します。
. 電源装置を再接続し、ストレージシステムの電源をオンにします。
. システムレベルの診断テストを再実行します。+システムレベルの診断テストが再度失敗した場合は、に連絡します link:http://mysupport.netapp.com/["mysupport.netapp.com"^]。


|===


== 手順 4 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
