---
permalink: a900/controller_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= AFF A900コントローラー交換ワークフロー
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A900 システムのコントローラー交換を開始するには、前提条件を確認し、障害が発生したコントローラーをシャットダウンし、ハードウェアを交換用コントローラーに移動して、システム構成を復元します。

障害のあるコントローラモジュールを交換するには、障害のあるコントローラをシャットダウンし、内蔵コンポーネントを交換用コントローラモジュールに移動して、交換用コントローラモジュールを取り付け、交換用コントローラをリブートする必要があります。

.作業を開始する前に
交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* すべてのドライブシェルフが適切に動作している必要があります。
* システムにV_StorageAttachライセンスがある場合は、この手順を実行する前に、必要な追加の手順を参照する必要があります。
* システムが HA ペアに含まれている場合、正常なコントローラが交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
+
この手順 を使用する場合は、 4 ノードまたは 8 ノードの MetroCluster 構成のコントローラの交換用手順 が HA ペアの場合と同じであることに注意してください。障害が HA ペアに制限されているため、 MetroCluster 固有の手順は必要ありません。また、 storage failover コマンドを使用すると、交換時に無停止操作を行うことができます。

* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから交換用コントローラにブートデバイスが移動され、交換用コントローラが古いコントローラモジュールと同じバージョンの ONTAP でブートするようになります。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** 障害のあるコントローラとは、交換するコントローラです。
** 交換用コントローラは、障害のあるコントローラに交換する新しいコントローラです。
** 正常なコントローラがサバイバーコントローラです。



