---
permalink: a900/controller_replace_overview.html 
sidebar: sidebar 
keywords: AFF A900 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラモジュール AFF A900 を交換してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害のあるコントローラモジュールを交換するには、障害のあるコントローラをシャットダウンし、内蔵コンポーネントを交換用コントローラモジュールに移動して、交換用コントローラモジュールを取り付け、交換用コントローラをリブートする必要があります。

.作業を開始する前に
交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

* すべてのドライブシェルフが適切に動作している必要があります。
* FlexArray システムの場合や V_StorageAttach ライセンスのあるシステムの場合は、この手順を実行する前に、必要な追加の手順を参照する必要があります。
* システムが HA ペアに含まれている場合、正常なコントローラが交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
+
この手順 を使用する場合は、 4 ノードまたは 8 ノードの MetroCluster 構成のコントローラの交換用手順 が HA ペアの場合と同じであることに注意してください。障害が HA ペアに制限されているため、 MetroCluster 固有の手順は必要ありません。また、 storage failover コマンドを使用すると、交換時に無停止操作を行うことができます。

* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから交換用コントローラにブートデバイスが移動され、交換用コントローラが古いコントローラモジュールと同じバージョンの ONTAP でブートするようになります。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** 障害のあるコントローラとは、交換するコントローラです。
** 交換用コントローラは、障害のあるコントローラに交換する新しいコントローラです。
** 正常なコントローラがサバイバーコントローラです。


* コントローラのコンソール出力を必ずテキストファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。


