---
permalink: a900/index.html 
sidebar: sidebar 
keywords: aff A900 maintenance, maintenance, repairing aff A900, repairing aff A900, replace aff A900 components, replace aff A900 components 
summary: ASA A900ハードウェアのメンテナンス 
---
= AFF A900ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A900ストレージシステムでは、次のコンポーネントに対してメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== DCPM を実行します

DCPM（デステージコントローラ電源モジュール）には、NVRAM11バッテリが搭載されています。



== ファン

ファンによってコントローラが冷却されます。



== I/O モジュール

I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



== LED USB

LED USB モジュールは、コンソールポートおよびシステムステータスへの接続を提供します。



== NVRAM

NVRAMモジュール（Non-Volatile Random Access Memory）を使用すると、電源を再投入したりシステムをリブートしたりしても、コントローラでデータを保持できます。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
