---
permalink: a900/maintain-overview.html 
sidebar: sidebar 
keywords: aff A900 maintenance, maintenance, repairing aff A900, repairing aff A900, replace aff A900 components, replace aff A900 components 
summary: AFF A900ハードウェアのメンテナンス 
---
= AFF A900ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A900ストレージ システムのハードウェアをメンテナンスして、長期的な信頼性と最適なパフォーマンスを確保します。故障したコンポーネントの交換など、定期的なメンテナンスを実施することで、ダウンタイムやデータ損失を防止できます。

メンテナンス手順では、 AFF A900ストレージ システムがONTAP環境にストレージ ノードとしてすでに導入されていることを前提としています。



== システムコンホオネント

AFF A900ストレージシステムでは、次のコンポーネントに対してメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["ブートメディア - 自動回復"]
 a| 
ブート メディアには、ストレージ システムがブートに使用するONTAPイメージ ファイルのプライマリ セットとセカンダリ セットが保存されます。自動リカバリ中に、ストレージ システムはパートナー ノードからブート イメージを取得し、適切なブート メニュー オプションを自動的に実行して、交換用ブート メディアにイメージをインストールします。自動ブートメディアリカバリプロセスは、 ONTAP 9.17.1以降でのみサポートされています。ストレージシステムで以前のバージョンのONTAPを実行している場合は、 link:bootmedia-replace-workflow.html["手動ブート回復手順"] 。



 a| 
link:bootmedia-replace-workflow.html["ブートメディア - 手動リカバリ"]
 a| 
ブート メディアには、ストレージ システムがブートに使用するONTAPイメージ ファイルのプライマリ セットとセカンダリ セットが保存されます。手動リカバリでは、USB ドライブからストレージ システムを起動し、ファイル システムのイメージと構成を手動で復元します。ストレージシステムがONTAP 9.17.1以降を実行している場合は、link:bootmedia-replace-workflow-bmr.html["自動ブート回復手順"] 。



 a| 
link:chassis_replace_overview.html["シャーシ"]
 a| 
シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



 a| 
link:controller_replace_overview.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



 a| 
link:dimm_replace.html["DIMM"]
 a| 
メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



 a| 
link:dcpm-nvram11-battery-replace.html["DCPM を実行します"]
 a| 
DCPM（デステージコントローラ電源モジュール）には、NVRAM11バッテリが搭載されています。



 a| 
link:fan_swap_out.html["ファン"]
 a| 
ファンによってコントローラが冷却されます。



 a| 
link:pci_cards_and_risers_replace.html["I/O モジュール"]
 a| 
I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



 a| 
link:led_module_replace.html["LED USB"]
 a| 
LED USB モジュールは、コンソールポートおよびシステムステータスへの接続を提供します。



 a| 
link:nvram_module_or_nvram_dimm_replacement.html["NVRAM"]
 a| 
NVRAMモジュール (不揮発性ランダム アクセス メモリ) により、コントローラは電源サイクルやシステムの再起動後もデータを保持でき、 NVRAM DIMM はNVRAM設定を維持します。



 a| 
link:power_supply_swap_out.html["電源装置"]
 a| 
電源装置は、コントローラに冗長な電源を提供します。



 a| 
link:rtc_battery_replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。

|===