---
permalink: asa800/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a800, prerequisite, replace the controller module 
summary: ASA A800システムのコントローラを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラーがあることを確認すること、コントローラーのコンソール出力をテキスト ログ ファイルに保存することが含まれます。 
---
= コントローラの交換要件 - ASA A800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A800システムのコントローラを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラーがあることを確認すること、コントローラーのコンソール出力をテキスト ログ ファイルに保存することが含まれます。

コントローラモジュールを交換するための要件を確認します。

* すべてのドライブシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換されるコントローラ (この手順では障害のあるコントローラと呼びます) を引き継ぐことができる必要があります。
* コントローラーのアップグレードにはこの手順を使用しないでください。参照 https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["コントローラハードウェアのアップグレード手順を選択"]ガイダンスのため。
* システムがMetroCluster構成の場合、 https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"]この手順を使用するかどうかを決定します。
* 故障したコンポーネントを、 NetAppから受け取ったフィールド交換可能ユニット (FRU) と交換します。
* コントローラー モジュールを同じモデル タイプのコントローラー モジュールと交換します。コントローラー モジュールを交換してもシステムをアップグレードすることはできません。
* この手順では、ドライブまたはドライブ シェルフを変更することはできません。
* ブート デバイスは、システムの背面にインストールされているシステム管理モジュールにあります。コントローラー モジュールを交換するときに、ブート デバイスを移動する必要はありません。
* この手順で使用されるコントローラの用語を理解します。
+
** 障害のあるコントローラーは交換されるコントローラーです。
** 交換用コントローラは、障害のあるコントローラと交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。


* コントローラーのコンソール出力をテキスト ログ ファイルにキャプチャします。
+
これにより、交換プロセス中に発生した問題をトラブルシューティングする手順が記録されます。



.次の手順
ASA A800コントローラを交換するための要件を確認した後、link:controller-replace-shutdown.html["障害のあるコントローラをシャットダウン"] 。
