---
permalink: a200/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: ブートメディアには、システムが起動時に使用するプライマリおよびセカンダリのシステムブートイメージファイルが格納されています。ネットワーク構成によっては、無停止交換または停止交換のいずれかを実行できます。AFF A200システムは、手動によるブートメディア復旧手順のみをサポートしています。 
---
= AFF A200システムのブートメディア交換について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリのシステム (ブート イメージ) ファイル セットが保存されます。ネットワーク構成に応じて、無停止交換または停止交換のいずれかを実行できます。AFF A200システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
.必要なもの
「 image_xxx.tgz 」ファイルを格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

.作業を開始する前に
* 無停止または停止を伴う方法でブートメディアを交換する場合は、 var ファイルシステムをリストアする必要があります。
+
** 無停止で交換する場合は、 HA ペアをネットワークに接続して var ファイルシステムをリストアする必要があります。
** 停止を伴う交換の場合、 var ファイルシステムをリストアするためにネットワーク接続は必要ありませんが、リブートが 2 回必要です。


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。



