---
permalink: a200/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラモジュールの交換の概要 - AFF A200
:icons: font
:imagesdir: ../media/


[role="lead"]
交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

.必要なもの
* すべてのドライブシェルフが適切に動作している必要があります。
* システムが HA ペアに含まれている場合、正常なコントローラが交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害ノード」と呼びます）。


.このタスクについて
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールは、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから交換用ノードにブートデバイスを移動して、古いコントローラモジュールと同じバージョンの ONTAP で _replacement _node がブートするようにします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_node は、交換するコントローラです。
** replacement _node は、障害のあるコントローラと交換する新しいコントローラです。
** healthy_node は、サバイバーコントローラです。


* コントローラのコンソール出力を必ずテキストファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。


