---
permalink: a200/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a200, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= AFF A200システムでコントローラーを交換するための要件を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A200 システムのコントローラーを交換する前に、交換手順の前提条件を確認し、お使いの ONTAP のバージョンに適した手順を選択してください。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
.必要なもの
* すべてのドライブシェルフが適切に動作している必要があります。
* システムが HA ペアに含まれている場合、正常なコントローラが交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害ノード」と呼びます）。


.このタスクについて
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールは、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから交換用ノードにブートデバイスを移動して、古いコントローラモジュールと同じバージョンの ONTAP で _replacement _node がブートするようにします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_node は、交換するコントローラです。
** replacement _node は、障害のあるコントローラと交換する新しいコントローラです。
** healthy_node は、サバイバーコントローラです。



