---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_install_nx-os_software_and_reference_configuration_files_@rcfs@.html 
keywords: rcfs, nx-os, install 
summary:  
---
= NX-OS ソフトウェアおよび RCF のインストール
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




==== Cisco Nexus 9336C-FX2 クラスタスイッチに NX-OS ソフトウェアと RCF をインストールします

Cisco NX-OS ソフトウェアとリファレンス構成ファイル（ RCF ）は、 Cisco Nexus 9336C-FX2 クラスタスイッチにインストールする必要があります。



===== 作業を開始する前に

クラスタスイッチに NX-OS ソフトウェアと RCF をインストールする前に、次の条件が満たされている必要があります。

* クラスタが完全に機能している必要があります（ログにエラーがあるなどの問題が発生していない）。
* NX-OS だけをインストールして現在の RCF バージョンをそのまま使用する場合は、目的のブートイメージを反映するように、 RCF で必要なブート設定を確認または設定しておく必要があります。
* 現在のブートイメージを反映するようにブート設定を変更する必要がある場合は、あとでリブートしたときに正しいバージョンがインスタンス化されるように、 RCF を再適用する前に変更する必要があります。
* RCF のインストール時に必要なスイッチへのコンソール接続が必要です。
* サポートされている ONTAP 、 NX-OS 、および RCF のバージョンについては、 Cisco イーサネットスイッチのページにあるスイッチ互換性の表を参照してください。を参照してください https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"] を参照してください。
* RCF のコマンド構文と、 NX-OS のバージョンにあるコマンド構文との間には、コマンドの依存関係が存在する場合があります。
* Cisco スイッチのアップグレードおよびダウングレード手順の詳細については、 Cisco の Web サイトで入手可能な、適切なソフトウェアおよびアップグレードガイドを参照しておく必要があります。を参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html["Cisco Nexus 9000 シリーズスイッチ"] を参照してください。
* 最新の RCF が必要です。




===== 初期セットアップ

この手順の例では、 2 つのノードを使用します。これらのノードは、 A400 コントローラに応じて 2 つの 100GbE クラスタインターコネクトポート e3a と e3b を使用します。を参照してください https://hwu.netapp.com["Hardware Universe"] をクリックして、プラットフォームのクラスタポートが正しいことを確認します。


NOTE: コマンド出力は、 ONTAP のリリースによって異なる場合があります。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つの Cisco スイッチの名前は、 _CS1_AND _CS2__ です。
* ノード名は _cluster1-01 と _cluster1-02 _ です。
* クラスタ LIF の名前は、 cluster1-02 および cluster1-01_clus1_clus1_clus2_cluster1 については、 cluster1-01 および _cluster1-02 _clus1_and _cluster1-02 _clus2_cluster2 についてはとなります。
* cluster1 ： * > プロンプトは、クラスタの名前を示します。



NOTE: 手順では、 ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。



===== 手順

. [[step1] このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージ「システムノード AutoSupport invoke -node * -type all -message MAINT= x h ’を呼び出して、ケースの自動作成を抑制します
+
x は、メンテナンス時間の長さ（時間単位）です。



. [[step2] 権限レベルを advanced に変更します。続行するかどうかを尋ねられたら、「 y 」と入力します。「 set -privilege advanced 」
+
advanced のプロンプト（ * > ）が表示されます。

. [[step3] 各クラスタインターコネクトスイッチの各ノードで設定されているクラスタインターコネクトインターフェイスの数を表示します。「 network device-discovery show -protocol cdp


[listing]
----
cluster1:: network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-02/cdp
            e3a    cs1                       Eth1/2            N9K-C9336C
            e3b    cs2                       Eth1/2            N9K-C9336C
cluster1-01/cdp
            e3a    cs1                       Eth1/1            N9K-C9336C
            e3b    cs2                       Eth1/1            N9K-C9336C
4 entries were displayed.
----
. [[step4] 各クラスタインターフェイスの管理ステータスまたは動作ステータスを確認します。
+
.. ネットワーク・ポートの属性を表示します network port show – ipspace Cluster




[listing]
----
cluster1::*> network port show -ipspace Cluster
Node: cluster1-02
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy

Node: cluster1-01
                                                  Speed(Mbps)  Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status
--------- ------------ ---------------- ---- ---- ------------ ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy
e3b       Cluster      Cluster          up   9000  auto/100000 healthy
4 entries were displayed.

----
. LIF に関する情報を表示します。「 network interface show -vserver Cluster


[listing]
----
cluster1::*> network interface show -vserver Cluster
        Logical            Status     Network            Current    Current Is
Vserver Interface          Admin/Oper Address/Mask       Node        Port   Home
------- ------------------ ---------- ------------------ ----------- ------ ----
Cluster
        cluster1-01_clus1  up/up      169.254.209.69/16  cluster1-01  e3a   true
        cluster1-01_clus2  up/up      169.254.49.125/16  cluster1-01  e3b   true
        cluster1-02_clus1  up/up      169.254.47.194/16  cluster1-02  e3a   true
        cluster1-02_clus2  up/up      169.254.19.183/16  cluster1-02  e3b   true
4 entries were displayed.
----
. [[step5] リモートクラスタ LIF に ping を実行します :cluster ping-cluster -node node-name`


[listing]
----
cluster1::*> cluster ping-cluster -node cluster1-02
Host is cluster1-02
Getting addresses from network interface table...
Cluster cluster1-01_clus1 169.254.209.69 cluster1-01     e3a
Cluster cluster1-01_clus2 169.254.49.125 cluster1-01     e3b
Cluster cluster1-02_clus1 169.254.47.194 cluster1-02     e3a
Cluster cluster1-02_clus2 169.254.19.183 cluster1-02     e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
    Local 169.254.19.183 to Remote 169.254.209.69
    Local 169.254.19.183 to Remote 169.254.49.125
    Local 169.254.47.194 to Remote 169.254.209.69
    Local 169.254.47.194 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step6] すべてのクラスタ LIF で auto-revert コマンドが有効になっていることを確認します。「 network interface show -vserver Cluster -fields auto-revert


[listing]
----
cluster1::*> network interface show -vserver Cluster -fields auto-revert
          Logical
Vserver   Interface            Auto-revert
--------- ––––––-------------- ------------
Cluster
          cluster1-01_clus1    true
          cluster1-01_clus2    true
          cluster1-02_clus1    true
          cluster1-02_clus2    true
4 entries were displayed.
----
. [[step7] 次のコマンドを使用して、スイッチ関連のログファイルを収集するためのイーサネットスイッチヘルスモニタのログ収集機能を有効にします。
+
** 「システムスイッチイーサネットログセットアップ - パスワード」
** 「システムスイッチのイーサネットログの有効化」




[listing]
----
cluster1::*> system switch ethernet log setup password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
cs1
cs2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: cs2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? {y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----

NOTE: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。



==== Cisco Nexus 9336C-FX2 クラスタスイッチに NX-OS ソフトウェアをインストールします

この手順を使用して、 Cisco Nexus 9336C-FX2 クラスタスイッチに NX-OS ソフトウェアをインストールできます。



===== 手順

. [[step1] クラスタスイッチを管理ネットワークに接続します。
. [step2] NX-OS ソフトウェアおよび RCF をホストするサーバへの接続を確認するには、 ping コマンドを使用します。
+
次の例では、スイッチが IP アドレス「 172.19.2.1 」のサーバに接続できることを確認します。



[listing]
----
cs2# ping 172.19.2.1
Pinging 172.19.2.1 with 0 bytes of data:
Reply From 172.19.2.1: icmp_seq = 0. time= 5910 usec.
----
. [[step3] NX-OS ソフトウェアおよび EPLD イメージを Nexus 9336C-FX2 スイッチにコピーします。


[listing]
----
cs2# copy sftp: bootflash: vrf management
Enter source filename: /code/nxos.9.3.5.bin
Enter hostname for the sftp server: 172.19.2.1
Enter username: user1
Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/nxos.9.3.5.bin  /bootflash/nxos.9.3.5.bin
/code/nxos.9.3.5.bin  100% 1261MB   9.3MB/s   02:15
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
cs2# copy sftp: bootflash: vrf management
Enter source filename: /code/n9000-epld.9.3.5.img
Enter hostname for the sftp server: 172.19.2.1
Enter username: user1
Outbound-ReKey for 172.19.2.1:22
Inbound-ReKey for 172.19.2.1:22
user1@172.19.2.1's password:
sftp> progress
Progress meter enabled
sftp> get   /code/n9000-epld.9.3.5.img  /bootflash/n9000-epld.9.3.5.img
/code/n9000-epld.9.3.5.img  100%  161MB   9.5MB/s   00:16
sftp> exit
Copy complete, now saving to disk (please wait)...
Copy complete.
----
. [[step4]] NX-OS ソフトウェアの実行中のバージョンを確認します : 'how version`


[listing]
----
cs2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.
Software
  BIOS: version 08.38
  NXOS: version 9.3(4)
  BIOS compile time:  05/29/2020
  NXOS image file is: bootflash:///nxos.9.3.4.bin
  NXOS compile time:  4/28/2020 21:00:00 [04/29/2020 02:28:31]
Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K
  Device name: cs2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 157524 usecs after Mon Nov  2 18:32:06 2020
  Reason: Reset Requested by CLI command reload
  System version: 9.3(4)
  Service:
plugin
  Core Plugin, Ethernet Plugin
Active Package(s):

cs2#
----
. [[step5] NX-OS イメージをインストールします。



NOTE: イメージファイルをインストールすると、スイッチをリブートするたびにロードされます。

[listing]
----
cs2# install all nxos bootflash:nxos.9.3.5.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive
Verifying image bootflash:/nxos.9.3.5.bin for boot variable "nxos".
[####################] 100% -- SUCCESS
Verifying image type.
[####################] 100% -- SUCCESS
Preparing "nxos" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS
Preparing "bios" version info using image bootflash:/nxos.9.3.5.bin.
[####################] 100% -- SUCCESS
Performing module support checks.
[####################] 100% -- SUCCESS
Notifying services about system upgrade.
[####################] 100% -- SUCCESS
Compatibility check is done:
Module  bootable       Impact     Install-type  Reason
------  --------  --------------- ------------  ------
  1       yes      disruptive         reset     default upgrade is not hitless
Images will be upgraded according to following table:
Module   Image    Running-Version(pri:alt                New-Version         Upg-
                                                                             Required
------- --------- -------------------------------------- ------------------- ------------
  1      nxos     9.3(4)                                 9.3(5)              yes
  1      bios     v08.37(01/28/2020):v08.23(09/23/2015)  v08.38(05/29/2020)  yes
Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)?  [n] y
Install is in progress, please wait.
Performing runtime checks.
[####################] 100% -- SUCCESS
Setting boot variables.
[####################] 100% -- SUCCESS
Performing configuration copy.
[####################] 100% -- SUCCESS
Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
Finishing the upgrade, switch will reboot in 10 seconds.
----
. [[step6] スイッチのリブート後に NX-OS ソフトウェアの新しいバージョンを確認します : 'how version`


[listing]
----
cs2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source.  This software is provided "as is," and unless
otherwise stated, there is no warranty, express or implied, including but not
limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0  or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
http://www.gnu.org/licenses/old-licenses/library.txt.
Software
  BIOS: version 05.33
  NXOS: version 9.3(5)
  BIOS compile time:  09/08/2018
  NXOS image file is: bootflash:///nxos.9.3.5.bin
  NXOS compile time:  11/4/2018 21:00:00 [11/05/2018 06:11:06]
Hardware
  cisco Nexus9000 C9336C-FX2 Chassis
  Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
  Processor Board ID FOC20291J6K
  Device name: cs2
  bootflash:   53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 277524 usecs after Mon Nov  2 22:45:12 2020
  Reason: Reset due to upgrade
  System version: 9.3(4)
  Service:
plugin
  Core Plugin, Ethernet Plugin
Active Package(s):
----
. [[step7] EPLD イメージをアップグレードし、スイッチをリブートします。


[listing]
----
cs2# show version module 1 epld
EPLD Device                     Version
---- -------------------------- -------
MI   FPGA                        0x7
IO   FPGA                        0x17
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
cs2# install epld bootflash:n9000-epld.9.3.5.img module 1
Compatibility check:
Module      Type        Upgradable  Impact      Reason
------  -------------- ------------ ----------- -------
     1      SUP        Yes          disruptive  Module Upgradable
Retrieving EPLD versions.... Please wait.
Images will be upgraded according to following table:
Module  Type   EPLD              Running-Version   New-Version  Upg-Required
------- ------ ----------------- ----------------- ------------ ------------
     1  SUP    MI FPGA           0x07              0x07         No
     1  SUP    IO FPGA           0x17              0x19         Yes
     1  SUP    MI FPGA2          0x02              0x02         No
The above modules require upgrade.
The switch will be reloaded at the end of the upgrade
Do you want to continue (y/n) ?  [n] y
Proceeding to upgrade Modules.
Starting Module 1 EPLD Upgrade
Module 1 : IO FPGA [Programming] : 100.00% (     64 of      64 sectors)
Module 1 EPLD upgrade is successful.
Module   Type  Upgrade-Result
-------- ----- --------------
     1   SUP   Success
EPLDs upgraded.
Module 1 EPLD upgrade is successful.
----
. [[step8] スイッチのリブート後に再度ログインし、新しいバージョンの EPLD が正常にロードされたことを確認します。


[listing]
----
cs2# show version module 1 epld
EPLD Device                     Version
---- -------------------------- --------
MI   FPGA                        0x7
IO   FPGA                        0x19
MI   FPGA2                       0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
GEM  FPGA                        0x2
----


==== Cisco Nexus 9336C-FX2 クラスタスイッチに RCF をインストールします

RCF は、 Nexus 9336C-FX2 クラスタスイッチを初めてセットアップしたあとにインストールできます。この手順を使用して、クラスタスイッチの RCF バージョンをアップグレードすることもできます。



===== このタスクについて

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つの Cisco スイッチの名前は 'CS1' および CS2' です
* ノード名は「 cluster1-01 」、「 cluster1-02 」、「 cluster1-02 」、「 cluster1-02 」、および「 cluster1-02 」です。
* クラスタ LIF の名前は、「 cluster1-01 _ clus1 」、「 cluster1-01 _ clus2 」、「 cluster1-02 _ clus1 」、「 cluster1-02 _ clus2 」、「 cluster1-03_clus1 」です。 「 cluster1-03_clus2` 」、「 cluster1-02 」、「 cluster1-04_clus1 」、「 cluster1-04_clus2 」。
* cluster1 ： * > プロンプトは、クラスタの名前を示します。



NOTE: 手順では、 ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。



===== 手順

. [[step1] クラスタスイッチに接続されている各ノードのクラスタポートを表示します。「 network device-discovery show 」を参照してください


[listing]
----
cluster1::*> network device-discovery show
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  --------
cluster1-01/cdp
            e3a    cs1                       Ethernet1/7       N9K-C9336C
            e0d    cs2                       Ethernet1/7       N9K-C9336C
cluster1-02/cdp
            e3a    cs1                       Ethernet1/8       N9K-C9336C
            e0d    cs2                       Ethernet1/8       N9K-C9336C
cluster1-03/cdp
            e3a    cs1                       Ethernet1/1/1     N9K-C9336C
            e3b    cs2                       Ethernet1/1/1     N9K-C9336C
cluster1-04/cdp
            e3a    cs1                       Ethernet1/1/2     N9K-C9336C
            e3b    cs2                       Ethernet1/1/2     N9K-C9336C
cluster1::*>
----
. [[step2] 各クラスタポートの管理ステータスおよび動作ステータスを確認します。
. [[step3]] すべてのクラスタポートが正常な状態で稼働していることを確認します : 「 network port show – role cluster 」


[listing]
----
cluster1::*> network port show -role cluster
Node: cluster1-01
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
Node: cluster1-02
                                                                       Ignore
                                                  Speed(Mbps) Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status   Status
--------- ------------ ---------------- ---- ---- ----------- -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy false
e0d       Cluster      Cluster          up   9000  auto/100000 healthy false
8 entries were displayed.
Node: cluster1-03

                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
Node: cluster1-04
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e0a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e0b       Cluster      Cluster          up   9000  auto/100000 healthy  false
cluster1::*>
----
. [[step4]] すべてのクラスタインターフェイス（ LIF ）がホームポートにあることを確認します：「 network interface show -role cluster 」


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status     Network         Current      Current Is
Vserver Interface          Admin/Oper Address/Mask    Node         Port    Home
------- ------------------ ---------- --------------- ------------ ------- ----
Cluster
        cluster1-01_clus1  up/up     169.254.3.4/23   cluster1-01  e3a     true
        cluster1-01_clus2  up/up     169.254.3.5/23   cluster1-01  e0d     true
        cluster1-02_clus1  up/up     169.254.3.8/23   cluster1-02  e3a     true
        cluster1-02_clus2  up/up     169.254.3.9/23   cluster1-02  e0d     true
        cluster1-03_clus1  up/up     169.254.1.3/23   cluster1-03  e3a     true
        cluster1-03_clus2  up/up     169.254.1.1/23   cluster1-03  e3b     true
        cluster1-04_clus1  up/up     169.254.1.6/23   cluster1-04  e3a     true
        cluster1-04_clus2  up/up     169.254.1.7/23   cluster1-04  e3b     true
8 entries were displayed.
cluster1::*>
----
. [[step5] クラスタが両方のクラスタスイッチの情報を表示することを確認します： 'system cluster-switch show-is-monitoring -enabled -operational true


[listing]
----
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    N9K-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cs2                         cluster-network    10.233.205.91    N9K-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cluster1::*>
----
. [[step6] ] クラスタ LIF での自動リバートを無効にします。


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert false
----
. [step7] クラスタスイッチ cs2 で、ノードのクラスタポートに接続されているポートをシャットダウンします。


[listing]
----
cs2(config)# interface eth1/1/1-2,eth1/7-8
cs2(config-if-range)# shutdown
----
. [[step8] クラスタ LIF が、クラスタスイッチ cs1 でホストされているポートに移行されていることを確認します。この処理には数秒かかることがあります。「 network interface show -role cluster 」のように表示されます


[listing]
----
cluster1::*> network interface show -role cluster
        Logical           Status     Network          Current      Current  Is
Vserver Interface         Admin/Oper Address/Mask     Node         Port     Home
------- ----------------- --------- ---------------- ------------- ------- ----
Cluster
        cluster1-01_clus1 up/up     169.254.3.4/23   cluster1-01   e3a     true
        cluster1-01_clus2 up/up     169.254.3.5/23   cluster1-01   e3a     false
        cluster1-02_clus1 up/up     169.254.3.8/23   cluster1-02   e3a     true
        cluster1-02_clus2 up/up     169.254.3.9/23   cluster1-02   e3a     false
        cluster1-03_clus1 up/up     169.254.1.3/23   cluster1-03   e3a     true
        cluster1-03_clus2 up/up     169.254.1.1/23   cluster1-03   e3a     false
        cluster1-04_clus1 up/up     169.254.1.6/23   cluster1-04   e3a     true
        cluster1-04_clus2 up/up     169.254.1.7/23   cluster1-04   e3a     false
8 entries were displayed.
cluster1::*>
----
. [[step9] クラスタが正常であることを確認します : cluster show


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
. [[step10] スイッチ cs2 の構成をクリーニングし、基本的なセットアップを実行します。
+
.. 設定を消去します。この手順では、スイッチへのコンソール接続が必要です。




[listing]
----
cs2# write erase
Warning: This command will erase the startup-configuration.
Do you wish to proceed anyway? (y/n)  [n] y
cs2# reload
This command will reboot the system. (y/n)?  [n] y
cs2#
----
. スイッチの基本設定を実行します。


. [[step11]] FTP 、 TFTP 、 SFTP 、または SCP のいずれかの転送プロトコルを使用して、 RCF をスイッチ cs2 のブートフラッシュにコピーします。Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。
+
この例は、 TFTP を使用して、スイッチ cs2 のブートフラッシュに RCF をコピーする方法を示しています。



[listing]
----
cs2# copy tftp: bootflash: vrf management
Enter source filename: Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt
Enter hostname for the tftp server: 172.22.201.50
Trying to connect to tftp server......Connection to Server Established.
TFTP get operation was successful
Copy complete, now saving to disk (please wait)...
----
. [[step12]] 以前にブートフラッシュにダウンロードした RCF を適用します。Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。
+
この例は、スイッチ cs2 にインストールされている RCF ファイル「 Nexus_9336C_RCF_v1.6 -Cluster-HA-Breakout .txt 」を示しています。



[listing]
----
cs2# copy Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
----
. [[step13]] 'How banner motd コマンドのバナー出力を調べますスイッチの設定と動作を適切に行うには、次の手順を参照して実行する必要があります。


[listing]
----
cs2# show banner motd
***************************************************************************
* NetApp Reference Configuration File (RCF)
*
* Switch   : Nexus N9K-C9336C-FX2
* Filename : Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt
* Date     : 10-23-2020
* Version  : v1.6
*
* Port Usage:
* Ports  1- 3: Breakout mode (4x10G) Intra-Cluster Ports, int e1/1/1-4,
* e1/2/1-4, e1/3/1-4
* Ports  4- 6: Breakout mode (4x25G) Intra-Cluster/HA Ports, int e1/4/1-4,
* e1/5/1-4, e1/6/1-4
* Ports  7-34: 40/100GbE Intra-Cluster/HA Ports, int e1/7-34
* Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Dynamic breakout commands:
* 10G: interface breakout module 1 port <range> map 10g-4x
* 25G: interface breakout module 1 port <range> map 25g-4x
*
* Undo breakout commands and return interfaces to 40/100G configuration in
* config mode:
* no interface breakout module 1 port <range> map 10g-4x
* no interface breakout module 1 port <range> map 25g-4x
* interface Ethernet <interfaces taken out of breakout mode>
* inherit port-profile 40-100G
* priority-flow-control mode auto
* service-policy input HA
* exit
*
***************************************************************************
----
. [[step14]] RCF ファイルが正しい新しいバージョンであることを確認します :'how running-config
+
出力をチェックして正しい RCF があることを確認する場合は、次の情報が正しいことを確認してください。

+
** RCF バナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールした RCF に固有の変更がないかリリースノートを参照してください。



. RCF のバージョンとスイッチの設定が正しいことを確認したら、 running-config ファイルを startup-config ファイルにコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。



[listing]
----
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
. [[step16]] スイッチ cs2 をリブートします。スイッチのリブート中にノードで報告される「クラスタポートが停止している」イベントは無視してかまいません。


[listing]
----
cs2# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step17]] 同じ RCF を適用し、実行中の設定をもう一度保存します。


[listing]
----
cs2# copy Nexus_9336C_RCF_v1.6-Cluster-HA-Breakout.txt running-config echo-commands
cs2# copy running-config startup-config [########################################] 100% Copy complete
----
. [[step18]] クラスタのクラスタポートの健常性を確認します。
+
.. クラスタ内のすべてのノードで e0d ポートが正常に稼働していることを確認します。「 network port show -role cluster 」




[listing]
----
cluster1::*> network port show -role cluster
Node: cluster1-01
                                                                   Ignore
                                             Speed(Mbps)  Health   Health
Port    IPspace   Broadcast Domain Link MTU  Admin/Oper   Status   Status
------- --------- ---------------- ---- ---- ------------ -------- ------
e3a     Cluster   Cluster          up   9000 auto/100000  healthy  false
e3b     Cluster   Cluster          up   9000 auto/100000  healthy  false

Node: cluster1-02
                                                                   Ignore
                                              Speed(Mbps)  Health  Health
Port    IPspace   Broadcast Domain Link MTU   Admin/Oper   Status  Status
------- --------- ---------------- ---- ----- ------------ -------- ------
e3a    Cluster   Cluster          up   9000  auto/100000  healthy  false
e3b    Cluster   Cluster          up   9000  auto/100000  healthy  false

Node: cluster1-03
                                                                   Ignore
                                              Speed(Mbps) Health   Health
Port   IPspace    Broadcast Domain Link MTU   Admin/Oper  Status   Status
------ ---------- ---------------- ---- ----- ----------- -------- ------
e3a    Cluster    Cluster          up   9000  auto/100000 healthy  false
e0d    Cluster    Cluster          up   9000  auto/100000 healthy  false

Node: cluster1-04
                                                                   Ignore
                                              Speed(Mbps) Health   Health
Port   IPspace    Broadcast Domain Link MTU   Admin/Oper  Status   Status
------ ---------- ---------------- ---- ----- ----------- -------- ------
e3a    Cluster      Cluster        up   9000  auto/100000 healthy  false
e0d    Cluster      Cluster        up   9000  auto/100000 healthy  false
8 entries were displayed.
----
. クラスタからスイッチのヘルスを確認します（ LIF が e0d にホームでないため、スイッチ cs2 が表示されない可能性があります）。


[listing]
----
cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------- --------
cluster1-01/cdp
            e3a    cs1                       Ethernet1/7       N9K-C9336C
            e0d    cs2                       Ethernet1/7       N9K-C9336C
cluster01-2/cdp
            e3a    cs1                       Ethernet1/8       N9K-C9336C
            e0d    cs2                       Ethernet1/8       N9K-C9336C
cluster01-3/cdp
            e3a    cs1                       Ethernet1/1/1     N9K-C9336C
            e3b    cs2                       Ethernet1/1/1     N9K-C9336C
cluster1-04/cdp
            e3a    cs1                       Ethernet1/1/2     N9K-C9336C
            e3b    cs2                       Ethernet1/1/2     N9K-C9336C
cluster1::*> system cluster-switch show -is-monitoring-enabled-operational true
Switch                      Type               Address          Model
--------------------------- ------------------ ---------------- -----
cs1                         cluster-network    10.233.205.90    NX9-C9336C
     Serial Number: FOCXXXXXXGD
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
cs2                         cluster-network    10.233.205.91    NX9-C9336C
     Serial Number: FOCXXXXXXGS
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
2 entries were displayed.
----

NOTE: スイッチにロードした RCF バージョンによっては、 cs1 スイッチコンソールで次の出力が表示されることがあります。

[listing]
----
2020 Nov 17 16:07:18 cs1 %$ VDC-1 %$ %STP-2-UNBLOCK_CONSIST_PORT: Unblocking port port-channel1 on VLAN0092. Port consistency restored.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_PEER: Blocking port-channel1 on VLAN0001. Inconsistent peer vlan.
2020 Nov 17 16:07:23 cs1 %$ VDC-1 %$ %STP-2-BLOCK_PVID_LOCAL: Blocking port-channel1 on VLAN0092. Inconsistent local vlan.
----
. [[step19]] クラスタスイッチ cs1 で、ノードのクラスタポートに接続されているポートをシャットダウンします。次の例では、手順 1 の出力例を使用しています。


[listing]
----
cs1(config)# interface eth1/1/1-2,eth1/7-8
cs1(config-if-range)# shutdown
----
. [step20] クラスタ LIF がスイッチ cs2 でホストされているポートに移行されたことを確認しますこの処理には数秒かかることがあります。「 network interface show -role cluster 」のように表示されます


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status      Network         Current      Current Is
Vserver Interface          Admin/Oper  Address/Mask    Node         Port    Home
------- ------------------ ----------- --------------- ------------ ------- ----
Cluster
        cluster1-01_clus1  up/up       169.254.3.4/23   cluster1-01   e0d  false
        cluster1-01_clus2  up/up       169.254.3.5/23   cluster1-01   e0d   true
        cluster1-02_clus1  up/up       169.254.3.8/23   cluster1-02   e0d  false
        cluster1-02_clus2  up/up       169.254.3.9/23   cluster1-02   e0d   true
        cluster1-03_clus1  up/up       169.254.1.3/23   cluster1-03   e3b  false
        cluster1-03_clus2  up/up       169.254.1.1/23   cluster1-03   e3b   true
        cluster1-04_clus1  up/up       169.254.1.6/23   cluster1-04   e3b  false
        cluster1-04_clus2  up/up       169.254.1.7/23   cluster1-04   e3b   true
8 entries were displayed.
cluster1::*>
----
. [[step2]] クラスタが正常であることを確認します : 'cluster show`


[listing]
----
cluster1::*> cluster show
Node                 Health   Eligibility   Epsilon
-------------------- -------- ------------- -------
cluster1-01          true     true          false
cluster1-02          true     true          false
cluster1-03          true     true          true
cluster1-04          true     true          false
4 entries were displayed.
cluster1::*>
----
. [[step22]] スイッチ cs1 で手順 7 から 14 を繰り返します。
. クラスタ LIF で自動リバートを有効にします。


[listing]
----
cluster1::*> network interface modify -vserver Cluster -lif * -auto-revert True
----
. [[step24]] スイッチ cs1 をリブートします。これは、クラスタ LIF のホームポートへのリバートをトリガーする際に行います。スイッチのリブート中にノードで報告される「クラスタポートが停止している」イベントは無視してかまいません。


[listing]
----
cs1# reload
This command will reboot the system. (y/n)?  [n] y
----
. [[step25]] クラスタポートに接続されているスイッチポートが稼働していることを確認します。


[listing]
----
cs1# show interface brief | grep up
.
.
Eth1/1/1      1       eth  access up      none                   100G(D) --
Eth1/1/2      1       eth  access up      none                   100G(D) --
Eth1/7        1       eth  trunk  up      none                   100G(D) --
Eth1/8        1       eth  trunk  up      none                   100G(D) --
.
.
----
. [[step26]] CS1 と CS2 の間の ISL が機能していることを確認します : 'how port-channel summary


[listing]
----
cs1# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)        Eth1/36(P)
cs1#
----
. [[step27]] クラスタ LIF がホームポートにリバートされたことを確認します。「 network interface show -role cluster 」


[listing]
----
cluster1::*> network interface show -role cluster
        Logical            Status     Network           Current     Current Is
Vserver Interface          Admin/Oper Address/Mask      Node        Port    Home
------- ------------------ ---------- ----------------- ----------- ------- ----
Cluster
        cluster1-01_clus1  up/up      169.254.3.4/23    cluster1-01  e0d   true
        cluster1-01_clus2  up/up      169.254.3.5/23    cluster1-01  e0d   true
        cluster1-02_clus1  up/up      169.254.3.8/23    cluster1-02  e0d   true
        cluster1-02_clus2  up/up      169.254.3.9/23    cluster1-02  e0d   true
        cluster1-03_clus1  up/up      169.254.1.3/23    cluster1-03  e3b   true
        cluster1-03_clus2  up/up      169.254.1.1/23    cluster1-03  e3b   true
        cluster1-04_clus1  up/up      169.254.1.6/23    cluster1-04  e3b   true
        cluster1-04_clus2  up/up      169.254.1.7/23    cluster1-04  e3b   true
8 entries were displayed.
cluster1::*>
----
. [step28]] クラスタが正常であることを確認します : cluster show


[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------- -------
cluster1-01          true    true          false
cluster1-02          true    true          false
cluster1-03          true    true          true
cluster1-04          true    true          false
4 entries were displayed.
cluster1::*>
----
. [[step29]] リモートクラスタインタフェースに ping を実行して接続を確認します : cluster ping-cluster -node local


[listing]
----
cluster1::*> cluster ping-cluster -node local
Host is cluster1-03
Getting addresses from network interface table...
Cluster cluster1-03_clus1 169.254.1.3 cluster1-03 e3a
Cluster cluster1-03_clus2 169.254.1.1 cluster1-03 e3b
Cluster cluster1-04_clus1 169.254.1.6 cluster1-04 e3a
Cluster cluster1-04_clus2 169.254.1.7 cluster1-04 e3b
Cluster cluster1-01_clus1 169.254.3.4 cluster1-01 e3a
Cluster cluster1-01_clus2 169.254.3.5 cluster1-01 e0d
Cluster cluster1-02_clus1 169.254.3.8 cluster1-02 e3a
Cluster cluster1-02_clus2 169.254.3.9 cluster1-02 e0d
Local = 169.254.1.3 169.254.1.1
Remote = 169.254.1.6 169.254.1.7 169.254.3.4 169.254.3.5 169.254.3.8 169.254.3.9
Cluster Vserver Id = 4294967293
Ping status:
............
Basic connectivity succeeds on 12 path(s)
Basic connectivity fails on 0 path(s)
................................................
Detected 9000 byte MTU on 12 path(s):
    Local 169.254.1.3 to Remote 169.254.1.6
    Local 169.254.1.3 to Remote 169.254.1.7
    Local 169.254.1.3 to Remote 169.254.3.4
    Local 169.254.1.3 to Remote 169.254.3.5
    Local 169.254.1.3 to Remote 169.254.3.8
    Local 169.254.1.3 to Remote 169.254.3.9
    Local 169.254.1.1 to Remote 169.254.1.6
    Local 169.254.1.1 to Remote 169.254.1.7
    Local 169.254.1.1 to Remote 169.254.3.4
    Local 169.254.1.1 to Remote 169.254.3.5
    Local 169.254.1.1 to Remote 169.254.3.8
    Local 169.254.1.1 to Remote 169.254.3.9
Larger than PMTU communication succeeds on 12 path(s)
RPC status:
6 paths up, 0 paths down (tcp check)
6 paths up, 0 paths down (udp check)
----


==== Cisco Nexus 9336C-FX2 ストレージスイッチに RCF をインストールします

リファレンス構成ファイル（ RCF ）は、 Cisco Nexus 9336C-FX2 ストレージスイッチでアップグレードできます。



===== 作業を開始する前に

ストレージスイッチの RCF をアップグレードする前に、次の条件が満たされている必要があります。

* スイッチが完全に機能している必要があります（ログにエラーがないか、または同様の問題が発生していないか）。
* NX-OS だけをインストールして現在の RCF バージョンをそのまま使用する場合は、目的のブートイメージを反映するように、 RCF で必要なブート変数を確認または設定しておく必要があります。
* 現在のブートイメージを反映するようにブート変数を変更する必要がある場合は、あとでリブートしたときに正しいバージョンがインスタンス化されるように、 RCF を再適用する前に変更する必要があります。
* Cisco ストレージのアップグレードおよびダウングレード手順の詳細なドキュメントについては、 Cisco の Web サイトで入手可能な、適切なソフトウェアおよびアップグレードガイドを参照しておく必要があります。を参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9336c-fx2-switch/model.html["Cisco Nexus 9000 シリーズスイッチ"] を参照してください。
* 100GbE ポートの数は、で使用可能なリファレンス構成ファイル（ RCF ）で定義されています https://mysupport.netapp.com/site/info/cisco-ethernet-switch["Cisco イーサネットスイッチ"] ページ




===== 手順のまとめ

. スイッチとポートのヘルスステータスの確認（手順 1~4 ）
. NX-OS イメージを Cisco スイッチ st2 にダウンロードし、リブートします（手順 5 ～ 8 ）。
. RCF を Cisco スイッチ st2 にコピーする（手順 9-12 ）
. スイッチとポートのヘルスステータスを再確認する（手順 13 ~ 15 ）
. Cisco スイッチ st1 について、手順 1 ～ 15 を繰り返します。



NOTE: コマンド出力は、 ONTAP のリリースによって異なる場合があります。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 2 つのストレージスイッチの名前は _st1_and _st2__ です。
* ノードは、 _ node1 _ と _ node2 _ です。



NOTE: 手順では、 ONTAP コマンドと Cisco Nexus 9000 シリーズスイッチコマンドの両方を使用する必要があります。特に明記されていないかぎり、 ONTAP コマンドを使用します。



===== 手順

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
x は、メンテナンス時間の長さ（時間単位）です。

. ストレージスイッチが使用可能であることを確認します。「 system switch ethernet show


[listing]
----
storage::*> system switch ethernet show
Switch                    Type               Address          Model
------------------------- ------------------ ---------------- ---------------
st1
                          storage-network    172.17.227.5     NX9-C9336C
      Serial Number: FOC221206C2
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
st2
                          storage-network    172.17.227.6     NX9-C9336C
      Serial Number: FOC220443LZ
       Is Monitored: true
             Reason: None
   Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                     9.3(5)
     Version Source: CDP
2 entries were displayed.
storage::*>
----
. [[step3]] ノードポートが正常で動作していることを確認します。「 storage port show -port-type enet 」


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                            VLAN
Node     Port   Type    Mode       (Gb/s)     State     Status        ID
------- ------- ------- ---------- ---------- --------- ----------- -----
node1
        e3a     ENET    storage    100        enabled   online         30
        e3b     ENET    storage      0        enabled   offline        30
        e7a     ENET    storage      0        enabled   offline        30
        e7b     ENET    storage    100        enabled   online         30
node2
        e3a     ENET    storage    100        enabled   online         30
        e3b     ENET    storage      0        enabled   offline        30
        e7a     ENET    storage      0        enabled   offline        30
        e7b     ENET    storage    100        enabled   online         30
----
. [[step4] クラスタにストレージスイッチやケーブル接続の問題がないことを確認します：「 system health alert show -instance 」


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step5] NX-OS イメージをスイッチ st2 にダウンロードします。
. システムイメージをインストールして、次回スイッチ st2 をリブートしたときに新しいバージョンがロードされるようにします。次の出力に示すように、スイッチは 10 秒後に新しいイメージでリブートされます。


[listing]
----
st2# install all nxos bootflash:nxos.9.3. 5.bin
Installer will perform compatibility check first. Please wait.
Installer is forced disruptive
Verifying image bootflash:/nxos.9.3.4.bin for boot variable "nxos".
[####################] 100% -- SUCCESS
Verifying image type.
[[####################] 100% -- SUCCESS
Preparing "nxos" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS
Preparing "bios" version info using image bootflash:/nxos.9.3.4.bin.
[####################] 100% -- SUCCESS
Performing module support checks.
[####################] 100% -- SUCCESS
Notifying services about system upgrade.
[####################] 100% -- SUCCESS
Compatibility check is done:
Module  bootable  Impact  Install-type  Reason
------    --------   ----- --------   ------------   ---- --
     1        yes      disruptive         reset  default upgrade is not hitless
Images will be upgraded according to following table:
Module Image        Running-Version(pri:alt)               New-Version  Upg
                                                                        Required
------ --------  ---------------------------------------  ------------  --------
 1     nxos                                     9.3(3)          9.3(4)       yes
 1     bios      v08.37(01/28/2020):v08.23(09/23/2015)   v08.38(05/29/2020)   no
Switch will be reloaded for disruptive upgrade.
Do you want to continue with the installation (y/n)? [n] y
input string too long
Do you want to continue with the installation (y/n)? [n] y
Install is in progress, please wait.
Performing runtime checks.
[####################] 100% -- SUCCESS
Setting boot variables.
[####################] 100% -- SUCCESS
Performing configuration copy.
[####################] 100% -- SUCCESS
Module 1: Refreshing compact flash and upgrading bios/loader/bootrom.
Warning: please do not remove or power off the module at this time.
[####################] 100% -- SUCCESS
Finishing the upgrade, switch will reboot in 10 seconds.
st2#
----
. [[step7] 設定を保存します。
+
次の例に示すように、システムをリブートするように求められます。



[listing]
----
st2# copy running-config startup-config
[########################################] 100% Copy complete.
st2# reload
This command will reboot the system. (y/n)? [n] y
----
. [[step8] 新しい NX-OS バージョン番号がスイッチ上にあることを確認します。


[listing]
----
st2# show version
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Upgrading a Cisco Nexus 9336C Storage Switch 6
Upgrading a Cisco Nexus 9336C storage switch
Copyright (C) 2002-2020, Cisco and/or its affiliates.
All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under their own
licenses, such as open source. This software is provided "as is," and unless otherwise stated, there is no warranty, express or implied, including but not limited to warranties of merchantability and fitness for a particular purpose.
Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or
GNU General Public License (GPL) version 3.0 or the GNU
Lesser General Public License (LGPL) Version 2.1 or
Lesser General Public License (LGPL) Version 2.0.
A copy of each such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://opensource.org/licenses/gpl-3.0.html and
http://www.opensource.org/licenses/lgpl-2.1.php and
.
Software
 BIOS: version 08.38
 NXOS: version 9.3(5)
 BIOS compile time: 05/29/2020
 NXOS image file is: bootflash:///nxos.9.3. 5.bin
 NXOS compile time: 4/28/2020 21:00:00 [04/29/2020 02:28:31]
Hardware
 cisco Nexus9000 C9336C Chassis (Nexus 9000 Series)
 Intel(R) Xeon(R) CPU E5-2403 v2 @ 1.80GHz with 8154432 kB of memory.
 Processor Board ID FOC20291J6K
 Device name: S2
 bootflash: 53298520 kB
Kernel uptime is 0 day(s), 0 hour(s), 3 minute(s), 42 second(s)
Last reset at 157524 usecs after Mon Nov 2 18:32:06 2020
           Reason: Reset due to upgrade
   System version: 9.3(5)
   Service:
plugin
   Core Plugin, Ethernet Plugin
   Active Package(s):
st2#
----
. [[step9] スイッチ st2 の RCF をスイッチのブートフラッシュにコピーします。 FTP 、 HTTP 、 TFTP 、 SFTP 、 SCP のいずれかの転送プロトコルを使用します。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。

+
次に、 HTTP を使用して、 RCF をスイッチ st2 のブートフラッシュにコピーする例を示します。



[listing]
----
st2# copy http://172.16.10.1//cfg/Nexus_9336C_RCF_v1.6-Storage.txt bootflash: vrf management
% Total % Received % Xferd   Average   Speed  Time   Time   Time
Current
   Dload     Upload  Total Spent   Left
Speed
 100    3254          100     3254      0       0     8175    0 --:--:-- --:--:-- --:--:–
8301
Copy complete, now saving to disk (please wait)...
Copy complete.
st2#
----
. [[step10] 以前にブートフラッシュにダウンロードした RCF を適用します。「 copy bootflash` 」
+
次の例は、 RCF ファイル「 Nexus_9336C_rcf_v1.6 -Storage.txt 」をスイッチ st2 にインストールする例を示しています。



[listing]
----
st2# copy Nexus_9336C_RCF_v1.6-Storage.txt running-config echo-commands
----
. [[step11]] RCF ファイルが正しい新しいバージョンであることを確認します :'how running-config
+
出力をチェックして正しい RCF があることを確認する場合は、次の情報が正しいことを確認してください。

+
** RCF バナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールした RCF に固有の変更がないかリリースノートを参照してください。

+
* 重要： * 「 How banner motd 」コマンドのバナー出力で、「重要な注意事項」セクションの指示を読んで、スイッチの設定と操作が適切であることを確認してください。





[listing]
----
st2# show banner motd
******************************************************************************
*NetApp Reference Configuration File (RCF)
*
*Switch : Nexus N9K-C9336C-FX2
*Filename : Nexus_9336C_RCF_v1.6-Storage.txt
* Date : 10-23-2020
*Version  : v1.6
*
*Port Usage: Storage configuration
*Ports 1-36: 100GbE Controller and Shelf Storage Ports
*
*IMPORTANT NOTES*
*- This RCF utilizes QoS and requires TCAM re-configuration, requiring RCF
*to be loaded twice with the Storage Switch rebooted in between.
*
*- Perform the following 4 steps to ensure proper RCF installation:
*
*(1) Apply RCF first time, expect following messages:
*- Please save config and reload the system...
*- Edge port type (portfast) should only be enabled on ports...
*- TCAM region is not configured for feature QoS class IPv4 ingress...
*
*(2) Save running-configuration and reboot Cluster Switch
*
*(3) After reboot, apply same RCF second time and expect following messages:
*- % Invalid command at '^' marker
*- Syntax error while parsing...
*
*(4) Save running-configuration again
******************************************************************************
st2#
----
. [[step12]] ソフトウェアのバージョンとスイッチの設定が正しいことを確認したら、スイッチ st2 の startup-config ファイルに running-config ファイルをコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。

+
次に 'running-config' ファイルが 'artup-config ファイルに正常にコピーされた例を示します



[listing]
----
st2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [[step13]] 再起動後にストレージスイッチが使用可能であることを再確認します : 'system switch ethernet show


[listing]
----
storage::*> system switch ethernet show
Switch                       Type               Address          Model
---------------------------- ------------------ ---------------- ---------------
st1
                            storage-network     172.17.227.5     NX9-C9336C
     Serial Number: FOC221206C2
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
st2
                            storage-network      172.17.227.6    NX9-C9336C
     Serial Number: FOC220443LZ
      Is Monitored: true
            Reason: None
  Software Version: Cisco Nexus Operating System (NX-OS) Software, Version
                    9.3(5)
    Version Source: CDP
2 entries were displayed.
storage::*
----
. [[step14]] リブート後にスイッチポートが正常で動作していることを確認します。「 storage port show -port-type enet 」


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                            VLAN
Node    Port    Type    Mode       (Gb/s)      State     Status       ID
------- ------- ------- ---------- ----------- --------- --------- -----
node1
        e3a     ENET    storage           100   enabled   online       30
        e3b     ENET    storage             0   enabled   offline      30
        e7a     ENET    storage             0   enabled   offline      30
        e7b     ENET    storage           100   enabled   online       30
node2
        e3a     ENET    storage           100   enabled   online       30
        e3b     ENET    storage             0   enabled   offline      30
        e7a     ENET    storage             0   enabled   offline      30
        e7b     ENET    storage           100   enabled   online       30
----
. [[step15]] クラスタにストレージスイッチやケーブル接続に問題がないことを再確認します : 'system health alert show-instance


[listing]
----
storage::*> system health alert show -instance
There are no entries matching your query.
----
. [[step16]] スイッチ st1 の手順に対して、この手順を繰り返します。
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージ「 system node AutoSupport invoke -node * -type all -message MAINT=end 」を呼び出して作成を再度有効にします




==== Cisco Nexus 9336C-FX2 共有スイッチに RCF をインストールします

ONTAP 9.9.9..1 から、 Cisco Nexus 9336C-FX2 スイッチを使用して、ストレージとクラスタの機能を共有スイッチシナリオに結合できます。



===== 作業を開始する前に

* クラスタスイッチが完全に機能している必要があります（ログにエラーがあるなどの問題が発生していない）。
* ストレージスイッチが完全に機能している必要があります（ログにエラーが記録されていないか、または同様の問題が発生していないことが必要です）。
* 2 つのストレージスイッチの名前は _sh1_and _sh2_.
* ここで使用した例は、新しいスイッチに共有 RCF をロードします。




===== 手順

. FTP 、 HTTP 、 TFTP 、 SFTP 、 SCP のいずれかの転送プロトコルを使用して、スイッチ sh2 上の RCF をスイッチブートフラッシュにコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。

+
次に、 HTTP を使用して、 RCF をスイッチ sh2 のブートフラッシュにコピーする例を示します。



[listing]
----
sh2# copy http://172.16.10.1//cfg/Nexus_9336C_RCF_v1.7-Cluster-Ha-Storage.txt bootflash: vrf management
% Total % Received % Xferd   Average   Speed  Time   Time   Time
Current
   Dload     Upload  Total Spent   Left
Speed
 100    5143          100     5143      0       0     11300    0 --:--:-- --:--:-- --:--:–
11300
Copy complete, now saving to disk (please wait)...
Copy complete.
sh2#
----
. [step2] 以前にブートフラッシュにダウンロードした RCF を適用します。
+
次に、スイッチ sh2 に RCF ファイル「 Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt 」をインストールする例を示します。



[listing]
----
sh2# copy Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt running-config echo-commands
----
. [[step3]] RCF ファイルが正しい新しいバージョンであることを確認します : 'how running-config
+
出力をチェックして正しい RCF があることを確認する場合は、次の情報が正しいことを確認してください。

+
** RCF バナー
** ノードとポートの設定
** カスタマイズ
+
出力内容はサイトの構成によって異なります。ポートの設定を確認し、インストールした RCF に固有の変更がないかリリースノートを参照してください。

+
* 重要： * 「 How banner motd 」コマンドのバナー出力で、「重要な注意事項」セクションの指示を読んで、スイッチの設定と操作が適切であることを確認してください。





[listing]
----
sh2# show banner motd
******************************************************************************
*NetApp Reference Configuration File (RCF)
*
*Switch : Nexus N9K-C9336C-FX2
*Filename : Nexus_9336C_RCF_v1.7-Cluster-HA-Storage.txt
* Date :  Jan-08-2021
*Version  : v1.7
*
*Port Usage:
*Ports  1-8: 40/100GbE Intra-Cluster/HA Ports, int e1/1-8
*Port     9: 10GbE breakout Intra-Cluster Ports, int e1/9/1-4
*Port    10: 25GbE breakout Intra-Cluster/HA Ports, int e1/10/1-4
*Ports 11-22: First HA-pair Controller and Shelf Storage Ports, int e1/11-22
*Ports 23-34: Second HA-pair Controller and Shelf Storage Ports, int e1/23-34
*Ports 35-36: Intra-Cluster ISL Ports, int e1/35-36
*
* Undo breakout commands and return interfaces to 40/100G configuration in
* config mode:
* no interface breakout module 1 port 9 map 10g-4x
* no interface breakout module 1 port 10 map 25g-4x
* interface Ethernet 1/9-10
* inherit port-profile CLUSTER_HA
* priority-flow-control mode auto
* service-policy type qos input HA_POLICY
* exit
*
*IMPORTANT NOTES*
* In certain conditions, N9K-C9336C-FX2 may not be able to auto-negotiate port
* speed correctly, and port speed must be manually set, in config mode, e.g.
* int e1/1
* speed 40000
* int e1/3
* speed 100000
*
******************************************************************************
sh2#
----
. [[step4]] ソフトウェアのバージョンとスイッチの設定が正しいことを確認したら、スイッチ sh2 の startup-config ファイルに「 running-config 」ファイルをコピーします。
+
Cisco コマンドの詳細については、『』の該当するガイドを参照してください https://www.cisco.com/c/en/us/support/switches/nexus-9000-series-switches/products-command-reference-list.html["Cisco Nexus 9000 シリーズ NX-OS コマンドリファレンスガイド"]。

+
次に 'running-config' ファイルが 'artup-config ファイルに正常にコピーされた例を示します



[listing]
----
sh2# copy running-config startup-config
[########################################] 100% Copy complete.
----
. [[step5] スイッチ sh1 の手順に対して、この を繰り返します。

