---
sidebar: sidebar 
permalink: switch-cisco-9336c-shared/9336c_replace_a_cisco_nexus_9336c-fx2_shared_switch.html 
keywords:  
summary:  
---
= Cisco Nexus 9336C-FX2 共有スイッチを交換します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/




==== Cisco Nexus 9336C-FX2 共有スイッチを交換します

障害のある Nexus 9336C-FX2 共有スイッチの交換は、無停止手順（ NDU ）です。



===== 作業を開始する前に

現在の環境および交換用スイッチでスイッチの交換を実行する前に、次の条件が満たされている必要があります。

* 既存のクラスタとネットワークインフラ：
+
** 既存のクラスタで、少なくとも 1 つのクラスタスイッチが完全に接続されており、完全に機能することを確認する必要があります。
** すべてのクラスタポートが稼働している必要があります。
** すべてのクラスタ LIF （論理インターフェイス）が、 * up * で、ホームポートにある必要があります。
** ONTAP cluster ping-cluster -node node1 コマンドは、すべてのパスで基本的な接続と larger than PMTU communication が成功したことを示す必要があります。


* Nexus 9336C-FX2 交換スイッチ：
+
** 交換用スイッチの管理ネットワーク接続が機能している必要があります。
** 交換用スイッチへのコンソールアクセスが確立されている必要があります。
** ノード接続はポート 1/1~1/34 です。
** ポート 1/35 および 1/36 では、すべてのスイッチ間リンク（ ISL ）ポートを無効にする必要があります。
** 必要なリファレンス構成ファイル（ RCF ）と NX-OS オペレーティングシステムのイメージスイッチをスイッチにロードする必要があります。
** STP 、 SNMP 、 SSH などの以前のサイトのカスタマイズは、すべて新しいスイッチにコピーする必要があります。






===== このタスクについて

クラスタ LIF を移行するコマンドは、そのクラスタ LIF がホストされているノードで実行する必要があります。

この手順の例では、スイッチとノードで次の命名法を使用しています。

* 既存の Nexus 9336C-FX2 スイッチの名前は、 _sh1_and _sh2__ です。
* 新しい Nexus 9336C-FX2 スイッチの名前は _newsh1_and _newsh2_です 。
* ノード名は _node1_AND _node2 _ です。
* 各ノードのクラスタポートの名前は _e3a および _e3b _ です。
* クラスタ LIF 名は、 node1 の場合は「 node1_clus1' 」、ノード 1 の場合は「 node1_clus1' 」、 node2 の場合は「 node2 _ clus2 」です。
* すべてのクラスタノードへの変更を求めるプロンプトは、 cluster1 ： * > です。



NOTE: 次の手順は、次のネットワークトポロジに基づいています。

[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false

Node: node2
                                                                        Ignore
                                                  Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000  auto/100000 healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000 healthy  false
4 entries were displayed.


cluster1::*> network interface show -vserver Cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::*> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1                       Eth1/2            N9K-C9336C
            e3b    sh2                       Eth1/2            N9K-C9336C

node1      /cdp
            e3a    sh1                       Eth1/1            N9K-C9336C
            e3b    sh2                       Eth1/1            N9K-C9336C
4 entries were displayed.

sh1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         144    H           FAS2980       e3a
node2              Eth1/2         145    H           FAS2980       e3a
sh2                Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
sh2 (FDO220329V5)   Eth1/36       176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       eb
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----


===== 手順

. このクラスタで AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT= xh
+
x は、メンテナンス時間の長さ（時間単位）です。

. オプション：スイッチ newsh2 に適切な RCF とイメージをインストールし、必要なサイトの準備を行います。
+
.. 必要に応じて、新しいスイッチ用に、 RCF および NX-OS ソフトウェアの適切なバージョンを確認、ダウンロード、およびインストールします。新しいスイッチが正しくセットアップされており、 RCF および NX-OS ソフトウェアの更新が不要であることを確認した場合は、に進みます <<step3,手順 3>>。
.. ネットアップサポートサイトのネットアップクラスタおよび管理ネットワークスイッチリファレンス構成ファイルの概要ページにアクセスします。
.. Cluster Network and Management Network Compatibility Matrix のリンクをクリックし、必要なスイッチソフトウェアのバージョンを確認します。
.. ブラウザの戻る矢印をクリックして概要ページに戻り、 [ 続行 ] をクリックしてライセンス契約に同意し、 [ ダウンロード ] ページに移動します。
.. ダウンロードページの手順に従って、インストールする ONTAP ソフトウェアのバージョンに対応した正しい RCF ファイルと NX-OS ファイルをダウンロードします。


. [[step3]] 新しいスイッチで admin としてログインし、ノードクラスタインターフェイス（ポート 1/1~1/34 ）に接続するすべてのポートをシャットダウンします。交換するスイッチが機能せず、電源がオフになっている場合は、に進みます <<step4,手順 4>>。クラスタノードの LIF は、各ノードのもう一方のクラスタポートにすでにフェイルオーバーされている必要があります。


[listing]
----
newsh2# config
Enter configuration commands, one per line. End with CNTL/Z.
newsh2(config)# interface e1/1-34
newsh2(config-if-range)# shutdown
----
. [[step4]] すべてのクラスタ LIF で自動リバートが有効になっていることを確認します。network interface show -vserver Cluster -fields auto-revert を実行します


[listing]
----
cluster1::> network interface show -vserver Cluster -fields auto-revert
             Logical
Vserver      Interface     Auto-revert
------------ ------------- -------------
Cluster      node1_clus1   true
Cluster      node1_clus2   true
Cluster      node2_clus1   true
Cluster      node2_clus2   true
4 entries were displayed.
----
. [[step5] すべてのクラスタ LIF が通信できることを確認します。 cluster ping-cluster <node name>


[listing]
----
cluster1::*> cluster ping-cluster node1
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step6] Nexus 9336C-FX2 スイッチ sh1 の ISL ポート 1/35 および 1/36 をシャットダウンします。


[listing]
----
sh1# configure
Enter configuration commands, one per line. End with CNTL/Z.
sh1(config)# interface e1/35-36
sh1(config-if-range)# shutdown
sh1(config-if-range)#
----
. [[step7] すべてのケーブルを Nexus 9336C-FX2 sh2 スイッチから取り外し、 Nexus C9336C-FX2 newsh2 スイッチの同じポートに接続します。
. sh1 スイッチと newsh2 スイッチの間で ISL ポート 1/35 と 1/36 を起動し、ポートチャネルの動作ステータスを確認します。
+
ポートチャネルは Po1 （ SU ）を示し、メンバーポートは Eth1/35 （ P ）および Eth1/36 （ P ）を示している必要があります。

+
次の例では、 ISL ポート 1/35 および 1/36 をイネーブルにし、スイッチ sh1 のポートチャネルの概要を表示します。



[listing]
----
sh1# configure
Enter configuration commands, one per line. End with CNTL/Z.
sh1 (config)# int e1/35-36
sh1 (config-if-range)# no shutdown
sh1 (config-if-range)# show port-channel summary
Flags:  D - Down        P - Up in port-channel (members)
        I - Individual  H - Hot-standby (LACP only)
        s - Suspended   r - Module-removed
        b - BFD Session Wait
        S - Switched    R - Routed
        U - Up (port-channel)
        p - Up in delay-lacp mode (member)
        M - Not in use. Min-links not met
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member       Ports
      Channel
--------------------------------------------------------------------------------
1     Po1(SU)     Eth      LACP      Eth1/35(P)   Eth1/36(P)

sh1 (config-if-range)#
----
. [[step9] すべてのノードでポート e3b が稼働していることを確認します「 network port show ipspace Cluster 」
+
出力は次のようになります。



[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ---------- - - -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                         Ignore
                                                   Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ----- ----------- -  -------- ----
e3a       Cluster      Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000  auto/auto    -        false
4 entries were displayed.
----
. [[step10]] 前の手順で使用したノードで、 network interface revert コマンドを使用して、前の手順でポートに関連付けられているクラスタ LIF をリバートします。
+
この例では、 Home の値が true でポート番号が e3b である場合、ノード 1 の LIF node1_clus2 は正常にリバートされています。

+
次のコマンドは、 node1 の LIF node1_clus2 をホームポート e3a に返し、両方のノードの LIF に関する情報を表示します。両方のクラスタインターフェイスの Is Home 列が * true であり、この例では e3a および node1 の e3b で正しいポート割り当てが示されている場合、最初のノードの起動は成功します。



[listing]
----
cluster1::*> network interface show -vserver Cluster

            Logical      Status     Network            Current    Current Is
Vserver     Interface    Admin/Oper Address/Mask       Node       Port    Home
----------- ------------ ---------- ------------------ ---------- ------- -----
Cluster
            node1_clus1  up/up      169.254.209.69/16  node1      e3a     true
            node1_clus2  up/up      169.254.49.125/16  node1      e3b     true
            node2_clus1  up/up      169.254.47.194/16  node2      e3a     true
            node2_clus2  up/up      169.254.19.183/16  node2      e3a     false
4 entries were displayed.
----
. [[step11]] クラスタ内のノードに関する情報を表示します : 'cluster show`
+
次の例では、このクラスタのノード node1 と node2 のノードの健常性が true であることを示します。



[listing]
----
cluster1::*> cluster show
Node          Health  Eligibility
------------- ------- ------------
node1         false   true
node2         true    true
----
. [[step12]] すべての物理クラスタポートが起動していることを確認します :`network port show ipspace Cluster`


[listing]
----
cluster1::*> network port show -ipspace Cluster

Node node1                                                                Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace     Broadcast Domain  Link  MTU   Admin/Oper   Status   Status
--------- ----------- ----------------- ----- ----- ------------ -------- ------
e3a       Cluster     Cluster           up    9000  auto/100000  healthy  false
e3b       Cluster     Cluster           up    9000  auto/100000  healthy  false

Node: node2
                                                                          Ignore
                                                    Speed(Mbps)  Health   Health
Port      IPspace      Broadcast Domain Link  MTU   Admin/Oper   Status   Status
--------- ------------ ---------------- ----- ----- ------------ -------- ------
e3a       Cluster      Cluster          up    9000  auto/100000  healthy  false
e3b       Cluster      Cluster          up    9000  auto/100000  healthy  false
4 entries were displayed.
----
. [[step13]] すべてのクラスタ LIF が通信できることを確認します :'cluster ping-cluster


[listing]
----
cluster1::*> cluster ping-cluster -node node2
Host is node2
Getting addresses from network interface table...
Cluster node1_clus1 169.254.209.69 node1 e3a
Cluster node1_clus2 169.254.49.125 node1 e3b
Cluster node2_clus1 169.254.47.194 node2 e3a
Cluster node2_clus2 169.254.19.183 node2 e3b
Local = 169.254.47.194 169.254.19.183
Remote = 169.254.209.69 169.254.49.125
Cluster Vserver Id = 4294967293
Ping status:
....
Basic connectivity succeeds on 4 path(s)
Basic connectivity fails on 0 path(s)
................
Detected 9000 byte MTU on 4 path(s):
Local 169.254.47.194 to Remote 169.254.209.69
Local 169.254.47.194 to Remote 169.254.49.125
Local 169.254.19.183 to Remote 169.254.209.69
Local 169.254.19.183 to Remote 169.254.49.125
Larger than PMTU communication succeeds on 4 path(s)
RPC status:
2 paths up, 0 paths down (tcp check)
2 paths up, 0 paths down (udp check)
----
. [[step14]] 次のクラスタネットワーク構成を確認します : 「 network port show 」


[listing]
----
cluster1::*> network port show -ipspace Cluster

Node: node1
                                                                        Ignore
                                       Speed(Mbps)             Health   Health
Port      IPspace     Broadcast Domain Link MTU   Admin/Oper   Status   Status
--------- ----------- ---------------- ---- ----- ------------ -------- ------
e3a       Cluster     Cluster          up   9000  auto/100000  healthy  false
e3b       Cluster     Cluster          up   9000  auto/100000  healthy  false

Node: node2
                                                                        Ignore
                                        Speed(Mbps)            Health   Health
Port      IPspace      Broadcast Domain Link MTU  Admin/Oper   Status   Status
--------- ------------ ---------------- ---- ---- ------------ -------- ------
e3a       Cluster      Cluster          up   9000 auto/100000  healthy  false
e3b       Cluster      Cluster          up   9000 auto/100000  healthy  false
4 entries were displayed.

cluster1::*> network interface show -vserver Cluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
Cluster
            node1_clus1  up/up    169.254.209.69/16  node1         e3a     true
            node1_clus2  up/up    169.254.49.125/16  node1         e3b     true
            node2_clus1  up/up    169.254.47.194/16  node2         e3a     true
            node2_clus2  up/up    169.254.19.183/16  node2         e3b     true
4 entries were displayed.

cluster1::> network device-discovery show -protocol cdp
Node/       Local  Discovered
Protocol    Port   Device (LLDP: ChassisID)  Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
node2      /cdp
            e3a    sh1    0/2               N9K-C9336C
            e3b    newsh2                    0/2               N9K-C9336C
node1      /cdp
            e3a    sh1                       0/1               N9K-C9336C
            e3b    newsh2                    0/1               N9K-C9336C
4 entries were displayed.

sh1# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID            Local Intrfce  Hldtme Capability  Platform      Port ID
node1                Eth1/1         144    H           FAS2980       e3a
node2                Eth1/2         145    H           FAS2980       e3a
newsh2               Eth1/35        176    R S I s     N9K-C9336C    Eth1/35
newsh2               Eth1/36        176    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4

sh2# show cdp neighbors
Capability Codes: R - Router, T - Trans-Bridge, B - Source-Route-Bridge
                  S - Switch, H - Host, I - IGMP, r - Repeater,
                  V - VoIP-Phone, D - Remotely-Managed-Device,
                  s - Supports-STP-Dispute
Device-ID          Local Intrfce  Hldtme Capability  Platform      Port ID
node1              Eth1/1         139    H           FAS2980       e3b
node2              Eth1/2         124    H           FAS2980       eb
sh1                Eth1/35        178    R S I s     N9K-C9336C    Eth1/35
sh1                Eth1/36        178    R S I s     N9K-C9336C    Eth1/36
Total entries displayed: 4
----
. [[step15]] 次のコマンドを使用して、スイッチ関連のログファイルを収集するためのイーサネットスイッチヘルスモニタログ収集機能を有効にします。
+
** 「システムスイッチイーサネットログセットアップパスワード」
** 「システムスイッチのイーサネットログの有効化」




[listing]
----
cluster1::*> system switch ethernet log setup-password
Enter the switch name: <return>
The switch name entered is not recognized.
Choose from the following list:
sh1
sh2
cluster1::*> system switch ethernet log setup-password
Enter the switch name: sh1
RSA key fingerprint is e5:8b:c6:dc:e2:18:18:09:36:63:d9:63:dd:03:d9:cc
Do you want to continue? {y|n}::[n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system switch ethernet log setup-password
Enter the switch name: sh2
RSA key fingerprint is 57:49:86:a1:b9:80:6a:61:9a:86:8e:3c:e3:b7:1f:b1
Do you want to continue? {y|n}:: [n] y
Enter the password: <enter switch password>
Enter the password again: <enter switch password>
cluster1::*> system  switch ethernet log enable-collection
Do you want to enable cluster log collection for all nodes in the cluster? y|n}: [n] y
Enabling cluster switch log collection.
cluster1::*>
----

NOTE: これらのコマンドのいずれかでエラーが返される場合は、ネットアップサポートにお問い合わせください。

. [[step16]] 古いスイッチ sh2 のストレージポートを新しいスイッチ newsh2 に移動します。
. HA ペア 1 の共有スイッチ newsh2 に接続されたストレージが正常であることを確認します。
. HA ペア 2 の共有スイッチ newsh2 に接続されたストレージが「 storage port show -port-type enet 」が正常であることを確認します


[listing]
----
storage::*> storage port show -port-type ENET
                                   Speed                            VLAN
Node    Port    Type    Mode       (Gb/s)      State     Status       ID
------- ------- ------- ---------- ----------- --------- --------- -----
node1
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30

node2
        e3a     ENET    storage          100   enabled   online       30
        e3b     ENET    storage            0   enabled   offline      30
        e7a     ENET    storage            0   enabled   offline      30
        e7b     ENET    storage          100   enabled   online       30
----
. [[step19]] シェルフが正しくケーブル接続されていることを確認します。「 storage shelf port show -fields remote-device 、 remote-port`


[listing]
----
cluster1::*> storage shelf port show -fields remote-device,remote-port
shelf id remote-port  remote-device
----- -- ------------ ----------------------------
3.20  0  Ethernet1/13 sh1
3.20  1  Ethernet1/13 newsh2
3.20  2  Ethernet1/14 sh1
3.20  3  Ethernet1/14 newsh2
3.30  0  Ethernet1/15 sh1
3.30  1  Ethernet1/15 newsh2
3.30  2  Ethernet1/16 sh1
3.30  3  Ethernet1/16 newsh2
8 entries were displayed.
----
. [[step20]] 古いスイッチ sh2 を削除します。
. スイッチ sh1 と新しいスイッチ newsh1 について、上記の手順を繰り返します。
. ケースの自動作成を抑制した場合は、 AutoSupport メッセージを呼び出して再度有効にします。「 system node AutoSupport invoke -node * -type all -message MAINT=end

