---
settings:
  search: ontap-systems
  name: Install and maintain
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  langs: ja-jp,us-en,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: AFF および FAS システムのドキュメント
    url: "/index.html"
  - title: はじめに
    entries:
    - title: 新機能
      url: "/whats-new.html"
    - title: リリースノート
      url: "/rel-notes.html"
  - title: AFF システム
    entries:
    - section: c190
    - section: a200
    - section: a220
    - section: a250
    - section: a300
    - section: a320
    - section: a400
    - section: a700
    - section: a700s
    - section: a800
    - section: a900
  - title: FAS システム
    entries:
    - section: fas500f
    - section: fas2600
    - section: fas2700
    - section: fas8200
    - section: fas8300
    - section: fas9000
    - section: fas9500
  - section: allsan
  - section: upgrade
  - title: システムレベルの診断
    entries:
    - title: はじめに
      url: "/platform-supplemental/sldiag-introduction.html"
    - title: 要件
      url: "/platform-supplemental/sldiag-requirements.html"
    - title: コマンドラインヘルプの使用方法
      url: "/platform-supplemental/sldiag-use-cli-help.html"
    - title: システムのインストール診断を実行します
      url: "/platform-supplemental/sldiag-system-installation-diagnostics.html"
    - title: システムパニック診断を実行します
      url: "/platform-supplemental/sldiag-system-panic-diagnostics.html"
    - title: システム応答の遅延診断を実行します
      url: "/platform-supplemental/sldiag-slow-system-diagnostics.html"
    - title: ハードウェアの設置診断を実行します
      url: "/platform-supplemental/sldiag-hardware-installation-diagnostics.html"
    - title: デバイス障害診断を実行します
      url: "/platform-supplemental/sldiag-device-failure-diagnostics.html"
  - title: ドライブシェルフ
    entries:
    - section: ns224
    - section: sas3
  - section: switch
  - title: キャビネットおよびレールキット
    entries:
    - title: SuperRail キット
      url: "/platform-supplemental/superrail-install.html"
    - title: AFF A700 / FAS9000 2 ポストレールキット
      url: "/platform-supplemental/telco-installation-instructions.html"
    - title: 42U 1280 mm システムキャビネット
      entries:
      - title: キャビネットを設置する準備をします
        entries:
        - title: キャビネットの機能
          url: "/platform-supplemental/42u-1280mm-features.html"
        - title: 必要な工具 / 機器
          url: "/platform-supplemental/42u-1280mm-required-tools.html"
        - title: 必要なスペースとキャビネットの寸法
          url: "/platform-supplemental/42u-1280mm-space-and-dimensions.html"
        - title: サポートされている PDU のタイプと仕様
          url: "/platform-supplemental/42u-1280mm-supported-pdu-types-and-specifications.html"
      - title: システムキャビネットを開梱します
        url: "/platform-supplemental/42u-1280mm-unpack.html"
      - title: キャビネットを設置
        entries:
        - title: 概要
          url: "/platform-supplemental/42u-1280mm-install.html"
        - title: キャビネットインターコネクトキットを設置
          url: "/platform-supplemental/42u-1280mm-install-cabinet-interconnect-kit.html"
        - title: ボルトダウンキットを取り付ける
          url: "/platform-supplemental/42u-1280mm-install-bolt-down-kit.html"
        - title: サポートレールを取り付けます
          url: "/platform-supplemental/42u-1280mm-install-additional-rails.html"
        - title: 機器を設置します
          url: "/platform-supplemental/42u-1280mm-install-equipment.html"
        - title: キャビネットの電源をオンにします
          url: "/platform-supplemental/42u-1280mm-power-on.html"
      - title: PDU を交換します
        url: "/platform-supplemental/42u-1280mm-replace-pdus.html"
      - title: キャビネット前面ドアを反転します
        entries:
        - title: 必要なもの
          url: "/platform-supplemental/42u-1280mm-reverse-front-door.html"
        - title: 照光バッジを取り外します
          url: "/platform-supplemental/42u-1280mm-remove-illuminated-badge.html"
        - title: キャビネットドアを取り外します
          url: "/platform-supplemental/42u-1280mm-remove-door.html"
        - title: バッジの電源装置とケーブルを移動します
          url: "/platform-supplemental/42u-1280mm-move-badge-ps-and-cabling.html"
        - title: リバースドアヒンジとロックキャッチ
          url: "/platform-supplemental/42u-1280mm-reverse-hinge-and-lock.html"
        - title: ドアと照光バッジを再度取り付けます
          url: "/platform-supplemental/42u-1280mm-reinstall-door-and-badge.html"
  - section: other
  - title: 法的通知
    url: "/legal-notices.html"
product-family:
  name: AFF and FAS Systems
  repo: ontap-systems-family
