---
permalink: a200/replace_internal_drive.html 
sidebar: sidebar 
keywords: AFF A200 
summary: 障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。 
---
= 障害が発生したドライブを交換します - AFF A200
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムで登録される修正可能なエラー修正コード（ ECC ）の数が増え続けている場合は、コントローラモジュールの DIMM を交換する必要があります。そのままにしているとシステムがパニック状態になります。

.作業を開始する前に
* ドライブをホットスワップする前に、 Disk Qualification Package （ DQP ）の最新バージョンをインストールすることを推奨します。
* システムコンソールから「 storage disk show -broken 」コマンドを実行して、障害が発生したディスクドライブを特定してください。障害が発生したドライブが障害ドライブのリストに表示されます。表示されない場合は、少し待ってからもう一度コマンドを実行してください。
* ディスクのホットスワップ方法は、ディスクドライブの使用方法によって異なります。SED 認証が有効になっている場合は、に記載されている SED の交換手順を使用する必要があります https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["ONTAP 9 ネットアップ暗号化パワーガイド"]。SED の交換前後に行う必要のある作業についても説明しています。
* 交換用ドライブがプラットフォームでサポートされている必要があります。を参照してください https://hwu.netapp.com["NetApp Hardware Universe の略"]。
* システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。


.このタスクについて
最新のファームウェアバージョンでない新しいドライブでは、ドライブファームウェアは自動的に（無停止で）更新されます。

複数のディスクドライブを交換する場合は、ストレージシステムがそれぞれの新しいディスクを認識できるように、障害が発生した各ディスクドライブを取り外してから交換用ディスクドライブを挿入するまで 1 分間待機する必要があります。

[role="tabbed-block"]
====
.オプション 1 ： SSD を交換する
--
<stdin> で未解決のディレクティブ : ../ _include/drive_hotswap _sas .adoc[]

--
.オプション 2 ： HDD を交換
--
<stdin> で未解決のディレクティブ : ../ _include/drive_hotswap _sas .adoc.adoc[]

--
====