---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: ONTAPハードウェアシステムの新しいプラットフォームについて説明します。 
---
= ONTAPハードウェアシステムの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAPハードウェアシステムの新機能について説明します。



== 2024年12月



=== AFF A20、AFF A30、およびAFF A50

新しいAFF A20、A30、A50ハードウェアシステムは、ハイパフォーマンスでインテリジェントな包括的なデータ管理機能をより多くのお客様やワークロードに拡張します。

このシステムは、MLベースのランサムウェアのリアルタイム検出、シームレスなクラウド統合、AI、VMware、データベース、分析などのミッションクリティカルなワークロードに対して卓越したパフォーマンスを提供し、ブロック、ファイル、オブジェクトストレージをサポートします。

link:https://www.netapp.com/data-storage/aff-a-series/["AFF Aシリーズシステムの詳細"]です。



=== AFF C30、AFF C60、およびAFF C80

新しいAFF C30、AFF C60、AFF C80ハードウェアシステムは、業界をリードする1.5PBのストレージ容量を2ラック環境で提供することで、企業がフラッシュのパフォーマンスと効率性を向上できるようにします。

このソリューションは、60TBドライブによる卓越した密度、パフォーマンスの向上、I/Oの柔軟性の向上を実現します。

link:https://www.netapp.com/data-storage/aff-c-series/["AFF Cシリーズシステムに関する詳細情報"]です。



== 2024年9月



=== ASA r2システム

新しいASA R2ハードウェアシステム（ASA A1K、ASA A70、およびASA A90）は、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせてシンプルなエクスペリエンスを実現します。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。



=== FAS70およびFAS90

新しいFAS70およびFAS90ハードウェアシステムは、手頃な価格ながらハイパフォーマンスなバックアップストレージを提供し、ランサムウェア攻撃からリカバリするためのセキュアなサイバーヴォールトを実現します。

link:https://www.netapp.com/data-storage/fas/["FASシステムに関する詳細情報"]です。
