---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, asa r2, aff, asa, fas 
summary: ONTAPハードウェアシステムの新しいプラットフォームについて説明します。 
---
= ONTAPハードウェアシステムの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAPハードウェアシステムの新機能について説明します。



== 2025年5月



=== ASA C30

新しい ASA C30 システムは、高性能でインテリジェントな包括的なデータ管理機能を、より多くの顧客とワークロードに拡張します。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。



== 2025年4月



=== FAS50

FAS50システムは、セカンダリストレージのギガバイトあたりのコストが最も低く、link:https://docs.netapp.com/us-en/netapp-solutions/cyber-vault/ontap-cyber-vault-overview.html["セキュアなサイバーボールト"]さらに、高速なバックアップ、高いIOPS、5~10ミリ秒の低レイテンシによって、セカンダリワークロードのパフォーマンスが向上します。

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FASシステムに関する詳細情報"]です。



== 2025年2月



=== ASA A20、ASA A30、およびASA A50

エントリレベルのASA A20およびミッドレンジのASA A30およびA50システムは、データベースや仮想マシンなどのミッションクリティカルなアプリケーション向けに、あらゆる規模の企業がブロックストレージを利用できるようにします。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。



== 2024年12月



=== AFF A20、AFF A30、およびAFF A50

新しいAFF A20、A30、A50ハードウェアシステムは、ハイパフォーマンスでインテリジェントな包括的なデータ管理機能をより多くのお客様とワークロードに拡張します。

このシステムは、MLベースのランサムウェアのリアルタイム検出、シームレスなクラウド統合、AI、VMware、データベース、分析などのミッションクリティカルなワークロードに対して卓越したパフォーマンスを提供し、ブロック、ファイル、オブジェクトストレージをサポートします。

link:https://www.netapp.com/data-storage/aff-a-series/["AFF Aシリーズシステムの詳細"]です。



=== AFF C30、AFF C60、およびAFF C80

新しいAFF C30、AFF C60、AFF C80ハードウェアシステムは、業界をリードする1.5PBのストレージ容量を2ラック環境で提供することで、企業がフラッシュのパフォーマンスと効率性を向上できるようにします。

このソリューションは、60TBドライブによる卓越した密度、パフォーマンスの向上、I/Oの柔軟性の向上を実現します。

link:https://www.netapp.com/data-storage/aff-c-series/["AFF Cシリーズシステムに関する詳細情報"]です。



=== NSM100Bシェルフモジュールを搭載したNS224ドライブシェルフ

NS224と新しいNSM100B NVMeストレージ拡張モジュールで、データセンターの機能を強化できます。新しいNSM100Bシェルフモジュールは、NSM100モジュールの直接交換用として設計されており、既存の環境にシームレスに統合できます。NS224シェルフの直接接続型構成とスイッチ接続型構成の両方がサポートされるため、ストレージシステムの効率性と拡張性を最適化する優れた柔軟性が実現します。



== 2024年9月



=== ASA r2システム

新しいASA R2ハードウェアシステム（ASA A1K、ASA A70、およびASA A90）は、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせてシンプルなエクスペリエンスを実現します。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。



=== FAS70およびFAS90

新しいFAS70およびFAS90ハードウェアシステムは、手頃な価格ながらハイパフォーマンスなバックアップストレージを提供し、ランサムウェア攻撃からリカバリするためのセキュアなサイバーヴォールトを実現します。

link:https://www.netapp.com/data-storage/fas/["FASシステムに関する詳細情報"]です。
