---
sidebar: sidebar 
permalink: whats-new.html 
keywords: new, features, afx, asa r2, aff, asa, fas 
summary: ONTAPハードウェアシステムの新しいプラットフォームについて説明します。 
---
= ONTAPハードウェアシステムの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
ONTAPハードウェアシステムの新機能について説明します。追加のサポート情報については、 link:supported-platforms.html["ONTAPのハードウェアとソフトウェアの互換性"]そしてlink:eoa-hardware.html["サポートされなくなったハードウェア"] 。



== 2025年10月



=== AFXストレージシステム

新しいNetApp AFX ストレージ システムは、AI/ML アプリケーションを含む高性能 NAS および S3 ワークロードの厳しい要件を満たすように設計された分散型ソリューションを提供します。AFX システムは、スケーラブルで高スループットのファイルおよびオブジェクト ストレージを必要とする顧客向けに特殊な機能を提供します。

link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["AFXシステムの詳細"] 。



=== AFX用の新しいドライブシェルフ

AFX 用の新しい NXS224 ストレージ シェルフは、高密度 SSD を接続するために Non-volatile Memory Express over Fabrics (NVMe-oF) を使用します。ディスクは、RDMA over Converged Ethernet (RoCE) を使用して、超低遅延ファブリックを介して通信します。I/O モジュール、NIC、ファン、電源装置を含むストレージ シェルフは、単一障害点のない完全な冗長性を備えています。自己管理型テクノロジーは、RAID 構成とディスク レイアウトのあらゆる側面を管理および制御するために使用されます。



=== AFXの新しいスイッチ

Cisco 9364D-GX2A スイッチとCisco 9332D-GX2B スイッチは、AFX コントローラ ノードをストレージ シェルフに接続します。これらの新しいスイッチを使用すると、2 つ以上のノードを持つONTAPクラスターを構築できます。パフォーマンスを最適化するために高度なプロトコルが使用されます。この設計は、複数のネットワーク パスを使用した VLAN タグ付けと技術更新構成に基づいており、継続的な運用とアップグレードの容易さを保証します。



== 2025年9月



=== プラットフォーム仕様

ONTAPハードウェアシステムのドキュメントには、以下の仕様も含まれるようになりました。link:https://hwu.netapp.com["Hardware Universe"] 。例えば、link:https://docs.netapp.com/us-en/ontap-systems/a1k/overview.html["AFF A1Kの主な仕様"] 。



=== プラットフォームファミリー別の交換リファレンス

ONTAPハードウェア システムのドキュメントには、 NetAppストレージ システムの交換手順がプラットフォーム ファミリ別にまとめられているようになりました。

link:fru-reference/index.html["交換手順を見つける"]ストレージ システムのフィールド交換可能ユニット (FRU) 用。



== 2025年5月



=== ASA C30

新しい ASA C30 システムは、高性能でインテリジェントな包括的なデータ管理機能を、より多くの顧客とワークロードに拡張します。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"^] 。



== 2025年4月



=== FAS50

FAS50 システムは、セカンダリ ストレージと安全なサイバー ボールトのギガバイトあたりのコストが最も低いだけでなく、バックアップの高速化、IOPS の向上、5 ～ 10 ミリ秒の低レイテンシにより、セカンダリ ワークロードのパフォーマンスが向上します。

link:https://www.netapp.com/pdf.html?item=/media/7819-ds-4020.pdf["FASシステムに関する詳細情報"^] 。



== 2025年2月



=== ASA A20、ASA A30、およびASA A50

エントリレベルのASA A20およびミッドレンジのASA A30およびA50システムは、データベースや仮想マシンなどのミッションクリティカルなアプリケーション向けに、あらゆる規模の企業がブロックストレージを利用できるようにします。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"^] 。



== 2024年リリース

.2024年12月
[%collapsible]
====
.AFF A20、AFF A30、およびAFF A50
新しいAFF A20、A30、A50ハードウェアシステムは、ハイパフォーマンスでインテリジェントな包括的なデータ管理機能をより多くのお客様とワークロードに拡張します。

このシステムは、MLベースのランサムウェアのリアルタイム検出、シームレスなクラウド統合、AI、VMware、データベース、分析などのミッションクリティカルなワークロードに対して卓越したパフォーマンスを提供し、ブロック、ファイル、オブジェクトストレージをサポートします。

link:https://www.netapp.com/aff-a-series/["AFF Aシリーズシステムの詳細"^]。

.AFF C30、AFF C60、およびAFF C80
新しいAFF C30、AFF C60、AFF C80ハードウェアシステムは、業界をリードする1.5PBのストレージ容量を2ラック環境で提供することで、企業がフラッシュのパフォーマンスと効率性を向上できるようにします。

このソリューションは、60TBドライブによる卓越した密度、パフォーマンスの向上、I/Oの柔軟性の向上を実現します。

link:https://www.netapp.com/data-storage/aff-c-series/["AFF Cシリーズシステムに関する詳細情報"^] 。

.NSM100Bシェルフモジュールを搭載したNS224ドライブシェルフ
NS224と新しいNSM100B NVMeストレージ拡張モジュールで、データセンターの機能を強化できます。新しいNSM100Bシェルフモジュールは、NSM100モジュールの直接交換用として設計されており、既存の環境にシームレスに統合できます。NS224シェルフの直接接続型構成とスイッチ接続型構成の両方がサポートされるため、ストレージシステムの効率性と拡張性を最適化する優れた柔軟性が実現します。

====
.2024年9月
[%collapsible]
====
.ASA r2システム
新しいASA R2ハードウェアシステム（ASA A1K、ASA A70、およびASA A90）は、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせてシンプルなエクスペリエンスを実現します。

link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"^] 。

.FAS70およびFAS90
新しいFAS70およびFAS90ハードウェアシステムは、手頃な価格ながらハイパフォーマンスなバックアップストレージを提供し、ランサムウェア攻撃からリカバリするためのセキュアなサイバーヴォールトを実現します。

link:https://www.netapp.com/data-storage/fas/["FASシステムに関する詳細情報"^] 。

====