---
permalink: asa400/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: asa a400, how to recable the system, how to reassign disks 
summary: ストレージリソースの制御を交換用コントローラに戻すと、ASA A400 システムは通常動作を再開できます。 
---
= コントローラを返却 - ASA A400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージリソースの制御を交換用コントローラに戻すと、ASA A400 システムは通常動作を再開できます。

[role="tabbed-block"]
====
.暗号化または External Key Manager（EKM）なし
--
障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。

.手順
. Loaderプロンプトで、と入力し `boot_ontap`ます。
. コンソールメッセージが停止したら、<enter>キーを押します。
+
** _login_promptが表示されたら、このセクションの最後の次の手順に進みます。
** 「_Waiting for giveback_」と表示された場合は、<enter>キーを押してパートナーノードにログインし、このセクションの最後の次の手順に進みます。


. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。 `storage failover giveback -ofnode _impaired_node_name_`
. 自動ギブバックを無効にした場合は、再度有効にします。 `storage failover modify -node local -auto-giveback _true_`
. AutoSupportが有効になっている場合は、ケースの自動作成をリストアまたは抑制解除します。 `system node autosupport invoke -node * -type all -message MAINT=END`


--
.オンボード暗号化（OKM）
--
OKM用のオンボード暗号化キーを復元して再封印し、コントローラを正常な動作状態に戻します。

.作業を開始する前に
開始する前に、 https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-show-backup.html["security key-manager onboard show-backup"]を確認するか、NetAppサポートにお問い合わせください。

.手順
. LoaderプロンプトからONTAPメニューを起動し `boot_ontap menu`、オプション10を選択します。
. 正常なコントローラからクラスタ全体のパスフレーズを取得して検証します。
+
.. 次のコマンドを実行して、クラスタ全体のパスフレーズを取得します：
+
`security key-manager onboard show-backup`

.. 次のコマンドを使用して、クラスタ全体のパスフレーズを確認します。
+
`security key-manager onboard verify-backup`



. OKMパスフレーズを入力します。
+

NOTE: パスフレーズの入力を2回求められます。

. プロンプトが表示されたら、バックアップキーのデータを入力します。
. ブートメニューで、「option for normal boot」と入力します `1`。
. 「_Waiting for giveback_」と表示されたら、<enter>キーを押します。
. パートナーノードにコンソールケーブルを接続し、としてログインします `admin`。
. CFOアグリゲート（ルートアグリゲート）のみをギブバックします。 `storage failover giveback -fromnode local -only-cfo-aggregates _true_`
+
** エラーが発生した場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。


. ギブバックレポートが完了してから5分待って、フェイルオーバーのステータスとギブバックのステータスを確認します（および `storage failover show-giveback`） `storage failover show`。
. キーの同期とステータスの確認を行います。
+
.. コンソールケーブルを交換用コントローラに戻します。
.. 欠落しているキーの同期： `security key-manager onboard sync`
+

NOTE: クラスタのOKMのクラスタ全体のパスフレーズを入力するように求められます。

.. キーのステータスを確認します。 `security key-manager key query -restored false`
+
正しく同期されている場合、出力には結果が表示されません。

+
出力に結果（システムの内部キーテーブルにないキーのキーID）が表示された場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。



. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。 `storage failover giveback -ofnode _impaired_node_name_`
. 自動ギブバックを無効にした場合は、再度有効にします。 `storage failover modify -node local -auto-giveback _true_`
+

NOTE: 鍵が見つからない場合の返却時に拒否権を上書きしないでください。NetApp サポートにお問い合わせください。

. AutoSupportが有効になっている場合は、ケースの自動作成をリストアまたは抑制解除します。 `system node autosupport invoke -node * -type all -message MAINT=END`


--
====
.次の手順
ストレージリソースの所有権を交換用コントローラに戻したら、の手順を実行する必要がありlink:controller-replace-restore-system-rma.html["コントローラの交換後の処理"]ます。
