---
permalink: c80/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: aff c80, replace the boot media 
summary: AFF C80システムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、適切な量のストレージを搭載したUSBフラッシュドライブがあること、および正しい交換用ブートデバイスがあることを確認します。 
---
= 手動ブートメディアリカバリの要件 - AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C80システムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、適切な量のストレージを搭載したUSBフラッシュドライブがあること、および正しい交換用ブートデバイスがあることを確認します。

システムがONTAP 9.17.1以降で実行されている場合は、 link:bootmedia-replace-workflow-bmr.html["自動ブート回復手順"] 。

.USB フラッシュ ドライブ
* USB フラッシュ ドライブが FAT32 にフォーマットされていることを確認します。
* USBには十分な保存容量が必要です `image_xxx.tgz`ファイル。


.ファイルの準備
コピー `image_xxx.tgz`ファイルをUSBフラッシュドライブに保存します。このファイルは、USBフラッシュドライブを使用してONTAPイメージを転送するときに使用されます。

.部品交換
故障したコンポーネントをNetAppが提供する交換用コンポーネントと交換します。

.コントローラー識別
障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。

* _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
* _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。


.次の手順
ブートメディアの交換要件を確認したら、を実行する必要がありlink:bootmedia-encryption-preshutdown-checks.html["暗号化キーのサポートとブートメディアのステータスを確認する"]ます。
