---
permalink: c80/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: c80, verify and set HA state, complete the replacement process 
summary: コントローラをリブートし、システムヘルスを確認し、障害が発生したパーツをNetAppに戻して、AFF C80シャーシの交換手順の最後の手順を完了します。 
---
= シャーシ交換後の処理- AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラをリブートし、システムヘルスを確認し、障害が発生したパーツをNetAppに戻して、AFF C80シャーシの交換手順の最後の手順を完了します。



== 手順1：コントローラをブートしてコントローラをギブバックする

コントローラがリブートしたら、ONTAPをブートしてコントローラをギブバックします。

.手順
. コンソールの出力を確認します。
+
.. コントローラがブートしてLoaderプロンプトが表示されたら、コマンドを使用してコントローラをリブートし `boot_ontap`ます。
.. リブート後にコンソールにと表示された場合 `waiting for giveback`は、パートナーコントローラにログインし、コマンドを使用して交換したコントローラのギブバックの準備が完了していることを確認します `storage failover show`。


. ギブバックを実行します。
+
.. パートナーコントローラにコンソールケーブルを接続します。
.. コマンドを使用してコントローラをギブバックし `storage failover giveback -fromnode local`ます。






== 手順2：ストレージシステムの健全性を確認する

コントローラがストレージをギブバックしたら、で全体の健全性を確認する必要があります https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]。

.手順
. ギブバックが完了したら、Active IQ Config Advisorを実行してストレージシステムの健全性を確認します。
. 発生した問題を修正します。




== 手順 3 ：障害が発生したパーツをネットアップに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
