---
permalink: c80/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: c80, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: コントローラのHA構成がアクティブで、AFF C80ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。 
---
= システム構成のリストアと確認- AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのHA構成がアクティブで、AFF C80ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。



== 手順1：HA構成を確認する

コントローラモジュールの「 HA 」状態を確認し、必要に応じてシステム構成に合わせて状態を更新する必要があります。

.手順
. メンテナンスモードでブートします。 `boot_ontap maint`
+
.. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。



. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。
. すべてのコンポーネントが同じ状態になっていることを確認し `HA`ます。 `ha-config show`
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたコントローラモジュールのシステム状態がシステム構成と一致しない場合は、コントローラモジュールの状態を設定し `HA`ます。 `ha-config modify controller ha`
+
HAの状態には次のいずれかの値を指定できます。

+
** 「 HA 」
** `mcc` （サポートされていません）
** `mccip`（ASAシステムではサポートされません）
** `non-ha` （サポートされていません）


. 設定が変更されたことを確認します。「 ha-config show 」




== 手順2：ディスクリストを確認する

すべてのシステム ディスクへのアダプタ リストとパスを確認する必要があります。

.手順
. アダプタのすべてのディスクへのパスがに表示されていることを確認します `storage show disk -p`。
+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. メンテナンスモードを終了します。 `halt`


.次の手順
AFF C80システムのシステム構成を復元して確認したら、を実行する必要がありますlink:controller-replace-recable-reassign-disks.html["コントローラをギブバック"]。
