---
sidebar: sidebar 
permalink: c80/install-requirements.html 
keywords: c80, install, setup, cautions 
summary: 必要な機器と、ストレージシステムおよびシェルフの持ち上げに関する注意事項を確認します。 
---
= インストール要件- AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C80ストレージシステムとストレージシェルフに必要な機器と、持ち上げる際の注意事項を確認します。



== 設置に必要な機器

AFF C80ストレージシステムを設置するには、次の機器および工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* NS224ストレージシェルフIDを設定するためのペーパークリップまたはボールペン
* No.2 プラスドライバ




== 吊り上げ時の注意事項

AFF C80ストレージシステムとNS224ストレージシェルフは重量があります。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== AFF C80ストレージシステム

AFF C80ストレージシステムの重量は最大68.8 kg（151.68ポンド）です。システムを持ち上げるには、4人で作業するか、油圧リフトを使用します。

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90 and AFF A70 weight cautionアイコン]



=== NS224シェルフ

NS224ストレージシェルフの重量は最大30.29kg（66.78ポンド）です。ストレージシェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224の持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]


.次の手順
ハードウェア要件を確認したら、link:install-prepare.html["AFF C80ストレージシステムを設置する準備"]
