---
permalink: c80/install-prepare.html 
sidebar: sidebar 
keywords: aff a70-90k, prepare installation 
summary: AFF C80ストレージシステムの設置を準備します。 
---
= インストールの準備- AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C80ストレージシステムを設置する準備をします。設置場所を準備し、開梱して内容を納品書と比較し、システムを登録してサポートを利用します。



== ステップ1：サイトを準備する

ストレージシステムを設置するには、設置場所および使用するキャビネットまたはラックが構成の仕様を満たしていることを確認してください。

.手順
. を使用して https://hwu.netapp.com["NetApp Hardware Universe の略"^]、サイトがストレージシステムの環境要件と電力要件を満たしていることを確認します。
. ストレージシステム、シェルフ、およびスイッチ用のキャビネットまたはラックスペースが十分にあることを確認します。
+
** 4U（HA構成）
** NS224ストレージシェルフごとに2U




. 必要なネットワークスイッチを取り付けます。
+
インストール手順および互換性情報については、を参照してください https://docs.netapp.com/us-en/ontap-systems-switches/index.html["スイッチのドキュメント"^] link:https://hwu.netapp.com["NetApp Hardware Universe の略"^] 。





== 手順2：箱を開封する

ストレージシステムに使用するキャビネットやラックが必要な仕様を満たしていることを確認したら、すべての箱を開封し、内容を納品書の項目と比較します。

.手順
. すべての箱を慎重に開き、内容を整理された方法でレイアウトします。
. 開梱した内容を、納品書のリストと比較します。
+

NOTE: 梱包箱の側面にあるQRコードをスキャンすると、梱包リストを取得できます。

+
次の項目は、ボックスに表示される内容の一部です。

+
箱の中のすべてが納品書のリストと一致していることを確認してください。不一致がある場合は、それらをメモして、さらに対処してください。

+
[cols="12,9,4"]
|===


| * ハードウェア * | *ケーブル* |  


 a| 
** ベゼル
** ケーブル マネジメント デバイス
** ストレージシステム
** 取扱説明書付きのレールキット（オプション）
** ストレージシェルフ（追加のストレージを注文した場合）

 a| 
** 管理イーサネットケーブル（RJ-45ケーブル）
** ネットワークケーブル
** 電源コード
** ストレージケーブル（追加のストレージを注文した場合）
** USB-Cシリアルコンソールケーブル

|  
|===




== 手順3：ストレージシステムを登録する

設置場所がストレージシステムの仕様要件を満たしていることを確認し、発注したパーツがすべて揃っていることを確認したら、ストレージシステムを登録する必要があります。

.手順
. 取り付けている各コントローラのシステムシリアル番号（SSN）を確認します。シリアル番号は次の場所にあります。
. シリアル番号は次の場所にあります。
+
** 納品書に
** 確認メール
** 各コントローラのシステム管理モジュール


+
image::../media/drw_ssn_label.svg[システムシリアル番号の場所を示す例]

. に進みます http://mysupport.netapp.com/["ネットアップサポートサイト"^]。
. ストレージシステムの登録が必要かどうかを判断します。
+
[cols="1a,2a"]
|===
| ユーザのタイプとアクセス方法 | 実行する手順 


 a| 
NetAppの既存のお客様
 a| 
.. ユーザ名とパスワードを使用してサインインします。
.. [システム]>*[マイシステム]*を選択します。
.. 新しいシリアル番号が表示されていることを確認します。
.. そうでない場合は、NetAppの新規のお客様向けの手順に従います。




 a| 
NetAppの新規のお客様
 a| 
.. [ 今すぐ登録 ] をクリックしてアカウントを作成します。
.. Systems *>* Register Systems *を選択します。
.. ストレージシステムのシリアル番号と要求された詳細を入力します。


登録が承認されると、必要なソフトウェアをダウンロードできます。承認プロセスには最大 24 時間かかる場合があります。

|===


.次の手順
AFF C80ハードウェアの設置準備が完了したら、次の作業link:install-hardware.html["AFF C80ストレージシステムのハードウェアを設置"]を行います。
