---
permalink: c80/maintain-overview.html 
sidebar: sidebar 
keywords: c80 maintenance, maintenance, repairing aff c80, repairing c80, replace c80 components 
summary: AFF C80ストレージシステムのハードウェアを保守して、長期的な信頼性と最適なパフォーマンスを確保します。ダウンタイムやデータ損失の防止に役立つため、障害のあるコンポーネントの交換などの定期的なメンテナンスタスクを実行します。 
---
= メンテナンス手順の概要- AFF C80
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C80ストレージシステムのハードウェアを保守して、長期的な信頼性と最適なパフォーマンスを確保します。ダウンタイムやデータ損失の防止に役立つため、障害のあるコンポーネントの交換などの定期的なメンテナンスタスクを実行します。

メンテナンス手順では、AFF C80システムがONTAP環境のストレージノードとしてすでに導入されていることを前提としています。



== システムコンホオネント

AFF C80ストレージシステムでは、次のコンポーネントに対してメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["ブートメディア"]
 a| 
ブートメディアには、システムがブート時に使用するONTAPイメージファイルのプライマリセットとセカンダリセットが格納されています。



 a| 
link:chassis-replace-workflow.html["シャーシ"]
 a| 
シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



 a| 
link:controller-replace-workflow.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAPオペレーティングシステムソフトウェアを実行します。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
デュアルインラインメモリモジュール（DIMM）は、コンピュータメモリの一種です。コントローラのマザーボードにシステムメモリを追加するために取り付けられます。



 a| 
link:drive-replace.html["ドライブ"]
 a| 
ドライブは、データに必要な物理ストレージを提供するデバイスです。



 a| 
link:fan-swap-out.html["ファン"]
 a| 
ファンがコントローラを冷却します。



 a| 
link:nvram-replace.html["NVRAM"]
 a| 
NVRAM（Non-Volatile Random Access Memory）は、システムの電源が切れた場合にコントローラが転送中のデータを保護および保存できるようにするモジュールです。システムIDはNVRAMモジュールにあります。交換したコントローラは、交換用NVRAMモジュールの新しいシステムIDを引き継ぎます。



 a| 
link:nvdimm-battery-replace.html["NVハツテリ"]
 a| 
NVバッテリは、電力損失後に転送中のデータをフラッシュメモリにデステージしている間、NVRAMモジュールに電力を供給します。



 a| 
link:io-module-overview.html["I/O モジュール"]
 a| 
I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



 a| 
link:power-supply-replace.html["電源装置"]
 a| 
電源装置は、コントローラに冗長な電源を提供します。



 a| 
link:rtc-battery-replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。



 a| 
link:system-management-replace.html["システム管理モジュール"]
 a| 
システム管理モジュールは、コントローラまたはシステムのメンテナンスを目的として、コントローラとコンソールまたはラップトップ間のインターフェイスを提供します。システム管理モジュールにはブートメディアが格納され、システムシリアル番号（SSN）が格納されています。

|===