---
permalink: platform-supplemental/42u-1280mm-replace-pdus.html 
sidebar: sidebar 
keywords: replace, fail, PDU, system, cabinet, replace, exist, replace pdu 
summary: システムキャビネット内の故障した PDU を交換したり、既存の PDU を別のタイプの PDU と交換したりできます。 
---
= PDU を交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムキャビネット内の故障した PDU を交換したり、既存の PDU を別のタイプの PDU と交換したりできます。

交換用 PDU がシステムキャビネットでサポートされ、設置されている機器に十分な電力を供給する必要があります。

https://hwu.netapp.com/["hwu.netapp.com"]

. 障害のあるPDUの回路ブレーカーをオフにし、障害のあるPDUをAC電源から取り外します。
. システムキャビネットのアース接続を行い、各システムコンポーネントと障害のあるPDUから電源コードを抜きます。
. PDU フレームの下部のネジを最初に外します。
+

NOTE: PDU の上部から最後のネジを外す際には、片手で PDU を支えてください。これにより、ネジを外したあとに PDU が落下したり、自分の方に倒れたりするのを防ぐことができます。

. 障害のあるPDUをシステムキャビネットから取り外します。
+
交換用 PDU の取り付け時に再利用できるように、必ず取り付けネジを残しておきます。

. 障害のあるPDUからブラケットを取り外し、交換用PDUの背面に取り付けます。
. 交換用PDUを支えながら、PDUの取り付けブラケットのスロットをシステムキャビネット内部のフレームの上部の穴に合わせ、障害のあるPDUの取り付けネジを使用してPDUをシステムキャビネットフレームに固定します。
. PDU の底部をシステムキャビネットフレームに固定し、すべての取り付けネジを締めます。
. すべての電源スイッチまたは回路ブレーカーがオフになっていることを確認します。
+
回路ブレーカーがオフになっていない場合は、小型のドライバまたはまっすぐに伸ばしたペーパークリップをオフラベルの右側のスロットに差し込み、回路ブレーカーを切って回路をオフにします。

. ストレージシステム、スイッチ、およびドライブシェルフから取り外した電源コードを交換用PDUに接続します。各コンポーネントはコンポーネントの真向かいにあるPDUコンセントに差し込みます。
+

TIP: PDU の分岐全体に負荷を分散し、各分岐の負荷を可能なかぎり均等にすることを推奨します。

. 各コンポーネントの電源ケーブルプラグを、プラグの上にあるケーブル固定クリップを使用して所定の位置に固定します。このとき、ケーブル固定クリップのカーブした方をプラグの肩部にスライドさせます。
. PDU の電源コードを AC 電源に接続します。
. PDU の電源スイッチまたは回路ブレーカーをオンにします。
+
PDU 回路ブレーカーは、ボタンが PDU フレームと同一平面上にある場合はオンです。


