---
permalink: platform-supplemental/42u-1280mm-features.html 
sidebar: sidebar 
keywords: system, cabinet, side, panel, front, rear, door, bolt-down, kit, optional, interconnect, pdu, equipment, integrate, cable, management, system, feature, system cabinet feature 
summary: システムキャビネットは、サイドパネル、前面ドアと背面ドア、オプションのボルトダウンキット、オプションのインターコネクトキット、機器の PDU 、および統合されたケーブル管理システムで構成されています。 
---
= システムキャビネットのコンポーネント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムキャビネットは、サイドパネル、前面ドアと背面ドア、オプションのボルトダウンキット、オプションのインターコネクトキット、機器の PDU 、および統合されたケーブル管理システムで構成されています。

[cols="1,2"]
|===
| フィーチャー（ Feature ） | 説明 


 a| 
サイドパネル
 a| 
システムキャビネットには、ロック、取り外し、および交換が可能なサイドパネルがあります。



 a| 
前面ドアと背面ドア
 a| 
システムキャビネットには、取り外し可能な前面ドアと背面ドアがあり、簡単に取り外せます。前面ドアは反転可能で、背面ドアは分割されています。どちらのドアにも冷却用の穴が開いています。



 a| 
共通キー
 a| 
このキーを使用して、前面ドア、背面ドア、サイドパネルのロックを解除します。



 a| 
スペアキット
 a| 
このキットは、システムキャビネットのキャビネットドアの内側に取り付けられています。次のコンポーネントで構成されます。

* 10-32 x 0.75 インチのプラスパイロットネジ × 4
* 10-32 ケージナット × 4
* ケージナット挿入工具 × 1
* マスターキーのコピー × 2




 a| 
ケーブルアクセス
 a| 
ケーブルを通すための開口部は、キャビネットの上部と下部、および背面ドアの下部とフレームの間に配置されています。



 a| 
ケーブル管理
 a| 
ケーブル管理用のフックとループストラップは、システムキャビネットのフレームに等間隔に取り付けられています。



 a| 
サポートレール
 a| 
サポートレールの数は、構成によって異なります。空のシステムキャビネットは、サポートレールが取り付けられていない状態で出荷されます。

* 構成済みのシステムキャビネットの場合、 80xx 、 FAS8200 、および DS4486 の後部押さえブラケットをサポートする固定レールキットがシステムキャビネットに 1 つ付属しています。
* クイック出荷のシステムキャビネットには、追加の固定レールキットは含まれていません。




 a| 
ブランクパネル
 a| 
ブランクパネルの数とサイズは、構成によって異なります。空のシステムキャビネットは、ブランクパネルが取り付けられていない状態で出荷されます。



 a| 
ボルトダウンキット
 a| 
このオプションキットを使用して、システムキャビネットをデータセンターの床に固定できます。このキットは耐震目的ではありません。

* ボルトダウンブラケット × 4
* スペーサーブラケット × 4
* M8 x 20mm 六角ボルトとワッシャ × 6




 a| 
インターコネクトキット
 a| 
このオプションキットを使用して、複数のシステムキャビネットを相互に接続できます。

* インターコネクトブラケット
+
** システムキャビネットをのサイドパネルに接続するためのインターコネクトブラケット × 4 セット
** システムキャビネットをサイドパネルから取り外すための、 4 つのインターコネクトブラケットのセット


* サイドパネルをオンにした状態でシステムキャビネットに使用する M12x20 Torx-30 ネジ × 4 。
* システムキャビネットでは、サイドパネルを外した状態で 6 x 10 皿 Torx -30 ネジを 8 本使用します。




 a| 
サポートレールキット
 a| 
システムキャビネットの注文時にサポートレールを追加した場合、各キットに左右のサポートレールが 1 本ずつ含まれます。


NOTE: サポートレールとキットは、 NetApp 42U 1280mm システムキャビネットにのみ合うように設計されています。他のシステムキャビネット用のレールやレールキットは、 42U 1280mm システムキャビネット用には設計されていないため使用しないでください。

* 左右のサポートレール
* レールをシステムキャビネットフレームに固定するためのネジをレールごとに 2 本




 a| 
モンキーレンチ
 a| 
クレセントレンチは、梱包パレットのホールドダウンブラケットの取り外し、システムキャビネットの水平調節脚の調整、およびボルトダウンキットブラケットの取り付け（注文した場合）に使用します。

|===