---
permalink: platform-supplemental/42u-1280mm-power-on.html 
sidebar: sidebar 
keywords: connect, system, component, pdu, cable, ac, power, source, cabinet, power on the system cabinet 
summary: システムコンポーネントを PDU に接続し、 PDU ケーブルを AC 電源に接続し、 AC 電源を電源に接続し、システムの電源をオンにする必要があります。 
---
= システムキャビネットの電源をオンにします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムコンポーネントを PDU に接続し、 PDU ケーブルを AC 電源に接続し、 AC 電源を電源に接続し、システムの電源をオンにする必要があります。


IMPORTANT: PDUに障害が発生した場合にシステムが停止するのを防ぐために、コンポーネントの両方の電源ケーブルを1つのPDUに接続しないでください。図に示すように、異なる回路に接続されているPDSに負荷を分散します。

システムキャビネット内の PDU ごとに別々の電源回路を使用できる必要があります。

. 機器をPDUに接続します。
+
.. コントローラの電源装置を、異なる電源に接続されている別 々 のPDUに接続します。
.. ドライブシェルフの電源装置を、異なる電源に接続されている別 々 のPDUに接続します。
.. スイッチの電源装置を、異なる電源に接続された別 々 のPDUに接続します。
+
image::../media/cabinet_power_cabling_IEOPS-1320.svg[キャビネット電源ケーブルIEOPS 1320]

+
PDUの電源ケーブルをシステムキャビネットの次のいずれかの開口部に通します。

+
*** システムキャビネットの上部
*** システムキャビネットの背面ドア底部とフレームの間
*** フロアの開口部を通ってシステムキャビネットの下




. PDU の電源スイッチまたは回路ブレーカーをオフにします。
. 各 PDU 電源ケーブルを、別々の AC 回路にある個別の AC 電源に接続します。
. PDU の電源スイッチまたは回路ブレーカーをオンにします。
. コンポーネントの電源を入れ、システムをブートします。
. システムキャビネットのドアを閉じてロックします。

