---
permalink: platform-supplemental/sldiag-introduction.html 
sidebar: sidebar 
keywords: system-level, diagnostic, command-line, interface, test, search, hardware, problem, storage, system, component, operating, identify, faulty, component, introduction, introduction to system-level diagnostic 
summary: システムレベルの診断では、コマンドラインインターフェイスを使用して、サポートされているストレージシステム上のハードウェアの問題を検索して特定するテストを実施します。システムレベルの診断を使用して、特定のコンポーネントが正常に動作していることを確認したり、障害のあるコンポーネントを特定したりします。 
---
= システムレベルの診断の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
システムレベルの診断では、コマンドラインインターフェイスを使用して、サポートされているストレージシステム上のハードウェアの問題を検索して特定するテストを実施します。システムレベルの診断を使用して、特定のコンポーネントが正常に動作していることを確認したり、障害のあるコンポーネントを特定したりします。

システムレベルの診断は、サポートされているストレージシステムでのみ使用できます。サポートされていないストレージシステムのコマンドラインインターフェイスでシステムレベルの診断を実行すると、エラーメッセージが表示されます。

システムレベルの診断は、トラブルシューティングを必要とする次のいずれかの状況のあとに実行します。

* システムの初期インストール
* ハードウェアコンポーネントの追加または交換
* 識別できないハードウェア障害が原因のシステムパニック
* 特定のデバイスへのアクセスが断続的になるか、デバイスが使用できなくなります
* システム応答時間の遅延


システムレベルの診断を実行するには、 Data ONTAP の * Maintenance mode boot * オプションにアクセスする必要があるため、 Data ONTAP をすでに実行している必要があります。このオプションにアクセスするにはいくつかの方法がありますが、このガイドで説明する手順ではこの方法を推奨します。システムの一部のハードウェアコンポーネントでは特定の方法が必要になる場合があります。その場合は、該当するフィールド交換可能ユニット（ FRU ）のリーフレットを参照してください。このガイドでは、特定のコマンド、サブコマンド、テスト、または条件の詳細な定義については説明していません。

コマンドを入力すると、テストはバックグラウンドで実行され、テストの成功または失敗した結果が、固定サイズの内部メモリベースログに記録されます。一部のテストはユーティリティであり、成功または失敗ではなく、単に完了したことを示します。適切なテストを実行すると、このガイドに記載されている手順に従ってステータスレポートを生成できます。テスト結果にシステムレベルの診断が正常に完了したことが示されたら、ログをクリアすることを推奨します。

テストに失敗した場合は、ステータスレポートを使用してテクニカルサポートが適切な推奨事項を提示できます。FRU を再取り付けするか、ケーブルが接続されていることを確認するか、テクニカルサポートが推奨するテストを有効にしたうえで、同じテストを再実行することで問題を解決できる場合があります。問題を解決できない場合は、ハードウェア障害が発生しているため、該当するハードウェアを交換する必要があります。

詳細な定義や説明を必要とするエラーメッセージはありません。
