---
permalink: platform-supplemental/sldiag-requirements.html 
sidebar: sidebar 
keywords: system-level, diagnostic, test, run, time, system, requirement, system, memory, general, nic, sas, fc-al, cna, interconnect, requirement for running system-level diagnostic 
summary: 実行しているシステムレベルの診断テストに応じて、所要時間とシステムハードウェアの要件を把握しておく必要があります。 
---
= システムレベルの診断を実行するための要件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
実行しているシステムレベルの診断テストに応じて、所要時間とシステムハードウェアの要件を把握しておく必要があります。

ドキュメントに記載されているタスクはそれぞれ少しずつ違いがあります。該当するタスクに推奨される手順を使用してください。

システムレベルの診断を実行するときは、次の要件を満たす必要があります。満たしていない場合、テストの一部が失敗し、ステータスレポートにエラーメッセージが表示されます。



== 一般的な要件

* テスト対象のシステムはそれぞれ別のネットワークにあることが必要です。
+
ネットワークインターフェイステストでは、ストレージシステムの使用可能なすべてのネットワークインターフェイスに、 172.25.150.23 から始まる一意の静的 IP アドレスが割り当てられます。その結果、異なるストレージコントローラのネットワークインターフェイスポートに同じ IP アドレスが割り当てられます。テスト中のシステムがすべて同じネットワークにある場合、 duplicate ip address という警告メッセージが接続されているコンソールに表示されます。これらの警告メッセージは、テスト結果には影響しません。





== システムメモリの要件

* メモリテストを実行する際には十分な時間を確保しておく必要があります。テスト時間は、ストレージシステムのメモリ容量が大きいほど長くなります。




== NIC の要件

* パフォーマンスを最大限に高めるには、標準のイーサネットケーブルを使用して、システム上の隣接するすべてのネットワークインターフェイスポートを接続する必要があります。
+
たとえば、 e0a と e0b 、または e2c と e2d などです。

+

NOTE: 内部スイッチ接続のため、ポート e0M と e0P を接続することはできません。ポート e0M と e0P を搭載したシステムの場合、最も効率的なポートの組み合わせは e0M と e0a 、 e0P と e0b です。

* システムに複数のネットワークインターフェイスポートがある場合、 NIC システムレベルの診断テストを複数回実行しなければならないことがあります。 1 回の実行でテストできるペアの数は 2 つまでです。




== SAS の要件

* SAS システムレベルの診断テストを実行する際のパフォーマンスを最大限に高めるには、隣接する SAS ポートを接続する必要があります。ストレージシェルフはポートから切断する必要があります。
+

NOTE: Data ONTAP 8.2 を実行するシステムでは、隣接する SAS ポート間の接続は不要になりました。 SAS ポートが接続されていないシステムに対しては、内部ループバックテストだけが実行されます。





== FC-AL の要件

* FC-AL システムレベルの診断テストを実行する場合、マザーボードまたは拡張アダプタ上の FC-AL インターフェイスにループバックフードが必要です。ストレージまたは Fibre Channel ネットワークのそれ以外のケーブルは、すべてポートから切断する必要があります。
+

NOTE: Data ONTAP 8.2 を実行するシステムでは、 FC-AL インターフェイスに対するループバックフードは不要になりました。インターフェイスに対するテスト対象の範囲も少なくなりました。





== CNA の要件

* ループバックフードの使用は、 CNA システムレベルの診断テストを実行するための要件ではありません。




== インターコネクトの要件

* デュアルコントローラシステムの場合、インターコネクトシステムレベルの診断テストを実行するためには、両方のプラットフォームコントローラモジュールがメンテナンスモードになっている必要があります。
+

NOTE: インターコネクトシステムレベルの診断テストを他のシステムレベルの診断テストと同時に実行しようとすると、警告メッセージが表示されます。


