---
permalink: platform-supplemental/sldiag-hardware-installation-diagnostics.html 
sidebar: sidebar 
keywords: run, diagnostic, add, replacing, replace, hardware, component, storage, systen, verify, installation, successful, run hardware installation diagnostic 
summary: ストレージシステムのハードウェアコンポーネントを追加または交換したら、診断を実行して、コンポーネントに問題がなく、設置が正常に完了したことを確認します。 
---
= ハードウェアの設置診断を実行
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージシステムのハードウェアコンポーネントを追加または交換したら、診断を実行して、コンポーネントに問題がなく、設置が正常に完了したことを確認します。

. ストレージ・システム・プロンプトで、 LOADER プロンプト「 halt 」に切り替えます
. LOADER プロンプトで「 boot_diags 」と入力します
+

NOTE: システムレベルの診断が正しく機能するためには、このコマンドを LOADER プロンプトから実行する必要があります。boot_diags コマンドは、システムレベルの診断専用に設計された特別なドライバを実行します。

. 次のコマンドを入力して、追加または交換した特定のデバイスに対してデフォルトテストを実行します。 'diag device run [-dev devtype|MB|slotnum][-name_device]
+
** -dev devtype は、テストするデバイスのタイプを指定します。
+
*** 「 ata 」は、 Advanced Technology Attachment デバイスです。
*** 「 bootmedia 」は、システム起動デバイスです。
*** 「 cna 」は、ネットワークまたはストレージデバイスに接続されていない統合型ネットワークアダプタです。
*** 「 env 」はマザーボード環境です。
*** 「 fcache 」は、 Performance Acceleration Module 2 とも呼ばれる Flash Cache アダプタです。
*** fcal は ' ストレージ・デバイスまたはファイバ・チャネル・ネットワークに接続されていないファイバ・チャネル・アービトレート型ループ・デバイスです
*** 'FCVI' はファイバ・チャネル・ネットワークに接続されていないファイバ・チャネル・仮想インターフェイスです
*** 相互接続または「 nvram-ib 」は、高可用性インターフェイスです。
*** 「 m 」はシステムメモリです。
*** 「 nic 」は、ネットワークに接続されていないネットワーク・インターフェイス・カードです。
*** 「 nvram 」は不揮発性 RAM です。
*** 「 nvmem 」は、 NVRAM とシステムメモリの組み合わせです。
*** 「 As 」は、ディスクシェルフに接続されていないシリアル接続 SCSI デバイスです。
*** 「 erviceproc 」はサービスプロセッサです。
*** 「ストレージ」とは、ディスクシェルフに接続された ATA 、 FC-AL 、または SAS インターフェイスです。
*** to' は NIC の一種である TCP オフロードエンジンです


** 「 m 」は、すべてのマザーボードデバイスをテストすることを指定します。
** 「 llot_slotnum_ 」は、特定のスロット番号のデバイスをテストすることを指定します。
** `-name_device_` は、特定のデバイスクラスとタイプを指定します。


. 次のコマンドを入力して、テストのステータスを表示します。「 diag device status 」
+
テストが実行中の間、ストレージシステムは次の出力を表示します。

+
[listing]
----
There are still test(s) being processed.
----
+
すべてのテストが完了すると、デフォルトで次の応答が表示されます。

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
. 次のコマンドを入力して、ストレージシステム上のハードウェアコンポーネントの追加または交換が原因でハードウェアの問題が発生していないことを確認します。 `diag device status [-dev devtype|MB|slotnum][-name device] -long -state failed`
+
次の例では、新しく取り付けた FC-AL アダプタをテストし、障害の完全なステータスを取得します。

+
[listing]
----

*> **sldiag device status -dev fcal -long -state failed**

TEST START ------------------------------------------
DEVTYPE: fcal
NAME: Fcal Loopback Test
START DATE: Sat Jan  3 23:10:56 GMT 2009

STATUS: Completed
Starting test on Fcal Adapter: 0b
Started gathering adapter info.
Adapter get adapter info OK
Adapter fc_data_link_rate: 1Gib
Adapter name: QLogic 2532
Adapter firmware rev: 4.5.2
Adapter hardware rev: 2

Started adapter get WWN string test.
Adapter get WWN string OK wwn_str: 5:00a:098300:035309

Started adapter interrupt test
Adapter interrupt test OK

Started adapter reset test.
Adapter reset OK

Started Adapter Get Connection State Test.
Connection State: 5
Loop on FC Adapter 0b is OPEN

Started adapter Retry LIP test
Adapter Retry LIP OK

ERROR: failed to init adaptor port for IOCTL call

ioctl_status.class_type = 0x1

ioctl_status.subclass = 0x3

ioctl_status.info = 0x0
 Started INTERNAL LOOPBACK:
INTERNAL LOOPBACK   OK
Error Count: 2  Run Time: 70 secs
>>>>> ERROR, please ensure the port has a shelf or plug.
END DATE: Sat Jan  3 23:12:07 GMT 2009

LOOP: 1/1
TEST END --------------------------------------------
----
+
[cols="1,2"]
|===
| システムレベルの診断のテスト結果 | 作業 


 a| 
は失敗なしで完了しました
 a| 
ハードウェアに問題はなく、ストレージシステムはプロンプトに戻ります。

.. 次のコマンドを入力して、ステータスログをクリアします。 `diag device clearstatus [-dev devtype]




| MB | slotslotnum]`.次のコマンドを入力して、ログがクリアされたことを確認します。 `ldiag device status [-dev devtype] 


| MB | slotslotnum]`+ 次のデフォルトの応答が表示されます。 +---SLDIAG ： No log messages are present.- - - - 。次のコマンドを入力して保守モードを終了します :haltLoader プロンプトで次のコマンドを入力して、ストレージ・システムをブートします。「 boot_ontap 」システム・レベルの診断が完了しました。 


 a| 
テストが失敗しました
 a| 
問題の原因を特定します

.. 次のコマンドを入力して保守モードを終了します :halt
.. クリーンシャットダウンを実行し、電源装置の接続を解除します。
.. システムレベルの診断を実行するための考慮事項をすべて確認するとともに、ケーブルがしっかりと接続されているか、ハードウェアコンポーネントがストレージシステムに適切に取り付けられているかを確認します。
.. 電源装置を再接続し、ストレージシステムの電源をオンにします。
.. ハードウェア設置診断の実行の手順 1~6 を繰り返します。


|===


同じ手順を繰り返しても問題が解決しない場合は、ハードウェアを交換する必要があります。
