---
permalink: sas3/install-change-shelf-id.html 
sidebar: sidebar 
keywords: change, shelf, id, system, ontap, run, hot-add, ontap, controller, module, available, serve, data, unown, spare, offline, aggregate 
summary: ONTAP がまだ実行されていない場合や、シェルフをシステムにケーブル接続する前にホットアドする場合は、システムのシェルフ ID を変更できます。また、 ONTAP が実行中で、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーである場合にも、シェルフ ID を変更できます \ （コントローラモジュールがデータを提供可能です \ ）。 
---
= シェルフ ID の変更 - DS212C、DS224C、または DS460C
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP がまだ実行されていない場合、またはシェルフをシステムにケーブル接続する前にホット アドする場合は、IOM12/IOM12B モジュールを搭載したシステム内のシェルフ ID を変更できます。また、ONTAPが実行中（コントローラ モジュールがデータを提供可能）の場合でも、シェルフ内のすべてのドライブが所有されていないか、スペアか、オフラインのアグリゲートのメンバーである場合にはシェルフIDを変更できます。

.このタスクについて
* 有効なシェルフ ID は 00~99 です。
* シェルフ ID は、 HA ペアまたはシングルコントローラ構成内で一意である必要があります。
+
内蔵ストレージを搭載したプラットフォームを使用する場合、シェルフ ID は内蔵のディスクシェルフおよび外付けのディスクシェルフ全体で一意である必要があります。

* シェルフ ID を有効にするには、シェルフの電源を再投入する必要があります。
+
電源をオンにするまでの待機時間は、この手順の後半で説明する ONTAP の状態によって異なります。



.作業を開始する前に
* ONTAP が実行中（コントローラモジュールがデータを提供可能）の場合は、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーであることを確認しておく必要があります。
+
「 storage disk show -shelf_shelf_number _ 」コマンドを使用すると、ドライブの状態を確認できます。Container Type 列の出力に、スペアまたは障害が発生したドライブである場合は破損が表示されます。また、 Container Name 列と Owner 列にはダッシュが表示されます。

* システムですでに使用されているシェルフIDを確認するには、Active IQ Config Advisorを実行するか、 `storage shelf show -fields shelf-id`コマンドを使用します。   https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisorをダウンロードしてアクセスする"] NetAppサポート サイトをご覧ください。


.手順
. ディスクシェルフの電源がオンになっていない場合は、オンにします。
. 左側のエンドキャップを外して、シェルフ LED の近くにあるボタンを見つけます。
. デジタルディスプレイの 1 桁目の数字が点滅するまでオレンジのボタンを押し続けて、シェルフ ID の 1 桁目の数字を変更します。点滅までに最大 3 秒かかります。
+
[NOTE]
====
ID の点滅に 3 秒以上かかる場合は、ボタンをもう一度押してください。

これにより、ディスクシェルフ ID のプログラミングモードがアクティブになります。

====
. 0 ～ 9 の範囲で目的の番号になるまで、ボタンを押して番号を伝えます。
+
1 桁目の数字は点滅し続けます。

. デジタルディスプレイの 2 番目の数字が点滅するまでボタンを押し続け、シェルフ ID の 2 桁目の数字を変更します。点滅までに最大 3 秒かかります。
+
デジタルディスプレイの 1 桁目の数字の点滅が停止します。

. ボタンを押して、目的の番号に 1 ～ 9 の範囲で移動します。
+
2 桁目の数字は点滅し続けます。

. 2 桁目の数字が点滅しなくなるまでボタンを押し続けてプログラミングモードを終了し、希望する番号をロックします。点滅が停止するまでに最大 3 秒かかります。
+
デジタルディスプレイの両方の数字が点滅し始め、約 5 秒後にオペレータ用ディスプレイパネルの黄色の LED が点灯してディスクシェルフ ID が保留中でまだ有効になっていないことを警告します。

. ディスクシェルフの電源を再投入し、シェルフ ID を有効にします。
+
電源を再投入するには、両方の電源スイッチをオフにし、しばらく待ってから再度オンにする必要があります。

+
** ONTAP が実行されていない場合、または（まだシステムにケーブルが接続されていない）シェルフをホットアドする場合は、少なくとも 10 秒待ちます。
** ONTAPが実行中（コントローラからデータを提供可能）で、シェルフ内のすべてのディスクドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーである場合は、少なくとも120秒待ちます。
+
この間に、 ONTAP は古いシェルフアドレスを削除し、新しいシェルフアドレスのコピーを更新します。



. 左側のエンドキャップを取り付けます。
. 追加するディスクシェルフごとに、手順 1~9 を繰り返します。
. システムに重複したシェルフ ID がないことを確認します。
+
複数のディスクシェルフで ID が同じ場合、重複するディスクシェルフに 100 以上のソフト ID 番号が割り当てられます。ソフト ID （重複）番号を変更する必要があります。

+
.. Active IQ Config Advisor を実行して重複したシェルフ ID のアラートを確認するか、「 storage shelf show -fields shelf-id 」コマンドを実行して、重複した ID を含めてすでに使用されているシェルフ ID のリストを表示します。
.. システムに重複したシェルフ ID がある場合は、この手順を繰り返して重複シェルフ ID を変更します。



