---
permalink: a320/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff, a320, locate, boot, media, controller, module, direction, replace, replace the boot media, manual, manual boot recovery 
summary: コントローラー モジュール内のブート メディアを見つけて、指示に従って交換する必要があります。AFF A320システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= AFF A320 システムのブートメディアの交換について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A320システムは、手動のブート メディア リカバリ手順のみをサポートします。

ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
「 image_xxx.tgz 」ファイルを格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

また ' この手順で後で使用するために 'image_xxx.tgz ファイルを USB フラッシュドライブにコピーする必要があります

* ブート・メディアを交換するための無停止かつ停止を伴う方法では 'var' ファイル・システムをリストアする必要があります
+
** 無停止で交換するには 'var' ファイル・システムをリストアするために HA ペアをネットワークに接続する必要があります
** 停止を伴う交換の場合 'var' ファイル・システムをリストアするためにネットワーク接続は必要ありませんが ' 再起動が 2 回必要です


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* 以下の手順のコマンドを正しいノードに適用することが重要です。
+
** impaired_node は、保守を実行しているノードです。
** Healthy node_name は、障害が発生したノードの HA パートナーです。



