---
permalink: a320/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: aff, a320, aff a320, replace, chassis, fan, controller, module, impair, model, shut, down, replacing, remove, move, equipment, rack, diagnostic, complete, replacement, process, replace the chassis, shut down the controllers when replacing a chassis, remove the controller modules, move the fans, replace a chassis from within the equipment rack or system cabinet, install the controller modules, run diagnostics, complete the replacement process 
summary: ファン、ハードドライブ、およびコントローラモジュールを障害のあるシャーシから新しいシャーシに移動し、装置ラックまたはシステムキャビネットの障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシと交換します。 
---
= ハードウェアの移動と交換 - AFF A320
:icons: font
:imagesdir: ../media/


[role="lead"]
ファン、ハードドライブ、およびコントローラモジュールを障害のあるシャーシから新しいシャーシに移動し、装置ラックまたはシステムキャビネットの障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシと交換します。



== 手順 1 ：コントローラモジュールを取り外す

シャーシを交換するには、古いシャーシからコントローラモジュールを取り外す必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. 電源ケーブル固定クリップを外し、電源装置からケーブルを抜きます。
. ケーブルマネジメントデバイスに接続しているケーブルをまとめているフックとループストラップを緩め、システムケーブルと SFP をコントローラモジュールから外し（必要な場合）、どのケーブルが何に接続されていたかを記録します。
+
ケーブルはケーブルマネジメントデバイスに収めたままにします。これにより、ケーブルマネジメントデバイスを取り付け直すときに、ケーブルを整理する必要がありません。

. ケーブルマネジメントデバイスをコントローラモジュールの右側と左側から取り外し、脇に置きます。
. コントローラモジュールをシャーシから取り外します。
+
.. コントローラモジュールの両側にあるラッチ機構に人差し指をかけます。
.. ラッチ機構の上部にあるオレンジ色のタブを押し下げて、シャーシのラッチピンを解除します。
+
ラッチ機構のフックがほぼ垂直に位置し、シャーシピンから解除されている必要があります。

.. コントローラモジュールの側面を持てるように、コントローラモジュールをゆっくりと少し手前に引き出します。
.. コントローラモジュールを両手でシャーシからゆっくりと引き出し、平らで安定した場所に置きます。


. シャーシ内の他のコントローラモジュールについて、上記の手順を繰り返します。




== 手順 2 ：ファンを移動します

シャーシを交換するときにファンモジュールを交換用シャーシに移動するには、特定の順序でタスクを実行する必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. （必要な場合）両手でベゼルの両側の開口部を持ち、手前に引いてシャーシフレームのボールスタッドからベゼルを外します。
. ファンモジュールのカムハンドルのリリースラッチを押し下げ、カムハンドルを下に回転させます。
+
ファンモジュールがシャーシから少し離れた場所に移動します。

. ファンモジュールをシャーシから引き出します。このとき、ファンモジュールがシャーシから落下しないように、必ず空いている手で支えてください。
+

CAUTION: ファンモジュールは奥行きがないので、シャーシから突然落下してけがをすることがないように、必ず空いている手でファンモジュールの底面を支えてください。

. ファンモジュールを脇へ置きます。
. 残りのファンモジュールに対して上記の手順を繰り返します。
. 交換用シャーシの開口部にファンモジュールを合わせ、スライドさせながらシャーシに挿入します。
. ファンモジュールのカムハンドルをしっかり押して、シャーシに完全に装着されるようにします。
+
ファンモジュールが完全に装着されると、カムハンドルが少し持ち上がります。

. カムハンドルを閉じる位置まで上げ、カムハンドルのリリースラッチがカチッという音を立ててロックされたことを確認します。
+
ファンが装着されて動作速度まで回転数が上がると、ファンの LED が緑色に点灯します。

. 残りのファンモジュールに対して上記の手順を繰り返します。




== 手順 3 ：装置ラックまたはシステムキャビネット内のシャーシを交換する

交換用シャーシを設置するには、装置ラックまたはシステムキャビネットから既存のシャーシを取り外す必要があります。

. シャーシ取り付けポイントからネジを外します。
. 古いシャーシをシステムキャビネットまたは装置ラックのラックレールからスライドさせて取り出し、脇に置きます。
. 接地対策がまだの場合は、自身で適切に実施します。
. 交換用シャーシを、システムキャビネットまたは装置ラックのラックレールに沿って挿入して、装置ラックまたはシステムキャビネットに設置します。この作業は 2 人で行ってください。
. シャーシをスライドさせて装置ラックまたはシステムキャビネットに完全に挿入します。
. 古いシャーシから取り外したネジを使用して、シャーシの前面を装置ラックまたはシステムキャビネットに固定します。
. まだベゼルを取り付けていない場合は、取り付けます。




== 手順 4 ：コントローラモジュールを取り付ける

新しいシャーシにコントローラモジュールを取り付けたら、コントローラモジュールをブートして診断テストを実行できる状態にする必要があります。

2 台のコントローラモジュールを同じシャーシに搭載する HA ペアでは、シャーシへの設置が完了すると同時にリブートが試行されるため、コントローラモジュールの取り付け順序が特に重要です。

. コントローラモジュールの端をシャーシの開口部に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

NOTE: 指示があるまでコントローラモジュールをシャーシに完全に挿入しないでください。

. コンソールとコントローラモジュールを再度ケーブル接続し、管理ポートを再接続します。
. 電源装置に電源ケーブルを接続し、電源ケーブルの固定クリップを再度取り付けます。
. コントローラモジュールの再取り付けを完了します。
+
.. ラッチアームが引き出された位置で固定されていることを確認します。
.. ラッチアームを使用して、コントローラモジュールをシャーシベイの奥まで押し込みます。
.. ラッチ上部にあるオレンジ色のタブを押し下げます。
.. コントローラモジュールをシャーシの端と揃うまで、シャーシベイにそっと押し込みます。
+

NOTE: ラッチのアームがシャーシ内にスライドします。

+
コントローラモジュールは、シャーシに完全に装着されるとすぐにブートを開始します。

.. ラッチを外してコントローラモジュールを所定の位置に固定します。
.. 電源装置を再度ケーブル接続します。
.. ケーブルマネジメントデバイスをまだ取り付けていない場合は、取り付け直します。
.. Ctrl キーを押しながら C キーを押して ' 通常の起動プロセスを中断します


. 同じ手順を繰り返して、 2 台目のコントローラを新しいシャーシに取り付けます。

