---
permalink: fas500f/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas500f, replace the chassis 
summary: FAS500f システムのシャーシを交換する前に、交換を正常に完了するために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることの確認、ONTAP のローカル管理者資格情報の確認、正しい交換用シャーシの確認、および必要なツールの確認が含まれます。 
---
= FAS500f システムのシャーシ交換の要件を確認します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS500f システムのシャーシを交換する前に、交換を正常に完了するために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることの確認、ONTAP のローカル管理者資格情報の確認、正しい交換用シャーシの確認、および必要なツールの確認が含まれます。

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。

次の要件を確認します。

* システムの他のすべてのコンポーネントが正常に機能していることを確認します。正常に機能していない場合は、に連絡してサポートを受けてください http://mysupport.netapp.com/["ネットアップサポート"^]
* ONTAPのローカル管理者のクレデンシャルがない場合は、そのクレデンシャルを取得します。
* 交換に必要な工具と機器が揃っていることを確認します。
* シャーシの交換手順は、システムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、NVMeドライブ、およびコントローラモジュールを新しいシャーシに移動することを前提としています。また、交換用シャーシはNetAppの新しいコンポーネントであることを前提としています。
* シャーシの交換手順はシステムの停止を伴います。2 ノードクラスタではサービスが完全に停止し、マルチノードクラスタでは部分的に停止します。


.次の手順
要件を確認した後、link:chassis-replace-prepare.html["シャーシを交換する準備"] 。
