---
permalink: c400/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: c400, replace the boot media 
summary: AFF C400システムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、適切なストレージ容量のUSBフラッシュドライブがあること、および交換用のブートデバイスが正しいことの確認が含まれます。 
---
= 手動ブートメディアリカバリの要件 - AFF C400
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C400システムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、適切なストレージ容量のUSBフラッシュドライブがあること、および交換用のブートデバイスが正しいことの確認が含まれます。

ストレージシステムがONTAP 9.17.1以降を実行している場合は、link:bootmedia-replace-workflow.html["手動ブート回復手順"]

.USB フラッシュ ドライブ
* USB フラッシュ ドライブが FAT32 にフォーマットされていることを確認します。
* USBには十分な保存容量が必要です `image_xxx.tgz`ファイル。


.ファイルの準備
コピー `image_xxx.tgz`ファイルをUSBフラッシュドライブに保存します。このファイルは、USBフラッシュドライブを使用してONTAPイメージを転送するときに使用されます。

.部品交換
故障したコンポーネントをNetAppが提供する交換用コンポーネントと交換します。

.コントローラー識別
障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。

* _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
* _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。


.次の手順
ブートメディアの交換要件を確認したら、を実行する必要がありlink:bootmedia-encryption-preshutdown-checks.html["暗号化キーのサポートとブートメディアのステータスを確認する"]ます。
