---
permalink: a800/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: a800, replace the boot media 
summary: AFF A800システムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、適切なストレージ容量のUSBフラッシュドライブがあること、および交換用のブートデバイスが正しいことの確認が含まれます。 
---
= AFF A800システムの手動ブートメディアリカバリの要件を確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A800システムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、適切なストレージ容量のUSBフラッシュドライブがあること、および交換用のブートデバイスが正しいことの確認が含まれます。

ストレージシステムがONTAP 9.17.1以降を実行している場合は、link:bootmedia-replace-workflow-bmr.html["自動ブート回復手順"] 。システムで以前のバージョンのONTAPを実行している場合は、手動ブートリカバリ手順を使用する必要があります。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
.USB フラッシュ ドライブ
* USB フラッシュ ドライブが FAT32 にフォーマットされていることを確認します。
* USBには十分な保存容量が必要です `image_xxx.tgz`ファイル。


.ファイルの準備
コピー `image_xxx.tgz`ファイルをUSBフラッシュドライブに保存します。このファイルは、USBフラッシュドライブを使用してONTAPイメージを転送するときに使用されます。

抽出された ONTAP イメージから、 `EFI`フォルダを USB フラッシュドライブのルートディレクトリにコピーします。

.部品交換
故障したコンポーネントをNetAppが提供する交換用コンポーネントと交換します。

.コントローラー識別
障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。

* _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
* _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。


.次の手順
ブートメディアの交換要件を確認したら、を実行する必要がありlink:bootmedia-encryption-preshutdown-checks.html["暗号化キーのサポートとブートメディアのステータスを確認する"]ます。
