---
permalink: a800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a800, verify and set HA state, run diagnostics, complete the replacement process 
summary: キットに付属する RMA 指示書に従って、シャーシの HA 状態を確認し、診断を実行し、障害が発生した部品をネットアップに返却する必要があります。 
---
= リストアと交換のプロセスを完了します（ AFF A800 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
キットに付属する RMA 指示書に従って、シャーシの HA 状態を確認し、診断を実行し、障害が発生した部品をネットアップに返却する必要があります。



== 手順 1 ：シャーシの HA 状態を確認して設定します

[role="lead"]
シャーシの HA 状態を確認し、必要に応じてシステム構成に合わせて更新する必要があります。

. メンテナンスモードでは、いずれかのコントローラモジュールから、ローカルコントローラモジュールとシャーシの HA 状態を表示します。「 ha-config show 」
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は、次の手順を実行します。
+
.. シャーシの HA 状態を設定します :'ha-config modify chassis_ha-state _
+
hA-state には、次のいずれかの値を指定できます。

+
*** 「 HA 」
*** 「 mcc 」
*** 「 MCCIP 」
*** 「 non-ha 」


.. 設定が変更されたことを確認します。「 ha-config show 」


. システムの残りのケーブルをまだ再接続していない場合は、ケーブルを再接続します。
. システムの前面にベゼルを再度取り付けます。




== 手順 2 ：診断を実行します

システムのコンポーネントを交換したら、そのコンポーネントに対して診断テストを実行する必要があります。

診断を開始するには、システムに LOADER プロンプトが表示されている必要があります。

診断手順のコマンドは、すべてコンポーネントを交換するコントローラから実行します。

.手順
. 保守対象のコントローラが LOADER プロンプトに表示されていない場合は、コントローラをリブートします。「 system node halt -node node_name 」
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. LOADER プロンプトで、システムレベルの診断用に特別に設計されたドライバ「 boot_diags 」にアクセスします
. 表示されたメニューから「 * Scan System * （システムのスキャン）」を選択して、診断テストの実行を有効にします。
. 表示されたメニューから * Test Memory * を選択します。
. 前述の手順の結果に応じて、次に進みます。
+
** テストに失敗した場合は、エラーを修正してからテストを再実行します。
** テストでエラーが報告されなかった場合は、メニューから Reboot を選択してシステムをリブートします。






== 手順 3 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
