---
permalink: a800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: aff a800, verify and set HA state, run diagnostics, complete the replacement process 
summary: キットに付属する RMA 指示書に従って、シャーシの HA 状態を確認し、診断を実行し、障害が発生した部品をネットアップに返却する必要があります。 
---
= リストアと交換のプロセスを完了します（ AFF A800 ）
:icons: font
:imagesdir: ../media/




== 手順 1 ：シャーシの HA 状態を確認して設定します

[role="lead"]
シャーシの HA 状態を確認し、必要に応じてシステム構成に合わせて更新する必要があります。

. メンテナンスモードでは、いずれかのコントローラモジュールから、ローカルコントローラモジュールとシャーシの HA 状態を表示します。「 ha-config show 」
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は、次の手順を実行します。
+
.. シャーシの HA 状態を設定します :'ha-config modify chassis_ha-state _
+
hA-state には、次のいずれかの値を指定できます。

+
*** 「 HA 」
*** 「 mcc 」
*** 「 MCCIP 」
*** 「 non-ha 」


.. 設定が変更されたことを確認します。「 ha-config show 」


. システムの残りのケーブルをまだ再接続していない場合は、ケーブルを再接続します。
. システムの前面にベゼルを再度取り付けます。




== 手順 2 ：診断を実行します

[role="lead"]
システムのコンポーネントを交換したら、そのコンポーネントに対して診断テストを実行する必要があります。

診断を開始するには、システムに LOADER プロンプトが表示されている必要があります。

診断手順のコマンドは、すべてコンポーネントを交換するノードから実行します。

.手順
. 作業をするノードに LOADER プロンプトが表示されていない場合は、ノードをリブートします。「 system node halt -node node_name 」
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. LOADER プロンプトで、システムレベルの診断用に特別に設計されたドライバ「 boot_diags 」にアクセスします
. 表示されたメニューから「 * Scan System * （システムのスキャン）」を選択して、診断テストの実行を有効にします。
. 表示されたメニューから * Test Memory * を選択します。
. 前述の手順の結果に応じて、次に進みます。
+
** テストに失敗した場合は、エラーを修正してからテストを再実行します。
** テストでエラーが報告されなかった場合は、メニューから Reboot を選択してシステムをリブートします。






== 手順 3 ：障害が発生したパーツをネットアップに返却する

[role="lead"]
部品を交換したあと、障害のある部品をネットアップに返却することができます。詳細については、キットに付属する RMA 指示書を参照してください。テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]RMA 番号を確認する場合や、交換用手順にサポートが必要な場合は、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。
