---
sidebar: sidebar 
permalink: upgrade/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: アグリゲートの再配置を使用してコントローラハードウェアをアップグレードする 
---
= アグリゲートの再配置を使用してコントローラハードウェアをアップグレードする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このガイドでは、アグリゲートの再配置を使用して、システムを停止することなくコントローラハードウェアをアップグレードする方法について説明します。

コントローラハードウェアをアップグレードするその他の方法については、を参照してください link:http://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["『 Controller Hardware Upgrade Express Guide 』を参照してください"]。

ONTAP を実行しているノードペアで、元のノードから同じクラスタ内の新しいノードにルート以外のアグリゲートを移行することで、コントローラハードウェアを無停止でアップグレードできます。アップグレード中は、アップグレード対象のノードでホストされているデータにアクセスできます。

この手順では、 Aggregate Relocation （ ARL ；アグリゲートの再配置）と呼ばれる方法を使用します。 ARL を使用すると、 HA 構成を活用して、ルート以外のアグリゲートの所有権をノード間で移動できます（ルートが同じクラスタ内のストレージを共有している場合）。

ARL には、システムコマンドまたは手動アップグレードを使用して、コントローラハードウェアをアップグレードする方法が 2 つあります。作業を開始する前に、コントローラハードウェアのアップグレードに適したガイドを選択していることを確認する必要があります。

システムコマンドを使用してアップグレードを実行する場合は、次の表を参照してください。

[cols="30,70"]
|===
| この ONTAP バージョンを実行している場合 | システムコマンドでアップグレードするには、次のコマンドを使用します。 


| 9.8 以降 | link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto-app/index.html["ONTAP 9.8 以降を実行しているコントローラハードウェアをアップグレードするには、「 system controller replace 」コマンドを使用します"] 


| 9.5 から 9.7 | link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-auto/index.html["ONTAP 9.5 を実行しているコントローラハードウェアを ONTAP 9.7 にアップグレードするには、「 system controller replace 」コマンドを使用します"] 
|===
手動でアップグレードする場合は、次の表を参照してください。

[cols="30,70"]
|===
| この ONTAP バージョンを実行している場合 | 手動でアップグレードするには、次を使用します 


| 9.8 以降 | link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual-app/index.html["アグリゲートの再配置を使用して、 ONTAP 9.8 以降を実行しているコントローラハードウェアを手動でアップグレードします"] 


| 9.0 から 9.7 | link:http://docs.netapp.com/us-en/ontap-systems/upgrade-arl-manual/index.html["アグリゲートの再配置を使用して、 ONTAP 9.7 以前を実行しているコントローラハードウェアを手動でアップグレードします"] 
|===