---
permalink: asa-r2-c30/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa c30, replace the boot media 
summary: ASA C30 ストレージシステムのブートメディアを交換する前に、交換を正常に行うために必要な要件と考慮事項を満たしていることを確認してください。これには、適切な交換用ブートメディアがあること、障害が発生したコントローラの e0S（e0M レンチ）ポートが正常に動作していることを確認すること、オンボード キー マネージャ（OKM）または外部キー マネージャ（EKM）が有効になっているかどうかを確認することが含まれます。 
---
= ブートメディアの交換要件- ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C30 ストレージシステムのブートメディアを交換する前に、交換を正常に行うために必要な要件と考慮事項を満たしていることを確認してください。これには、適切な交換用ブートメディアがあること、障害が発生したコントローラの e0S（e0M レンチ）ポートが正常に動作していることを確認すること、オンボード キー マネージャ（OKM）または外部キー マネージャ（EKM）が有効になっているかどうかを確認することが含まれます。



== 要件

* 障害が発生したコンポーネントは、NetAppから受け取ったものと同じ容量の交換用FRUコンポーネントと交換する必要があります。
* 障害のあるコントローラのe0S（e0Mレンチ）ポートを障害状態にすることはできません。
+
e0Sポートは自動ブートリカバリに使用されます。

* OKMを使用するには、OKMパスフレーズファイルの内容が必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。






== 考慮事項

* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。


* 該当するプラットフォームの物理的な位置を特定するために、必要に応じてプラットフォームシャーシロケーション（青色）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
プラットフォームシャーシにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。



.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["コントローラをシャットダウン"]
