---
permalink: asa-r2-c30/io-module-overview.html 
sidebar: sidebar 
keywords: AFF c30, AFF c60, replace io module, add io module, hotswap io module 
summary: ASA C30 ストレージ システムは、I/O モジュールを拡張または交換する柔軟性を提供し、ネットワークの接続性とパフォーマンスを強化します。I/Oモジュールの追加または交換は、ネットワーク機能をアップグレードする場合や、障害が発生したモジュールに対処する場合に不可欠です。 
---
= I/O モジュールのメンテナンスの概要 - ASA C30
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C30ストレージシステムは、I/Oモジュールの拡張や交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードしたり、故障したモジュールに対処したりする際には、I/Oモジュールの追加、ホットスワップ、交換が不可欠です。

ストレージシステム内の故障したI/Oモジュールは、同じタイプのI/Oモジュール、または異なるタイプのI/Oモジュールと交換できます。ストレージシステムが特定の要件を満たしている場合は、クラスタとHA I/Oモジュールをホットスワップできます。また、空きスロットがあるストレージシステムにI/Oモジュールを追加することもできます。

* link:io-module-add.html["I/Oモジュールの追加"]
+
I/Oモジュールを追加すると、冗長性が向上し、1つのI/Oモジュールに障害が発生してもストレージシステムが動作し続けるようになります。

* link:io-module-hotswap-ha-slot4.html["クラスタとHA I/Oモジュールのホットスワップ"]
+
障害が発生したクラスタとHA I/Oモジュールをホットスワップすることで、ストレージシステムを最適な動作状態に復元できます。ホットスワップは、障害が発生したコントローラを手動で引き継ぐことなく実行できます。

+
この手順を使用するには、ストレージ システムでONTAP 9.17.1 以降が実行されており、特定のシステム要件を満たしている必要があります。

* link:io-module-replace.html["I/Oモジュールの交換"]
+
障害が発生したI/Oモジュールを交換すると、ストレージシステムを最適な動作状態に戻すことができます。


