---
permalink: a250/overview.html 
sidebar: sidebar 
keywords: AFF A250 specifications, AFF A250 specs, NetApp AFF A250, AFF A250 hardware 
summary: AFF A250ストレージシステムの主な仕様 
---
= AFF A250の主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下はAFF A250の厳選された仕様です。訪問 https://hwu.netapp.com["NetApp Hardware Universe の略"^]AFF A250 の仕様の完全なリストについては、(HWU) を参照してください。このページは、単一の高可用性ペアを反映しています。



=== AFF A250の主な仕様

プラットフォーム構成: AFF A250シングルシャーシ HA ペア

最大生容量: 1.1016 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 4

最小ONTAPバージョン: ONTAP 9.8RC1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 12 | 13.2 PB / 11.7 PiB | 1536 GB 


| SAN | 6 | 6.6 PB / 5.9 PiB | 768 GB 


| HAペア |  | 1.1 PB / 1.0 PiB | 128.0000 
|===


=== IO



==== オンボードIO

|===


| プロトコル | ポート 


| イーサネット 25 Gbps | 4 


| イーサネット 10 Gbps | 4 
|===


==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 4 


| イーサネット 25 Gbps | 20 


| イーサネット 10 Gbps | 4 


| FC 32 Gbps | 16 


| NVMe/FC 32Gbps | 16 


|  | 0 


| SAS 12Gbps | 8 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 2642 BTU/時
* 最悪の場合の電力: 3476 BTU/時
* 重量: 54.3ポンド/24.6kg
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 10°C ～ 35°C (50°F ～ 95°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 80% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響騒音：表示音響出力（LwAd）：7.2；br／音圧（LpAm）（傍観者位置）：69.1 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、外部シェルフの SAS 接続を介した SAS インバンド管理。
