---
permalink: a250/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: a250, replace the boot media 
summary: AFF A250 システムのブート メディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。 
---
= 自動ブートメディアリカバリの要件 - AFF A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 のブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、正しい交換用ブートメディアがあることの確認、障害のあるコントローラの e0S（e0M レンチ）ポートに障害がないことの確認、Onboard Key Manager（OKM）または External Key Manager（EKM）が有効になっているかどうかの確認が含まれます。

自動ブートメディアリカバリプロセスは、ONTAP 9.18.1 以降でのみサポートされています。ストレージシステムで以前のバージョンの ONTAP を実行している場合は、link:bootmedia-replace-workflow.html["手動ブート回復手順"]を使用してください。

* 障害が発生したコンポーネントは、NetAppから受け取ったものと同じ容量の交換用FRUコンポーネントと交換する必要があります。
* 障害のあるコントローラーの e0M (レンチ) ポートが接続されており、障害がないことを確認します。
+
e0M ポートは、自動ブート回復プロセス中に 2 つのコントローラー間で通信するために使用されます。

* OKM の場合、クラスター全体のパスフレーズとバックアップ データも必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。


* 障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。
+
** _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
** _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。




.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["コントローラをシャットダウン"]
