---
permalink: a250/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: aff a250, shutdown the controllers 
summary: シャーシを交換するには、コントローラをシャットダウンする必要があります。 
---
= コントローラをシャットダウンします（ AFF A250 ）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
この手順 は、2ノード、非MetroCluster構成専用です。システムのノードが3つ以上の場合は、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["4ノードクラスタで1つのHAペアを正常にシャットダウンして電源をオンにする方法"^]。

.作業を開始する前に
必要なもの：

* ONTAP のローカル管理者のクレデンシャル。
* ストレージ暗号化を使用する場合は、ネットアップのオンボードキー管理（OKM）クラスタ全体のパスフレーズ。
* 各コントローラのSP / BMCへのアクセス性。
* すべてのクライアント/ホストからネットアップシステム上のデータへのアクセスを停止します。
* 外部バックアップジョブを一時停止します。
* 交換に必要な工具と機器。



NOTE: FabricPool のクラウド階層として使用されるネットアップStorageGRID またはONTAP S3のシステムの場合は、を参照してください https://kb.netapp.com/onprem/ontap/hardware/What_is_the_procedure_for_graceful_shutdown_and_power_up_of_a_storage_system_during_scheduled_power_outage#["ストレージシステムの『解決ガイド』を正常にシャットダウンし、電源を投入します"] この手順 を実行した後。


NOTE: FlexArray アレイLUNを使用している場合は、この手順 の実行後に該当するシステムでシャットダウン手順 に関するベンダーのストレージアレイのドキュメントを参照してください。


NOTE: SSDを使用している場合は、を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU490["SU490：（影響：重大）SSDのベストプラクティス：電源がオフになってから2カ月以上が経過すると、ドライブ障害やデータ損失のリスクを回避できます"]

シャットダウン前のベストプラクティスは次のとおりです。

* 追加を実行します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["システムの健全性チェック"]。
* ONTAP をシステムの推奨リリースにアップグレードします。
* いずれかを解決します https://activeiq.netapp.com/["Active IQ ウェルネスアラートとリスク"]。システムコンポーネントのLEDなど、現在システムに発生している障害をメモします。


.手順
. SSHを使用してクラスタにログインするか、クラスタ内の任意のノードからローカルのコンソールケーブルとラップトップ/コンソールを使用してログインします。
. AutoSupport をオフにして、システムがオフラインになるまでの時間を指定します。
+
`system node autosupport invoke -node * -type all -messages "MAINT=8h Power Maintenance"`

. すべてのノードのSP / BMCアドレスを特定します。
+
`system service-processor show -node * -fields address`

. クラスタシェルを終了します。 `exit`
. 前の手順の出力に表示されたいずれかのノードのIPアドレスを使用して、SSH経由でSP / BMCにログインします。
+
コンソール/ラップトップを使用している場合は、同じクラスタ管理者のクレデンシャルを使用してコントローラにログインします。

+

NOTE: 進捗状況を監視できるように、すべてのSP / BMC接続とのSSHセッションを開きます。

. クラスタ内のすべてのノードを停止します。
+
`system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`。

+

NOTE: StrictSyncモードで動作するSnapMirror同期を使用するクラスタの場合： `system node halt -node * -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. というメッセージが表示されたら、クラスタ内の各コントローラに「* y *」と入力します `_Warning: Are you sure you want to halt node "cluster name-controller number"?
{y|n}:_`
. 各コントローラが停止するまで待ち、LOADERプロンプトを表示します。
. PSUのオン/オフスイッチがない場合は、各PSUの電源をオフにするか、電源プラグを抜きます。
. 各PSUから電源コードを抜きます。
. クラスタに関連付けられているすべてのコントローラ、ドライブシェルフ、およびスイッチの電源がオフになっていることを確認します。

