---
permalink: fas8200/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: fas8200, replace the boot media, manual, manual boot recovery 
summary: FAS8200システムでのブート メディアの交換について学習し、さまざまな交換方法を理解します。FAS8200システムは、手動のブート メディア回復手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= ブートメディアの交換 - FAS8200 の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS8200システムでのブート メディアの交換について学習し、さまざまな交換方法を理解します。ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリ ブート イメージ ファイルが格納されます。ネットワーク構成に応じて、無停止交換（HA ペアをネットワークに接続）または停止交換（2 回の再起動が必要）のいずれかを実行できます。

FAS8200システムは、手動のブート メディア回復手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。

「 image_xxx.tgz 」ファイルを格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

また ' この手順で後で使用するために 'image_xxx.tgz ファイルを USB フラッシュドライブにコピーする必要があります

* ブート・メディアを交換するための無停止かつ停止を伴う方法では 'var' ファイル・システムをリストアする必要があります
+
** 無停止で交換するには 'var' ファイル・システムをリストアするために HA ペアをネットワークに接続する必要があります
** 停止を伴う交換の場合 'var' ファイル・システムをリストアするためにネットワーク接続は必要ありませんが ' 再起動が 2 回必要です


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* 以下の手順のコマンドを正しいノードに適用することが重要です。
+
** impaired_node は、保守を実行しているノードです。
** Healthy node_name は、障害が発生したノードの HA パートナーです。



