---
permalink: fas8200/maintain-overview.html 
sidebar: sidebar 
keywords: fas8200 maintenance, maintenance, repairing fas8200, replace fas8200 components 
summary: FAS8200ストレージシステムのコンポーネント（ブートメディア、シャーシ、コントローラ、DIMM、電源など）に対してメンテナンス手順を実行できます。 
---
= FAS8200ストレージシステムのメンテナンスについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS8200ストレージシステムのコンポーネント（ブートメディア、シャーシ、コントローラ、DIMM、電源など）に対してメンテナンス手順を実行できます。



[[boot-media]]
== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



[[caching-module]]
== キャッシングモジュール

モジュールがオフラインになったことを示す単一のAutoSupport（ASUP）メッセージがシステムで登録された場合は、コントローラのキャッシングモジュールを交換する必要があります。



[[chassis]]
== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



[[controller]]
== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



[[dimm]]
== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



[[drive]]
== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



[[nvmem-battery]]
== NVMEM バッテリ

バッテリはコントローラに搭載されており、 AC 電源で障害が発生した場合にキャッシュデータを保持します。



[[pcie-card]]
== PCIe カード

PCIe（Peripheral Component Interconnect Express）カードは、マザーボードのPCIeスロットに接続する拡張カードです。



[[power-supply]]
== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



[[real-time-clock-battery]]
== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
