---
permalink: fas8200/maintain-overview.html 
sidebar: sidebar 
keywords: fas2600 maintenance, maintenance, repairing fas2600, repairing fas2600, replace aff fas2600 components, replace aff fas2600 components 
summary: fas2600ハードウェアのメンテナンス 
---
= FAS8200ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS8200ストレージシステムでは、次のコンポーネントについてメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== キャッシングモジュール

モジュールがオフラインになったことを示す単一のAutoSupport（ASUP）メッセージがシステムで登録された場合は、コントローラのキャッシングモジュールを交換する必要があります。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



== NVEMバッテリ

バッテリはコントローラに搭載されており、 AC 電源で障害が発生した場合にキャッシュデータを保持します。



== PCIe カード

PCIe（Peripheral Component Interconnect Express）カードは、マザーボードのPCIeスロットに接続する拡張カードです。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
