---
permalink: afx-1k/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: afx 1k, shut down the controller 
summary: ブート メディアを交換するときにデータの損失を防ぎ、システムの安定性を確保するために、AFX 1K ストレージ システム内の障害のあるコントローラーをシャットダウンします。 
---
= コントローラーをシャットダウンしてブートメディアを交換します - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブート メディアを交換するときにデータの損失を防ぎ、システムの安定性を確保するために、AFX 1K ストレージ システム内の障害のあるコントローラーをシャットダウンします。

障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じてコントローラのストレージ フェイルオーバー テイクオーバーを実行して、正常なコントローラが障害のあるコントローラ ストレージから引き続きデータを提供できるようにする必要があります。

.このタスクについて
* 4 つ以上のノードを持つクラスターがある場合は、クォーラム内になければなりません。ノードに関するクラスター情報を表示するには、 `cluster show`指示。詳細については、 `cluster show`コマンドについては、link:https://docs.netapp.com/us-en/ontap/system-admin/display-nodes-cluster-task.html["ONTAPクラスタ内のノードレベルの詳細を表示する"^] 。
* クラスターがクォーラムにない場合、または (障害のあるコントローラー以外の) コントローラーの正常性または適格性が false と表示される場合は、障害のあるコントローラーをシャットダウンする前に問題を修正する必要があります。見るlink:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^] 。


.手順
. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。
+
`system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`

+
次のAutoSupport メッセージは、ケースの自動作成を2時間停止します。

+
`cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 障害のあるコントローラのコンソールからの自動ギブバックを無効にします。
+
`storage failover modify -node impaired-node -auto-giveback-of false`

+

NOTE: 「自動ギブバックを無効にしますか？」と表示されたら、次のように入力します。 `y` 。

+
.. ONTAPバージョン 9.17.1 を実行していて、障害のあるコントローラを起動できないか、すでに引き継がれている場合は、障害のあるコントローラを起動する前に、正常なコントローラから HA 相互接続リンクを停止する必要があります。これにより、障害のあるコントローラによる自動ギブバックの実行が防止されます。
+
`system ha interconnect link off -node healthy-node -link 0`

+
`system ha interconnect link off -node healthy-node -link 1`

+

NOTE: ONTAPバージョン 9.17.1 を実行していない場合は、上記の手順をスキップして手順 3 に進みます。



. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
システムプロンプトまたはパスワードプロンプト
 a| 
正常なコントローラから障害のあるコントローラを引き継ぐか、停止します。
`storage failover takeover -ofnode _impaired_node_name_ -halt _true_`

_-halt true_ パラメータは、障害のあるノードを LOADER プロンプトに表示します。

|===


.次の手順
コントローラーをシャットダウンした後、link:bootmedia-replace.html["ブートメディアを変更する"] 。
