---
permalink: afx-1k/io-module-add.html 
sidebar: sidebar 
keywords: afx 1k, add I/O module 
summary: AFX 1K ストレージ システムに I/O モジュールを追加すると、ネットワーク接続が強化され、システムのデータ トラフィック処理能力が拡張されます。 
---
= I/Oモジュールを追加 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K ストレージ システムに I/O モジュールを追加すると、ネットワーク接続が強化され、システムのデータ トラフィック処理能力が拡張されます。

空きスロットがある場合、またはすべてのスロットが完全に使用されている場合は、AFX 1K ストレージ システムに I/O モジュールを追加できます。



== 手順1：障害のあるコントローラモジュールをシャットダウン

障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

.作業を開始する前に
ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。

.手順
. AutoSupportが有効になっている場合は、 AutoSupportメッセージ コマンドを呼び出して自動ケース作成を抑制します。
+
`system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`

+
次のAutoSupportコマンドは、自動ケース作成を 2 時間抑制します。

+
`cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。
+
`storage failover modify –node local -auto-giveback false`

. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待機しています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
正常なコントローラから障害コントローラをテイクオーバーまたは停止します。

`storage failover takeover -ofnode impaired_node_name -halt true`

その `-halt true`パラメータを指定すると、LOADER プロンプトが表示されます。

|===




== 手順2：新しいI/Oモジュールを追加する

ストレージシステムに使用可能なスロットがある場合は、使用可能なスロットの1つに新しいI/Oモジュールを取り付けます。すべてのスロットに空きがある場合は、既存のI/Oモジュールを取り外してスペースを確保し、新しいI/Oモジュールを取り付けます。

.作業を開始する前に
* チェックしてください https://hwu.netapp.com/["NetApp Hardware Universe の略"^]新しい I/O モジュールがストレージ システムおよびONTAPバージョンと互換性があることを確認します。
* 複数のスロットが使用可能な場合は、でスロットの優先順位を確認します https://hwu.netapp.com/["NetApp Hardware Universe の略"^] また、お使いの I/O モジュールに最適なものを使用してください。
* 他のすべてのコンポーネントが正常に機能していることを確認します。
* NetAppから受け取った交換用コンポーネントがあることを確認してください。


[role="tabbed-block"]
====
.使用可能なスロットへのI/Oモジュールの追加
--
使用可能なスロットがあるストレージシステムに、新しいI/Oモジュールを追加できます。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. ケーブルマネジメントトレイの内側にあるボタンを引いて下に回転させ、ケーブルマネジメントトレイを下に回転させます。
. ターゲットスロットブランキングモジュールをキャリアから取り外します。
+
.. ターゲットスロットのブランクモジュールのカムラッチを押し下げます。
.. カムラッチをモジュールからできるだけ離します。
.. カムレバーの開口部に指をかけ、モジュールをエンクロージャから引き出して、モジュールをエンクロージャから取り外します。


. I/O モジュールを取り付けます。
+
.. I/Oモジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. I/Oモジュールを指定のデバイスにケーブル接続します。
+

NOTE: 使用していない I/O スロットには、熱の問題を防ぐためにブランクが取り付けられていることを確認してください。

. ケーブルマネジメントトレイを上に回転させて閉じます。
. Loaderプロンプトで、ノードをリブートします。
+
`bye`

+

NOTE: これにより、I/Oモジュールとその他のコンポーネントが再初期化され、ノードがリブートされます。

. コンソールメッセージが停止したら、<enter>キーを押します。
+
** _login_ プロンプトが表示されたら、次の手順に進みます。
** ログイン プロンプトが表示されない場合は、パートナー ノードにログインします。


. override-destination-checks オプションを使用してルートのみを返します。
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 次のコマンドは、診断モードの特権レベルでのみ使用できます。権限レベルの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["ONTAP CLIコマンドの権限レベルを理解する"^] 。

+
エラーが発生した場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

. ギブバックレポートが完了してから5分待って、フェイルオーバーのステータスとギブバックのステータスを確認します。
+
`storage failover show`そして `storage failover show-giveback`

+

NOTE: 次のコマンドは、診断モードの特権レベルでのみ使用できます。

. HA 内部接続リンクがダウンしている場合は、次のようにしてリンクを復旧します。
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。
+
「 storage failover giveback -ofnode _impaired_node_name _

. コントローラ B について、上記の手順を繰り返します
. 正常なノードから、自動ギブバックを無効にした場合はリストアします。
+
`storage failover modify -node local -auto-giveback-of _true_`

. AutoSupportが有効になっている場合は、ケースの自動作成をリストアします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.フル実装したシステムへのI/Oモジュールの追加
--
フル装備のシステムにI/Oモジュールを追加するには、既存のI/Oモジュールを取り外し、その場所に新しいI/Oモジュールを取り付けます。

.このタスクについて
フル装備のシステムに新しいI/Oモジュールを追加する場合は、次のシナリオについて理解しておく必要があります。

[cols="1,2"]
|===
| シナリオ | アクションが必要です 


 a| 
NICからNIC（同じ数のポート）
 a| 
LIF は、コントローラモジュールがシャットダウンすると自動的に移行されます。



 a| 
NICからNIC（異なるポート数）
 a| 
選択したLIFを別のホームポートに完全に再割り当てします。詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF を移行する"^] 。



 a| 
NICからストレージI/Oモジュール
 a| 
System Manager を使用して、 LIF を別のホームポートに完全に移行します。手順については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF を移行する"^]。

|===
.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. ターゲット I/O モジュールのケーブルをすべて取り外します。
. ケーブルマネジメントトレイの内側にあるボタンを引いて下に回転させ、ケーブルマネジメントトレイを下に回転させます。
. ターゲットの I/O モジュールをシャーシから取り外します。
+
.. カムラッチボタンを押します。
.. カムラッチをモジュールからできるだけ離します。
.. カムレバーの開口部に指をかけ、モジュールをエンクロージャから引き出して、モジュールをエンクロージャから取り外します。
+
I/O モジュールが取り付けられていたスロットを記録しておいてください。



. I/Oモジュールをエンクロージャのターゲットスロットに取り付けます。
+
.. モジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. I/Oモジュールを指定のデバイスにケーブル接続します。
. 取り外しと取り付けの手順を繰り返して、コントローラの他のモジュールを交換します。
. ケーブルマネジメントトレイを上に回転させて閉じます。
. LOADERプロンプトからコントローラをリブートします。_bye_
+
これにより、PCIeカードおよびその他のコンポーネントが再初期化され、ノードがリブートされます。

. コンソールメッセージが停止したら、<enter>キーを押します。
+
** _login_ プロンプトが表示されたら、次の手順に進みます。
** ログイン プロンプトが表示されない場合は、パートナー ノードにログインします。


. override-destination-checks オプションを使用してルートのみを返します。
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: 次のコマンドは、診断モードの特権レベルでのみ使用できます。権限レベルの詳細については、以下を参照してください。link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["ONTAP CLIコマンドの権限レベルを理解する"^] 。

+
エラーが発生した場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

. ギブバックレポートが完了してから5分待って、フェイルオーバーのステータスとギブバックのステータスを確認します。
+
`storage failover show`そして `storage failover show-giveback`

+

NOTE: 次のコマンドは、診断モードの特権レベルでのみ使用できます。

. HA 内部接続リンクがダウンしている場合は、次のようにしてリンクを復旧します。
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。
+
`storage failover giveback -ofnode impaired_node_name`

. 自動ギブバックを無効にした場合は有効にします。
+
`storage failover modify -node local -auto-giveback-of true`

. 次のいずれかを実行します。
+
** ストレージ I/O モジュールを削除し、新しい NIC I/O モジュールをインストールした場合は、各ポートに対して次のネットワーク コマンドを使用します。
+
`storage port modify -node <node name>__ -port <port name>__ -mode network`

** NIC I/Oモジュールを取り外してストレージI/Oモジュールを取り付けた場合は、以下の手順に従ってNX224シェルフを取り付けてケーブル接続します。link:../nx224/hot-add-shelf.html["ホットアドNX224シェルフ"] 。


. コントローラ B について、上記の手順を繰り返します


--
====