---
permalink: afx-1k/maintain-overview.html 
sidebar: sidebar 
keywords: afx 1k maintenance, maintenance, repairing a1k, repairing afx 1k, replace afx 1k components, replace afx 1k components 
summary: AFX 1K ストレージ システムのハードウェアをメンテナンスして、長期的な信頼性と最適なパフォーマンスを確保します。故障したコンポーネントの交換など、定期的なメンテナンスを実施することで、ダウンタイムやデータ損失を防止できます。 
---
= メンテナンス手順の概要 - AFX 1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFX 1K ストレージ システムのハードウェアをメンテナンスして、長期的な信頼性と最適なパフォーマンスを確保します。故障したコンポーネントの交換など、定期的なメンテナンスを実施することで、ダウンタイムやデータ損失を防止できます。

メンテナンス手順では、AFX 1K ストレージ システムがすでにONTAP環境にストレージ ノードとして導入されていることを前提としています。



== システムコンホオネント

AFX 1K ストレージ システムでは、次のコンポーネントに対してメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow.html["ブートメディア"]
 a| 
ブート メディアには、システムのブート時に使用されるONTAPイメージ ファイルのプライマリ セットとセカンダリ セットが保存されます。



 a| 
link:controller-replace-workflow.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAPオペレーティングシステムソフトウェアを実行します。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
デュアルインラインメモリモジュール（DIMM）は、コンピュータメモリの一種です。コントローラのマザーボードにシステムメモリを追加するために取り付けられます。



 a| 
link:fan-replace.html["ファン"]
 a| 
ファンがコントローラを冷却します。



 a| 
link:nvram-replace.html["NVRAMモシユウル"]
 a| 
NVRAM (不揮発性ランダム アクセス メモリ) モジュールにより、システムの電源が失われた場合でも、コントローラは飛行中のデータを保護および保存できます。システム ID はNVRAMモジュールに保存されます。交換されると、コントローラは交換されたNVRAMモジュールからの新しいシステム ID を使用します。



 a| 
link:nvdimm-battery-replace.html["NVハツテリ"]
 a| 
NVバッテリは、電力損失後に転送中のデータをフラッシュメモリにデステージしている間、NVRAMモジュールに電力を供給します。



 a| 
link:io-module-overview.html["I/O モジュール"]
 a| 
I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



 a| 
link:power-supply-replace.html["電源装置"]
 a| 
電源装置は、コントローラに冗長な電源を提供します。



 a| 
link:rtc-battery-replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。



 a| 
link:system-management-replace.html["システム管理モジュール"]
 a| 
システム管理モジュールは、コントローラまたはシステムのメンテナンスを目的として、コントローラとコンソールまたはラップトップ間のインターフェイスを提供します。システム管理モジュールにはブートメディアが格納され、システムシリアル番号（SSN）が格納されています。

|===