---
permalink: asa150/overview.html 
sidebar: sidebar 
keywords: ASA A150 specifications, ASA A150 specs, NetApp ASA A150, ASA A150 hardware 
summary: ASA A150ストレージシステムの主な仕様 
---
= ASA A150の主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下はASA A150の厳選された仕様です。訪問 https://hwu.netapp.com["NetApp Hardware Universe の略"^]ASA A150 の仕様の完全なリストについては、(HWU) を参照してください。このページは、単一の高可用性ペアを反映しています。



=== ASA A150の主な仕様

プラットフォーム構成: ASA A150 UTA2 シングルシャーシ HA ペア

最大生容量: 0.5472 PB

メモリ: 64.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット:

最小ONTAPバージョン: ONTAP 9.13.1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS |  |  |  


| SAN | 6 | 3.3 PB / 2.9 PiB | 384 GB 


| HAペア |  | 0.5 PB / 0.5 PiB | 64.0000 
|===


=== IO



==== オンボードIO

|===


| プロトコル | ポート 


| イーサネット 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12Gbps | 4 
|===


==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 10 Gbps | 12 


| FC 16 Gbps | 8 


| SAS 12Gbps | 4 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 2. 
|===


=== ストレージネットワークのサポート

FC; iSCSI; NVMe/TCP;



=== システム環境仕様

利用できる環境データがありません。



=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネットベースのベースボード管理コントローラ（BMC）とONTAP管理インターフェース、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、SAS接続によるSASインバンド管理、[//] 2025-10-15 ontap-systems-internal/issues/1357
