---
permalink: fas50/bootmedia-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, replace the boot media 
summary: FAS50システムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、適切な量のストレージを搭載したUSBフラッシュドライブがあること、および正しい交換用ブートデバイスがあることを確認します。 
---
= ブートメディアの交換要件- FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50システムのブートメディアを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、適切な量のストレージを搭載したUSBフラッシュドライブがあること、および正しい交換用ブートデバイスがあることを確認します。

ブートメディアを交換する前に、次の要件と考慮事項を確認してください。



== 要件

* 「 image_xxx.tgz 」を格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。
* この手順であとで使用できるように、ファイルをUSBフラッシュドライブにコピーする必要があります `image_xxx.tgz` 。
* 障害が発生したコンポーネントは、プロバイダから受け取った容量と同じ容量の交換用FRUコンポーネントと交換する必要があります。




== 考慮事項

* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。


* 該当するプラットフォームの物理的な位置を特定するために、必要に応じてプラットフォームシャーシロケーション（青色）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
プラットフォームシャーシにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。



.次の手順
ブートメディアの交換要件を確認したら、を実行する必要がありlink:bootmedia-encryption-preshutdown-checks.html["暗号化キーのサポートとブートメディアのステータスを確認する"]ます。
