---
permalink: fas50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: fas50, prerequisite, replace the controller module 
summary: FAS50ストレージ・システムのコントローラを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、システムの他のすべてのコンポーネントが正常に動作していること、正しい交換用コントローラがあることの確認、コントローラのコンソール出力のテキストログファイルへの保存が含まれます。 
---
= コントローラの交換要件- FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50ストレージ・システムのコントローラを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、システムの他のすべてのコンポーネントが正常に動作していること、正しい交換用コントローラがあることの確認、コントローラのコンソール出力のテキストログファイルへの保存が含まれます。

コントローラの交換手順に関する要件と考慮事項を確認します。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====


== 要件

* すべてのシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
* コントローラを同じモデルタイプのコントローラと交換する必要があります。コントローラを交換するだけではシステムをアップグレードできません。
* この手順では、ドライブやシェルフを変更することはできません。




== 考慮事項

この手順のコマンドを正しいコントローラに適用することが重要です。

* impaired_controller は、交換するコントローラです。
* replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
* healthy_controller はサバイバーコントローラです。


.次の手順
障害のあるコントローラの交換要件を確認したら、を行う必要がありますlink:controller-replace-shutdown.html["障害のあるコントローラをシャットダウン"]。
