---
permalink: fas50/overview.html 
sidebar: sidebar 
keywords: FAS50 specifications, FAS50 specs, NetApp FAS50, FAS50 hardware 
summary: FAS50ストレージシステムの主な仕様 
---
= FAS50の主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下は FAS50 の厳選仕様です。訪問 https://hwu.netapp.com["NetApp Hardware Universe の略"^]FAS50 仕様の完全なリストについては、(HWU) を参照してください。このページは、単一の高可用性ペアを反映しています。



=== FAS50の主な仕様

プラットフォーム構成: FAS50 シングルシャーシ HA ペア

最大生容量: 10.5600 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、HAコントローラ2台

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 12

最小ONTAPバージョン: ONTAP 9.16.1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 4 | 42.2 PB / 37.5 PiB | 512 GB 


| SAN | 4 | 42.2 PB / 37.5 PiB | 512 GB 


| HAペア |  | 10.6 PB / 9.4 PiB | 128.0000 
|===


=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 16 


| イーサネット 25 Gbps | 24 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS 12Gbps | 16 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 2319 BTU/時
* 最悪の場合の電力: 3872 BTU/時
* 重量: 52.2ポンド/23.7kg
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 10°C ～ 35°C (50°F ～ 95°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 80% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響ノイズ：表示音響出力（LwAd）：8.0；br／音圧（LpAm）（傍観者位置）：70.5 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、外部シェルフの SAS 接続を介した SAS インバンド管理。
