---
permalink: fas50/io-module-overview.html 
sidebar: sidebar 
keywords: fas50, replace io module 
summary: FAS50 ストレージ システムは、I/O モジュールを拡張または交換してネットワーク接続とパフォーマンスを強化する柔軟性を提供します。ネットワーク機能をアップグレードしたり、故障したモジュールに対処したりする際には、I/Oモジュールの追加、ホットスワップ、交換が不可欠です。 
---
= I/Oモジュールメンテナンスの概要 - FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50 ストレージ システムは、I/O モジュールを拡張または交換してネットワーク接続とパフォーマンスを強化する柔軟性を提供します。ネットワーク機能をアップグレードしたり、故障したモジュールに対処したりする際には、I/Oモジュールの追加、ホットスワップ、交換が不可欠です。

ストレージシステム内の故障したI/Oモジュールは、同じタイプのI/Oモジュール、または異なるタイプのI/Oモジュールと交換できます。ストレージシステムが特定の要件を満たしている場合は、クラスタとHA I/Oモジュールをホットスワップできます。また、空きスロットがあるストレージシステムにI/Oモジュールを追加することもできます。

* link:io-module-add.html["I/Oモジュールの追加"]
+
I/Oモジュールを追加すると、冗長性が向上し、1つのI/Oモジュールに障害が発生してもストレージシステムが動作し続けるようになります。

* link:io-module-hotswap.html["I/O モジュールのホット スワップ"]
+
特定のI/Oモジュールを同等のI/Oモジュールとホット スワップすることで、ストレージシステムを最適な動作状態に復元できます。ホット スワップは、手動でテイクオーバーを実行することなく実行できます。

+
この手順を使用するには、ストレージ システムでONTAP 9.17.1 以降が実行されており、特定のシステム要件を満たしている必要があります。

* link:io-module-replace.html["I/Oモジュールの交換"]
+
障害が発生したI/Oモジュールを交換すると、ストレージシステムを最適な動作状態に戻すことができます。


