---
permalink: fas50/maintain-overview.html 
sidebar: sidebar 
keywords: fas50 maintenance, maintenance, repairing fas50, replace fas50 components 
summary: FAS50ストレージシステムのハードウェアをメンテナンスすることで、長期的な信頼性と最適なパフォーマンスを確保できます。故障したコンポーネントの交換など、定期的なメンテナンスを実施することで、ダウンタイムやデータ損失を防止できます。 
---
= ハードウェアメンテナンスの概要- FAS50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS50ストレージシステムのハードウェアをメンテナンスすることで、長期的な信頼性と最適なパフォーマンスを確保できます。故障したコンポーネントの交換など、定期的なメンテナンスを実施することで、ダウンタイムやデータ損失を防止できます。

メンテナンス手順では、FAS50 ストレージ システムがONTAP環境にストレージ ノードとしてすでに導入されていることを前提としています。



== システムコンホオネント

FAS50ストレージ・システムでは、次のコンポーネントについてメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["ブートメディア - 自動回復"]
 a| 
ブートメディアには、プライマリおよびセカンダリのONTAPイメージファイルセットが保存されています。ストレージシステムはこれを使用して、パートナーノードからイメージを起動し、適切なブートメニューオプションを自動的に実行して、交換用ブートメディアにブートイメージをインストールします。自動ブートメディアリカバリプロセスは、 ONTAP 9.17.1以降でのみサポートされています。ストレージシステムで以前のバージョンのONTAPを実行している場合は、 link:bootmedia-replace-workflow.html["手動ブート回復手順"] 。



 a| 
link:bootmedia-replace-workflow.html["ブートメディア - 手動リカバリ"]
 a| 
ブート メディアには、ストレージ システムが USB ドライブからイメージをブートし、パートナー ノードから構成を復元するために使用するONTAPイメージ ファイルのプライマリ セットとセカンダリ セットが保存されます。



 a| 
link:caching-module-hot-swap.html["キャッシングモジュール"]
 a| 
キャッシングモジュール（Flash Cacheモジュール）は、高速SSDを使用してアクセス頻度の高いデータを格納し、読み出しを高速化します。



 a| 
link:chassis-replace-workflow.html["シャーシ"]
 a| 
シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



 a| 
link:controller-replace-workflow.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAPオペレーティングシステムソフトウェアを実行します。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
デュアルインラインメモリモジュール（DIMM）は、コンピュータメモリの一種です。コントローラのマザーボードにシステムメモリを追加するために取り付けられます。



 a| 
link:fan-replace.html["ファン"]
 a| 
ファンによってコントローラとドライブが冷却されます。



 a| 
link:io-module-overview.html["I/O モジュール"]
 a| 
I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



 a| 
link:nvdimm-battery-replace.html["NVハツテリ"]
 a| 
不揮発性メモリ（NV）バッテリは、停電後に転送中のデータをフラッシュメモリにデステージしながら、NVMEMコンポーネントに電力を供給します。



 a| 
link:power-supply-replace.html["電源装置"]
 a| 
電源装置は、コントローラに冗長な電源を提供します。



 a| 
link:rtc-battery-replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。

|===