---
permalink: fas9500/bootmedia_replace.html 
sidebar: sidebar 
keywords: FAS9500, replace, boot, media, controller, directions. replace boot media, transfer image 
summary: コントローラモジュールを取り外して開き、コントローラのブートメディアの場所を確認して交換してから、交換用ブートメディアにイメージを転送する必要があります。 
---
= コントローラを取り外してブートメディアを交換し、ブートイメージFAS9500を転送します
:allow-uri-read: 


[role="lead"]
コントローラモジュールを取り外して開き、コントローラのブートメディアの場所を確認して交換してから、交換用ブートメディアにイメージを転送する必要があります。



== 手順 1 ：コントローラモジュールを取り外す

コントローラ内部のコンポーネントにアクセスするには、まずコントローラモジュールをシステムから取り外し、続いてコントローラモジュールのカバーを外す必要があります。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. 障害のあるコントローラモジュールからケーブルを外し、どのケーブルが何に接続されていたかを記録します。
. カムハンドルのテラコッタボタンを下にスライドさせてロックを解除します。
+
.アニメーション-コントローラモジュールの取り外し
video::5e029a19-8acc-4fa1-be5d-ae78004b365a[panopto]
+
image::../media/drw_9500_remove_PCM_source.svg[DRW 9500がPCMソースを削除します]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
カムハンドルのリリースボタン



 a| 
image::../media/legend_icon_02.svg[凡例アイコン 02]
 a| 
カムハンドル

|===
. カムハンドルを回転させて、コントローラモジュールをシャーシから完全に外し、コントローラモジュールをシャーシから引き出します。
+
このとき、空いている手でコントローラモジュールの底面を支えてください。

. コントローラモジュールのふた側を上にして、平らで安定した場所に置きます。カバーの青いボタンを押し、コントローラモジュールの背面にカバーをスライドさせてから、カバーを上に動かしてコントローラモジュールから外します。
+
image::../media/drw_9500_PCM_open_source.svg[DRW 9500 PCMオープンソース]



[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
コントローラモジュールのカバーの固定ボタン

|===


== 手順 2 ：ブートメディアを交換します

コントローラのブートメディアの場所を確認し、手順に従って交換する必要があります。

.手順
. コントローラモジュールの背面にある黒のエアダクトを開き、次の図またはコントローラモジュールの FRU マップを使用してブートメディアの場所を確認します。
+
.アニメーション-ブートメディアの交換
video::16df490c-f94f-498d-bb04-ae78004b3781[panopto]
+
image::../media/drw_9500_remove_boot_dev_source.svg[DRW 9500がブート開発ソースを削除します]

+
[cols="20%,90%"]
|===


 a| 
image:../media/legend_icon_01.svg["幅= 20"]
 a| 
リリースタブを押します



 a| 
image:../media/legend_icon_02.svg["幅= 20"]
 a| 
ブートメディア

|===
. ブートメディアケースの青いボタンを押してブートメディアをケースからリリースし、ブートメディアソケットからゆっくりと引き出します。
+

NOTE: ソケットやブートメディアが損傷する可能性があるため、ブートメディアをねじったり、真上に引き出したりしないでください。

. 交換用ブートメディアの端をブートメディアソケットに合わせ、ソケットにゆっくりと押し込みます。
. ブートメディアが正しい向きでソケットに完全に装着されたことを確認します。
+
必要に応じて、ブートメディアを取り外してソケットへの装着をやり直します。

. ブートメディアを押し下げて、ブートメディアケースの固定ボタンをはめ込みます。
. コントローラモジュールのカバーにあるピンをマザーボードキャリアのスロットに合わせてカバーを再び取り付け、所定の位置に収まるまでスライドさせます。




== 手順 3 ：ブートイメージをブートメディアに転送します

イメージがインストールされた USB フラッシュドライブを使用して、交換用ブートメディアにシステムイメージをインストールできます。ただし ' この手順の実行中に 'var' ファイル・システムをリストアする必要があります

.作業を開始する前に
* FAT32 にフォーマットされた、 4GB 以上の容量の USB フラッシュドライブが必要です。
* 障害のあるコントローラが実行していたバージョンの ONTAP イメージのコピー。該当するイメージは、ネットアップサポートサイトのダウンロードセクションからダウンロードできます
+
** NVE が有効な場合は、ダウンロードボタンの指示に従って、 NetApp Volume Encryption を使用してイメージをダウンロードします。
** NVE が有効になっていない場合は、ダウンロードボタンの指示に従って、 NetApp Volume Encryption なしでイメージをダウンロードします。


* スタンドアロンシステムの場合はネットワーク接続は必要ありませんが、 var ファイルシステムをリストアしたときに追加のリブートを実行する必要があります。


.手順
. コントローラモジュールの端をシャーシの開口部に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
. 必要に応じて、コントローラモジュールにケーブルを再接続します。
. USB フラッシュドライブをコントローラモジュールの USB スロットに挿入します。
+
USB フラッシュドライブは、 USB コンソールポートではなく、 USB デバイス用のラベルが付いたスロットに取り付けてください。

. コントローラモジュールをシステムに最後まで押し込み、カムハンドルの位置が USB フラッシュドライブに干渉していないことを確認します。カムハンドルを強く押し込んでコントローラモジュールを装着し、カムハンドルを閉じます。
+
ノードは、シャーシに完全に取り付けられるとすぐにブートを開始します。

. ブートを開始するときに Ctrl+C キーを押し、ブートプロセスを中断して LOADER プロンプトで停止します。「 Starting autoboot 」というメッセージが表示されたら、 Ctrl+C を押して中止します
+
このメッセージが表示されない場合は、 Ctrl+C キーを押し、メンテナンスモードでブートするオプションを選択して、ノードを停止して LOADER プロンプトを表示します。

. 環境変数と bootargs は保持されますが 'printenv bootargname' コマンドを使用して ' 必要なすべてのブート環境変数と bootargs がシステムタイプと構成に適切に設定されていることを確認し 'setenv variable-name <value> コマンドを使用してエラーを修正する必要があります
+
.. ブート環境変数を確認します。
+
*** bootarg.init.boot_clustered
*** partner-sysid
*** bootarg.init.flash_optimized for AFF の略
*** bootarg.init.san_optimized for AFF の略
*** bootarg.init.switchless_cluster.enable


.. 外部キーマネージャが有効になっている場合は、「 kenv 」 ASUP 出力に表示された bootarg 値を確認します。
+
*** bootarg.storageencryption.support<value>
*** bootarg.keymanager. support <value>
*** kmip.init.interface < 値 >
*** kmip.init.ipaddr < 値 >
*** kmip.init.netmask < 値 >
*** kmip.init.gateway < 値 >


.. オンボードキーマネージャが有効になっている場合は、「 kenv 」 ASUP 出力に表示されている bootarg 値を確認します。
+
*** bootarg.storageencryption.support<value>
*** bootarg.keymanager. support <value>
*** bootarg.onboard keymanager <value> という 2 つの属性を設定します


.. 'avenv' コマンドを使用して変更した環境変数を保存します
.. printenv variable-name コマンドを使用して ' 変更内容を確認します


. LOADER プロンプトでネットワーク接続タイプを設定します。
+
** DHCP を構成している場合： ifconfig e0a-auto
+

NOTE: 設定するターゲットポートは、ネットワーク接続を使用した var ファイルシステムのリストア中に、正常なノードから障害ノードへの通信に使用するポートです。このコマンドでは e0M ポートを使用することもできます。

** 手動接続を設定する場合は、「 ifconfig e0a-addr= filer_addr-mask= netmask -gw= gateway -dns= dns_addr-domain= dns_domain' 」のように入力します
+
*** filer_addr は、ストレージシステムの IP アドレスです。
*** netmask は、 HA パートナーに接続されている管理ネットワークのネットワークマスクです。
*** gateway は、ネットワークのゲートウェイです。
*** dns_addr は、ネットワーク上のネームサーバの IP アドレスです。
*** dns_domain は、 DNS ドメイン名です。
+
このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はありません。必要なのはサーバのホスト名だけです。





+

NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。詳細については、ファームウェアのプロンプトで「 help ifconfig 」と入力してください。

. コントローラがストレッチまたはファブリック接続の MetroCluster に含まれている場合は、 FC アダプタの構成をリストアする必要があります。
+
.. 保守モードでブート： boot_ontap maint
.. MetroCluster ポートをイニシエータとして設定します。 ucadmin modify -m fc -t iniitator adapter_name
.. 停止して保守モードに戻ります : 「 halt 」


+
変更はシステムのブート時に実装されます。


