---
permalink: fas9500/controller_replace_system_config_restore_and_verify.html 
sidebar: sidebar 
keywords:  
summary: ハードウェアの交換が完了してメンテナンスモードでブートしたら、交換用コントローラの下位のシステム構成を確認し、必要に応じてシステムを再設定してから、システムレベルの診断を実行します。 
---
= システム構成をリストアして確認します（FAS9500）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの交換が完了したら、交換用コントローラの下位のシステム構成を確認し、必要に応じてシステム設定を再設定してから、システムレベルの診断を実行します。



== 手順 1 ：コントローラモジュールの交換後にシステム時間を設定して確認します

交換用コントローラモジュールの日付と時刻は、 HA ペアの正常なコントローラモジュール、またはスタンドアロン構成の信頼できるタイムサーバに照らして確認する必要があります。日付と時刻が一致しない場合は、時刻の違いによるクライアントの停止を防ぐために、交換用コントローラモジュールで日付と時刻をリセットする必要があります。

これらの手順のコマンドを正しいシステムに適用することが重要です。

* replacement _node は、この手順で障害ノードと交換した新しいノードです。
* healthy_node は、 _replacement _node の HA パートナーです。


.手順
. _replacement _node に LOADER プロンプトが表示されない場合は、システムを停止して LOADER プロンプトを表示します。
. _healthy_node で、システム時刻「 show date 」を確認します
+
日付と時刻は GMT で表示されます。

. LOADER プロンプトで、 _replacement node の日付と時刻を確認します。 'how date]
+
日付と時刻は GMT で表示されます。

. 必要に応じて、交換用ノードの日付を GMT で設定します。 'et date_mm/dd/yyyy_`
. 必要に応じて、交換用ノードの時刻を GMT で設定します。「 set time _hh ： mm ： ss_` 」
. LOADER プロンプトで、 _replacement _node の日付と時刻を確認します。 'how dat'
+
日付と時刻は GMT で表示されます。





== 手順 2 ：コントローラモジュールの HA 状態を確認して設定します

コントローラモジュールの「 HA 」状態を確認し、必要に応じてシステム構成に合わせて状態を更新する必要があります。

. 交換用コントローラモジュールの保守モードで ' すべてのコンポーネントが同じ HA 状態を表示していることを確認します HA 構成の場合は 'ha-config show と表示されます
+
[cols="1,2"]
|===
| システムの構成 | すべてのコンポーネントの HA の状態 


 a| 
HA ペア
 a| 
高可用性



 a| 
4 つ以上のノードを含む MetroCluster FC 構成
 a| 
MCC



 a| 
MetroCluster IP 構成
 a| 
mccip

|===
. 表示されたコントローラモジュールのシステム状態がシステム構成と一致しない場合は、コントローラモジュールの HA 状態を「 ha-config modify controller_A_2 state_」 に設定します
. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は ' シャーシの HA 状態を設定します HA config modify chassis_HA-state_




== 手順 3 ：システムレベルの診断を実行します

コントローラを交換するたびに、特定のコンポーネントとサブシステムについて包括的な診断テストまたは集中的な診断テストを実行する必要があります。

診断手順のコマンドは、すべてコンポーネントを交換するノードから実行します。

. サービスを提供するノードが LOADER プロンプトに表示されていない場合は、ノードをリブートします。「 halt
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. LOADER プロンプトで、システムレベルの診断用に特別に設計されたドライバ「 boot_diags 」にアクセスします
+
ブート・プロセス中に 'Maintenance] モードのプロンプト（ *> ）が表示されるまで 'y とプロンプトを入力しても安全です

. コントローラモジュールで使用可能なデバイスを表示してメモします。 'diag device show -dev MB
+
コントローラモジュールのデバイスおよびポートとして、次のいくつかが表示されます。

+
** bootmedia は、システムのブートデバイスです。
** cna は、ネットワークやストレージデバイスに接続されていない統合ネットワークアダプタまたはインターフェイスです。
** fcal は、 Fibre Channel ネットワークに接続されていない Fibre Channel-Arbitrated Loop デバイスです。
** env は、マザーボード環境です。
** mem はシステムメモリです。
** nic は、ネットワークインターフェイスカードです。
** nvram は、不揮発性 RAM です。
** nvmem は、 NVRAM とシステムメモリの組み合わせです。
** sas は、ディスクシェルフに接続されていない Serial Attached SCSI デバイスです。


. 必要に応じて診断を実行します。
+
[cols="1,2"]
|===
| 診断テストを実行する対象 | 作業 


 a| 
個々のコンポーネント
 a| 
.. ステータスログ「 `diag device clearstatus` 」を消去します
.. 選択したデバイスで使用可能なテストを表示します。「 sldiag device show -dev dev_name
+
dev_name には、前の手順で特定したポートとデバイスのいずれかを指定します。

.. 出力を確認し、必要に応じて実行するテストのみを選択します。「 sldiag device modify -dev dev_name -selection only
+
-selection only - デバイスに対して実行しないその他のテストをすべて無効にします。

.. 選択したテスト「 sldiag device run -dev dev_name 」を実行します
+
テストが完了すると、次のメッセージが表示されます。

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. 失敗したテストがないことを確認します :sldiag device status -dev dev_name -long-state failed
+
テストに失敗した場合は、プロンプトに戻ります。失敗した場合は、そのステータスがすべて表示されます。





 a| 
同時に複数のコンポーネント
 a| 
.. 前の手順の出力で有効なデバイスと無効なデバイスを確認し、同時に実行するデバイスを決定します。
.. デバイスに対する個々のテストを一覧表示します。「 sldiag device show -dev dev_name 」
.. 出力を確認し、必要に応じて実行するテストのみを選択します。「 sldiag device modify -dev dev_name -selection only
+
- selection only を指定すると、デバイスに対して実行しないその他のテストがすべて無効になります。

.. テストが変更されたことを確認します。 'lddiag device show'
.. 同時に実行するデバイスごとに上記の手順を繰り返します。
.. すべてのデバイスで診断を実行します： 'lddiag device run
+

IMPORTANT: 診断の実行を開始した後は、エントリを追加または変更しないでください。

+
テストが完了すると、次のメッセージが表示されます。

+
[listing]
----
*> <SLDIAG:_ALL_TESTS_COMPLETED>
----
.. ノードにハードウェアの問題がないことを確認します。「 diag device status -llong -state failed 」
+
テストに失敗した場合は、プロンプトに戻ります。失敗した場合は、そのステータスがすべて表示されます。



|===
. 前述の手順の結果に応じて、次に進みます。
+
[cols="1,2"]
|===
| システムレベルの診断のテスト結果 | 作業 


 a| 
は失敗なしで完了しました
 a| 
.. ステータスログ「 `diag device clearstatus` 」を消去します
.. ログがクリアされたことを確認します。「 diag device status 」
+
次のデフォルトの応答が表示されます。

+
SLDIAG ：ログメッセージが存在しません。

.. 保守モードを終了します :halt
+
ノードに LOADER プロンプトが表示されます。

.. LOADER プロンプトからノードをブートします。 bye
.. ノードを通常動作に戻します。


|===


[cols="1,2"]
|===
| ノードの構成 | 作業 


 a| 
HA ペア
 a| 
ギブバックを実行します。「 storage failover giveback -ofnode replacement_node_name 」


NOTE: 自動ギブバックを無効にした場合は、 storage failover modify コマンドを使用して再度有効にします。



 a| 
テストが失敗しました
 a| 
問題の原因を特定します。

. 保守モードを終了します :halt
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. シャーシ内のコントローラモジュールの数に応じて、電源装置をオフにするか、オンのままにします。+ 他のコントローラモジュールに電力を供給するために、電源装置をオンのままにします。
. システムレベルの診断を実行するための考慮事項をすべて確認するとともに、ケーブルがしっかりと接続されているか、ハードウェアコンポーネントがストレージシステムに適切に取り付けられているかを確認します。
. 対象となるコントローラモジュールをブートし、ブートメニューを表示するよう求められたら Ctrl+C キーを押して、ブートを中断します。+ コントローラモジュールを完全に取り付けると、モジュールがブートします。
. メニューから、メンテナンスモードでのブートを選択します。
. 次のコマンドを入力して保守モードを終了します :halt
+
コマンドを問題したら、システムが LOADER プロンプトで停止するまで待ちます。

. システムレベルの診断テストを再実行します。


|===