---
permalink: fas9500/controller_replace_system_config_restore_and_verify.html 
sidebar: sidebar 
keywords:  
summary: ハードウェアの交換が完了してメンテナンスモードでブートしたら、交換用コントローラの下位システム構成を確認し、必要に応じてシステムを再設定します。 
---
= システム構成をリストアして確認します（FAS9500）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ハードウェアの交換が完了したら、交換用コントローラの下位システム構成を確認し、必要に応じてシステム設定を再設定します。



== 手順 1 ：コントローラモジュールの交換後にシステム時間を設定して確認します

交換用コントローラモジュールの日付と時刻は、 HA ペアの正常なコントローラモジュール、またはスタンドアロン構成の信頼できるタイムサーバに照らして確認する必要があります。日付と時刻が一致しない場合は、時刻の違いによるクライアントの停止を防ぐために、交換用コントローラモジュールで日付と時刻をリセットする必要があります。

.このタスクについて
これらの手順のコマンドを正しいシステムに適用することが重要です。

* replacement _node は、この手順で障害ノードと交換した新しいノードです。
* healthy_node は、 _replacement _node の HA パートナーです。


.手順
. _replacement _node に LOADER プロンプトが表示されない場合は、システムを停止して LOADER プロンプトを表示します。
. _healthy_nodeで、システム時間を確認します。 `cluster date show`
+
日時は設定されたタイムゾーンに基づいています。

. LOADER プロンプトで、 _replacement node の日付と時刻を確認します。 'how date]
+
日付と時刻は GMT で表示されます。

. 必要に応じて、交換用ノードの日付を GMT で設定します。 'et date_mm/dd/yyyy_`
. 必要に応じて、交換用ノードの時刻を GMT で設定します。「 set time _hh ： mm ： ss_` 」
. LOADERプロンプトで、_replacement_nodeの日時を確認します。 `date`
+
日付と時刻は GMT で表示されます。





== 手順 2 ：コントローラモジュールの HA 状態を確認して設定します

コントローラモジュールの「 HA 」状態を確認し、必要に応じてシステム構成に合わせて状態を更新する必要があります。

. 交換用コントローラモジュールの保守モードで ' すべてのコンポーネントが同じ HA 状態を表示していることを確認します HA 構成の場合は 'ha-config show と表示されます
+
[cols="1,2"]
|===
| システムの構成 | すべてのコンポーネントの HA の状態 


 a| 
HA ペア
 a| 
高可用性



 a| 
4 つ以上のノードを含む MetroCluster FC 構成
 a| 
MCC



 a| 
MetroCluster IP 構成
 a| 
mccip

|===
. 表示されたコントローラモジュールのシステム状態がシステム構成と一致しない場合は、コントローラモジュールの HA 状態を「 ha-config modify controller_A_2 state_」 に設定します
. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は ' シャーシの HA 状態を設定します HA config modify chassis_HA-state_

