---
permalink: fas9500/controller_replace_recable_reassign_disks.html 
sidebar: sidebar 
keywords:  
summary:  
---
= システムとFAS9500をケーブルで再接続します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージおよびネットワーク接続をケーブルで再接続して、交換用手順を続行します。



== 手順 1 ：システムにケーブルを再接続します

コントローラモジュールのストレージとネットワークをケーブルで再接続する必要があります。

.手順
. システムにケーブルを再接続します。
. を使用して、ケーブル接続が正しいことを確認します https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
.. Config Advisor をダウンロードしてインストールします。
.. ターゲットシステムの情報を入力し、データ収集をクリックします。
.. Cabling タブをクリックし ' 出力を確認しますすべてのディスクシェルフが表示されていること、およびすべてのディスクが出力に表示されていることを確認し、ケーブル接続に関する問題が見つかった場合は修正します。
.. 該当するタブをクリックして他のケーブル接続を確認し、 Config Advisor からの出力を確認します。





NOTE: システム ID とディスク割り当て情報は NVRAM モジュールにあります。 NVRAM モジュールはコントローラモジュールとは別のモジュールに搭載されており、コントローラモジュールの交換による影響はありません。



== 手順 2 ：ディスクを再割り当てする

HA ペアのストレージシステムの場合、手順の最後でギブバックが実行されると、新しいコントローラモジュールのシステム ID がディスクに自動的に割り当てられます。_replacement _node のブート時にシステム ID の変更を確定し、その変更が実施されたことを確認する必要があります。

この手順は、 HA ペアの ONTAP を実行するシステムにのみ適用されます。

. _replacement _node が Maintenance モード ( プロンプトに *>` が表示されている ) の場合は 'Maintenance モードを終了して ' LOADER プロンプト :halt に進みます
. システム ID が一致しないためにシステム ID を上書きするかどうかを尋ねられた場合は、 _replacement _ node の LOADER プロンプトから「 y 」と入力し、ノードをブートします。「 boot_ontap 」
. _replacement _node コンソールに Waiting for giveback... というメッセージが表示されるまで待ち、正常なノードから、新しいパートナーシステム ID が自動的に割り当てられていることを確認します。 storage failover show
+
コマンド出力には、障害ノードでシステム ID が変更されたことを示すメッセージが表示され、正しい古い ID と新しい ID が示されます。次の例では、 node2 の交換が実施され、新しいシステム ID として 151759706 が設定されています。

+
[listing]
----
node1> storage failover show
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 正常なノードから、コアダンプがすべて保存されたことを確認します。
+
.. advanced 権限レベルに切り替えます。「 set -privilege advanced 」
+
advanced モードで続行するかどうかを確認するプロンプトが表示されたら、「 y 」と入力します。advanced モードのプロンプトが表示されます（ * > ）。

.. コアダンプをすべて保存します。「 system node run -node _local-node-name_partner savecore 」
.. savecore コマンドの完了を待機してからギブバックを実行します。
+
次のコマンドを入力すると、 savecore コマンドの進行状況を監視できます。 'system node run -node _local-node-name_partner savecore -s

.. admin 権限レベルに戻ります。「 set -privilege admin 」


. ストレージシステムでストレージまたはボリュームの暗号化が設定されている場合は、オンボードキー管理と外部キー管理のどちらを使用しているかに応じて、次のいずれかの手順に従ってストレージまたはボリューム暗号化機能をリストアする必要があります。
+
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html["オンボードキー管理の暗号化キーをリストア"^]
** https://docs.netapp.com/us-en/ontap/encryption-at-rest/restore-external-encryption-keys-93-later-task.html["外部キー管理の暗号化キーをリストアします"^]


. ノードをギブバックします。
+
.. 正常なノードから、交換したノードのストレージをギブバックします。「 storage failover giveback -ofnode replacement_node_name _
+
_replacement _node はストレージをテイクバックしてブートを完了します。

+
システム ID が一致しないためにシステム ID を上書きするかどうかを確認するメッセージが表示された場合は 'y' と入力する必要があります

+

NOTE: ギブバックが拒否されている場合は、拒否を無効にすることを検討してください。

+
詳細については、を参照してください https://docs.netapp.com/us-en/ontap/high-availability/ha_manual_giveback.html#if-giveback-is-interrupted["手動ギブバックコマンド"^] 拒否を無視するトピック。

.. ギブバックが完了したら、 HA ペアが正常でテイクオーバーが可能であることを確認します。 storage failover show
+
「 storage failover show 」コマンドの出力に、パートナーメッセージで変更されたシステム ID は含まれません。



. ディスクが正しく割り当てられたことを確認します。「 storage disk show -ownership
+
replacement _node には、新しいシステム ID が表示されます。次の例では、 node1 で所有されているディスクに、新しいシステム ID 1873775277 が表示されています。

+
[listing]
----
node1> storage disk show -ownership

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----
. システムが MetroCluster 構成になっている場合は ' ノードのステータスを監視します MetroCluster node show
+
MetroCluster 構成では、交換後に通常の状態に戻るまで数分かかります。この時点で各ノードの状態が設定済みになります。 DR ミラーリングは有効で、通常モードになります。MetroCluster node show -fields node-systemid' コマンドの出力には、 MetroCluster 設定が通常の状態に戻るまで古いシステム ID が表示されます。

. ノードが MetroCluster 構成になっている場合は、 MetroCluster の状態に応じて、元の所有者がディザスタサイトのノードである場合に DR ホーム ID のフィールドにディスクの元の所有者が表示されることを確認します。
+
これは、次の両方に該当する場合に必要です。

+
** MetroCluster 構成がスイッチオーバー状態である。
** replacement _node は、ディザスタサイトのディスクの現在の所有者です。
+
詳細については、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["4 ノード MetroCluster 構成での HA テイクオーバーおよび MetroCluster スイッチオーバー中のディスク所有権の変更"^] トピック：



. システムが MetroCluster 構成になっている場合は、各ノードが構成されていることを確認します。「 MetroCluster node show -fields configurion-state 」
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 各ノードに、想定されるボリュームが存在することを確認します。 vol show -node node-name
. リブート時の自動テイクオーバーを無効にした場合は、正常なノードで「 storage failover modify -node replacement-node-name -onreboot true 」を有効にします

