---
permalink: fas9500/dcpm_NVRAM11_battery_replace.html 
sidebar: sidebar 
keywords: FAS9500 
summary: NVRAM11 バッテリを搭載したデステージコントローラ電源モジュール \ （ DCPM \ ）をホットスワップするには、障害が発生した DCPM モジュールの場所を確認し、シャーシから取り外して、交換用 DCPM モジュールをインストールする必要があります。 
---
= NVRAM11バッテリを搭載したデステージコントロール電源モジュールFAS9500を交換してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NVRAM11 バッテリを搭載したデステージコントローラ電源モジュール（ DCPM ）をホットスワップするには、障害が発生した DCPM モジュールの場所を確認し、シャーシから取り外して、交換用の DCPM モジュールをインストールする必要があります。

障害が発生したモジュールをシャーシから取り外す前に、交換用の DCPM モジュールを手元に置いておく必要があります。このモジュールは、取り外してから 5 分以内に交換する必要があります。DCPM モジュールをシャーシから取り外すと、他のコントローラモジュールへのフェイルオーバー以外に、 DCPM モジュールを所有するコントローラモジュールのシャットダウン保護はありません。



== 手順 1 ： DCPM モジュールを交換します

システムの DCPM モジュールを交換するには、障害が発生した DCPM モジュールをシステムから取り外し、新しい DCPM モジュールと交換する必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. システム前面のベゼルを取り外し、脇に置きます。
. モジュールの警告 LED を調べて、システムの前面にある故障した DCPM モジュールの場所を確認します。
+
モジュールに障害が発生すると、 LED はオレンジに点灯します。

+

IMPORTANT: DCPM モジュールは取り外してから 5 分以内にシャーシ内で交換する必要があります。そうしないと、関連するコントローラがシャットダウンします。

. モジュールハンドルのテラコッタロックボタンを押し、 DCPM モジュールをシャーシから取り出します。
+



endif::[]
