---
permalink: fas9500/fan_swap_out.html 
sidebar: sidebar 
keywords:  
summary: サービスを中断せずにファンモジュールを交換するには、特定の順序でタスクを実行する必要があります。 
---
= ファンとFAS9500を交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
サービスを中断せずにファンモジュールを交換するには、特定の順序でタスクを実行する必要があります。


IMPORTANT: シャーシからファンモジュールを取り外したら 2 分以内にファンモジュールを交換する必要があります。システムの通気が遮断されて 2 分が経過すると、過熱を防ぐためにコントローラモジュールがシャットダウンします。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. （必要な場合）両手でベゼルの両側の開口部を持ち、手前に引いてシャーシフレームのボールスタッドからベゼルを外します。
. 交換が必要なファンモジュールを特定するために、コンソールのエラーメッセージを確認し、ファンモジュールの警告 LED を確認します。
. ファンモジュールのテラコッタボタンを押し、空いている手でファンモジュールを支えながら、ファンモジュールをシャーシからまっすぐ引き出します。
+

IMPORTANT: ファンモジュールは奥行きがないので、シャーシから突然落下してけがをすることがないように、必ず空いている手でファンモジュールの底面を支えてください。

+
.アニメーション-ファンの取り外し/取り付け
video::86b0ed39-1083-4b3a-9e9c-ae78004c2ffc[panopto]
+
image::../media/drw_9500_remove_install_fan.svg[DRW 9500がインストールファンを取り外します]

+
[cols="20%,80%"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
Terra cotta リリースボタン



 a| 
image::../media/legend_icon_02.svg[凡例アイコン 02]
 a| 
ファンをスライドさせてシャーシから取り外します

|===
. ファンモジュールを脇へ置きます。
. 交換用ファンモジュールの端をシャーシの開口部に合わせ、完全に固定されるまでシャーシに挿入します。
+
稼働中のシステムの場合、ファンモジュールがシャーシに正常に挿入されると、黄色の警告 LED が 4 回点滅します。

. ベゼルをボールスタッドに合わせ、ボールスタッドにそっと押し込みます。
. 障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"^] 詳細については、を参照してください。

