---
permalink: fas9500/maintain-overview.html 
sidebar: sidebar 
keywords: FAS9500 maintenance, maintenance, repairing FAS9500, repairing aff FAS9500, replace FAS9500 components, replace FAS9500 components 
summary: ASA FAS9500ハードウェアのメンテナンス 
---
= FAS9500ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS9500ストレージ・システムでは、次のコンポーネントのメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== キャッシングモジュール

モジュールがオフラインになったことを示す単一のAutoSupport（ASUP）メッセージがシステムで登録された場合は、コントローラのキャッシングモジュールを交換する必要があります。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DCPM を実行します

DCPM（デステージコントローラ電源モジュール）には、NVRAM11バッテリが搭載されています。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== ファン

ファンによってコントローラが冷却されます。



== I/O モジュール

I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



== LED USB

LED USB モジュールは、コンソールポートおよびシステムステータスへの接続を提供します。



== NVRAM

NVRAMモジュール（Non-Volatile Random Access Memory）を使用すると、電源を再投入したりシステムをリブートしたりしても、コントローラでデータを保持できます。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
