---
permalink: fas2800/bootmedia-replace.html 
sidebar: sidebar 
keywords: fas2800, replace, boot, media, controller, module, fru map 
summary: コントローラのブートメディアの場所を確認し、手順に従って交換する必要があります。 
---
= ブートメディアを交換します- FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


ブートメディアを交換するには、障害のあるコントローラモジュールを取り外し、交換用ブートメディアを取り付けて、ブートイメージを USB フラッシュドライブに転送する必要があります。



== 手順 1 ：コントローラモジュールを取り外す

[role="lead"]
コントローラ内部のコンポーネントにアクセスするには、まずコントローラモジュールをシステムから取り外し、続いてコントローラモジュールのカバーを外す必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. ケーブルマネジメントデバイスに接続しているケーブルをまとめているフックとループストラップを緩め、システムケーブルと SFP をコントローラモジュールから外し（必要な場合）、どのケーブルが何に接続されていたかを記録します。
. カムハンドルのラッチをつかんで解除し、カムハンドルを最大限に開いてコントローラモジュールをミッドプレーンから離し、両手でコントローラモジュールをシャーシから外します。
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[DRW 2850 PCM取り外し取り付けIEOPS 694]

. コントローラモジュールを裏返し、平らで安定した場所に置きます。
. コントローラモジュールの側面にある青いボタンを押してカバーを開き、カバーを上に回してコントローラモジュールから取り外します。
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[DRW 2850オープンコントローラモジュールはIEOPS 695をカバーしています]



[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
コントローラモジュールカバーのリリースボタン

|===


== 手順 2 ：ブートメディアを交換します

メザニンカードの下にあるコントローラモジュールのブートメディアの場所を確認し、手順に従って交換します。

.アニメーション-ブートメディアを交換します
video::10a29a01-a86e-451c-b05a-af4701726f57[panopto]
image:../media/drw_2850_replace_boot_media_IEOPS-696.svg["幅= 500"]

[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
ブートメディアの固定ツメ

|===
.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. 次の図またはコントローラモジュールのFRUマップを使用して、メザニンカードを取り外します。
+
.. メザニンカードベゼルをコントローラモジュールからまっすぐ引き出して取り外します。
.. メザニンカードの取り付けネジを緩めます。
+

NOTE: つまみネジは、指またはドライバで緩めることができます。指を使用する場合は、NVバッテリの横にある取り付けネジで指で購入しやすくするために、NVバッテリを上に回転させなければならない場合があります。

.. メザニンカードをまっすぐ持ち上げます。


. ブートメディアを交換します。
+
.. ブートメディアケースの青いボタンを押してブートメディアをケースから外し、ブートメディアを上に回転させ、ブートメディアソケットからゆっくりと引き出します。
+

NOTE: ソケットやブートメディアが損傷する可能性があるため、ブートメディアをねじったり、真上に引き出したりしないでください。

.. 交換用ブートメディアの端をブートメディアソケットに合わせ、ソケットにゆっくりと押し込みます。
ブートメディアが正しい向きでソケットに完全に装着されたことを確認し、必要に応じてブートメディアを取り外してソケットに装着し直します。
.. 青色の固定ボタンを押し、ブートメディアを最後まで回転させ、ロックボタンを放してブートメディアを所定の位置にロックします。


. メザニンカードを再度取り付けます。
+
.. マザーボードのソケットをメザニンカードのソケットに合わせ、カードをソケットに慎重に装着します。
.. メザニンカードの3本の取り付けネジを締めます。
.. メザニンベゼルを再度取り付けます。


. コントローラモジュールのカバーを再度取り付け、所定の位置にロックします。




== 手順 3 ：ブートイメージをブートメディアに転送します

イメージがインストールされたUSBフラッシュドライブを使用して、交換用ブートメディアにシステムイメージをインストールします。この手順の実行中にvarファイルシステムをリストアする必要があります。

.作業を開始する前に
* 4GB以上の容量がある、MBR / FAT32にフォーマットされたUSBフラッシュドライブが必要です。
* ネットワーク接続が必要です。


.手順
. 適切なバージョンのONTAPイメージを、フォーマットされたUSBフラッシュドライブにダウンロードします。
+
.. 使用 https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_determine_if_the_running_ONTAP_version_supports_NetApp_Volume_Encryption_(NVE)["実行しているONTAPのバージョンでNetApp Volume Encryption（NVE）がサポートされているかどうかを確認する方法"^] ボリューム暗号化が現在サポートされているかどうかを確認します。
+
*** クラスタでNVEがサポートされている場合は、NetApp Volume Encryptionを含むイメージをダウンロードします。
*** クラスタでNVEがサポートされていない場合は、NetApp Volume Encryptionを含まないイメージをダウンロードします。
を参照してください https://kb.netapp.com/onprem/ontap/os/Which_ONTAP_image_should_I_download%3F_With_or_without_Volume_Encryption%3F["どのONTAPイメージをダウンロードすればよいですか？ボリューム暗号化を使用するかどうか"^] 詳細：




. ダウンロードしたイメージを解凍します。
+

NOTE: Windows を使用して内容を展開する場合は、 winzip を使用してネットブートイメージを展開しないでください。7-Zip や WinRAR など、別の抽出ツールを使用します。

+
解凍されたサービスイメージファイルには、次の 2 つのフォルダがあります。

+
** 「 boot 」を指定します
** 「 EFI 」
+
... EFI フォルダを USB フラッシュドライブの最上位ディレクトリにコピーします
+
USB フラッシュドライブには、 EFI フォルダと、障害のあるコントローラが実行しているものと同じバージョンの Service Image （ BIOS ）が必要です。

... USB フラッシュドライブをラップトップから取り外します。




. コントローラモジュールを設置します。
+
.. コントローラモジュールの端をシャーシの開口部に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
.. コントローラモジュールにケーブルを再接続します。
+
ケーブルを再接続する際は、メディアコンバータ（ SFP ）も取り付け直してください（メディアコンバータを取り外した場合）。



. USB フラッシュドライブをコントローラモジュールの USB スロットに挿入します。
+
USB フラッシュドライブは、 USB コンソールポートではなく、 USB デバイス用のラベルが付いたスロットに取り付けてください。

. コントローラモジュールをシステムに最後まで押し込み、カムハンドルの位置が USB フラッシュドライブに干渉していないことを確認します。カムハンドルを強く押し込んでコントローラモジュールを装着し、カムハンドルを閉じ、取り付けネジを締めます。
+
コントローラは、シャーシに完全に取り付けられるとすぐにブートを開始します。

. ブートを開始するときに Ctrl+C キーを押し、ブートプロセスを中断して LOADER プロンプトで停止します。「 Starting autoboot 」というメッセージが表示されたら、 Ctrl+C を押して中止します
+
このメッセージが表示されない場合は、 Ctrl+C キーを押し、メンテナンスモードでブートするオプションを選択してから、コントローラを停止して LOADER プロンプトを表示します。

. シャーシ内にコントローラが 1 台しかないシステムの場合は、電源を再接続して電源装置の電源をオンにします。
+
システムがブートを開始し、 LOADER プロンプトで停止します。

. LOADER プロンプトでネットワーク接続タイプを設定します。
+
** DHCP を構成している場合： ifconfig e0a-auto
+

NOTE: 設定するターゲットポートは、正常なコントローラから障害コントローラへの通信に使用するポートで、 var ファイルシステムのリストア時にネットワーク接続で使用します。このコマンドでは e0M ポートを使用することもできます。

** 手動接続を設定する場合は、「 ifconfig e0a-addr= filer_addr-mask= netmask -gw= gateway -dns= dns_addr-domain= dns_domain' 」のように入力します
+
*** filer_addr は、ストレージシステムの IP アドレスです。
*** netmask は、 HA パートナーに接続されている管理ネットワークのネットワークマスクです。
*** gateway は、ネットワークのゲートウェイです。
*** dns_addr は、ネットワーク上のネームサーバの IP アドレスです。
*** dns_domain は、 DNS ドメイン名です。
+
このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はありません。必要なのはサーバのホスト名だけです。





+

NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細を確認できます。


