---
permalink: fas2800/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: キットに付属のRMA指示書に従って、シャーシのHA状態を確認し、アグリゲートをスイッチバックし、障害が発生したパーツをNetAppに返却する必要があります。 
---
= 構成をリストアして確認- FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


キットに付属のRMA指示書の説明に従って、シャーシのHA状態でシステムを起動し、障害が発生した部品をNetAppに戻します。



== 手順 1 ：シャーシの HA 状態を確認して設定します

シャーシの HA 状態を確認し、必要に応じてシステム構成に合わせて更新する必要があります。

. メンテナンスモードでは、いずれかのコントローラモジュールから、ローカルコントローラモジュールとシャーシの HA 状態を表示します。「 ha-config show 」
+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたシャーシのシステム状態がシステム構成と一致しない場合は、次の手順を実行します。
+
.. システムの既存の構成に基づいて、シャーシのHA状態を設定します。 `ha-config modify chassis _ha-state_`
+
hA-state には、次のいずれかの値を指定できます。

+
*** 「 HA 」
*** 「 non-ha 」


.. 設定が変更されたことを確認します。「 ha-config show 」


. システムの残りのケーブルをまだ再接続していない場合は、ケーブルを再接続します。
. メンテナンスモードを終了します。 `halt`。    LOADER プロンプトが表示されます。
. コントローラモジュールをブートします。




== 手順2：システムを起動します

. 電源ケーブルをPSUに接続し直します（まだ接続していない場合）。
. ロッカーのスイッチを*オン*に切り替えてPSUをオンにし、コントローラの電源が完全にオンになるまで待ちます。
. 電源投入後、シャーシとコントローラの前面と背面に障害LEDがないかどうかを確認します。
. SSHを使用してノードのSPまたはBMCのIPアドレスに接続します。このアドレスは、ノードのシャットダウンに使用するアドレスと同じです。
. の説明に従って、追加の健全性チェックを実行します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAPでスクリプトを使用してクラスタの健全性チェックを実行する方法"^]
. AutoSupportのメンテナンス時間がトリガーされた場合は、を使用して終了します `system node autosupport invoke -node * -type all -message MAINT=END` コマンドを実行します


[]
====

NOTE: ベストプラクティスとして、次のことを実行することを推奨します。

* いずれかを解決します https://activeiq.netapp.com/["Active IQ ウェルネスアラートとリスク"^] （Active IQ は電源投入後のAutoSupportの処理に時間がかかります。結果が遅れることが予想されます）
* を実行します https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]
* を使用してシステムヘルスを確認します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAPでスクリプトを使用してクラスタの健全性チェックを実行する方法"^]


====


== 手順 3 ：障害が発生したパーツをネットアップに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
