---
permalink: fas2800/chassis-replace-shutdown.html 
sidebar: sidebar 
keywords: fas2800, replace, chassis, shut down, controller, metrocluster, power, supply, ha, state, controller, configuration, switch, aggregates, replace, move, remove, swap 
summary: シャーシを交換するには、コントローラをシャットダウンする必要があります。 
---
= コントローラのシャットダウン- FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シャーシのメンテナンスを実施できるように、コントローラをシャットダウンします。

この手順は、2ノード構成のシステムが対象です。システムのノードが3つ以上の場合は、を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_perform_a_graceful_shutdown_and_power_up_of_one_HA_pair_in_a_4__node_cluster["4ノードクラスタで1つのHAペアの正常なシャットダウンと電源投入の実行方法"^]。

.作業を開始する前に
* すべてのクライアント/ホストからネットアップシステム上のデータへのアクセスを停止します。
* 外部バックアップジョブを一時停止します。
* 必要な権限とクレデンシャルがあることを確認します。
+
** ONTAP のローカル管理者のクレデンシャル。
** ストレージ暗号化またはNVE / NAEを使用する場合は、NetAppのオンボードキー管理（OKM）クラスタ全体のパスフレーズ。
** 各コントローラのBMCへのアクセス性。


* 交換に必要な工具と機器が揃っていることを確認します。
* シャットダウン前のベストプラクティスは次のとおりです。
+
** 追加を実行します https://kb.netapp.com/onprem/ontap/os/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["システムの健全性チェック"]。
** ONTAP をシステムの推奨リリースにアップグレードします。
** いずれかを解決します https://activeiq.netapp.com/["Active IQ ウェルネスアラートとリスク"]。システムコンポーネントのLEDなど、現在システムに発生している障害をメモします。




.手順
. SSHを使用してクラスタにログインするか、クラスタ内の任意のノードからローカルのコンソールケーブルとラップトップ/コンソールを使用してログインします。
. AutoSupportをオフにして、システムがオフラインになるまでの時間を指定します。
+
`system node autosupport invoke -node * -type all -message "MAINT=8h Power Maintenance"`

. すべてのノードのSP / BMCアドレスを特定します。
+
`system service-processor show -node * -fields address`

. クラスタシェルを終了します。 `exit`
. 前の手順の出力に表示されたいずれかのノードのIPアドレスを使用して、SSH経由でSP / BMCにログインします。
+
コンソール/ラップトップを使用している場合は、同じクラスタ管理者のクレデンシャルを使用してコントローラにログインします。

+

NOTE: 進捗状況を監視できるように、すべてのSP / BMC接続とのSSHセッションを開きます。

. 障害のあるシャーシにある2つのノードを停止します。
+
`system node halt -node <node1>,<node2> -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true`

+

NOTE: StrictSyncモードで動作するSnapMirror同期を使用するクラスタの場合： `system node halt -node <node1>,<node2>  -skip-lif-migration-before-shutdown true -ignore-quorum-warnings true -inhibit-takeover true -ignore-strict-sync-warnings true`

. 表示されたら、クラスタ内の各コントローラに「* y *」と入力します。 `_Warning: Are you sure you want to halt node "cluster <node-name> number"?
{y|n}:_`
. 各コントローラが停止するまで待ち、LOADERプロンプトを表示します。

