---
permalink: fas2800/controller-replace-overview.html 
sidebar: sidebar 
keywords: fas2800, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラモジュールの交換の概要- FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* すべてのドライブシェルフが適切に動作している必要があります。
* システムが HA ペアに含まれている場合、正常なコントローラが交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* この手順 には、システムの構成に応じて、 _replacement _ controller にドライブを自動的に再割り当てする手順、または手動で再割り当てする手順が含まれています。
+
手順の指示に従って、ドライブの再割り当てを実行する必要があります。

* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから _replacement _ controller にブートデバイスが移動され、古いコントローラモジュールと同じバージョンの ONTAP で _replacement _ controller がブートします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。



