---
permalink: fas2800/controller-replace-recable-reassign-disks.html 
sidebar: sidebar 
keywords: fas2820, how to recable the system, how to reassign disks 
summary: コントローラーの交換を完了し、FAS2820システムを完全な動作状態に戻すには、ストレージを再接続し、ディスクの再割り当てを確認し、NetAppストレージ暗号化の設定を復元し（必要な場合）、新しいコントローラーのライセンスをインストールする必要があります。 
---
= FAS2820 システムのコントローラーを返却して、通常業務を再開します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
交換手順を完了してFAS2820システムを完全な動作状態に戻すには、ストレージを再接続し、ディスクの再割り当てを確認し、NetApp Storage Encryption の設定を復元し（必要な場合）、新しいコントローラーのライセンスをインストールする必要があります。



[[step-1-recable-the-system]]
== 手順 1 ：システムにケーブルを再接続します

コントローラモジュールのストレージとネットワーク接続を確認するには、 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"] 。

.手順
. Config Advisor をダウンロードしてインストールします。
. ターゲットシステムの情報を入力し、データ収集をクリックします。
. Cabling タブをクリックし ' 出力を確認しますすべてのディスクシェルフが表示されていること、およびすべてのディスクが出力に表示されていることを確認し、ケーブル接続に関する問題が見つかった場合は修正します。
. 該当するタブをクリックして他のケーブル接続を確認し、 Config Advisor からの出力を確認します。




[[step-2-reassign-disks]]
== 手順 2 ：ディスクを再割り当てする

_replacement _controller をブートしたときにシステム ID の変更を確認し、その変更が実装されたことを確認する必要があります。

. _replacement _controller が Maintenance モード (`*>` プロンプトが表示されている ) の場合は 'Maintenance モードを終了して ' LOADER プロンプト :halt に進みます
. システム ID が一致していないためにシステム ID を上書きするかどうかを尋ねられた場合は 'boot_ontap `` を」と入力して ' コントローラをブートします
. _replacement _controller コンソールに Waiting for giveback... というメッセージが表示されるまで待ち、正常なコントローラから、新しいパートナーシステム ID が自動的に割り当てられていることを確認します。 storage failover show
+
コマンド出力には、障害のあるコントローラでシステム ID が変更されたことを示すメッセージが表示され、正しい古い ID と新しい ID が示されます。次の例では、 node2 の交換が実施され、新しいシステム ID として 151759706 が設定されています。

+
[listing]
----
node1> `storage failover show`
                                    Takeover
Node              Partner           Possible     State Description
------------      ------------      --------     -------------------------------------
node1             node2             false        System ID changed on partner (Old:
                                                  151759755, New: 151759706), In takeover
node2             node1             -            Waiting for giveback (HA mailboxes)
----
. 正常なコントローラから、コアダンプがすべて保存されたことを確認します。
+
.. advanced 権限レベルに切り替えます。「 set -privilege advanced 」
+
advanced モードで続行するかどうかを確認するプロンプトが表示されたら、「 y 」と入力します。advanced モードのプロンプトが表示されます（ * > ）。

.. コアダンプをすべて保存します。「 system node run -node _local-node-name_partner savecore 」
.. を待ちます `savecore` ギブバックを実行する前に完了するコマンド。
+
次のコマンドを入力すると、 savecore コマンドの進行状況を監視できます。 'system node run -node _local-node-name_partner savecore -s

.. admin 権限レベルに戻ります。「 set -privilege admin 」


. コントローラをギブバックします。
+
.. 正常なコントローラから、交換したコントローラのストレージをギブバックします。 storage failover giveback -ofnode replacement_node_name _`
+
_replacement _controller はストレージをテイクバックしてブートを完了します。

+
システム ID が一致しないためにシステム ID を上書きするかどうかを確認するメッセージが表示された場合は 'y' と入力する必要があります

+

IMPORTANT: ギブバックが拒否された場合は、拒否問題を解決します。拒否の解決が重要でない場合は、無視してかまいません。

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["使用しているバージョンの ONTAP 9 に対するハイアベイラビリティ構成のコンテンツを検索してください"]

.. ギブバックが完了したら、 HA ペアが正常で、テイクオーバーが可能であることを確認します。「 storage failover show
+
「 storage failover show 」コマンドの出力に、パートナーメッセージで変更されたシステム ID は含まれません。



. ディスクが正しく割り当てられたことを確認します。「 storage disk show -ownership
+
replacement _controller に属するディスクには、新しいシステム ID が表示されます。次の例では、 node1 で所有されているディスクに、新しいシステム ID 1873775277 が表示されています。

+
[listing]
----
node1> `storage disk show -ownership`

Disk  Aggregate Home  Owner  DR Home  Home ID    Owner ID  DR Home ID Reserver  Pool
----- ------    ----- ------ -------- -------    -------    -------  ---------  ---
1.0.0  aggr0_1  node1 node1  -        1873775277 1873775277  -       1873775277 Pool0
1.0.1  aggr0_1  node1 node1           1873775277 1873775277  -       1873775277 Pool0
.
.
.
----

