---
permalink: fas2800/pci-cards-and-risers-replace.html 
sidebar: sidebar 
keywords: fas2800, fas2800, replace, pcie, mezzanine, card, disconnect, cable, sfp, qsfp, module, fail, mezzanine, shut, down, impair, controller, pcie, switch, aggregate, two-node, metrocluster, complete, replacement, process, replace a pcie or mezzanine card, shut down the impaired controller, remove the controller module, replace a pcie card, replace the mezzanine card, install the controller module, switch back aggregates in a two-node metrocluster configuration, restore the controller module to operation, complete the replacement process 
summary: PCIe カードまたはメザニンカードを交換するには、ケーブルとすべての SFP モジュールと QSFP モジュールをカードから外し、障害が発生した PCIe カードまたはメザニンカードを交換してから、カードにケーブルを再接続する必要があります。 
---
= メザニンカードを交換してください- FAS2800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
メザニンカードを交換するには、カードからケーブルとSFPモジュールとQSFPモジュールを取り外し、障害が発生したメザニンカードを交換してから、カードにケーブルを再接続します。

* この手順は、システムでサポートされるすべてのバージョンの ONTAP で使用できます
* システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。


.アニメーション-メザニンカードを交換します
video::a8ec891d-f6f6-4479-9ca2-af47017254ff[panopto]


== 手順 1 ：障害のあるコントローラをシャットダウンします

障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。

.手順
. AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT=_Number_OF_hours_down_h
+
次の AutoSupport メッセージは、ケースの自動作成を 2 時間停止します。 cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`

. 障害のあるコントローラが HA ペアの一部である場合は、正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify -node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
コントローラモジュールの取り外しに進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し、「 y 」と入力します。



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。「 storage failover takeover -ofnode impaired_node_name _

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===




== 手順 2 ：コントローラモジュールを取り外す

コントローラモジュールをシステムから取り外し、コントローラモジュールのカバーを取り外します。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. ケーブルマネジメントデバイスに接続しているケーブルをまとめているフックとループストラップを緩め、システムケーブルと SFP をコントローラモジュールから外し（必要な場合）、どのケーブルが何に接続されていたかを記録します。
+
ケーブルはケーブルマネジメントデバイスに収めたままにします。これにより、ケーブルマネジメントデバイスを取り付け直すときに、ケーブルを整理する必要がありません。

. ケーブルマネジメントデバイスをコントローラモジュールの右側と左側から取り外し、脇に置きます。
. カムハンドルのラッチをつかんで解除し、カムハンドルを最大限に開いてコントローラモジュールをミッドプレーンから離し、両手でコントローラモジュールをシャーシから外します。
+
image::../media/drw_2850_pcm_remove_install_IEOPS-694.svg[DRW 2850 PCM取り外し取り付けIEOPS 694]

. コントローラモジュールを裏返し、平らで安定した場所に置きます。
. コントローラモジュールの側面にある青いボタンを押してカバーを開き、カバーを上に回してコントローラモジュールから取り外します。
+
image::../media/drw_2850_open_controller_module_cover_IEOPS-695.svg[DRW 2850オープンコントローラモジュールはIEOPS 695をカバーしています]



[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
コントローラモジュールカバーのリリースボタン

|===


== 手順3：メザニンカードを交換します

メザニンカードを交換してください。

. 接地対策がまだの場合は、自身で適切に実施します。
. 次の図またはコントローラモジュールのFRUマップを使用して、メザニンカードを取り外します。
+
image::../media/drw_2850_replace_HIC_IEOPS-700.svg[DRW 2850はHIC IEOPS 700の代わりに使用します]

+
[cols="1,3"]
|===


 a| 
image::../media/legend_icon_01.svg[凡例アイコン 01]
 a| 
ライザーベゼル



 a| 
image::../media/legend_icon_02.svg[凡例アイコン 02]
 a| 
PCIeメザニンカード

|===
+
.. メザニンカードベゼルをコントローラモジュールからまっすぐ引き出して取り外します。
.. メザニンカードの取り付けネジを緩め、メザニンカードを真上に持ち上げます。
+

NOTE: つまみネジは、指またはドライバで緩めることができます。指を使用する場合は、NVバッテリの横にある取り付けネジで指で購入しやすくするために、NVバッテリを上に回転させなければならない場合があります。



. メザニンカードを再度取り付けます。
+
.. 交換用メザニンカードプラグのソケットをマザーボードのソケットに合わせ、カードをソケットに対して垂直にそっと装着します。
.. メザニンカードの3本の取り付けネジを締めます。
.. メザニンベゼルを再度取り付けます。


. コントローラモジュールのカバーを再度取り付け、所定の位置にロックします。




== 手順 4 ：コントローラモジュールを取り付ける

コントローラモジュールを再度取り付けます。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. コントローラモジュールのカバーをまだ取り付けていない場合は取り付けます。
. コントローラモジュールを裏返し、シャーシの開口部に端を合わせます。
. コントローラモジュールをシステムの途中までそっと押し込みます。コントローラモジュールの端をシャーシの開口部に合わせ、コントローラモジュールをシステムの途中までそっと押し込みます。
+

NOTE: 指示があるまでコントローラモジュールをシャーシに完全に挿入しないでください。

. 必要に応じてシステムにケーブルを再接続します。
+
光ファイバケーブルを使用する場合は、メディアコンバータ（ QSFP または SFP ）を取り付け直してください（取り外した場合）。

. コントローラモジュールの再取り付けを完了します。
+
.. カムハンドルを開き、コントローラモジュールをミッドプレーンまでしっかりと押し込んで完全に装着し、カムハンドルをロック位置まで閉じます。
+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをスライドしてシャーシに挿入する際に力を入れすぎないでください。

+
コントローラは、シャーシに装着されるとすぐにブートを開始します。

.. ケーブルマネジメントデバイスをまだ取り付けていない場合は、取り付け直します。
.. ケーブルマネジメントデバイスに接続されているケーブルをフックとループストラップでまとめます。


. ストレージをギブバックして、コントローラを通常の動作に戻します。 storage failover giveback -ofnode impaired_node_name _`
. を使用して自動ギブバックをリストアします `storage failover modify -node local -auto-giveback true` コマンドを実行します
. AutoSupportのメンテナンス時間がトリガーされた場合は、を使用して終了します `system node autosupport invoke -node * -type all -message MAINT=END` コマンドを実行します




== 手順 5 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
