---
permalink: fas2800/power-supply-swap-out.html 
sidebar: sidebar 
keywords: fas2800, swap, power, supply, turn off, disconnect, remove, install, connect, turn on, replacement 
summary: 電源装置を交換するには、障害のある電源装置の電源を切り、接続を解除してから取り外し、交換用電源装置を取り付けて接続し、電源をオンにします。 
---
= 電源装置の交換- FAS2820
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
電源装置を交換するには、障害のある電源装置の電源を切り、接続を解除してから取り外し、交換用電源装置を取り付けて接続し、電源をオンにします。

システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。

* 電源装置は冗長で、ホットスワップに対応しています。
* この手順は、一度に 1 台の電源装置を交換するために作成されたものです。
+

NOTE: シャーシから電源装置を取り外してから 2 分以内に電源装置を交換することを推奨します。システムは引き続き動作しますが、電源装置が交換されるまでは、デグレード状態の電源装置に関するメッセージが ONTAP からコンソールに送信されます。

* 電源装置では自動で電圧が調整されます。


.アニメーション-電源装置を交換します
video::0631b48a-ad6f-4433-a2bd-af54014778c2[panopto]
.手順
. コンソールのエラーメッセージまたは電源装置の LED から、交換する電源装置を特定します。
. 接地対策がまだの場合は、自身で適切に実施します。
. 電源装置をオフにし、電源ケーブルを外します。
+
.. 電源装置の電源スイッチをオフにします。
.. 電源ケーブルの固定クリップを開き、電源装置から電源ケーブルを抜きます。
.. 電源から電源ケーブルを抜きます。


. 電源装置のカムハンドルのラッチを押し、カムハンドルを最大まで開いて電源装置をミッドプレーンから外します。
+
image::../media/drw_2850_replace_PSU_IEOPS-702.svg[PSUの交換]

. カムハンドルをつかみ、電源装置をスライドしてシステムから引き出します。
+

CAUTION: 電源装置を取り外すときは、重量があるので必ず両手で支えながら作業してください。

. 新しい電源装置のオン / オフスイッチがオフになっていることを確認します。
. 両手で支えながら電源装置の端をシステムシャーシの開口部に合わせ、カムハンドルを使用して電源装置をシャーシにそっと押し込みます。
+
電源装置にはキーが付いており、一方向のみ取り付けることができます。

+

NOTE: 電源装置をスライドさせてシステムに挿入する際に力を入れすぎないようにしてください。コネクタが破損する可能性があります。

. カムハンドルを閉じます。ラッチがカチッという音を立ててロックされ、電源装置が完全に収まります。
. 電源装置のケーブルを再接続します。
+
.. 電源装置と電源に電源ケーブルを再接続します。
.. 電源ケーブルの固定クリップを使用して電源ケーブルを電源装置に固定します。


+
電源装置への電力供給が復旧すると、ステータス LED が緑色に点灯します。

. 新しい電源装置の電源をオンにし、電源装置のアクティビティ LED を確認します。
+
電源装置がオンラインになると、電源装置の LED が点灯します。

. 障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"^]詳細については、ページを参照してください。

