---
permalink: asa250/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a250, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラーを交換するための要件 - ASA A250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A250ストレージ システムのコントローラーを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラがあることを確認すること、コントローラのコンソール出力をテキスト ログ ファイルに保存することが含まれます。

交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

* すべてのドライブシェルフが適切に動作している必要があります。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから _replacement _ controller にブートデバイスが移動され、古いコントローラモジュールと同じバージョンの ONTAP で _replacement _ controller がブートします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。


* コントローラのコンソール出力を必ずテキストファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。



.次の手順
故障したコントローラーを交換するための要件を確認した後、link:controller-replace-shutdown.html["障害のあるコントローラをシャットダウン"]。
