---
permalink: c30-60/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff c30, aff c60, replace the chassis 
summary: 障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシに交換します。 
---
= シャーシの交換要件- AFF C30およびAFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C30またはAFF C60システムのシャーシを交換する前に、交換を成功させるために必要な要件を満たしていることを確認してください。具体的には、システムの他のすべてのコンポーネントが正常に動作していること、正しい交換用シャーシがあること、および必要な工具が揃っていることを確認します。

シャーシを交換する前に、次の要件と考慮事項を確認してください。



== 要件

* 交換用シャーシは、障害のあるシャーシと同じモデルである必要があります。この手順は、アップグレードではなく、同等の交換を目的としています。
* ストレージシステムの他のすべてのコンポーネントが正常に動作している必要があります。正常に動作していない場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]。




== 考慮事項

* *シャーシの交換手順はシステムの停止を伴います。*2 ノードクラスタではサービスが完全に停止し、マルチノードクラスタでは部分的に停止します。
* シャーシの交換手順は、ストレージシステムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、ドライブ、ドライブブランク、およびコントローラを新しいシャーシに移動することを前提としています。
* 影響を受けるストレージシステムの物理的な位置を特定するために、必要に応じてストレージシステムのロケーション（青色の）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
ストレージシステムにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。



.次の手順
シャーシの交換要件を確認したら、次の作業を行う必要があります。link:chassis-replace-shutdown.html["コントローラをシャットダウン"]
