---
permalink: c30-60/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: aff c30, aff c60, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: コントローラのHA構成がアクティブで、AFF C30またはAFF C60ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。 
---
= システム構成のリストアと検証（AFF C30 and AFF C60）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのHA構成がアクティブで、AFF C30またはAFF C60ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。



== 手順1：HA構成を確認する

コントローラの状態を確認し、必要に応じてストレージシステム構成に合わせて更新する必要があります `HA`。

. メンテナンスモードでブートします。
+
`boot_ontap maint`

+
.. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。



. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。
. すべてのコンポーネントが同じ状態になっていることを確認し `HA`ます。
+
`ha-config show`

+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたコントローラのシステム状態がストレージシステム構成と一致しない場合は、コントローラの状態を設定し `HA`ます。
+
`ha-config modify controller ha-state`

+
hA-state には、次のいずれかの値を指定できます。

+
** 「 HA 」
** `non-ha` （サポートされていません）


. 設定が変更されたことを確認します。
+
`ha-config show`





== 手順2：ディスクリストを確認する

. アダプタにすべてのディスクへのパスがリストされていることを確認します。
+
`storage show disk -p`

+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. メンテナンスモードを終了します。
+
`halt`



.次の手順
AFF C30またはAFF C60システムのシステム構成をリストアして確認したら、を実行する必要がありますlink:controller-replace-recable-reassign-disks.html["コントローラをギブバック"]。
