---
sidebar: sidebar 
permalink: c30-60/install-requirements.html 
keywords: aff c30, aff c60, install, setup, cautions 
summary: 必要な機器と、プラットフォームとシェルフの持ち上げに関する注意事項を確認します。 
---
= インストール要件- AFF C30およびAFF C60
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C30またはAFF C60ストレージシステムの要件を確認します。



== 設置に必要な機器

ストレージシステムを設置するには、次の機器および工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* No.2 プラスドライバ




== 吊り上げ時の注意事項

ストレージシステムやシェルフは重い。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== ストレージシステムノオモミ

ストレージシステムを移動または持ち上げるときは、必要な予防措置を講じてください。

ストレージシステムの重量は最大27.9 kg（61.5ポンド）です。ストレージ・システムを持ち上げるには、2人で作業するか、油圧リフトを使用します。

image::../media/drw_g_lifting_weight_ieops-1831.svg[AFF A20 A30 A50およびC30およびC60重量警告アイコン]



=== シェルフの重量

シェルフを移動または持ち上げるときは、必要な予防措置を講じてください。

NSM100Bモジュールを搭載したNS224シェルフの重量は最大25.8kg（56.8ポンド）です。シェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。シェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）をシェルフに保管してください。

image::../media/drw_ns224_nsm100b_lifting_weight_ieops-1832.svg[NSM100bを搭載したNS224の持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]


.次の手順
ストレージシステムのインストール要件と考慮事項を確認したら、を実行しlink:install-prepare.html["設置の準備"]ます。
