---
permalink: c30-60/overview.html 
sidebar: sidebar 
keywords: AFF C30 C60 specifications, AFF C30 C60 specs, AFF C30 C60 capacity, AFF C30 C60 memory, AFF C30 C60 IO, AFF C30 C60 compliance 
summary: 単一の高可用性ペアにおける AFF C30 および AFF C60 ストレージシステムの主な仕様 
---
= AFF C30およびAFF C60の主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
これらは、AFF C30 および AFF C60 ストレージシステムを単一の高可用性ペアで構成した場合の主な仕様です。これらのストレージシステムの完全な仕様については、 https://hwu.netapp.com["NetApp Hardware Universe の略"^]をご覧ください。



[[aff-c60]]
== AFF C60用



[[key-specifications-for-aff-c60]]
=== AFF C60の主な仕様

プラットフォーム構成: AFF C60 シングルシャーシ HA ペア

最大生容量: 7.3680 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

PCIe拡張スロット: 8

最小ONTAPバージョン: ONTAP 9.16.1RC1



[[scaleout-maximums]]
=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 4 | 29.5 PB / 26.2 PiB | 512 GB 


| SAN | 4 | 29.5 PB / 26.2 PiB | 512 GB 


| HAペア |  | 7.4 PB / 6.5 PiB | 128.0000 
|===


[[io]]
=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 16 


| イーサネット 25 Gbps | 24 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


[[storage-networking-supported]]
=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



[[system-environment-specifications]]
=== システム環境仕様

* 標準電力: 2892 BTU/時
* 最悪の場合の電力: 4445 BTU/時
* 重量: 60.7ポンド (27.5 kg)
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 標高3048m（10000フィート）まで10°C～35°C（50°F～95°F）、相対湿度8%～80%、結露なし
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで、相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響騒音：表示音響出力（LwAd）：8.0；音圧（LpAm）（傍観者位置）：70.5 dB




[[compliance]]
=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




[[high-availability]]
=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ可能なコントローラ、冗長ホットスワップ可能な電源装置。



[[aff-c30]]
== AFF C30用



[[key-specifications-for-aff-c30]]
=== AFF C30の主な仕様

プラットフォーム構成: AFF C30 シングルシャーシ HA ペア

最大生容量: 2.2104 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

PCIe拡張スロット: 8

最小ONTAPバージョン: ONTAP 9.16.1RC1



[[scaleout-maximums]]
=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 4 | 8.8 PB / 7.9 PiB | 512 GB 


| SAN | 4 | 8.8 PB / 7.9 PiB | 512 GB 


| HAペア |  | 2.2 PB / 2.0 PiB | 128.0000 
|===


[[io]]
=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 16 


| イーサネット 25 Gbps | 24 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


[[storage-networking-supported]]
=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



[[system-environment-specifications]]
=== システム環境仕様

* 標準電力: 2892 BTU/時
* 最悪の場合の電力: 4445 BTU/時
* 重量: 60.7ポンド (27.5 kg)
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 標高3048m（10000フィート）まで10°C～35°C（50°F～95°F）、相対湿度8%～80%、結露なし
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで、相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響騒音：表示音響出力（LwAd）：8.0；音圧（LpAm）（傍観者位置）：70.5 dB




[[compliance]]
=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




[[high-availability]]
=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ可能なコントローラ、冗長ホットスワップ可能な電源装置。
