---
permalink: a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the boot media 
summary: AFF A20、 AFF A30、およびAFF A50 ストレージ システムのブート メディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、正しい交換用ブート メディアがあることを確認すること、障害のあるコントローラの e0S（e0M レンチ）ポートが正常に動作していることを確認すること、およびオンボード キー マネージャ（OKM）または外部キー マネージャ（EKM）が有効になっているかどうかを確認することが含まれます。 
---
= 自動ブートメディアリカバリの要件 - AFF A20、 AFF A30、およびAFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20、 AFF A30、およびAFF A50ストレージシステムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、正しい交換用ブートメディアがあること、障害が発生したコントローラのe0S（e0Mレンチ）ポートが正常に動作していることを確認すること、およびオンボードキーマネージャ（OKM）または外部キーマネージャ（EKM）が有効になっているかどうかを確認することが含まれます。

自動ブートメディアリカバリプロセスは、 ONTAP 9.17.1以降でのみサポートされています。ストレージシステムで以前のバージョンのONTAPを実行している場合は、 link:bootmedia-replace-workflow.html["手動ブート回復手順"] 。

次の要件を確認します。

* 障害が発生したコンポーネントは、NetAppから受け取ったものと同じ容量の交換用FRUコンポーネントと交換する必要があります。
* 障害のあるコントローラーの e0M (レンチ) ポートが接続されており、障害がないことを確認します。
+
e0M ポートは、自動ブート回復プロセス中に 2 つのコントローラー間で通信するために使用されます。

* OKMを使用するには、OKMパスフレーズファイルの内容が必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。


* 障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。
+
** _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
** _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。




.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["コントローラをシャットダウン"]
