---
permalink: a20-30-50/bootmedia-recovery-image-boot.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, boot the recovery image 
summary: ONTAP イメージを USB ドライブからブートし、ファイルシステムをリストアして、環境変数を確認する必要があります。 
---
= リカバリイメージのブート（AFF A20、AFF A30、およびAFF A50）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20、AFF A30、またはAFF A50システムに新しいブートメディアデバイスを取り付けたら、リカバリイメージをUSBドライブからブートし、パートナーノードから設定をリストアできます。

.手順
. LOADER プロンプトから、 USB フラッシュドライブ「 boot_recovery 」からリカバリ・イメージをブートします
+
イメージが USB フラッシュドライブからダウンロードされます。

. プロンプトが表示されたら、イメージの名前を入力するか、画面に表示されたデフォルトのイメージをそのまま使用します。
. var ファイルシステムを復元します。
+
[role="tabbed-block"]
====
.オプション1：ONTAP 9 16.0以前
--
.. 障害のあるコントローラで、 `Y` `Do you want to restore the backup configuration now?`
.. 障害コントローラでプロンプトが表示されたら、キーを押し `Y`て_/etc/ssh/ssh_host_ECDSA_KEY_を上書きします。
.. 正常なパートナーコントローラで、障害コントローラをadvanced権限レベルに設定します。 `set -privilege advanced`
.. 正常なパートナーコントローラで、restore backupコマンドを実行します `system node restore-backup -node local -target-address impaired_node_IP_address`。
+
*注：*リストアが正常に完了した以外のメッセージが表示された場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

.. 正常なパートナーコントローラで、障害のあるコントローラをadminレベルに戻します `set -privilege admin`。
.. 障害のあるコントローラで、というメッセージが表示されたら `Was the restore backup procedure successful?`キーを押し `Y`ます。
.. 障害のあるコントローラで、というメッセージが表示されたら `...would you like to use this restored copy now?`キーを押し `Y`ます。
.. 障害コントローラのリブートを求めるプロンプトが表示されたらと入力し、を押し `Y`てブートメニューを表示します。 `ctrl-c`
.. システムが暗号化を使用していない場合は、_option 1 Normal Bootを選択します。暗号化を使用していない場合は、に進みます。link:bootmedia-encryption-restore.html["アンコウカノ"]


--
.オプション2：ONTAP 9 16.1以降
--
.. 障害のあるコントローラで、バックアップ構成をリストアするかどうかを確認するメッセージが表示されたらと入力し `Y`ます。
+
リストア手順が正常に完了すると、コンソールにこのメッセージが表示されます `syncflash_partner: Restore from partner complete`。

.. 障害コントローラで、リストアバックアップが成功したかどうかを確認するプロンプトが表示されたらと入力し `Y`ます。
.. 障害コントローラで、リストアした構成を使用するかどうかを確認するメッセージが表示されたらと入力し `Y`ます。
.. 障害コントローラで、ノードのリブートを求めるプロンプトが表示されたらと入力し `Y`ます。
.. 障害コントローラのリブートを求めるプロンプトが表示されたらと入力し、を押し `Y`てブートメニューを表示します。 `ctrl-c`
.. システムが暗号化を使用していない場合は、_option 1 Normal Bootを選択します。暗号化を使用していない場合は、に進みます。link:bootmedia-encryption-restore.html["アンコウカノ"]


--
====


. パートナーコントローラにコンソールケーブルを接続します。
. storage failover giveback -fromnode local コマンドを使用して、コントローラをギブバックします。
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。
. AutoSupportが有効になっている場合は、コマンドを使用してケースの自動作成をリストアまたは抑制解除し `system node autosupport invoke -node * -type all -message MAINT=END` ます。
+
*注意：*プロセスが失敗した場合は、に連絡してください https://support.netapp.com["ネットアップサポート"]。



.次の手順
リカバリイメージを起動したら、を実行する必要がありlink:bootmedia-encryption-restore.html["ブートメディアで暗号化をリストアする"]ます。
