---
permalink: a20-30-50/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: aff a20, aff a30, aff a50, replace the chassis 
summary: 障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシに交換します。 
---
= 要件と考慮事項- AFF A20、AFF A30、およびAFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
シャーシを交換する前に、次の要件と考慮事項を確認してください。



== 要件

* 交換用シャーシは、障害のあるシャーシと同じモデルである必要があります。この手順は、アップグレードではなく、同等の交換を目的としています。
* ストレージシステムの他のすべてのコンポーネントが正常に動作している必要があります。正常に動作していない場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]。




== 考慮事項

* *シャーシの交換手順はシステムの停止を伴います。*2 ノードクラスタではサービスが完全に停止し、マルチノードクラスタでは部分的に停止します。
* シャーシの交換手順は、ストレージシステムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、ドライブ、ドライブブランク、およびコントローラを新しいシャーシに移動することを前提としています。
* 影響を受けるストレージシステムの物理的な位置を特定するために、必要に応じてストレージシステムのロケーション（青色の）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
ストレージシステムにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。


