---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: aff a20, aff a30, and aff a50, replace io module, add io module, hotswap io module 
summary: AFF A20、 AFF A30、およびAFF A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードする場合や、故障したモジュールに対処する場合、I/Oモジュールの追加、ホットスワップ、または交換は不可欠です。 
---
= I/Oモジュールのメンテナンスの概要 - AFF A20、 AFF A30、およびAFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20、 AFF A30、およびAFF A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードする場合や、故障したモジュールに対処する場合、I/Oモジュールの追加、ホットスワップ、または交換は不可欠です。

* link:io-module-add.html["I/Oモジュールの追加"]
+
I/Oモジュールを追加することで冗長性を高め、1つのI/Oモジュールに障害が発生してもストレージシステムの運用を継続できます。I/Oモジュールは、スロットに空きがある場合、またはすべてのスロットがいっぱいになっている場合に追加できます。

* link:io-module-hotswap.html["I/O モジュールのホット スワップ"]
+
特定のI/Oモジュールを同等のI/Oモジュールとホット スワップすることで、ストレージシステムを最適な動作状態に復元できます。ホット スワップは、手動でテイクオーバーを実行することなく実行できます。

+
この手順を使用するには、ストレージ システムでONTAP 9.17.1以降が実行されており、システムで実行されているONTAPのバージョンの特定の要件を満たしている必要があります。

* link:io-module-replace.html["I/Oモジュールの交換"]
+
故障したI/Oモジュールを交換することで、ストレージシステムを最適な動作状態に復元できます。この手順では、故障したI/Oモジュールを搭載したコントローラを手動でテイクオーバーする必要があります。


