---
permalink: a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: AFF A20, AFF A30, and AFF A50, replace io module, add io module, hotswap io module 
summary: AFF A20、 AFF A30、およびAFF A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードする場合や、故障したモジュールに対処する場合、I/Oモジュールの追加、ホットスワップ、または交換は不可欠です。 
---
= I/Oモジュールの追加、ホットスワップ、交換の概要 - AFF A20、 AFF A30、 AFF A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A20、 AFF A30、およびAFF A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードする場合や、故障したモジュールに対処する場合、I/Oモジュールの追加、ホットスワップ、または交換は不可欠です。

ストレージシステム内の故障したI/Oモジュールは、同じタイプのI/Oモジュール、または異なるタイプのI/Oモジュールと交換できます。ストレージシステムが特定の要件を満たしている場合は、クラスタとHA I/Oモジュールをホットスワップできます。また、空きスロットがあるストレージシステムにI/Oモジュールを追加することもできます。

* link:io-module-add.html["I/Oモジュールの追加"]
+
I/Oモジュールを追加すると、冗長性が向上し、1つのI/Oモジュールに障害が発生してもストレージシステムが動作し続けるようになります。

* link:io-module-hotswap-ha-slot4.html["クラスタとHA I/Oモジュールのホットスワップ"]
+
障害が発生したクラスタとHA I/Oモジュールをホットスワップすることで、ストレージシステムを最適な動作状態に復元できます。ホットスワップは、障害が発生したコントローラを手動で引き継ぐことなく実行できます。

+
この手順を使用するには、ストレージ システムでONTAP 9.17.1 以降が実行されており、特定のストレージ システム要件を満たしている必要があります。

* link:io-module-replace.html["I/Oモジュールの交換"]
+
障害が発生したI/Oモジュールを交換すると、ストレージシステムを最適な動作状態に戻すことができます。


