---
permalink: a20-30-50/overview.html 
sidebar: sidebar 
summary: A20-30-50プラットフォームグループの主な仕様 
---
= A20-30-50プラットフォームグループの主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下は、A20-30-50 プラットフォーム グループの選択仕様です。訪問 https://hwu.netapp.com["NetApp Hardware Universe の略"^]仕様の完全なリストについては、(HWU) をご覧ください。このページは、単一の高可用性ペアを反映しています。



== AFF A50用



=== AFF A50の主な仕様

プラットフォーム構成: AFF A50 シングルシャーシ HA ペア

最大生容量: 4.0392 PB

メモリ: 256.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 8

最小ONTAPバージョン: ONTAP 9.16.1RC1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 12 | 48.5 PB / 43.0 PiB | 3072 GB 


| SAN | 6 | 24.2 PB / 21.5 PiB | 1536 GB 


| HAペア |  | 4.0 PB / 3.6 PiB | 256.0000 
|===


=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 16 


| イーサネット 25 Gbps | 24 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS 12Gbps | 16 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 3076 BTU/時
* 最悪の場合の電力: 4860 BTU/時
* 重量: 60.7ポンド/27.5kg
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 10°C ～ 35°C (50°F ～ 95°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 80% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響ノイズ：表示音響出力（LwAd）：8.0；br／音圧（LpAm）（傍観者位置）：70.5 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、外部シェルフの SAS 接続を介した SAS インバンド管理。



== AFF A20用



=== AFF A20の主な仕様

プラットフォーム構成: AFF A20 シングルシャーシ HA ペア

最大生容量: 4.0392 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 8

最小ONTAPバージョン: ONTAP 9.16.1RC1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 3. | 12.1 PB / 10.8 PiB | 384 GB 


| SAN | 3. | 12.1 PB / 10.8 PiB | 384 GB 


| HAペア |  | 4.0 PB / 3.6 PiB | 128.0000 
|===


=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 12 


| イーサネット 25 Gbps | 32 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS 12Gbps | 16 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 2489 BTU/時
* 最悪の場合の電力: 3890 BTU/時
* 重量: 60.7ポンド/27.5kg
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 10°C ～ 35°C (50°F ～ 95°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 80% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響ノイズ：表示音響出力（LwAd）：8.0；br／音圧（LpAm）（傍観者位置）：70.5 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、外部シェルフの SAS 接続を介した SAS インバンド管理。



== AFF A30用



=== AFF A30の主な仕様

プラットフォーム構成: AFF A30 シングルシャーシ HA ペア

最大生容量: 4.0392 PB

メモリ: 128.0000 GB

フォームファクター: 2Uシャーシ、2つのHAコントローラと24のドライブスロット

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 8

最小ONTAPバージョン: ONTAP 9.16.1RC1



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 4 | 16.2 PB / 14.3 PiB | 512 GB 


| SAN | 4 | 16.2 PB / 14.3 PiB | 512 GB 


| HAペア |  | 4.0 PB / 3.6 PiB | 128.0000 
|===


=== IO



==== オンボードIO

オンボード IO データがありません。



==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 16 


| イーサネット 25 Gbps | 24 


| イーサネット 10 Gbps | 24 


| FC 64 Gbps | 24 


| NVMe/FC 64 Gbps | 24 


|  | 0 


| SAS 12Gbps | 16 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 2. 


| RS-232 115 Kbps | 4 


| USB 600 Mbps | 2. 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 2892 BTU/時
* 最悪の場合の電力: 4445 BTU/時
* 重量: 60.7ポンド/27.5kg
* 高さ: 2U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 深さ：
* 動作温度/高度/湿度: 10°C ～ 35°C (50°F ～ 95°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 80% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響ノイズ：表示音響出力（LwAd）：8.0；br／音圧（LpAm）（傍観者位置）：70.5 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55032、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 15598-1、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ対応コントローラ、冗長ホットスワップ対応電源、外部シェルフの SAS 接続を介した SAS インバンド管理。
