---
permalink: c250/controller-replace-requirements.html 
sidebar: sidebar 
keywords: aff c250, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= AFF C250ストレージシステムのコントローラーを交換する前に要件を確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C250ストレージ システムのコントローラーを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラがあることを確認すること、コントローラのコンソール出力をテキスト ログ ファイルに保存することが含まれます。

交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* すべてのドライブシェルフが適切に動作している必要があります。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順 では、障害のあるコントローラから _replacement _ controller にブートデバイスが移動され、古いコントローラモジュールと同じバージョンの ONTAP で _replacement _ controller がブートします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。




.次の手順
故障したコントローラーを交換するための要件を確認した後、link:controller-replace-shutdown.html["障害のあるコントローラをシャットダウン"]。
