---
permalink: asa-r2-a1k/bootmedia-replace-bmr.html 
sidebar: sidebar 
keywords: asa r2 a1k, replace the boot media 
summary: ブートメディアを交換する前に、コントローラモジュールのライザー 3 を取り外して障害が発生したブートメディアの場所を確認する必要があります。 
---
= ブートメディアの交換- ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブートメディアを交換するには、システムの背面からシステム管理モジュールを取り外し、障害のあるブートメディアを取り外し、交換用ブートメディアをシステム管理モジュールに取り付ける必要があります。

.手順
ブートメディアはシステム管理モジュールの内部にあり、モジュールをシステムから取り外すとアクセスできます。

image::../media/drw_a1k_boot_media_remove_replace_ieops-1377.svg[ブートメディアの交換の図]

[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[番号1]
 a| 
システム管理モジュールのカムラッチ



 a| 
image::../media/legend_icon_02.svg[番号2]
 a| 
ブートメディアロックボタン



 a| 
image::../media/legend_icon_03.svg[番号3]
 a| 
ブートメディア

|===
. 接地対策がまだの場合は、自身で適切に実施します。
. コントローラからPSUから電源装置ケーブルを抜きます。
+

NOTE: ストレージシステムにDC電源装置が搭載されている場合は、電源装置（PSU）から電源ケーブルブロックを外します。

+
.. システム管理モジュールに接続されているケーブルをすべて取り外します。モジュールを再度取り付けるときに正しいポートにケーブルを接続できるように、ケーブルの接続先にラベルを付けておいてください。
.. ケーブルマネジメントトレイ内部の両側にあるボタンを引いてケーブルマネジメントトレイを下に回転させ、トレイを下に回転させます。
.. システム管理カムボタンを押します。
.. カムラッチをできるだけ下に回転させます。
.. カムレバーの開口部に指をはさみ、モジュールをエンクロージャから引き出して、システム管理モジュールをエンクロージャから取り外します。
.. システム管理モジュールを静電気防止用マットの上に置き、ブートメディアにアクセスできるようにします。


. 管理モジュールからブートメディアを取り外します。
+
.. 青色のロックボタンを押します。
.. ブートメディアを上に回転させ、ソケットから引き出して脇に置きます。


. 交換用ブートメディアをシステム管理モジュールに取り付けます。
+
.. ブートメディアの端をソケットケースに合わせ、ソケットに対して垂直にゆっくりと押し込みます。
.. ブートメディアをロックボタンの方に回転させます。
.. 固定ボタンを押し、ブートメディアを最後まで回転させて固定ボタンを放します。


. システム管理モジュールを取り付け直します。
+
.. モジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. ケーブルマネジメントトレイを上に回転させて閉じます。
+
.. システム管理モジュールにケーブルを再接続します。



