---
permalink: asa-r2-a1k/controller-replace-move-hardware.html 
sidebar: sidebar 
keywords: asa r2 a1k, move the controller module hardware 
summary: コントローラモジュールを交換するには、障害のあるコントローラを取り外し、 FRU コンポーネントを交換用コントローラモジュールに移動し、交換用コントローラモジュールをシャーシに取り付けてから、システムをメンテナンスモードでブートする必要があります。 
---
= コントローラモジュールハードウェアを交換- ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラを交換するには、障害のあるコントローラを取り外し、FRUコンポーネントを交換用コントローラモジュールに移動し、交換用コントローラモジュールをエンクロージャに取り付けてから、システムをメンテナンスモードでブートする必要があります。



== 手順 1 ：コントローラモジュールを取り外す

コントローラモジュールを交換する場合、またはコントローラモジュール内部のコンポーネントを交換する場合は、コントローラモジュールをエンクロージャから取り外す必要があります。

. システムのスロット4/5にあるNVRAMステータスLEDを確認します。コントローラモジュールの前面パネルにもNVRAM LEDがあります。NVアイコンを探します。
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[NVRAMの警告/ステータスLEDの場所の図]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
 a| 
NVRAMステータスLED



 a| 
image:../media/legend_icon_02.svg["番号1、幅= 30px"]
 a| 
NVRAM警告LED

|===
+

NOTE: NVRAMステータスLEDが点滅している場合は、コントローラモジュールがテイクオーバーされていないか適切に停止されていない（データがコミットされていない）可能性があります。障害のあるコントローラモジュールがパートナーコントローラモジュールに正常にテイクオーバーされなかった場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"] 。

+
障害のあるコントローラモジュールのNVRAMステータスLEDの一般的な動作は次のとおりです。

+
** コントローラモジュールの電源をオフにしてコントローラモジュールが「waiting for giveback」状態になるか、コントローラモジュールがテイクオーバーされていないか適切に停止されていない（データがコミットされていない）と、NVRAMステータスLEDが点滅します。
** コントローラモジュールをエンクロージャから取り外すとNVRAMステータスLEDが点滅します。コントローラモジュールがテイクオーバーされていないか、適切に停止されていない（データがコミットされていない）可能性があります。パートナーコントローラモジュールまたは障害のあるコントローラモジュールによってコントローラモジュールが正常にテイクオーバーされたことを確認します `waiting for giveback`。その後、点滅しているLEDは無視してかまいません（コントローラをエンクロージャから取り外すこともできます）。


. 接地対策がまだの場合は、自身で適切に実施します。
. ユニットの前面で、ロックカムの穴に指をかけ、カムレバーのタブを軽く押しながら、両方のラッチを同時に手前にしっかりと回転させます。
+
コントローラモジュールがエンクロージャから少し引き出します。

+
image::../media/drw_a1k_pcm_remove_replace_ieops-1375.svg[コントローラの取り外し図]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
| Aロッキングカムラッチ 
|===
. コントローラモジュールをエンクロージャから引き出し、平らで安定した場所に置きます。
+
このとき、コントローラモジュールをエンクロージャから引き出すときは、必ず底面を支えてください。





== 手順 2 ：ファンを移動します

障害のあるコントローラモジュールから交換用コントローラモジュールに5つのファンモジュールを取り外す必要があります。

. 接地対策がまだの場合は、自身で適切に実施します。
. （必要な場合）両手でベゼルの両側の開口部を持ち、手前に引いてシャーシフレームのボールスタッドからベゼルを外します。
. ファンモジュールのグレーのロックボタンを押し、空いている手で支えながらファンモジュールをシャーシからまっすぐ引き出します。
+

NOTE: ファンモジュールは奥行きがないので、シャーシから突然落下してけがをすることがないように、必ず空いている手でファンモジュールの底面を支えてください。

+
image::../media/drw_a1k_fan_remove_replace_ieops-1376.svg[ファン取り外しAFF A1K]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[番号1]
 a| 
黒のロックボタン

|===
. 交換用コントローラモジュールにファンを取り付けます。
+
.. ファンケースの端を交換用コントローラモジュール前面の開口部に合わせます。
.. ファンモジュールを所定の位置に固定されるまで、交換用コントローラモジュールの奥までそっとスライドさせます。


. 残りのファンモジュールに対して上記の手順を繰り返します。




== 手順 3 ： NV バッテリを移動します

NVバッテリを交換用コントローラに移動します。

. NVバッテリーエアダクトカバーを開き、NVバッテリーの場所を確認します。
+
image::../media/drw_a1k_remove_replace_nvmembat_ieops-1379.svg[NVバッテリ取り外しAFF A1K]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[番号1]
| NVバッテリーエアダクトカバー 


 a| 
image::../media/legend_icon_02.svg[番号2]
 a| 
NVバッテリプラグ



 a| 
image::../media/legend_icon_03.svg[番号3]
 a| 
NVバッテリパック

|===
. バッテリを持ち上げて、バッテリプラグにアクセスします。
. バッテリプラグ前面のクリップを押してプラグをソケットから外し、バッテリケーブルをソケットから抜きます。
. バッテリを持ち上げてエアダクトとコントローラモジュールから取り出します。
. バッテリパックを交換用コントローラモジュールに移動し、NVバッテリエアダクトに取り付けます。
+
.. 交換用コントローラモジュールのNVバッテリエアダクトを開きます。
.. バッテリプラグをソケットに差し込み、プラグが所定の位置にロックされていることを確認します。
.. バッテリパックをスロットに挿入し、バッテリパックをしっかりと押し下げて所定の位置に固定します。
.. エアダクトカバーを閉じます。






== 手順 4 ：システム DIMM を移動します

DIMMを交換用コントローラモジュールに移動します。

. マザーボードのエアダクトを開き、DIMMの場所を確認します。
+
image::../media/drw_a1k_dimms_ieops-1512.svg[DIMM AFF A1Kの取り外し]

+
[cols="1,4"]
|===


 a| 
image::../media/legend_icon_01.svg[番号1]
 a| 
システムDIMM

|===
. DIMM を交換用コントローラモジュールに正しい向きで挿入できるように、ソケット内の DIMM の向きをメモします。
. DIMM の両側にある 2 つのツメをゆっくり押し開いて DIMM をスロットから外し、そのままスライドさせてスロットから取り出します。
+

NOTE: DIMM 回路基板のコンポーネントに力が加わらないように、 DIMM の両端を慎重に持ちます。

. 交換用コントローラモジュールでDIMMを取り付けるスロットの場所を確認します。
. DIMM をスロットに対して垂直に挿入します。
+
DIMM のスロットへの挿入にはある程度の力が必要です。簡単に挿入できない場合は、 DIMM をスロットに正しく合わせてから再度挿入してください。

+

NOTE: DIMM がスロットにまっすぐ差し込まれていることを目で確認してください。

. DIMM の両端のノッチにツメがかかるまで、 DIMM の上部を慎重にしっかり押し込みます。
. 残りのDIMMについても、上記の手順を繰り返します。マザーボードのエアダクトを閉じます。




== 手順 5 ：コントローラモジュールを取り付ける

コントローラモジュールを再度取り付けてブートします。

. まだ行っていない場合は、エアダクトを閉じます。
. コントローラモジュールの端をエンクロージャの開口部に合わせ、レバーをシステム前面から離すようにしてコントローラモジュールをシャーシに挿入します。
. コントローラモジュールの奥へのスライドを止めたら、ファンの下に固定されるまでカムハンドルを内側に回転させます。
+

NOTE: コネクタの損傷を防ぐため、コントローラモジュールをエンクロージャにスライドさせるときは力を入れすぎないでください。

+
コントローラモジュールは、エンクロージャに完全に装着されるとすぐにブートを開始します。

. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。
. AutoSupportが有効になっている場合は、コマンドを使用してケースの自動作成をリストアまたは抑制解除し `system node autosupport invoke -node * -type all -message MAINT=END` ます。

