---
permalink: asa-r2-a1k/io-module-add.html 
sidebar: sidebar 
keywords: asa r2 a1k, add I/O module 
summary: PCIeカードを交換するには、カードからケーブルを外し、SFPモジュールとQSFPモジュールをカードから取り外してから、SFPモジュールとQSFPモジュールを再度取り付けてから、カードをケーブル接続する必要があります。 
---
= I/Oモジュールの追加- ASA A1K
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
空きスロットがある場合、またはすべてのスロットに空きがある場合は、ASA A1KストレージシステムにI/Oモジュールを追加できます。



== 手順1：障害のあるコントローラモジュールをシャットダウン

障害のあるコントローラモジュールをシャットダウンするかテイクオーバーします。

障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

.このタスクについて
ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。

.手順
. AutoSupportが有効になっている場合は、AutoSupport messageコマンドを呼び出してケースの自動作成を抑制します。 `system node autosupport invoke -node * -type all -message MAINT=number_of_hours_downh`
+
次のAutoSupportコマンドは、ケースの自動作成を2時間停止します。 `cluster1:*> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待機しています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
障害のあるコントローラを正常なコントローラから停止またはテイクオーバーします。 `storage failover takeover -ofnode _impaired_node_name_`

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===




== 手順2：新しいI/Oモジュールを追加する

ストレージシステムに使用可能なスロットがある場合は、使用可能なスロットの1つに新しいI/Oモジュールを取り付けます。すべてのスロットに空きがある場合は、既存のI/Oモジュールを取り外してスペースを確保し、新しいI/Oモジュールを取り付けます。

.作業を開始する前に
* を参照し https://hwu.netapp.com/["NetApp Hardware Universe の略"^] て、新しいI/Oモジュールがストレージシステムおよび実行中のONTAPのバージョンと互換性があることを確認します。
* 複数のスロットが使用可能な場合は、でスロットの優先順位を確認します https://hwu.netapp.com/["NetApp Hardware Universe の略"^] また、お使いの I/O モジュールに最適なものを使用してください。
* 他のすべてのコンポーネントが正常に機能していることを確認します。


[role="tabbed-block"]
====
.使用可能なスロットへのI/Oモジュールの追加
--
使用可能なスロットがあるストレージシステムに、新しいI/Oモジュールを追加できます。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. ケーブルマネジメントトレイの内側にあるボタンを引いて下に回転させ、ケーブルマネジメントトレイを下に回転させます。
. ターゲットスロットブランキングモジュールをキャリアから取り外します。
+
.. ターゲットスロットのブランクモジュールのカムラッチを押し下げます。
.. カムラッチをモジュールからできるだけ離します。
.. カムレバーの開口部に指をかけ、モジュールをエンクロージャから引き出して、モジュールをエンクロージャから取り外します。


. I/O モジュールを取り付けます。
+
.. I/Oモジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. I/Oモジュールを指定のデバイスにケーブル接続します。
+

NOTE: 使用していない I/O スロットには、熱の問題を防ぐためにブランクが取り付けられていることを確認してください。

. ケーブルマネジメントトレイを上に回転させて閉じます。
. Loaderプロンプトで、ノードをリブートします。
+
`bye`

+

NOTE: これにより、I/Oモジュールとその他のコンポーネントが再初期化され、ノードがリブートされます。

. パートナーコントローラからコントローラをギブバックします。
+
`storage failover giveback -ofnode target_node_name`

. コントローラ B について、上記の手順を繰り返します
. 正常なノードから、自動ギブバックを無効にした場合はリストアします。
+
`storage failover modify -node local -auto-giveback _true_`

. AutoSupportが有効になっている場合は、ケースの自動作成をリストアします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`



--
.フル実装したシステムへのI/Oモジュールの追加
--
フル装備のシステムにI/Oモジュールを追加するには、既存のI/Oモジュールを取り外し、その場所に新しいI/Oモジュールを取り付けます。

.このタスクについて
フル装備のシステムに新しいI/Oモジュールを追加する場合は、次のシナリオについて理解しておく必要があります。

[cols="1,2"]
|===
| シナリオ | アクションが必要です 


 a| 
NICからNIC（同じ数のポート）
 a| 
LIF は、コントローラモジュールがシャットダウンすると自動的に移行されます。



 a| 
NICからNIC（異なるポート数）
 a| 
選択したLIFを別のホームポートに完全に再割り当てします。詳細については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF を移行する"^] 。



 a| 
NICからストレージI/Oモジュール
 a| 
System Manager を使用して、 LIF を別のホームポートに完全に移行します。手順については、を参照してください https://docs.netapp.com/ontap-9/topic/com.netapp.doc.onc-sm-help-960/GUID-208BB0B8-3F84-466D-9F4F-6E1542A2BE7D.html["LIF を移行する"^]。

|===
.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. ターゲット I/O モジュールのケーブルをすべて取り外します。
. ケーブルマネジメントトレイの内側にあるボタンを引いて下に回転させ、ケーブルマネジメントトレイを下に回転させます。
. ターゲットの I/O モジュールをシャーシから取り外します。
+
.. カムラッチボタンを押します。
.. カムラッチをモジュールからできるだけ離します。
.. カムレバーの開口部に指をかけ、モジュールをエンクロージャから引き出して、モジュールをエンクロージャから取り外します。
+
I/O モジュールが取り付けられていたスロットを記録しておいてください。



. I/Oモジュールをエンクロージャのターゲットスロットに取り付けます。
+
.. モジュールをエンクロージャスロット開口部の端に合わせます。
.. モジュールをスロットにゆっくりと挿入してエンクロージャの奥まで押し込み、カムラッチを上に回転させてモジュールを所定の位置にロックします。


. I/Oモジュールを指定のデバイスにケーブル接続します。
. 取り外しと取り付けの手順を繰り返して、コントローラの他のモジュールを交換します。
. ケーブルマネジメントトレイを上に回転させて閉じます。
. LOADERプロンプトからコントローラをリブートします。_bye_
+
これにより、PCIeカードおよびその他のコンポーネントが再初期化され、ノードがリブートされます。

+

NOTE: リブート中に問題 が発生した場合は、を参照してください https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1494308["BURT 1494308 - I/Oモジュールの交換中に環境のシャットダウンがトリガーされることがあります"]

. パートナーコントローラからコントローラをギブバックします。
+
`storage failover giveback -ofnode target_node_name`

. 自動ギブバックを無効にした場合は有効にします。
+
`storage failover modify -node local -auto-giveback true`

. 次のいずれかを実行します。
+
** NIC I/Oモジュールを取り外し、新しいNIC I/Oモジュールを取り付けた場合は、ポートごとに次のnetworkコマンドを使用します。
+
`storage port modify -node *_<node name>__ -port *_<port name>__ -mode network`

** NIC I/Oモジュールを取り外してストレージI/Oモジュールを取り付けた場合は、NS224シェルフを取り付けてケーブル接続します（を参照）link:../ns224/hot-add-shelf-overview.html["ホツトアトワアクフロオ"]。


. コントローラ B について、上記の手順を繰り返します


--
====