= 手順 1 ：障害のあるコントローラをシャットダウンします
:allow-uri-read: 


コントローラモジュールのリアルタイムクロック（ RTC ）バッテリを交換して、正確な時刻同期に依存するシステムのサービスとアプリケーションが機能を継続できるようにします。

* この手順は、システムでサポートされるすべてのバージョンの ONTAP で使用できます。
* システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。




== 手順 1 ：障害のあるコントローラをシャットダウンします

次のいずれかのオプションを使用して、障害のあるコントローラをシャットダウンまたはテイクオーバーします。

[role="tabbed-block"]
====
.オプション 1 ：ほとんどのシステム
--
障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

.このタスクについて
* SANシステムを使用している場合は、障害コントローラのSCSIブレードのイベントメッセージを確認しておく必要があり  `cluster kernel-service show`ます）。コマンド（priv advancedモードから）を実行すると、 `cluster kernel-service show` ノード名、そのノードのクォーラムステータス、そのノードの可用性ステータス、およびそのノードの動作ステータスが表示されます。
+
各 SCSI ブレードプロセスは、クラスタ内の他のノードとクォーラムを構成している必要があります。交換を進める前に、すべての問題を解決しておく必要があります。

* ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。


.手順
. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。 `system node autosupport invoke -node * -type all -message MAINT=<# of hours>h`
+
次のAutoSupport メッセージは、ケースの自動作成を2時間停止します。 `cluster1:> system node autosupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
+

NOTE: 自動ギブバックを無効にしますか?_と表示されたら'y'を入力します

. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。「 storage failover takeover -ofnode impaired_node_name _

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
.オプション 2 ：コントローラが MetroCluster に搭載されている
--
障害のあるコントローラをシャットダウンするには、コントローラのステータスを確認し、必要に応じて正常なコントローラが障害のあるコントローラストレージからデータを引き続き提供できるようにコントローラをテイクオーバーする必要があります。

* ノードが 3 つ以上あるクラスタは、クォーラムを構成している必要があります。クラスタがクォーラムを構成していない場合、または正常なコントローラで適格性と正常性についてfalseと表示される場合は、障害のあるコントローラをシャットダウンする前に問題 を修正する必要があります。を参照してください link:https://docs.netapp.com/us-en/ontap/system-admin/synchronize-node-cluster-task.html?q=Quorum["ノードをクラスタと同期します"^]。
* MetroCluster 構成を使用している場合は、 MetroCluster 構成状態が構成済みで、ノードが有効かつ正常な状態であることを確認しておく必要があります（「 MetroCluster node show 」）。


.手順
. AutoSupport が有効になっている場合は、 AutoSupport メッセージを呼び出してケースの自動作成を抑制します。「 system node AutoSupport invoke -node * -type all -message MAINT=number_OF_hours_downh
+
次の AutoSupport メッセージは、ケースの自動作成を 2 時間停止します。 cluster1 ： * > system node AutoSupport invoke -node * -type all -message MAINT=2h`

. 正常なコントローラのコンソールから自動ギブバックを無効にします。 storage failover modify – node local-auto-giveback false
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラの表示 | 作業 


 a| 
LOADER プロンプト
 a| 
次の手順に進みます。



 a| 
ギブバックを待っています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。「 storage failover takeover -ofnode impaired_node_name _

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===


--
====


== 手順 2 ：コントローラモジュールを取り外す

コントローラモジュールを交換する場合、またはコントローラモジュール内部のコンポーネントを交換する場合は、コントローラモジュールをエンクロージャから取り外す必要があります。

. システムのスロット4/5にあるNVRAMステータスLEDを確認します。コントローラモジュールの前面パネルにもNVRAM LEDがあります。NVアイコンを探します。
+
image::../media/drw_a1K-70-90_nvram-led_ieops-1463.svg[NVRAMの警告/ステータスLEDの場所の図]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
 a| 
NVRAMステータスLED



 a| 
image:../media/legend_icon_02.svg["番号1、幅= 30px"]
 a| 
NVRAM警告LED

|===
+

NOTE: NVRAMステータスLEDが点滅している場合は、コントローラモジュールがテイクオーバーされていないか適切に停止されていない（データがコミットされていない）可能性があります。障害のあるコントローラモジュールがパートナーコントローラモジュールに正常にテイクオーバーされなかった場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"] 。

+
障害のあるコントローラモジュールのNVRAMステータスLEDの一般的な動作は次のとおりです。

+
** コントローラモジュールの電源をオフにしてコントローラモジュールが「waiting for giveback」状態になるか、コントローラモジュールがテイクオーバーされていないか適切に停止されていない（データがコミットされていない）と、NVRAMステータスLEDが点滅します。
** コントローラモジュールをエンクロージャから取り外すとNVRAMステータスLEDが点滅します。コントローラモジュールがテイクオーバーされていないか、適切に停止されていない（データがコミットされていない）可能性があります。パートナーコントローラモジュールまたは障害のあるコントローラモジュールによってコントローラモジュールが正常にテイクオーバーされたことを確認します `waiting for giveback`。その後、点滅しているLEDは無視してかまいません（コントローラをエンクロージャから取り外すこともできます）。


. 接地対策がまだの場合は、自身で適切に実施します。
. ユニットの前面で、ロックカムの穴に指をかけ、カムレバーのタブを軽く押しながら、両方のラッチを同時に手前にしっかりと回転させます。
+
コントローラモジュールがエンクロージャから少し引き出します。

+
image::../media/drw_a1k_pcm_remove_replace_ieops-1375.svg[コントローラの取り外し図]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
| Aロッキングカムラッチ 
|===
. コントローラモジュールをエンクロージャから引き出し、平らで安定した場所に置きます。
+
このとき、コントローラモジュールをエンクロージャから引き出すときは、必ず底面を支えてください。





== 手順 3 ： RTC バッテリを交換します

障害が発生したRTCバッテリを取り外し、交換用RTCバッテリを取り付けます。

. コントローラ上部のコントローラエアダクトを開きます。
+
.. エアダクトの遠端にあるくぼみに指を入れます。
.. エアダクトを持ち上げ、所定の位置まで上に回転させます。


. エアダクトの下のRTCバッテリの場所を確認します。
+
image::../media/drw_a1k_rtc_remove_replace_ieops-1381.svg[RTC バッテリを交換します]

+
[cols="1,4"]
|===


 a| 
image:../media/legend_icon_01.svg["番号1、幅= 30px"]
| RTC バッテリとホルダー 
|===
. バッテリをそっと押してホルダーから離し、持ち上げてホルダーから取り出します。
+

NOTE: ホルダーから取り外す際に、バッテリの極の向きを確認しておいてください。バッテリに記載されているプラス記号に従って、バッテリをホルダーに正しく配置する必要があります。ホルダーの近くにプラス記号が表示されているので、バッテリーの位置を確認できます。

. 交換用バッテリを静電気防止用の梱包バッグから取り出します。
. RTC バッテリの極の向きを確認し、バッテリを斜めに傾けた状態で押し下げてホルダーに挿入します。
. バッテリがホルダーに完全に取り付けられ、かつ極の向きが正しいことを目で見て確認します。




== 手順 4 ：コントローラモジュールを再度取り付けます

コントローラモジュールを再度取り付けてブートします。

. まだ行っていない場合は、エアダクトを閉じます。
. コントローラモジュールの端をエンクロージャの開口部に合わせ、レバーをシステム前面から離すようにしてコントローラモジュールをシャーシに挿入します。
. コントローラモジュールの奥へのスライドを止めたら、ファンの下に固定されるまでカムハンドルを内側に回転させます。
+

NOTE: コネクタの損傷を防ぐため、コントローラモジュールをエンクロージャにスライドさせるときは力を入れすぎないでください。

+
コントローラモジュールは、エンクロージャに完全に装着されるとすぐにブートを開始します。

. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。
. AutoSupportが有効になっている場合は、コマンドを使用してケースの自動作成をリストアまたは抑制解除し `system node autosupport invoke -node * -type all -message MAINT=END` ます。




== 手順5：コントローラの日時をリセットする


NOTE: RTCバッテリを交換し、コントローラを挿入して最初にBIOSをリセットすると、次のエラーメッセージが表示されます。これらのメッセージは省略されており、この手順を続行できます。
`RTC date/time error. Reset date/time to default`
`RTC power failure error`

. cluster date show_コマンドを使用して、正常なコントローラの日時を確認します。



NOTE: システムがブートメニューで停止した場合は、オプションを選択し  `Reboot node` てプロンプトが表示されたら「_y_」と応答し、Ctrl+C_を押してLOADERにブートします。

. ターゲットコントローラのLOADERプロンプトで、コマンドを使用して日時を確認します `cluster date show` 。
. 必要に応じて 'set date mm/dd/yyyy` コマンドで日付を変更します
. 必要に応じて、「 set time hh ： mm ： ss 」コマンドを使用して、時刻を GMT で設定します。
+
.. ターゲットコントローラの日付と時刻を確認します。
.. LOADERプロンプトで_bye_と入力してPCIeカードおよびその他のコンポーネントを再初期化し、コントローラをリブートします。
.. コントローラのストレージをギブバックして、コントローラを通常動作に戻します。_storage failover giveback -ofnode_impaired_node_name_
.. 自動ギブバックが無効になっていた場合は、再度有効にします。_storage failover modify -node local -auto-giveback true_






== 手順 6 ：障害が発生したパーツをネットアップに返却する

障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。を参照してください https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"] 詳細については、を参照してください。
