= 手順1：コントローラをギブバックする
:allow-uri-read: 


コントローラをギブバックして交換手順を続行します。



== 手順1：コントローラをギブバックする

. ストレージシステムで暗号化が設定されている場合は、次の手順に従ってストレージまたはボリュームの暗号化機能をリストアし、システムをリブートする必要があります。
+
.. メニューから起動し、オプション10を実行します。
.. パスフレーズを入力してデータをバックアップし、標準ブートを実行します。を参照してください。 https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Restore_onboard_key_management_encryption_keys["オンボードキー管理の暗号化キーをリストア"]
.. CFOのみのギブバックの実行
.. オンボード同期を実行し、SVM-KEKがtrueに設定されていることを確認します。を参照してください。 https://kb.netapp.com/on-prem/ontap/DM/Encryption/Encryption-KBs/Onboard_keymanager_sync_fails_after_motherboard_replacement["MBの交換に失敗したあとのギブバック-キーマネージャで処理が拒否された"]
.. SFOのギブバック（強制なし）


. システムで暗号化が設定されていない場合は、次の手順を実行してシステムをリブートします。
+
.. メニューから起動し、オプション1を実行します。
.. コントローラをギブバックします。
.. 正常なコントローラから、交換したコントローラのストレージをギブバックします。 storage failover giveback -ofnode replacement_node_name _`
+
_replacement _controller はストレージをテイクバックしてブートを完了します。

+

NOTE: ギブバックが拒否されている場合は、拒否を無効にすることを検討してください。

+
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62286["使用しているバージョンの ONTAP 9 に対するハイアベイラビリティ構成のコンテンツを検索してください"]

.. ギブバックが完了したら、 HA ペアが正常で、テイクオーバーが可能であることを確認します。「 storage failover show


. システムが MetroCluster 構成になっている場合は ' コントローラのステータスを監視します MetroCluster node show
+
MetroCluster 構成では、交換後に通常の状態に戻るまで数分かかります。この時点で各コントローラの状態が設定済みになります。 DR ミラーリングは有効で、通常モードになります。MetroCluster node show -fields node-systemid' コマンドの出力には、 MetroCluster 設定が通常の状態に戻るまで古いシステム ID が表示されます。

. コントローラが MetroCluster 構成になっている場合は、 MetroCluster の状態に応じて、元の所有者がディザスタサイトのコントローラである場合に DR ホーム ID フィールドにディスクの元の所有者が表示されることを確認します。
+
これは、次の両方に該当する場合に必要です。

+
** MetroCluster 構成がスイッチオーバー状態である。
** replacement _controller は、ディザスタサイトのディスクの現在の所有者です。
+
https://docs.netapp.com/us-en/ontap-metrocluster/manage/concept_understanding_mcc_data_protection_and_disaster_recovery.html#disk-ownership-changes-during-ha-takeover-and-metrocluster-switchover-in-a-four-node-metrocluster-configuration["4 ノード MetroCluster 構成での HA テイクオーバーおよび MetroCluster スイッチオーバー中のディスク所有権の変更"]



. システムが MetroCluster 構成になっている場合は、各コントローラが構成されていることを確認します。「 MetroCluster node show -fields configurion-state 」
+
[listing]
----
node1_siteA::> metrocluster node show -fields configuration-state

dr-group-id            cluster node           configuration-state
-----------            ---------------------- -------------- -------------------
1 node1_siteA          node1mcc-001           configured
1 node1_siteA          node1mcc-002           configured
1 node1_siteB          node1mcc-003           configured
1 node1_siteB          node1mcc-004           configured

4 entries were displayed.
----
. 各コントローラに、想定されるボリュームが存在することを確認します。 vol show -node node-name
. リブート時の自動テイクオーバーを無効にした場合は、正常なコントローラで storage failover modify -node replacement-node-name -onreboot true を有効にします
. AutoSupportが有効になっている場合は、コマンドを使用してケースの自動作成をリストアまたは抑制解除し `system node autosupport invoke -node * -type all -message MAINT=END` ます。

