= 
:allow-uri-read: 


.作業を開始する前に
* OKM の場合、クラスター全体のパスフレーズとバックアップ データが必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。




.手順
. Loaderプロンプトで、次のコマンドを入力します。
+
`boot_recovery -partner`

+
画面に次のメッセージが表示されます。

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. ブートメディアのインストールリカバリプロセスを監視します。
+
プロセスが完了し、メッセージが表示されます `Installation complete`。

. 暗号化と暗号化の種類がチェックされ、2つのメッセージのいずれかが表示されます。表示されるメッセージに応じて、次のいずれかの操作を実行します。
+

IMPORTANT: システムにキー管理ツールが設定されているかどうかをプロセスで特定できない場合があります。システムでキー管理ツールが設定されているかどうかを確認してから、どのタイプのキー管理ツールが設定されているかを確認するエラーメッセージが表示されます。問題を解決すると、プロセスが再開されます。

+
.構成エラーの検索プロンプトの例を表示します。
[%collapsible]
====
....
Error when fetching key manager config from partner ${partner_ip}: ${status}

Has key manager been configured on this system

Is the key manager onboard

....
====
+
[cols="1,2"]
|===
| 表示されるメッセージ | 操作 


 a| 
`key manager is not configured. Exiting.`
 a| 
システムで暗号化が設定されていません。次の手順を実行します。

.. コンソールメッセージが停止したら、<enter>キーを押します。
+
*** ログインプロンプトが表示された場合は、手順 4 に進みます。
*** ログイン プロンプトが表示されない場合は、パートナー ノードにログインして手順 4 に進みます。


.. 自動ギブバックが無効になっている場合は、手順 6 に進み、有効にします。




 a| 
`key manager is configured.`
 a| 
適切なキー マネージャーを復元するには、手順 5 に進みます。

ノードはブート メニューにアクセスし、次を実行します。

** オプション10：オンボードキーマネージャ（OKM）が搭載されたシステムの場合。
** オプション11：外部キーマネージャ（EKM）が搭載されたシステムの場合。


|===
. システムに暗号化がインストールされておらず、ログインプロンプトが表示されない場合。次の手順を実行します。
+
.. override-destination-checks オプションを使用してルートのみを返します。
+
`storage failover giveback -ofnode impaired-node -only-root true -override -destination-checks true`

+

NOTE: このコマンドは診断モードでのみ使用できます。詳細については、 link:https://docs.netapp.com/us-en/ontap/system-admin/administrative-privilege-levels-concept.html["ONTAP CLI コマンドの権限レベル"^] 。

+
エラーが発生した場合は、にお問い合わせください https://support.netapp.com["ネットアップサポート"]。

.. ギブバックレポートが完了してから5分待って、フェイルオーバーのステータスとギブバックのステータスを確認します。
+
`storage failover show`そして `storage failover show-giveback`

+

NOTE: 次のコマンドは、診断モードの特権レベルでのみ使用できます。

.. ONTAP 9.17.1 を実行していて、HA 内部接続リンクがダウンしている場合は、次のようにしてリンクを復旧します。
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`

+

NOTE: 9.18.1 以降を実行している場合は、上記の手順をスキップして次の手順に進みます。

.. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。
+
「 storage failover giveback -ofnode _impaired_node_name _



. キー マネージャーが設定されているシステムの場合は、適切なキー マネージャーの復元プロセスを選択します。
+
[role="tabbed-block"]
====
.オンボードキーマネージャ（ OKM ）
--
OKMが検出されると、次のメッセージが表示され、ブートメニューオプション10の実行が開始されます。

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. OKMリカバリプロセスを開始するかどうかを確認するプロンプトでと入力し `Y`ます。
.. プロンプトが表示されたら、次のように入力します。
+
... パスフレーズ
... 確認を求められたらパスフレーズをもう一度入力してください
... オンボードキーマネージャーのバックアップデータ
+
.パスフレーズとバックアップデータのプロンプトの例を示す
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the passphrase again to confirm:
-----BEGIN PASSPHRASE-----
<passphrase_value>
-----END PASSPHRASE-----
Enter the backup data:
-----BEGIN BACKUP-----
<passphrase_value>
-----END ACKUP-----
....
=====


.. 引き続きリカバリプロセスを監視し、パートナーノードから適切なファイルをリストアします。
+
リカバリプロセスが完了すると、ノードがリブートします。次のメッセージは、リカバリが成功したことを示します。

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.keydb file.

Successfully recovered keymanager secrets.
....
.. ノードがリブートしたら、システムがオンラインに戻って動作可能になったことを確認して、ブートメディアのリカバリが成功したことを確認します。
.. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。
+
「 storage failover giveback -ofnode _impaired_node_name _

+
... HA 相互接続リンクがダウンしている場合は、それらを復旧して自動ギブバックを再開します。
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`



.. パートナーノードが完全に稼働してデータを提供したら、クラスタ全体でOKMキーを同期します。
+
`security key-manager onboard sync`



--
.外部キーマネージャ（ EKM ）
--
EKMが検出されると、次のメッセージが表示され、ブートメニューオプション11の実行が開始されます。

....
key manager is configured.
Entering Bootmenu Option 11...
....
.. キーが正常にリストアされたかどうかに応じて、次のいずれかの操作を実行します。
+
*** もしあなたが `kmip2_client: Successfully imported the keys from external key server: xxx.xxx.xxx.xxx:5696`出力では、EKM 構成が正常に復元されたことが示されています。
+
このプロセスは、パートナー ノードから適切なファイルを復元し、ノードを再起動しようとします。次の手順に進みます。

*** キーが正常に復元されなかった場合、システムは停止し、キーを復元できなかったことが示されます。エラーおよび警告メッセージが表示されます。回復プロセスを再実行する必要があります。
+
`boot_recovery -partner`

+
.キーリカバリのエラーおよび警告メッセージの例を示します。
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...
WARNING: kmip_init: authentication keys might not be available.
********************************************************
*                 A T T E N T I O N                    *
*                                                      *
*       System cannot connect to key managers.         *
*                                                      *
********************************************************
ERROR: kmip_init: halting this system with encrypted mroot...
.
Terminated

Uptime: 11m32s
System halting...

LOADER-B>
....
=====


.. ノードがリブートしたら、システムがオンラインに戻って動作可能になったことを確認して、ブートメディアのリカバリが成功したことを確認します。
.. コントローラのストレージをギブバックして、コントローラを通常動作に戻します。
+
「 storage failover giveback -ofnode _impaired_node_name _

+
... HA 相互接続リンクがダウンしている場合は、それらを復旧して自動ギブバックを再開します。
+
`system ha interconnect link on -node healthy-node -link 0`

+
`system ha interconnect link on -node healthy-node -link 1`





--
====


. 自動ギブバックを無効にした場合は、再度有効にします。
+
`storage failover modify -node local auto-giveback-of true`

. AutoSupportが有効になっている場合は、ケースの自動作成をリストアします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`


