= 
:allow-uri-read: 


 `boot_recovery -partner`ONTAP 9 .16.0以降を実行しているASA R2プラットフォームでコマンドを使用すると、パートナーノードからONTAPイメージ（ブートメディアリカバリ）をリストアできます。

.作業を開始する前に
ノードをブートしたときにそのノードのブートメディアが破損すると、Loaderプロンプトに次のメッセージとブートプロセス（stop）が表示されます。

[listing]
----

Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014


Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel:Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0,fat)


ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0,fat)


Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>

----
このメッセージが表示された場合は、ONTAPイメージをリストアする必要があります。

.手順
. Loaderプロンプトで、_boot_recovery-partner_commandを入力します。
+
画面にメッセージが表示さ `Starting boot media recovery (BMR) process press Ctrl-C to abort...`れ、初期チェックが開始されます。

. Loaderがローカルクラスタポートを設定し、を使用してネットブートを実行する際のプロセスを監視します `\http://<remote-partner-IP>:65530/recoverydisk/image.tgz`。
+
ネットブートが実行されると、 `Starting BMR ...`が画面に表示され、インストールプロセスが完了します。

+
.. キー管理ツールが設定されていない場合は、次のメッセージが表示されます。
+
....
key manager is not configured. Exiting.
....
.. 次のメッセージが表示された場合は、オンボードキーマネージャ（OKM）が設定されています。
+
....

key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):

....
+
に進み、リカバリプロセスを完了します。

.. 次のメッセージが表示された場合は、外部キーマネージャ（EKM）が設定されています。EKMトピックに移動し、リカバリプロセスを完了します。
+
....
Error when fetching key manager config from partner 169.254.139.209: 28
Has key manager been configured on this system? {y|n}

....


. BMRプロセスを監視して、パートナーからrestore backup config、env file、mdb、およびrdbを実行します。
. 次のように表示されると、ノードがリブートし、BMRが完了します。


....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....