= セキュリティキー管理ツールの設定を確認
:allow-uri-read: 


障害のあるコントローラをシャットダウンする前に、システムでセキュリティキー管理機能が有効になっているかディスクが暗号化されているかを確認する必要があります。



== セキュリティキー管理ツールの設定を確認

.手順
. security key-manager keystore show_コマンドを使用して、キー管理ツールがアクティブかどうかを確認します。詳細については、 https://docs.netapp.com/us-en/ontap-cli/security-key-manager-keystore-show.html["security key-manager keystore showのマニュアルページ"^]
+

NOTE: 他にもキー管理ツールのタイプがある場合があります。タイプは `KMIP`、 `AKV`、および `GCP`です。これらのタイプを確認するプロセスは、キー管理ツールのタイプを確認するプロセスと同じ `external` `onboard` です。

+
** 出力が表示されない場合は、に進み、障害ノードをシャットダウンします link:bootmedia-shutdown.html["障害コントローラをシャットダウン"] 。
** コマンドで出力が表示された場合は、システムがアクティブで `security key-manager` あるため、タイプとステータスを表示する必要があり `Key Manager` ます。


. security key-manager key query_コマンド を使用して、アクティブなの情報を表示します `Key Manager` 。
+
** タイプにと表示され、列にと表示されていれば、 `Key Manager` `external` `Restored` `true`障害のあるコントローラを安全にシャットダウンできます。
** タイプがと表示され、列にが表示された場合は `Key Manager` `onboard` `Restored` `true`、いくつかの手順を追加で実行する必要があります。
** タイプがと表示され、列に以外の値が表示されている場合は `Key Manager` `external` `Restored` `true`、いくつかの手順を追加で実行する必要があります。
** タイプがと表示され、列に以外の値が表示されている場合は `Key Manager` `onboard` `Restored` `true`、いくつかの手順を追加で実行する必要があります。


. タイプがと表示され、列にと表示された場合は `Key Manager` `onboard` `Restored` `true`、OKM情報を手動でバックアップします。
+
.. 続行するかどうかを尋ねられたら、と入力し `y` ます `set -priv advanced`
.. 次のコマンドを入力して、キー管理情報を表示します。_security key-manager onboard show -backup_
.. バックアップ情報の内容を別のファイルまたはログファイルにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
.. 障害のあるコントローラを安全にシャットダウンできます。


. タイプがと表示され、列に次の以外が表示されている場合 `Key Manager` `onboard` `Restored` `true`：
+
.. onboard security key-manager syncコマンドを入力します。_security key-manager onboard sync_
+

NOTE: プロンプトで、32文字のオンボードキー管理のパスフレーズを英数字で入力します。パスフレーズを指定できない場合は、NetAppサポートにお問い合わせください。 http://mysupport.netapp.com/["mysupport.netapp.com"^]

.. すべての認証キーの列にと表示されていることを確認し `Restored` `true` ます。 `security key-manager key query`
.. タイプが表示されていることを確認し `Key Manager` `onboard`、OKM情報を手動でバックアップします。
.. 次のコマンドを入力して、キー管理バックアップ情報を表示します。_security key-manager onboard show -backup_
.. バックアップ情報の内容を別のファイルまたはログファイルにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
.. コントローラは安全にシャットダウンできます。


. タイプがと表示され、列に次の以外が表示されている場合 `Key Manager` `external` `Restored` `true`：
+
.. 外部キー管理の認証キーをクラスタ内のすべてのノードにリストアします：「 securitykey-manager external restore
+
コマンドが失敗した場合は、NetAppサポートにお問い合わせください http://mysupport.netapp.com/["mysupport.netapp.com"^]。

.. すべての認証キーの列にと表示されていることを確認します `Restored` `true` 。_security key-manager key query_
.. 障害のあるコントローラを安全にシャットダウンできます。



