= NVE の設定を確認する
:allow-uri-read: 


障害のあるコントローラをシャットダウンする前に、システムで NetApp Volume Encryption （ NVE ）または NetApp Storage Encryption （ NSE ）が有効になっているかどうかを確認する必要があります。その場合は、設定を確認する必要があります。

.手順
. 障害のあるコントローラにコンソールケーブルを接続します。
. クラスタ内のボリュームに NVE が設定されているかどうかを確認します。 volume show -is-encrypted true
+
出力に含まれるボリュームには NVE が設定されているため、 NVE の設定を確認する必要があります。ボリュームが表示されない場合は、 NSE が設定されているかどうかを確認します。

. NSE が設定されているかどうかを確認します。「 storage encryption disk show 」
+
** モードとキー ID の情報を含むドライブの詳細がコマンド出力に表示される場合は、 NSE が設定されているので、 NSE の設定を確認する必要があります。
** NVE と NSE が設定されていない場合は、障害のあるコントローラを安全にシャットダウンできます。






== NVE の設定を確認する

.手順
. キー管理サーバに格納されている認証キーのキー ID を表示します。「 securitykey-manager query
+
** [Restored （復元） ] 列に [yes] と表示され、すべてのキー管理ツールに [Available] と表示されている場合は、障害のあるコントローラをシャットダウンしても安全です。
** [Restored （復元） ] 列に 'yes' 以外の項目が表示される場合、またはいずれかのキー管理ツールに [Unavailable （利用不可） ] と表示される場合は、いくつかの追加手順を実行する必要があります。
** オンボードキー管理が有効になっている場合にこのコマンドがサポートされませんというメッセージが表示された場合は、他の手順をいくつか実行する必要があります。


. [ リストア済み ] カラムに 'yes' 以外のものが表示されている場合 ' または ' キー・マネージャに unavailable と表示されている場合は ' 次の手順を実行します
+
.. すべての認証キーと関連キー ID を取得してリストアします： 'securitykey-manager restore-address*
+
コマンドが失敗した場合は、ネットアップサポートにお問い合わせください。

+
http://["mysupport.netapp.com"]

.. すべての認証キーについて 'restored' 列に yes と表示され ' すべてのキー・マネージャには Available ： 'securitykey-manager query と表示されていることを確認します
.. 障害のあるコントローラをシャットダウンします。


. オンボードキー管理が有効になっているときに「 This command is not supported when onboard key management 」というメッセージが表示された場合は、オンボードキーマネージャに格納されているキーを表示します。「 securitykey-manager key show -detail」
+
.. [Restored （リストア済み） ] カラムに 'yes' と表示されている場合は ' オンボード・キー管理情報を手動でバックアップします
+
*** advanced 権限モードに切り替え、続行するかどうかを尋ねられたら「 y 」と入力します。「 set -priv advanced 」
*** コマンドを入力して、 OKM バックアップ情報を表示します：「 securitykey-manager backup show 」
*** バックアップ情報の内容を別のファイルまたはログファイルにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
*** admin モードに戻ります。 'set-priv admin'
*** 障害のあるコントローラをシャットダウンします。


.. [ リストア済み ] カラムに 'yes' 以外の項目が表示される場合は ' 次の手順を実行します
+
*** key-manager setup ウィザードを実行します： 'securitykey-manager setup -node target/impaired node name
+

NOTE: プロンプトで、お客様のオンボードキー管理のパスフレーズを入力します。パスフレーズを指定できない場合は、にお問い合わせください http://["mysupport.netapp.com"]

*** すべての認証キーに対して 'restored' カラムに yes が表示されていることを確認します 'securitykey-manager key show-detail
*** advanced 権限モードに切り替え、続行するかどうかを尋ねられたら「 y 」と入力します。「 set -priv advanced 」
*** コマンドを入力して、 OKM バックアップ情報を表示します：「 securitykey-manager backup show 」
*** バックアップ情報の内容を別のファイルまたはログファイルにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
*** admin モードに戻ります。 'set-priv admin'
*** コントローラは安全にシャットダウンできます。








== NSE の設定を確認

.手順
. キー管理サーバに格納されている認証キーのキー ID を表示します。「 securitykey-manager query
+
** [Restored （復元） ] 列に [yes] と表示され、すべてのキー管理ツールに [Available] と表示されている場合は、障害のあるコントローラをシャットダウンしても安全です。
** [Restored （復元） ] 列に 'yes' 以外の項目が表示される場合、またはいずれかのキー管理ツールに [Unavailable （利用不可） ] と表示される場合は、いくつかの追加手順を実行する必要があります。
** オンボードキー管理が有効になっている場合にこのコマンドがサポートされませんというメッセージが表示された場合は、他の手順をいくつか実行する必要があります


. [ リストア済み ] カラムに 'yes' 以外のものが表示されている場合 ' または ' キー・マネージャに unavailable と表示されている場合は ' 次の手順を実行します
+
.. すべての認証キーと関連キー ID を取得してリストアします： 'securitykey-manager restore-address*
+
コマンドが失敗した場合は、ネットアップサポートにお問い合わせください。

+
http://["mysupport.netapp.com"]

.. すべての認証キーについて 'restored' 列に yes と表示され ' すべてのキー・マネージャには Available ： 'securitykey-manager query と表示されていることを確認します
.. 障害のあるコントローラをシャットダウンします。


. オンボードキー管理が有効になっているときに「 This command is not supported when onboard key management 」というメッセージが表示された場合は、オンボードキーマネージャに格納されているキーを表示します。「 securitykey-manager key show -detail」
+
.. [Restored （復元） ] 列に「 yes 」と表示されている場合は、オンボードキー管理情報を手動でバックアップします。
+
*** advanced 権限モードに切り替え、続行するかどうかを尋ねられたら「 y 」と入力します。「 set -priv advanced 」
*** コマンドを入力して、 OKM バックアップ情報を表示します：「 securitykey-manager backup show 」
*** バックアップ情報の内容を別のファイルまたはログファイルにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
*** admin モードに戻ります。 'set-priv admin'
*** 障害のあるコントローラをシャットダウンします。


.. [ リストア済み ] カラムに 'yes' 以外の項目が表示される場合は ' 次の手順を実行します
+
*** key-manager setup ウィザードを実行します： 'securitykey-manager setup -node target/impaired node name
+

NOTE: プロンプトで、お客様の OKM パスフレーズを入力します。パスフレーズを指定できない場合は、にお問い合わせください http://["mysupport.netapp.com"]

*** すべての認証キーについて 'restored' 列に yes と表示されていることを確認します
*** advanced 権限モードに切り替え、続行するかどうかを尋ねられたら「 y 」と入力します。「 set -priv advanced 」
*** コマンド「 security key-manager backup show 」を入力して、 OKM の情報をバックアップします
+

NOTE: OKM 情報がログファイルに保存されていることを確認してください。この情報は、 OKM を手動でリカバリする必要がある災害シナリオで必要になります。

*** バックアップ情報の内容を別のファイルまたはログにコピーします。OKM は手動でリカバリする必要がある災害シナリオで必要になります。
*** admin モードに戻ります。 'set-priv admin'
*** コントローラは安全にシャットダウンできます。





