= 
:allow-uri-read: 


I/O の実行中に障害が発生したドライブを無停止で交換できます。

.作業を開始する前に
* 取り付けるドライブがストレージシステムでサポートされている必要があります。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

* 自己暗号化ドライブ（SED）認証が有効になっている場合は、ONTAPのドキュメントに記載されているSEDの交換手順を使用する必要があります。
+
ONTAP のドキュメントには、 SED の交換前と交換後に実行する必要がある手順も記載されています。

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["CLI での NetApp Encryption の概要"^]

* ストレージシステムの他のすべてのコンポーネントが正常に動作している必要があります。正常に動作していない場合は、この手順を続行する前にににアクセスする必要が https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]あります。
* 取り外すドライブで障害が発生していることを確認します。
+
「 storage disk show -broken 」コマンドを実行して、ドライブが障害状態であることを確認できます。障害が発生したドライブが障害ドライブのリストに表示されます。表示されない場合は、少し待ってからもう一度コマンドを実行してください。

+

NOTE: ドライブのタイプと容量によっては、障害ドライブのリストに表示されるまでに数時間かかることがあります。



.このタスクについて
* 障害が発生したドライブを交換する場合は、ドライブが取り外されたことをストレージシステムが認識できるように、ドライブを取り外してから交換用ドライブを挿入するまで70秒待つ必要があります。
* ドライブをホットスワップする前に、Disk Qualification Package（DQP）の最新バージョンをインストールしておくことを推奨します。
+
DQP の最新バージョンをインストールしておくと、新しく認定されたドライブがシステムで認識されて使用できるようになります。これにより、ドライブの情報が最新でない場合に表示されるシステムイベントメッセージを回避できるほか、ドライブが認識されないために発生するドライブのパーティショニングを回避できます。さらに、ドライブのファームウェアが最新でない場合も、通知で知ることができます。

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware/download/DISKQUAL/ALL/qual_devices.zip["ネットアップのダウンロード： Disk Qualification Package"^]

* FRUコンポーネントを交換する前に、お使いのシステムのNVMeシェルフモジュール（NSM）ファームウェアとドライブファームウェアを最新バージョンにしておくことを推奨します。
+
https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

+
https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"^]

+
[NOTE]
====
ファームウェアをシェルフおよびそのコンポーネントに対応しないバージョンにリバートしないでください。

====
* 最新のファームウェアバージョンでない新しいドライブのドライブファームウェアは自動的に（無停止で）更新されます。
+

NOTE: ドライブファームウェアは 2 分ごとにチェックされます。

* 影響を受けるストレージシステムの物理的な位置を特定するために、必要に応じてストレージシステムのロケーション（青色の）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
ストレージシステムにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。


