= 
:allow-uri-read: 


この手順を使用するには、ストレージ システムで ONTAP 9.17.1 以降が実行されており、ストレージ システムが実行している ONTAP のバージョンのすべての要件を満たしている必要があります。


NOTE: ストレージ システムで ONTAP 9.17.1 以降が実行されていない場合、またはストレージ システムで実行されている ONTAP のバージョンのすべての要件を満たしていない場合は、この手順は使用できません。link:io-module-replace.html["I/Oモジュールの交換手順"]を使用する必要があります。

[role="tabbed-block"]
====
.ONTAP 9.17.1 または 9.18.1RC
--
* 障害が発生したクラスタとスロット4のHA I/Oモジュールを、同等のI/Oモジュールにホット スワップしています。I/Oモジュールのタイプは変更できません。
* 障害が発生したクラスタとHA I/Oモジュールを持つコントローラ（障害コントローラ）は、正常なパートナー コントローラをすでにテイクオーバーしている必要があります。I/Oモジュールに障害が発生した場合、テイクオーバーは自動的に実行されるはずです。
+
2ノードクラスタの場合、ストレージシステムはどちらのコントローラに障害が発生したI/Oモジュールがあるかを判別できないため、どちらかのコントローラがテイクオーバーを開始する可能性があります。ホットスワップは、障害が発生したI/Oモジュールを持つコントローラ（障害コントローラ）が正常なコントローラをテイクオーバーした場合にのみサポートされます。I/Oモジュールのホットスワップは、システムを停止させずに復旧する唯一の方法です。

+
障害のあるコントローラが正常なコントローラを正常に引き継いだかどうかを確認するには、  `storage failover show`指示。

+
故障したI/Oモジュールがどのコントローラにあるのか分からない場合は、  https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"] 。

* ストレージ システム構成では、スロット 4 にクラスタと HA I/O モジュールが 2 つではなく、クラスタと HA I/O モジュールが 1 つだけ配置されている必要があります。
* ストレージ システムは、2 ノード (スイッチレスまたはスイッチ) のクラスター構成である必要があります。
* ストレージシステムの他のすべてのコンポーネントが正常に動作している必要があります。正常に動作していない場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]。


--
.ONTAP 9.18.1GA以降
--
* クラスタ、HA、クライアントで使用されるポートの組み合わせが任意のスロットにあるイーサネットI/Oモジュールを、同等のI/Oモジュールとホット スワップしています。I/Oモジュールのタイプを変更することはできません。
+
ストレージまたはMetroClusterに使用されるポートを持つEthernet I/Oモジュールはホットスワップ対応ではありません。

* ストレージ システム（スイッチレスまたはスイッチ クラスタ構成）には、ストレージ システムでサポートされる任意の数のノードを含めることができます。
* クラスタ内のすべてのノードは、同じONTAPバージョン（ONTAP 9.18.1GA以降）を実行しているか、同じONTAPバージョンの異なるパッチ レベルを実行している必要があります。
+
クラスタ内のノードが異なるONTAPバージョンを実行している場合、これは混合バージョンのクラスタと見なされ、I/Oモジュールのホットスワップはサポートされません。



* ストレージ システム内のコントローラは、次のいずれかの状態になります：
+
** 両方のコントローラが起動して I/O（データの提供）を実行できます。
** テイクオーバーが障害が発生した I/O モジュールによって発生し、コントローラがそれ以外は正常に機能している場合、いずれかのコントローラがテイクオーバー状態になることがあります。
+
特定の状況では、ONTAPは、障害が発生したI/Oモジュールが原因で、いずれかのコントローラの自動テイクオーバーを実行できます。たとえば、障害が発生したI/Oモジュールにすべてのクラスタポートが含まれている場合（そのコントローラ上のすべてのクラスタリンクがダウンしている場合）、ONTAPは自動的にテイクオーバーを実行します。





* ストレージシステムの他のすべてのコンポーネントが正常に動作している必要があります。正常に動作していない場合は、この手順を続行する前にににお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]。


--
====