= 
:allow-uri-read: 


障害が発生したクラスターと HA I/O モジュールを安全に取り外せるように、ストレージ システムと I/O モジュール スロット 4 を準備します。

. 自身の適切な接地対策を行います
. 障害が発生したクラスターと HA I/O モジュールからケーブルを外します。
+
この手順の後半でケーブルを同じポートに再接続できるように、ケーブルに必ずラベルを付けてください。

. AutoSupportが有効になっている場合は、AutoSupportメッセージを呼び出してケースの自動作成を停止します。
+
`system node autosupport invoke -node * -type all -message MAINT=<number of hours down>h`

+
たとえば、次のAutoSupportメッセージは、自動ケース作成を 2 時間抑制します。

+
`node2::> system node autosupport invoke -node * -type all -message MAINT=2h`

. 自動ギブバックを無効にする:
+
.. 障害のあるコントローラのコンソールから次のコマンドを入力します。
+
`storage failover modify -node local -auto-giveback false`

.. 入力 `y`「自動ギブバックを無効にしますか?」というプロンプトが表示されたら、


. スロット 4 の障害が発生したクラスタと HA モジュールをサービスから削除し、電源をオフにして、取り外す準備をします。
+
.. 次のコマンドを入力します。
+
`system controller slot module remove -node _impaired_node_name_ -slot _slot_number_`

.. 入力 `y`「続行しますか?」というプロンプトが表示されたら
+
たとえば、次のコマンドは、ノード 2 (障害のあるコントローラ) のスロット 4 にあるモジュールを削除する準備を行い、安全に削除できることを示すメッセージを表示します。

+
[listing]
----
node2::> system controller slot module remove -node node2 -slot 4

Warning: IO_2X_100GBE_NVDA_NIC module in slot 4 of node node2 will be powered off for removal.

Do you want to continue? {y|n}: y

The module has been successfully removed from service and powered off. It can now be safely removed.
----


. 障害が発生したクラスタとスロット 4 の HA モジュールの電源がオフになっていることを確認します。
+
`system controller slot module show`

+
出力には次のように表示されるはずです `_powered-off_`スロット 4 の障害が発生したモジュールのステータス列に表示されます。


