= 設置に必要な機器
:allow-uri-read: 




== 設置に必要な機器

ストレージシステムを設置するには、次の機器および工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* NS224ストレージシェルフIDを設定するためのペーパークリップまたはボールペン
* No.2 プラスドライバ




== 吊り上げ時の注意事項

ストレージシステムとストレージシェルフは重量があります。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== ストレージシステムノオモミ

ストレージシステムを移動または持ち上げるときは、必要な予防措置を講じてください。

[role="tabbed-block"]
====
.A1K
--
A1Kストレージシステムの重量は最大28.5 kg（62.83ポンド）です。システムを持ち上げるには、2人で作業するか、油圧リフトを使用します。

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1Kリフティング警告アイコン]

--
.A70およびA90
--
A70ストレージ・システムまたはA90ストレージ・システムの重量は'最大68.8 kg（151.68ポンド）ですシステムを持ち上げるには、4人で作業するか、油圧リフトを使用します。

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90 and AFF A70 weight cautionアイコン]

--
====


=== 収納シェルフの重量

NS224ストレージシェルフの重量は最大30.29kg（66.78ポンド）です。ストレージシェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224の持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]

