= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF システム
--
AFF AシリーズシステムとAFF Cシリーズシステムは、仮想環境に特化した堅牢なスケールアウトプラットフォームを提供します。スタンドアロンシステムとして導入することも、NetApp ONTAP構成でハイパフォーマンス階層として導入することもできます。との詳細については、こちらをご覧くださいlink:https://www.netapp.com/aff-a-series/["AFF Aシリーズシステム"]link:https://www.netapp.com/aff-c-series/["AFF Cシリーズシステム"]。

AFF AシリーズおよびAFF Cシリーズシステムは、次のONTAPリリース以降でサポートされます。

ONTAP 9.16.1::
+
--
* AFF A20用
* AFF A30用
* AFF A50用
* AFF C30用
* AFF C60用
* AFF C80用


--
ONTAP 9.15.1::
+
--
* AFF A1K用
* AFF A70用
* AFF A90用


--
ONTAP 9.12.1P1::
+
--
* AFF A150
* AFF C250
* AFF C400
* AFF C800


--
ONTAP 9.10.1::
+
--
* AFF A900 の略


--
ONTAP 9.8::
+
--
* AFF A250


--
ONTAP 9.7::
+
--
* AFF A400
* AFF A800


--


--
.AFXシステム
--
AFX システムは、AI/ML アプリケーションを含む高性能 NAS および S3 ワークロードの厳しい要件を満たすように設計された分散型ソリューションを提供します。link:https://docs.netapp.com/us-en/ontap-afx/get-started/ontap-afx-storage.html["AFXシステムの詳細"^] 。

AFX システムは、次のONTAPリリース以降でサポートされます。

ONTAP 9.17.1::
+
--
* AFX 1K


--


--
.ASA r2システム
--
ASA r2 システムは、SAN のみを利用するお客様のニーズに合わせた簡素化されたエクスペリエンスを実現する、統合されたハードウェアおよびソフトウェア ソリューションを提供します。link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"^] 。

ASA R2システムは、次のONTAPリリース以降でサポートされます。

ONTAP 9.16.1::
+
--
* ASA A20
* ASA A30
* ASA A50
* ASA C30


--
ONTAP 9 .16.0::
+
--
* ASA A1K
* ASA A70
* ASA A90


--


--
.ASAシステム
--
ASA AシリーズおよびASA Cシリーズシステムは、シンプルで専用のSANエクスペリエンスを提供し、FCPまたはiSCSIプロトコルを使用して、エンタープライズのミッションクリティカルなデータベースやその他のSANワークロードに継続的なデータ可用性を提供します。link:https://www.netapp.com/asa/["ASAシステムの詳細"]です。

ASAシステムは、次のONTAPリリース以降でサポートされます。

ONTAP 9.13.1P1::
+
--
* ASA C250
* ASA C400
* ASA C800


--
ONTAP 9.13.1::
+
--
* ASA A150
* ASA A250
* ASA A400
* ASA A900


--
ONTAP 9.8::
+
--
* ASA AFF A250の略
* ASA AFF A800の略


--
ONTAP 9.7::
+
--
* ASA AFF A400の略


--


--
.FAS システム
--
FASシステムは、効率的でセキュアなセカンダリストレージを提供します。これは、階層化、バックアップ、ディザスタリカバリに最適な究極のソリューションです。link:https://www.netapp.com/data-storage/fas/["FASシステムに関する詳細情報"]です。

FASシステムは、次のONTAPリリース以降でサポートされます。

ONTAP 9.16.1::
+
--
* FAS50


--
ONTAP 9.15.1::
+
--
* FAS70
* FAS90


--
ONTAP 9.13.1::
+
--
* FAS2820


--
ONTAP 9.11.1::
+
--
* FAS9500


--
ONTAP 9.10.1P3::
+
--
* FAS9500


--
ONTAP 9.7::
+
--
* FAS2750
* FAS8300
* FAS8700 の場合


--


--
.ドライブシェルフ
--
ドライブ シェルフは、 NetApp AFF、AFX、 ASA、 FASシステム向けに特別に設計されており、デジタル変革に必要なパフォーマンス、復元力、柔軟性を実現します。

ドライブシェルフは、次のONTAPリリース以降で使用できます。

ONTAP 9.17.1::
+
--
* AFXシステム用NSX224シェルフ


--
ONTAP 9.16.1::
+
--
* SAS-3シェルフ用DCM3
* NS224とNSM100Bモジュール


--
ONTAP 9.6:: NSM100モジュールを搭載したNS224シェルフ


--
====