= 
:allow-uri-read: 


[role="tabbed-block"]
====
.AFF システム
--
AFF AシリーズモデルとCシリーズモデルは、仮想環境向けに構築された堅牢なスケールアウトプラットフォームで、独立したシステムとして導入することも、NetApp ONTAP構成のハイパフォーマンス階層として導入することもできます。link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["AFFシステムの詳細"]です。

.AFF A20、AFF A30、AFF A50
ONTAP 9.16.1以降で利用可能

.AFF C30、AFF C60
ONTAP 9.16.1以降で利用可能

.AFF A1K、AFF A70、およびAFF A90
ONTAP 9.15.1以降で利用可能

.AFF A150
ONTAP 9.13.1、ONTAP 9.12.1P1、ONTAP 9.11.1P8、ONTAP 9.10.1P12以降で利用可能

.AFF A900 の略
ONTAP 9.10.1以降で利用可能

.AFF A250およびAFF A800
ONTAP 9.8以降で利用可能

.AFF A400
ONTAP 9.7以降で利用可能

.AFF C250、AFF C400、AFF C800
ONTAP 9.12.1P1、ONTAP 9.13.1 GA以降で利用可能

--
.ASA r2システム
--
ASA R2システムは、ハードウェアとソフトウェアの統合ソリューションを提供し、SANのみのお客様のニーズに合わせてシンプルな操作性を実現します。link:https:://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA R2システムの詳細"]です。

.ASA A1K、ASA A70、ASA A90
ONTAP 9.16.0以降で利用可能

--
.ASAシステム
--
ASA AシリーズおよびCシリーズモデルは、SAN専用のシンプルなエクスペリエンスを提供し、FCPまたはiSCSIプロトコルを使用して、エンタープライズのミッションクリティカルなデータベースやその他のSANワークロードに継続的なデータ可用性を提供します。link:https:://www.netapp.com/data-storage/all-flash-san-storage-array["ASAシステムの詳細"]です。

.ASA A150、ASA A250、ASA A400、ASA A900
ONTAP 9.13.1以降で利用可能

.ASA C250、C400、C800
ONTAP 9.13.1P1以降で利用可能

--
.FAS システム
--
FASシステムは、効率的でセキュアなセカンダリストレージを提供します。これは、階層化、バックアップ、ディザスタリカバリに最適な究極のソリューションです。link:https:://www.netapp.com/data-storage/fas/["FASシステムに関する詳細情報"]です。

.FAS70およびFAS90
ONTAP 9.15.1以降で利用可能

.FAS9500
ONTAP 9.11.1、ONTAP 9.10.1P3以降で利用可能

.FAS8300とFAS700
ONTAP 9.7以降で利用可能

.FAS2820
ONTAP 9.13.1以降で利用可能

.FAS2700
ONTAP 9.13.1以降で利用可能

--
====