= 
:allow-uri-read: 


ONATPブートメニューから外部キーマネージャの設定をリストアします。

.作業を開始する前に
外部キー管理ツール（EKM）の設定をリストアするには、次の情報が必要です。

* 別のクラスタノードの/cfcard/kmip/servers.cfgファイルのコピー、または次の情報。
+
** KMIPサーバのアドレス。
** KMIPポート。
** 別のクラスタノードの/cfcard/kmip/certs/client.crtファイルのコピー、またはクライアント証明書。
** 別のクラスタノードまたはクライアントキーからの/cfcard/kmip/certs/client.keyファイルのコピー。
** 別のクラスタノードまたはKMIPサーバCAの/cfcard/kmip/certs/CA.pemファイルのコピー。




.手順
. コンソールケーブルをターゲットコントローラに接続します。
. ONTAPのブートメニューからオプション11を選択します。
+
.ブートメニューの例を表示します。
[%collapsible]
====
....

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 11
....
====
. プロンプトが表示されたら、必要な情報を収集したことを確認します。
+
.プロンプトの例を表示
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/certs/client.crt file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/client.key file? {y/n}
Do you have a copy of the /cfcard/kmip/certs/CA.pem file? {y/n}
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
....
====
+
.代わりにこれらのプロンプトが表示される場合があります
[%collapsible]
====
....
Do you have a copy of the /cfcard/kmip/servers.cfg file? {y/n}
Do you know the KMIP server address? {y/n}
Do you know the KMIP Port? {y/n}
....
====
. プロンプトが表示されたら、クライアントとサーバの情報を入力します。
+
.プロンプトを表示
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
Enter the client key (client.key) file contents:
Enter the KMIP server CA(s) (CA.pem) file contents:
Enter the server configuration (servers.cfg) file contents:
....
====
+
.例を示します
[%collapsible]
====
....
Enter the client certificate (client.crt) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the client key (client.key) file contents:
-----BEGIN RSA PRIVATE KEY-----
<key_value>
-----END RSA PRIVATE KEY-----

Enter the KMIP server CA(s) (CA.pem) file contents:
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----

Enter the IP address for the KMIP server: 10.10.10.10
Enter the port for the KMIP server [5696]:

System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
kmip_init: configuring ports
Running command '/sbin/ifconfig e0M'
..
..
kmip_init: cmd: ReleaseExtraBSDPort e0M
....
====
. リカバリプロセスが完了します。
+
.プロンプトの例を表示
[%collapsible]
====
....


System is ready to utilize external key manager(s).
Trying to recover keys from key servers....
Performing initialization of OpenSSL
Successfully recovered keymanager secrets.

....
.. ブートメニューからオプション1を選択して、ONTAPのブートを続行します。
+
....

***********************************************************************************
* Select option "(1) Normal Boot." to complete the recovery process.
*
***********************************************************************************


(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 1

....


====
. 自動ギブバックを無効にした場合はリストアします。
+
`storage failover modify -node local -auto-giveback true`

. AutoSupportが有効になっている場合は、次のコマンドを入力してケースの自動作成をリストアします。
+
`system node autosupport invoke -node * -type all -message MAINT=END`


