= 
:allow-uri-read: 


ノード 4 をラックに設置し、ノード 2 の接続をノード 4 に転送し、ノード 4 をブートする必要があります。ノード 2 のスペア、ルートに属するディスク、および node3 でそれよりも前に再配置されなかったルート以外のアグリゲートも再割り当てする必要があります。

node2 に同じバージョンの ONTAP 9 がインストールされていない場合は、 node4 をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに格納されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:prepare_for_netboot.html["ネットブートを準備"]

ただし、 node2 に同じバージョンまたはそれ以降のバージョンの Data ONTAP 9 がインストールされている場合は、ネットブートノード 4 を実行する必要はありません。

* 重要 * ：

* V シリーズシステム、またはストレージアレイに接続された FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、を完了する必要があります <<man_install4_Step1,手順 1.>> から <<man_install4_Step7,手順 7>>をクリックします <<man_install4_Step8,手順 8>> およびの手順に従ってください link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"] 必要に応じて、メンテナンスモードでコマンドを入力します。その後、このセクションに戻って手順を再開する必要があります <<man_install4_Step9,手順 9>>。
* ただし、ストレージディスクが搭載されたシステムをアップグレードする場合は、このセクション全体を完了してから、セクションに進んでください link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"]クラスタ・プロンプトでコマンドを入力します。


.手順
. [[man_install4_Step1] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| ノード 4 の配置先 | 作業 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step2,手順 2>>。 


| 同じシャーシを node3 と一緒に配置する | 手順 2 と 3 を省略して、に進みます <<man_install4_Step4,手順 4>>。 
|===
. [[man_install4_Step2]] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 と node3 が別々のシャーシにある場合は、 node4 を node2 と同じ場所に配置できます。node3 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. [[man_install4_Step4]] ケーブルノード 4 を接続し、ノード 2 からノード 4 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** _ インストールおよびセットアップ手順 _ または _ FlexArray 仮想化インストール要件およびリファレンス _ （ノード 4 プラットフォーム用）
** 該当するディスクシェルフガイドを参照してください
** ONTAP 9 ハイアベイラビリティ構成ガイド _
+
次の配線を行います。

** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート


+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカード / FC-VI カードまたはインターコネクト / FC-VI ケーブルの接続を node2 から node4 に移動する必要はありません。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| ノード 4 の構成 | 作業 


| ノード 3 と同じシャーシ | に進みます <<man_install4_Step8,手順 8>>。 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step6,手順 6>>。 
|===
. [man_install4_Step6]] ノード 4 の電源をオンにし 'Ctrl+C キーを押してブートを中断してブート環境プロンプトにアクセスします
+

NOTE: node4 をブートすると、次のメッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7] ステップ 6 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: * 警告 : 遅延を上書きしないでください。バッテリーの充電に失敗すると、データが失われる可能性があります。 *



. [[man_install4_Step8] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ディスクがあり、バックエンドストレージがない | 手順 9 から 14 を省略して、に進みます <<man_install4_Step15,手順 15>>。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
.. node4 の FC または UTA / UTA2 設定のセクションに移動し、セクションの作業を行います link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"] および link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"]必要に応じて、システムに適用されます。
.. このセクションに戻って、から始めて残りの手順を実行します <<man_install4_Step9,手順 9>>。


* 重要 * ： V シリーズシステムで Data ONTAP をブートする前に、オンボード FC ポート、 UTA / UTA2 オンボードポート、 UTA / UTA2 カードを再設定する必要があります。

|===
. [[man_install4_Step9] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. ストレージアレイ上のアレイ LUN に関連付けられたホストまたはボリュームグループの World Wide Port Name （ WWPN ；ワールドワイドポート名）値を変更する。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. スイッチベースのゾーニングを使用している場合は、新しい WWPN 値が反映されるようにゾーニングを調整します。
. 次のコマンドを入力し、出力を調べて、アレイ LUN が node4 に認識されていることを確認します。
+
「 sysconfig -v 」を使用します

+
各 FC イニシエータポートで認識されるすべてのアレイ LUN が表示されます。アレイ LUN が表示されない場合は、このセクションの後半で node2 から node4 にディスクを再割り当てすることはできません。

. Ctrl キーを押しながら C キーを押して ' ブート・メニューを表示し ' メンテナンス・モードを選択します
. [[man_install4_Step15]] メンテナンスモードのプロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. ONTAP のノード 4 を設定します。
+
「デフォルト設定」

. この構成で FDE を使用する場合 '`setenv.storageencryption.support` 変数は 'true' に設定する必要がありますまた 'node2 構成のロード後にブートループが発生しないように 'kmip.init.maxwait` 変数は 'off' に設定する必要があります
+
'etenv bootarg.storageencryption.support true

+
'etenv kmip.init.maxwait off

. ノード 4 にインストールされている ONTAP のバージョンが node2 にインストールされている ONTAP 9 と同じかそれ以降の場合は、次のコマンドを入力します。
+
「 boot_ontap menu

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 作業 


| ノード 4 に正しい ONTAP バージョンまたは現在の バージョンがない | に進みます <<man_install4_Step20,手順 20>>。 


| ノード 4 の ONTAP のバージョンが正しいか、最新のバージョンであることが必要です | に進みます <<man_install4_Step25,手順 25>>。 
|===
. [[man_install4_Step20]] 次のいずれかの操作を選択して、ネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP アドレスを使用する必要があります。アップグレードの実行中にデータ LIF の IP アドレスを使用しないでください。データ LIF が停止する可能性があります。

+
[cols="30,70"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで「 ifconfig e0M -auto 」コマンドを入力すると、接続が自動的に設定されます 


| 実行されていません | ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。 ifconfig e0M -addr= <filer_addr> mask= <netmask> -gw= <gateway> dns_addr> domain= <dns_domain> `<filer_addr>`<netmask>` はストレージシステムのネットワークマスクです。「 <gateway>` 」は、ストレージシステムのゲートウェイです。「 <dns_addr> 」は、ネットワーク上のネームサーバの IP アドレスです。「 <dns_domain> 」は、 Domain Name Service （ DNS ；ドメインネームサービス）ドメイン名です。このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はなく、サーバのホスト名だけを指定します。* 注 * ：インターフェイスによっては、他のパラメータが必要になる場合があります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。 
|===
. ノード 4 でネットブートを実行します。
+
[cols="30,70"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://<web_server_ip/path_to_webaccessible_directory>/netboot/kernel` 


| その他すべてのシステム | netboot\http://<web_server_ip/path_to_webaccessible_directory/ontap_version>_image.tgz` 
|===
+
「 <path_the_web-accessible_directory> 」は、「 <ONTAP_version>_image.tgz 」をダウンロードした場所を指します link:prepare_for_netboot.html#man_netboot_Step1["手順 1."] の項で、 netboot_ の準備を参照してください。

+

NOTE: トランクを中断しないでください。

. 起動メニューから 'option(7) Install new software first ’を選択します
+
このメニューオプションを選択すると、新しい Data ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
次のメッセージは無視してください。

+
` この手順は HA ペアの無停止アップグレードではサポートされていません

+
コントローラのアップグレードではなく、 Data ONTAP による環境の無停止アップグレードも記録されています。

. [man_install4_step23]] 手順を続行するかどうかを確認するメッセージが表示されたら、 y を入力します。パッケージの入力を求められたら、次の URL を入力します。
+
http://<web_server_ip/path_to_web-accessible_directory/ontap_version>_image.tgz` にアクセスします

. 次の手順を実行します。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. [man_install4_Step25]] ブートメニューからメンテナンスモード「 5 」を選択し ' ブートを続行するように求められたら 'y' を入力します
. [[man_install4_Step26]] 続行する前に、に進みます link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"] ノードの FC ポートまたは UTA / UTA2 ポートに必要な変更を加えるため。これらのセクションで推奨される変更を行ってからノードをリブートし、メンテナンスモードに切り替えます。
. 次のコマンドを入力し、出力を調べて node4 のシステム ID を特定します。
+
「ディスクショー - A` 」

+
次の例に示すように、ノードのシステム ID 、およびそのディスクに関する情報が表示されます。

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. ノード 2 のスペア、ルートに属するディスク、および前のセクションでノード 3 に再配置されなかったルート以外のアグリゲートを再割り当てします link:relocate_non_root_aggr_node2_node3.html["ルート以外のアグリゲートを node2 から node3 に再配置します。"]：
+
[cols="35,65"]
|===
| ディスクタイプ | 実行するコマンド 


| 共有ディスクの場合 | `Disk reassign -s `<node2 _ssysid>-d <node4 sysid>-p node3 <sysid>` 


| 共有なし | 「ディスクの再割り当て」 -s 「 <node2 _sysid>-d <node4 sysid>` 」 
|===
+
<node2 _sysid>` の値には、で取得した情報を使用します link:record_node2_information.html#man_node2_info_step10["手順 10"] をクリックします。`<node4 sysid>` の場合は、で取得した情報を使用します <<man_install4_step23,手順 23>>。

+

NOTE: -p オプションは ' 共有ディスクが存在する場合にのみ保守モードで必要です

+
「 disk reassign 」コマンドを使用すると、「 <node2 _sysid> 」が現在の所有者であるディスクだけが再割り当てされます。

+
次のメッセージが表示されます。

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
ディスクの再割り当てを中止するかどうかを尋ねられたら 'n' を入力します

+
ディスクの再割り当てを中止するように求められた場合は、次の手順に従って一連のプロンプトを回答に出力する必要があります。

+
.. 次のメッセージが表示されます。
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. 「 y 」と入力して続行します。
+
次のメッセージが表示されます。

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. ディスク所有権の更新を許可するには 'y' を入力します


. 外付けディスクが搭載されたシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ A800 システムなど）にアップグレードする場合は、 node4 を root として設定し、 node2 のルートアグリゲートからブートするようにします。
+

WARNING: * 警告：次の手順を記載された順序で実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。 *

+
次の手順では、 node4 に node2 のルートアグリゲートからブートするよう設定しています。

+
.. node2 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node2 アグリゲートの全体的なステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node2 アグリゲートをオンラインにします。
+
'aggr_online root_aggr_from_<node2>] を選択します

.. ノード 4 が元のルートアグリゲートからブートしないようにします。
+
'aggr offline <root_aggr_on_node4 >`

.. node2 のルートアグリゲートを node4 の新しいルートアグリゲートとして設定します。
+
「 aggr options aggr_from_<node2> root 」のように指定します



. 次のコマンドを入力し、出力を確認して、コントローラとシャーシが「 ha 」として設定されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

+
コントローラとシャーシが「 ha 」として設定されていない場合は、次のコマンドを使用して設定を修正します。

+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください。

+
MetroCluster 構成を使用している場合は、次のコマンドを使用して設定を修正します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. node4 にあるメールボックスを破棄します。
+
「マイボックス破壊ローカル」

. メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. ノード 3 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. ノード 4 で、ブート環境プロンプトの日付を確認します。
+
「日付」

. 必要に応じて、 node4 に日付を設定します。
+
'Set date <mm/dd/yyyy>`

. ノード 4 で、ブート環境プロンプトの時刻を確認します。
+
「時間」

. 必要に応じて、 node4 に時間を設定します。
+
時刻を設定します

. パートナーシステム ID が、に示すように正しく設定されていることを確認します <<man_install4_Step26,手順 26>> オプション（ Option ）の下。
+
printenv partner-sysid

. 必要に応じて、 node4 にパートナーシステム ID を設定します。
+
getenv partner-sysid <node3 sysid>`

+
.. 設定を保存します。
+
'aveenv



. ブート環境プロンプトでブートメニューを入力します。
+
「 boot_ontap menu

. ブート・メニューで ' プロンプトに「 6 」と入力して 'Option *(6) Update flash from backup config * を選択します
+
次のメッセージが表示されます。

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. プロンプトで「 y 」と入力します。
+
ブートが正常に続行され、システム ID の不一致を確認するように求められます。

+

NOTE: 不一致の警告が表示される前にシステムが 2 回リブートする可能性があります。

. 不一致を確認します。正常にブートする前に、ノードの 1 回のリブートが完了することがあります。
. ノード 4 にログインします。

