= 


アグリゲートを node2 から node3 に再配置したら、 node2 によって所有されている NAS データ LIF を node3 に移動する必要があります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 3 からノード 4 に LIF を移動し、ノード 4 がオンラインになったあとで、 LIF が正常に機能しており、適切なポートに配置されていることを確認する必要があります。

.手順
. [[step1] ノードごとに次のコマンドを入力し、出力をキャプチャして、 node2 が所有するすべての NAS データ LIF を一覧表示します。
+
'network interface show -data-protocol nfs|cifs -home-node <node2 >`

+
次の例は、 node2 のコマンドの出力を示しています。

+
[listing]
----
cluster::> network interface show -data-protocol nfs|cifs -home-node node2
              Logical     Status      Network             Current  Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node     Port     Home
 -----------  ----------  ----------  ------------------  -------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node2    a0a      true
              data1       up/up       10.63.0.50/18       node2    e0c      true
              rads1       up/up       10.63.0.51/18       node2    e1a      true
              rads2       up/down     10.63.0.52/24       node2    e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node2    e0c      true
              lif2        up/up       172.17.176.121/24   node2    e1a      true
----
. [[step2]] 次のいずれかの操作を実行します。
+
[cols="35,65"]
|===
| ノード 2 の条件 | 作業 


| インターフェイスグループまたは VLAN が設定されている | に進みます <<man_move_lif_2_3_step3,手順 3>>。 


| インターフェイスグループまたは VLAN が設定されていない | 手順 3 を省略して、に進みます <<man_move_lif_2_3_step4,手順 4>>。 
|===
. [man_move_lif_2_3_step3] 次の手順を実行して、 node2 のインターフェイスグループおよび VLAN でホストされている NAS データ LIF を移行します。
+
.. [[man_move_lif_2_3_substpa]] ノード 2 のインターフェイスグループでホストされているすべてのデータ LIF を、同じネットワーク上の LIF をホストできるノード 3 のポートに移行するには、各 LIF に対して 1 回、次のコマンドを入力します。
+
` network interface migrate -vserver <Vserver_name> -lif <lif_name> -destination-node <node3 > – destination-port <netport | ifgrp> 」の形式で指定します

.. LIF のホームポートとホームノードを変更します <<man_move_lif_2_3_substepa,手順 a>> 各ノードについて次のコマンドを 1 回入力して、 LIF を現在ホストしているポートとノードに接続します。
+
` network interface modify -vserver <Vserver_name> -lif <lif_name> -home-node <node3 > -home-port <netport | ifgrp> 」の形式で指定します

.. [man_move_lif_2_3_substpc ]] node2 上の VLAN でホストされている LIF を、 node2 上のポートにノード 3 上のポートに移行します。その際、各 LIF に対して 1 回、次のコマンドを入力して、 VLAN と同じネットワーク上の LIF をホストできます。
+
` network interface migrate -vserver <Vserver_name> -lif <lif_name> -destination-node <node3 > – destination-port <netport | ifgrp> 」の形式で指定します

.. LIF のホームポートとホームノードを変更します <<man_move_lif_2_3_substepc,サブステップ c>> LIF をホストしているポートとノードに対して次のコマンドを 1 回入力します。
+
` network interface modify -vserver <Vserver_name> -lif <lif_name> -home-node <node3 > -home-port <netport | ifgrp> 」の形式で指定します



. [man_move_lif_2_3_step4] 次のいずれかの操作を実行します
+
[cols="35,65"]
|===
| クラスタの設定対象 | 作業 


| NAS | - 完了しました <<man_move_lif_2_3_step5,手順 5>> から <<man_move_lif_2_3_step8,手順 8>>。 


| SAN | 手順 5 から 8 をスキップし、完了します <<man_move_lif_2_3_step9,手順 9>>。 


| NAS と SAN の両方 | - 完了しました <<man_move_lif_2_3_step5,手順 5>> から <<man_move_lif_2_3_step9,手順 9>>。 
|===
. [[man_move_lif_2_3_step5] プラットフォームで同じでないデータポートがある場合は、ブロードキャストドメインにポートを追加します。
+
「 network port broadcast-domain add-ports -ipspace <IPspace_name> -broadcast-domain mgmt -ports <node:port>` 」のように指定します

+
次の例は、ノード「 6280 」のポート「 e0a 」とノード「 8060-1 」のポート「 e0i 」を IPspace 「 Default 」のブロードキャストドメイン「 mgmt 」に追加します。

+
[listing]
----
cluster::> network port broadcast-domain add-ports -ipspace Default
           -broadcast-domain mgmt -ports 6280-1:e0a, 8060-1:e0i
----
. [[step6] それぞれの LIF に対して次のコマンドを 1 回入力して、各 NAS データ LIF を node3 に移行します。
+
` network interface migrate -vserver <Vserver_name> -lif <lif_name> -destination-node <node3 > -destination-port <netport | ifgrp> 」の形式で指定します

. [[step7] 両方のノードで次のコマンドを入力し、 NAS LIF が正しいポートに移動されていること、および LIF のステータスが up になっていることを確認します。
+
network interface show -curr-node <node3 > -data-protocol cifs | nfs ’

. [[man_move_lif_2_3_step8] いずれかの LIF が停止している場合は、各 LIF に対して 1 回次のコマンドを入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「 network interface modify -vserver <Vserver_name> -lif <LIF_NAME> -status-admin up 」という形式になります

. [man_move_lif_2_3_step9] インターフェイスグループまたは VLAN が設定されている場合は、次の手順を実行します。
+
.. インターフェイスグループから VLAN を削除します。
+
「 network port vlan delete -node <node_name > -port <ifgrp> -vlan-id <vlan_ID> 」のように指定します

.. 次のコマンドを入力し、その出力を調べて、ノードにインターフェイスグループが設定されているかどうかを確認します。
+
「 network port ifgrp show -node <node_name > -ifgrp <ifgrp_name> -instance 」の形式で指定します

+
次の例に示すように、ノードのインターフェイスグループ情報が表示されます。

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node2
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: MAC_address
    ort Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. ノードにインターフェイスグループが設定されている場合は、インターフェイスグループの名前とグループに割り当てられているポートを記録し、各ポートについて次のコマンドを 1 回入力してポートを削除します。
+
「 network port ifgrp remove-port -node <node_name > -ifgrp <ifgrp_name> -port <port_name> 」の形式で指定します




