= 


正しく設定されるようにするには、 HA ペアを有効にする必要があります。さらに、 node3 と node4 が相互のストレージにアクセスできること、およびクラスタ内の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、 node3 が node1 のアグリゲートを所有しており、 node4 が node2 のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認する必要があります。

.手順
. いずれかのノードで次のコマンドを入力して、ストレージフェイルオーバーを有効にします。
+
'storage failover modify -enabled true -node <node3 >`

. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 次のいずれかを実行します。
+
|===
| クラスタの種類 | 説明 


| 2 ノードクラスタ | どちらかのノードで cluster ha modify -configured true コマンドを入力して ' クラスタの高可用性を有効にします 


| 3 ノード以上のクラスタ | に進みます <<man_ensure_setup_Step4,手順 4>>。 
|===
. [[man_ver_setup_Step4]] 次のコマンドを入力して、 node3 と node4 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを入力し、出力を調べて、 node3 と node4 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを入力し、出力を調べて、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 または node4 に、クラスタ内の他のノードがホーム所有するデータ LIF がある場合は、「 network interface revert 」コマンドを使用して、データ LIF をホーム所有者にリバートします。

. ノード 3 がノード 1 のアグリゲートを所有していること、およびノード 4 がノード 2 のアグリゲートを所有していることを確認します。
+
「 storage aggregate show-owner-name <node3 > 'storage aggregate show-owner-name <node4 > 」という形式で表示されます

. オフラインになっているボリュームがないかを確認します。
+
volume show -node <node3 > -state offline `volume show -node <node4 > -state offline`

. オフラインのボリュームがある場合は、で取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html#step19d["手順 19 （ d ）"] で、各ボリュームに対して次のコマンドを 1 回入力して、アップグレードの準備をし、必要に応じてオフラインのボリュームをオンラインにします。
+
'volume online -vserver <vserver-name> -volume <volume_name>`

. ノードごとに次のコマンドを入力して、新しいノード用の新しいライセンスをインストールします。
+
'system license add - license-code <license_code, license_code, license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、ライセンスキーごとにカンマで区切って複数ずつ追加することもできます。

. 構成に NetApp Storage Encryption （ NSE ）を使用していた場合は、「 kmip.init.maxwait` 」変数を「 off 」にして「 etenv bootarg storageencryption.support 」コマンドを「 true 」に設定します（を参照） link:install_boot_node3.html#step16["手順 16"] of _ Install and boot node3 _ ）では、変数をリセットする必要があります。 `set diag ； systemshell -node <node-name> command sudo kenv -u -p kmip.init.maxwait`
. 元のノードから古いライセンスをすべて削除するには、次のいずれかのコマンドを入力します。
+
'system license clean-up-unused -expired 'system license delete -serial-number <Node_serial_number> -package <license_package> です

+
** 期限切れのライセンスをすべて削除するには、次のように入力します
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除するには、次のように入力し
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを入力します。
+
「 system license delete -serial-number <node1 -serial-number> -package * 「 system license delete -serial-number <node2 -serial-number> -package *

+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します



. 次のコマンドを入力し、出力を調べて、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
でキャプチャした出力と比較することを推奨します link:prepare_nodes_for_upgrade.html#step30["手順 30"] で、ノードをアップグレードする準備をしています。

. 両方のノードで次のコマンドを実行して、 SP を設定します。
+
「 system service-processor network modify -node <node-name> 」のように指定します

+
に進みます link:other_references.html["参考資料"] SP の詳細については ' システム管理リファレンスにリンクし '_System ONTAP 9 コマンド：マニュアルページリファレンスにリンクし 'system service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードの 1 つで次の操作を実行します。
+
.. 次のコマンドを入力して、 advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. 次のコマンドを入力します。
+
「 storage failover modify -node <node-name> -CIFS-NDO -duration default | medium | low 」

+
*** 処理の 50 ～ 75 パーセントが 4 KB 以下のワークロードがある場合は、「 m edium 」と入力します。
*** システムのワークロードが 75% ～ 100% の場合は 'low' と入力します


.. 次のコマンドを入力して、 admin レベルに戻ります。
+
「特権管理者」

.. システムをリブートして、変更が有効になっていることを確認します。


. 新しいノードにスイッチレスクラスタをセットアップする場合は、に進みます link:other_references.html["参考資料"] ネットワークサポートサイトへのリンクをクリックし、 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、の手順を実行します link:set_up_storage_encryption_new_controller.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の手順を実行します 。
