= 


ノード 1 をシャットダウンして撤去するには、そのクラスタネットワークポート、管理ポート、および FC ポートとその NVRAM システム ID に関する情報を事前に記録しておく必要があります。この情報は、ノード 1 をノード 3 にマッピングし、ディスクを再割り当てするときに、手順で必要になります。

.手順
. [[step1] 次のコマンドを入力し、その出力を取得します。
+
「 network route show 」と表示されます

+
次の例のような出力が表示されます。

+
[listing]
----
 cluster::> network route show

 Vserver        Destination    Gateway      Metric
  -------------- -------------- ----------- -------
  iscsi vserver  0.0.0.0/0      10.10.50.1  20
  node1          0.0.0.0/0      10.10.20.1  10
  ....
  node2          0.0.0.0/0      192.169.1.1 20
----
. 次のコマンドを入力し、出力をキャプチャします。
+
vserver services name-service dns show

+
次の例のような出力が表示されます。

+
[listing]
----
 cluster::> vserver services name-service dns show
                                                               Name
 Vserver        State     Domains                              Servers
 -------------- --------- ------------------------------------ ---------------
 node 1 2       enabled   alpha.beta.gamma.netapp.com          10.10.60.10,
                                                               10.10.60.20
 vs_base1       enabled   alpha.beta.gamma.netapp.com,         10.10.60.10,
                          beta.gamma.netapp.com,               10.10.60.20
 ...
 ...
 vs peer1        enabled  alpha.beta.gamma.netapp.com,         10.10.60.10,
                          gamma.netapp.com                     10.10.60.20
----
. [man_record_node1_step3] どちらかのコントローラで次のコマンドを入力して、ノード管理ポートとクラスタネットワークを特定します。
+
network interface show -curr-node <node1> -role cluster 、 intercluster 、 node-mgmt 、 cluster-mgmt

+
次の例に示すように、クラスタ内のノードについて、クラスタ LIF 、クラスタ間 LIF 、ノード管理 LIF 、およびクラスタ管理 LIF が表示されます。

+
[listing]
----
 cluster::> network interface show -curr-node <node1>
            -role cluster,intercluster,node-mgmt,cluster-mgmt

              Logical       Status     Network            Current  Current Is
  Vserver     Interface     Admin/Oper Address/Mask       Node     Port    Home
  ----------- ------------- ---------- ------------------ -------- ------- ----
  vserver1
              cluster mgmt   up/up     192.168.x.xxx/24   node1    e0c     true
  node1
              intercluster   up/up     192.168.x.xxx/24   node1    e0e     true
              clus1          up/up     169.254.xx.xx/24   node1    e0a     true
              clus2          up/up     169.254.xx.xx/24   node1    e0b     true
              mgmt1          up/up     192.168.x.xxx/24   node1    e0c     true
 5 entries were displayed.
----
+

NOTE: システムにクラスタ間 LIF がない可能性があります。

. のコマンドの出力に情報を記録します <<man_record_node1_step3,手順 3>> をクリックしてください link:map_ports_node1_node3.html["ポートを node1 から node3 にマッピングします"]。
+
出力情報は、新しいコントローラポートを古いコントローラポートにマッピングするために必要です。

. node1 で次のコマンドを入力します。
+
network port show -node <node1> -type physical`

+
次の例に示すように、ノードの物理ポートが表示されます。

+
[listing]
----
 sti8080mcc-htp-008::> network port show -node sti8080mcc-htp-008 -type physical

 Node: sti8080mcc-htp-008

                                                                  Ignore
                                            Speed(Mbps)  Health   Health
 Port  IPspace  Broadcast Domain Link MTU   Admin/Oper   Status   Status
 ----  -------  ---------------- ---- ----  -----------  -------  -------
 e0M   Default  Mgmt             up   1500  auto/1000    healthy  false
 e0a   Default  Default          up   9000  auto/10000   healthy  false
 e0b   Default  -                up   9000  auto/10000   healthy  false
 e0c   Default  -                down 9000  auto/-       -        false
 e0d   Default  -                down 9000  auto/-       -        false
 e0e   Cluster  Cluster          up   9000  auto/10000   healthy  false
 e0f   Default  -                up   9000  auto/10000   healthy  false
 e0g   Cluster  Cluster          up   9000  auto/10000   healthy  false
 e0h   Default  Default          up   9000  auto/10000   healthy  false
 9 entries were displayed.
----
. ポートとそのブロードキャストドメインを記録します。
+
ブロードキャストドメインは、あとで手順の新しいコントローラの新しいポートにマッピングする必要があります。

. node1 で次のコマンドを入力します。
+
「 network fcp adapter show -node <node1> 」のように表示されます

+
次の例に示すように、ノードの FC ポートが表示されます。

+
[listing]
----
 cluster::> fcp adapter show -node <node1>
                      Connection  Host
 Node         Adapter Established Port Address
 ------------ ------- ----------- ------------
 node1
               0a     ptp         11400
 node1
               0c     ptp         11700
 node1
               6a     loop        0
 node1
               6b     loop        0
 4 entries were displayed.
----
. ポートを記録します。
+
出力情報は、手順の後半で新しいコントローラの新しい FC ポートをマッピングするために必要です。

. まだ設定していない場合は、次のコマンドを入力して、ノード 1 でインターフェイスグループまたは VLAN が設定されているかどうかを確認します。
+
「 network port ifgrp show 」のように表示されます

+
「 network port vlan show 」と表示されます

+
このセクションの情報を使用します link:map_ports_node1_node3.html["ポートを node1 から node3 にマッピングします"]。

. 次のいずれかを実行します。
+
[cols="60,40"]
|===
| 状況 | 作業 


| セクションに NVRAM システム ID 番号を記録しました link:prepare_nodes_for_upgrade.html["アップグレードのためのノードを準備"]。 | 次のセクションに進みます。 link:retire_node1.html["ノード 1 を撤去"]。 


| セクションに NVRAM システム ID 番号が記録されていませんでした link:prepare_nodes_for_upgrade.html["アップグレードのためのノードを準備"] | - 完了しました <<man_record_node1_step11,手順 11>> および <<man_record_node1_step12,手順 12>> に進みます link:retire_node1.html["ノード 1 を撤去"]。 
|===
. [[man_record_node1_step11]] どちらかのコントローラで次のコマンドを入力します。
+
「 system node show -instance -node <node1> 」のように表示されます

+
次の例に示すように、 node1 に関する情報が表示されます。

+
[listing]
----
 cluster::> system node show -instance -node <node1>
                              Node: node1
                             Owner:
                          Location: GDl
                             Model: FAS6240
                     Serial Number: 700000484678
                         Asset Tag: -
                            Uptime: 20 days 00:07
                   NVRAM System ID: 1873757983
                         System ID: 1873757983
                            Vendor: NetApp
                            Health: true
                       Eligibility: true
----
. [[man_record_node1_step12]] セクションで使用する NVRAM システム ID 番号を記録します link:install_boot_node3.html["node3 をインストールしてブートします"]。

