= 


ノード 3 をラックに設置し、ノード 1 の接続をノード 3 に転送し、ノード 3 をブートして、 ONTAP をインストールする必要があります。そのあとで、ノード 1 のスペアディスク、ルートボリュームに属するディスク、およびルート以外のアグリゲートを node2 に再割り当てする必要があります。

ノード 1 にインストールされている ONTAP 9 のバージョンが異なる場合は、ノード 3 をネットブートする必要があります。node3 のインストールが完了したら、 Web サーバに保存されている ONTAP 9 イメージからブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。を参照してください link:prepare_for_netboot.html["ネットブートを準備"]。

ただし、ノード 1 にインストールされている ONTAP 9 のバージョンが同じかそれ以降である場合は、ノード 3 をネットブートする必要はありません。


NOTE: * 重要：ストレージアレイに接続された V シリーズシステム、またはストレージアレイに接続された FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、この作業を完了する必要があります <<man_install3_step1,手順 1.>> から <<man_install3_step5,手順 5>>をクリックします <<man_install3_step6,手順 6>> およびの手順に従ってください link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および  必要に応じて、保守モードでコマンドを入力します。その後、このセクションに戻ってからを使用して再開する必要があります <<man_install3_step7,手順 7>>。ただし、ストレージディスクが搭載されたシステムをアップグレードする場合は、このセクション全体を実行し、に進みます link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および クラスタ・プロンプトでコマンドを入力します。

.手順
. [[man_install3_step1] ノード 3 のラックスペースがあることを確認します。
+
ノード 1 とノード 2 が別々のシャーシに搭載されている場合は、ノード 3 をノード 1 と同じラックの場所に設置できます。ただし、 node1 が node2 の同じシャーシに設置されている場合は、 node3 を専用のラックスペースに配置する必要があります。その場合は、 node1 の場所に近い場所に配置することを推奨します。

. [[step2] ノードモデルの _ インストールおよびセットアップ手順 _ に従って、ラックにノード 3 をインストールします。
+

NOTE: 両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 と node3 をシャーシに設置します。そうしないと、ノードをブートしたときにノードがデュアルシャーシ構成と同じように動作し、 node4 をブートした場合、ノード間のインターコネクトは稼働しません。

. [[step3]] ケーブルノード 3 を接続し、ノード 1 からノード 3 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** _ インストールおよびセットアップ手順 _ または _ FlexArray 仮想化インストール要件およびリファレンス _ （ node3 プラットフォーム用）
** 該当するディスクシェルフガイドを参照してください
** ONTAP 9 ハイアベイラビリティ構成ガイド _


+
次の配線を行います。

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカードまたはクラスタインターコネクトケーブルの接続を node1 から node3 に移動する必要はない場合があります。MetroCluster 構成の場合、 FC-VI ケーブルの接続を node1 から node3 に移動する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. [[man_install3_step4]] ノード 3 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 もリブートします。ただし、 node4 のブートはあとで破棄することができます。

+

NOTE: node3 をブートすると、次の警告メッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]] で警告メッセージが表示される場合 <<man_install3_step4,手順 4>>を使用して、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

NOTE: * 注意 * ：遅延は無視しないでください。バッテリーの充電に失敗すると、データが失われるおそれがあります。



. [[man_install3_step6] 次のいずれかの操作を実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ディスクがあり、バックエンドストレージがない | 手順 7 から 12 を省略して、に進みます <<man_install3_step13,手順 13>>。 


| は、 V シリーズシステム、または FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムです  a| 
.. に進みます link:set_fc_uta_uta2_config_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"] をクリックし、サブセクションを完了します  および 必要に応じて、システムに適用されます。
.. このセクションに戻って、から始めて残りの手順を実行します <<man_install3_step7,手順 7>>。


* 重要 * ： V シリーズまたは FlexArray 仮想化ソフトウェアで ONTAP をブートする前に、オンボード FC ポート、 CNA オンボードポート、 CNA カードを再設定する必要があります。

|===
. [man_install3_step7] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
システムにテープ SAN がある場合は、イニシエータをゾーニングする必要があります。手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. [man_install3_step8] FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. [[man_install3_step9] ストレージアレイのアレイ LUN に関連付けられたホストまたはボリュームグループでの World Wide Port Name （ WWPN ；ワールドワイドポート名）の値を変更します。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. [man_install3_step10] ：構成でスイッチベースのゾーニングを使用している場合は、ゾーニングを調整して新しい WWPN 値を反映させます。
. [[man_install3_step11]] アレイ LUN が node3 に表示されることを確認します。
+
「 sysconfig -v 」を使用します

+
各 FC イニシエータポートで認識されるすべてのアレイ LUN が表示されます。アレイ LUN が表示されない場合は、このセクションで後述する node1 から node3 にディスクを再割り当てすることはできません。

. [[man_install3_step12]] Ctrl+C キーを押してブートメニューを表示し、メンテナンスモードを選択します。
. [[man_install3_step13]] メンテナンスモードのプロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. [[man_install3_step14]] 次のいずれかの操作を実行します
+
[cols="35,65"]
|===
| アップグレード後のシステムの構成 | 作業 


| デュアルシャーシ構成（コントローラが別々のシャーシに搭載されている場合） | に進みます <<man_install3_step15,手順 15>>。 


| シングルシャーシ構成（コントローラが同じシャーシに搭載されている場合）  a| 
.. コンソールケーブルを node3 から node4 に切り替えます。
.. ノード 4 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のコントローラが同じシャーシ内にある場合は、電源はすでにオンになっているはずです。

+
* 注： node4 はブート環境のプロンプトのままにします。その場合はの node4 に戻ります link:install_boot_node4.html["ノード 4 をインストールしてブートします"]。

.. に警告メッセージが表示される場合は <<man_install3_step4,手順 4>>の手順に従ってください <<man_install3_step5,手順 5>>
.. コンソールケーブルを node4 から node3 に戻します。
.. に進みます <<man_install3_step15,手順 15>>。


|===
. [[man_install3_step15]] ONTAP の node3 の設定：
+
「デフォルト設定」

. [man_install3_step16]] NetApp Storage Encryption （ NSE ）がこの構成で使用されている場合、「 setenv bootarg.storageencryption.support 」コマンドは「 true 」に設定する必要があります。また、 node1 構成のロード後にブートループが発生しないように、「 kmip.init.maxwait` variable needs to be 'off' 」に設定する必要があります。
+
'etenv bootarg.storageencryption.support true

+
'etenv kmip.init.maxwait off

. [[man_install3_step17]] node3 にインストールされている ONTAP のバージョンが、 node1 にインストールされている ONTAP 9 のバージョンと同じかそれ以降である場合は、ディスクをリストして新しい node3 に再割り当てします。
+
「 boot_ontap 」

+

WARNING: * 警告 * ：この新しいノードが他のクラスタまたは HA ペアで使用されたことがある場合は、次に進む前に「 wipeconfig 」を実行する必要があります。これを行わないと、サービスの停止やデータの損失が発生する可能性があります。交換用コントローラを以前に使用したことがある場合、特にコントローラが ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。

. [[man_install3_step18]] CTRL-C を押してブートメニューを表示します。
. [[man_install3_step19]] 次のいずれかの操作を実行します
+
[cols="35,65"]
|===
| アップグレードするシステム | 作業 


| Does _ not_ have the correct or current ONTAP version on node3 （ノード 3 に正しい バージョンまたは現在の バージョンがありません | に進みます <<man_install3_step20,手順 20>>。 


| ノード 3 に正しいバージョンまたは最新バージョンの ONTAP があること | に進みます <<man_install3_step25,手順 25>>。 
|===
. [[man_install3_step20]] 次のいずれかの操作を実行して、ネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。データ LIF IP を使用しないでください。使用していると、アップグレードの実行中にデータが停止する可能性があります。

+
[cols="35,65"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで「 ifconfig e0M -auto 」コマンドを入力すると、接続が自動的に設定されます 


| 実行されていません | ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。 ifconfig e0M -addr= <filer_addr> -mask= <netmask> -gw= <gateway> -dns= <dns_addr> domain= <dns_domain> `<filer_addr>`<netmask>` はストレージシステムのネットワークマスクです。「 <gateway>` 」は、ストレージシステムのゲートウェイです。「 <dns_addr> 」は、ネットワーク上のネームサーバの IP アドレスです。「 <dns_domain> 」は、 Domain Name Service （ DNS ；ドメインネームサービス）ドメイン名です。このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はなく、サーバのホスト名だけを指定します。* 注 * ：インターフェイスによっては、他のパラメータが必要になる場合があります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。 
|===
. [[man_install3_step21] ノード 3 でネットブートを実行します。
+
[cols="35,65"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://<web_server_ip>/<path_to_webaccessible_directory>/netboot/kernel` 


| その他すべてのシステム | netboot\http://<web_server_ip>/<path_to_webaccessible_directory>/<ontap_version>_image.tgz` 
|===
+
「 <path_the_web-accessible_directory> 」は、「 <ONTAP_version>_image.tgz 」をダウンロードした場所を指します link:prepare_for_netboot.html#man_netboot_Step1["手順 1."] の項で、 netboot_ の準備を参照してください。

+

NOTE: トランクを中断しないでください。

. [man_install3_step22]] ブートメニューから、オプション * （ 7 ） Install new software * first を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+

NOTE: 次のメッセージは無視してください。

+
[listing]
----
This procedure is not supported for Non-Disruptive Upgrade on an HA pair.
----
+
コントローラのアップグレードではなく、 ONTAP による環境の無停止アップグレードも記録されています。

+

NOTE: 新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境はすべての ONTAP リリースに対応しています。

. [man_install3_step23]] 手順を続行するかどうかを確認するメッセージが表示されたら 'y`' と入力し ' パッケージのプロンプトが表示されたら ' 次の URL を入力します
+
http://<web_server_ip>/<path_to_web-accessible_directory>/<ontap_version_image>.tgz` にアクセスします

. [[man_install3_step24]] 次の手順を実行します
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. [man_install3_step25]] '*(5) Maintenance mode boot を選択しますこれには '5` を入力し ' ブートを続行するように求められたら 'y' を入力します
. [[man_install3_step26]] 続行する前に、に進みます link:set_fc_uta_uta2_config_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"] ノードの FC ポートまたは UTA / UTA2 ポートに必要な変更を加えるため。
+
これらのセクションで推奨される変更を行ってからノードをリブートし、メンテナンスモードに切り替えます。

. [[man_install3_step27]] node3 のシステム ID を確認します。
+
「ディスクショー - A` 」

+
次の例に示すように、ノードのシステム ID 、およびそのディスクに関する情報が表示されます。

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: コマンドを入力すると、「ディスクはありません」というメッセージが表示される場合があります。これはエラーメッセージではないため、手順を続行できます。

. [man_install3_step28] 再割り当てするノードのスペア、ルートに属するディスク、およびでノード 2 に再配置されなかったルート以外のアグリゲート link:relocate_non_root_aggr_node1_node2.html["ルート以外のアグリゲートを node1 から node2 に再配置します。"]。
+
システムに共有ディスクがあるかどうかに応じて、適切な形式の「 disk reassign 」コマンドを入力します。

+
[cols="35,65"]
|===
| ディスクタイプ | 実行するコマンド 


| 共有ディスクの場合 | 「ディスクの再割り当て -s <node1 の sysid> -d <node3 の sysid> -p <node2 の sysid>` 」 


| ディスクを共有しない | 「ディスクの再割り当て -s <node1 の sysid> -d <node3 の sysid>` 
|===
+
「 <node1 _sysid>` 」の値には、で取得した情報を使用します link:record_node1_information.html["ノード 1 の情報を記録します"]。「 <node3 sysid>` 」の値を取得するには、「 sysconfig 」コマンドを使用します。

+

NOTE: -p オプションは ' 共有ディスクが存在する場合にのみ保守モードで必要です

+
「 disk reassign 」コマンドは、「 <node1 _sysid> 」が現在の所有者であるディスクだけを再割り当てします。

+
次のメッセージが表示されます。

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [man_install3_step29]] 「 n` 」と入力します。
+
次のメッセージが表示されます。

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [man_install3_step30]] 「 y 」と入力します
+
次のメッセージが表示されます。

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [man_install3_step31]] 「 y 」と入力します。
. [[man_install3_step32]] 外付けディスクがあるシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ AFF A800 システムなど）にアップグレードする場合は、 node1 アグリゲートを root として設定して、 node1 のルートアグリゲートからブートするようにします。
+

WARNING: * 警告 * ：次の手順を記載された順序で実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。

+
次の手順は、 node3 を node1 のルートアグリゲートからブートするように設定します。

+
.. node1 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node1 アグリゲートのステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node1 アグリゲートをオンラインにします。
+
'aggr_online <root_aggr_from_node1>

.. node3 が元のルートアグリゲートからブートしないようにします。「 aggr offline <root_aggr_on_node3 >`
.. node1 ルートアグリゲートを、 node3 の新しいルートアグリゲートとして設定します。
+
「 aggr options <aggr_from_node1> root 」のように指定します

.. ノード 3 のルートアグリゲートがオフラインになっていること、およびノード 1 からテイクオーバーされたディスクのルートアグリゲートがオンラインになっていて root に設定されていることを確認します。
+
「 aggr status 」を入力します

+

NOTE: 前の手順を実行しないと、原因 node3 を内部ルートアグリゲートからブートするか、原因システムで新しいクラスタ構成が存在すると想定するか、あるいはクラスタ構成を特定するように求められる可能性があります。

+
次の例は、コマンドの出力を示しています。



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [man_install3_step33]] コントローラとシャーシが 'ha' として構成されていることを確認します
+
「 ha-config show 」

+
次に、 ha-config show コマンドの出力例を示します。

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

+
コントローラとシャーシが「 HA 」として構成されていない場合は、次のコマンドを使用して構成を修正します。

+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください

+
MetroCluster 構成の場合は、次のコマンドを使用してコントローラとシャーシを変更します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. [man_install3_step34]] ノード 3 のメールボックスを破棄します
+
「マイボックス破壊ローカル」

+
コンソールに次のメッセージが表示されます。

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [man_install3_step35]] ローカルメールボックスを破棄することを確認するプロンプトで 'y' を入力します
. [[man_install3_step36]] メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. [man_install3_step37]] node2 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. [man_install3_step38]] ノード 3 で、ブート環境プロンプトで日付を確認します。
+
「日付」

. [[man_install3_step39]] 必要に応じて、 node3 の日付を設定します。
+
'Set date <mm/dd/yyyy>`

. [man_install3_step40]] ノード 3 で、ブート環境のプロンプトで時刻を確認します。
+
「時間」

. [[man_install3_step41] 必要に応じて、 node3 に時間を設定します。
+
時刻を設定します

. [[man_install3_step42]] パートナーシステム ID がで説明したとおりに正しく設定されていることを確認します <<man_install3_step28,手順 28>> アン下の -p スイッチ：
+
printenv partner-sysid

. [[man_install3_step43] 必要に応じて、 node3 にパートナーシステム ID を設定します。
+
'setenv partner-sysid <node2 _sysid>`

+
設定を保存します。

+
'aveenv

. [man_install3_step44]] ブート環境プロンプトでブートメニューにアクセスします
+
「 boot_ontap menu

. [man_install3_step45]] ブートメニューで ' プロンプトで '6` を入力して 'option *(6) Update flash from backup config* を選択します
+
次のメッセージが表示されます。

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]] プロンプトで「 y 」と入力します。
+
ブートが正常に続行され、システム ID の不一致を確認するよう求められます。

+

NOTE: 不一致の警告が表示される前にシステムが 2 回リブートする可能性があります。

. [[man_install3_step47]] 次の例に示すように、不一致を確認します。
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
正常にブートする前に、ノードが 1 回限りのリブートを実行する可能性があります。

. [[man_install3_step48]] node3 にログインします。

