= ノード 4 の UTA / UTA2 ポートを確認して設定してください




== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードは FC イニシエータと FC ターゲットをサポートします。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。

* 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。ストレージアレイに接続された MetroCluster FC システム、 V シリーズシステム、または FlexArray 仮想化ソフトウェアを搭載したシステムがある場合、 UTA / UTA2 ポートを設定するにはメンテナンスモードにする必要があります。

.手順
. ノード 4 で次のいずれかのコマンドを使用して、ポートが現在どのように設定されているかを確認します。
+
[cols="35,65"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. 「 system node hardware unified-connect show 」コマンドと「 ucadmin show 」コマンドの出力を調べ、 UTA / UTA2 ポートに希望するパーソナリティが設定されているかどうかを確認します。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| CNA ポートの状況 | 作業 


| 希望するパーソナリティがない | に進みます <<man_check_4_Step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<man_check_4_Step13,手順 13>>。 
|===
. [[man_check_4_Step5]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあり、 Data ONTAP 8.3 を実行している | node4 をブートし、メンテナンスモードに入ります。「 boot_ontap maint 」と入力します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | に進みます <<man_check_4_Step6,手順 6>>。すでにメンテナンスモードになっている必要があります。 
|===
. [[man_check_4_Step6]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| を設定する場合 | 作業 


| UTA / UTA2A カードのポート | に進みます <<man_check_4_Step7,手順 7>>。 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<man_check_4_Step8,手順 8>>。 
|===
. [[man_check_4_Step7] アダプタがイニシエータモードの場合、 UTA / UTA2 ポートがオンラインの場合は、 UTA / UTA2 ポートをオフラインにします。
+
「 storage disable adapter <adapter_name> 」

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[man_check_4_Step8] 現在の設定が目的の使用方法と一致しない場合は、次のコマンドを入力して必要に応じて設定を変更します。
+
ucadmin modify -m fc | cna-t initiator | target <adapter_name> `

+
** 「 -m' 」はパーソナリティ・モードである FC または 10 GbE UTA です。
** `-t` は FC4 のタイプで ' ターゲットまたはイニシエータです


+

NOTE: テープドライブおよび FlexArray 仮想化システムには、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。

. 次のコマンドを入力し、出力を確認して、設定を確認します。
+
ucadmin show

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります  a| 
.. 次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

.. 次のコマンドを入力します。
+
「 boot_ontap 」





| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載したストレージアレイに接続され、 Data ONTAP 8.3 を実行しているシステムです | 保守モードで再起動します（「 boot_ontap maint 」） 
|===
. 設定を確認します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | 次のコマンドを入力します。 'system node hardware unified-connect show' 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを入力します。 ucadmin show 
|===
+
次の例の出力では ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更されており ' アダプタ「 2a 」と「 2b 」のモードが CNA に変更されています

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. 次のいずれかのコマンドをポートごとに 1 回入力して、ターゲットポートをオンラインにします。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | 「 network fcp adapter modify -node <node_name > -adapter <adapter_name> -state up 」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config <adapter_name> up' 
|===
. [[man_check_4_Step13]] ポートをケーブル接続します。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"]。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | section_Install および boot node4 _ に戻り、のセクションを再開します link:install_boot_node4.html#Step9["手順 9"]。 
|===

