---
permalink: c190/bootmedia-encryption-restore.html 
sidebar: sidebar 
keywords: aff c190, post boot media replacement steps for okm, nse, and nve 
summary: 環境変数を確認したら、オンボードキーマネージャ \ （ OKM \ ）、 NetApp Storage Encryption \ （ NSE\ ）、または NetApp Volume Encryption \ （ NVE \ ）が有効になっているシステムに固有の手順を実行する必要があります。 
---
= 必要に応じて、 OKM 、 NSE 、 NVE をリストアします - AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
環境変数を確認したら、オンボードキーマネージャ（ OKM ）、 NetApp Storage Encryption （ NSE ）、または NetApp Volume Encryption （ NVE ）が有効になっているシステムに固有の手順を実行する必要があります。

. OKM 、 NSE 、または NVE 構成のリストアに使用するセクションを決定します。 NSE または NVE がオンボードキーマネージャとともに有効になっている場合、この手順の最初に取得した設定をリストアする必要があります。
+
** NSE または NVE が有効で、オンボードキーマネージャが有効になっている場合は、に進みます <<オンボードキーマネージャを有効にした場合は、 NVE または NSE をリストアします>>。
** ONTAP 9.6 に対して NSE または NVE が有効になっている場合は、に進みます <<ONTAP 9.6 以降を実行しているシステムで NSE / NVE をリストアする>>。






== オンボードキーマネージャを有効にした場合は、 NVE または NSE をリストアします

.手順
. コンソールケーブルをターゲットコントローラに接続します。
. LOADER プロンプトで「 boot_ontap 」コマンドを使用して、コントローラをブートします。
. コンソールの出力を確認します。
+
[cols="1,2"]
|===
| * と表示されます | * 次に ... * 


 a| 
LOADER プロンプト
 a| 
コントローラをブートメニュー「 boot_ontap menu 」からブートします



 a| 
ギブバックを待っています
 a| 
.. プロンプトで「 Ctrl+C 」と入力します
.. というメッセージが表示された場合：このノードを halt するのではなく、 [y/n] をクリックしますか？「 y 」と入力します
.. LOADER プロンプトで「 boot_ontap menu 」コマンドを入力します。


|===
. ブートメニューで、非表示のコマンド「 recover _onboard keymanager 」を入力し、プロンプトで「 y 」と応答します
. この手順の冒頭でお客様から入手したオンボードキーマネージャのパスフレーズを入力します。
. バックアップ・データの入力を求められたら、この手順の最初にキャプチャしたバックアップ・データを貼り付けます。「 securitykey-manager backup show 」コマンドまたは「 securitykey-manager onboard show -backup 」コマンドの出力を貼り付けます
+

NOTE: データは 'securitykey-manager backup show または 'securitykey-manager onboard show-backup' コマンドから出力されます

+
バックアップデータの例：

+
[]
====
-------------- バックアップの開始 TmV0QXBwIEISELAALAC6AALAG3ATVATLH1DBZ12piVATVZ4ATLASYFSSAJAXAJAXAZAAALAC6AALACBAALAC6AALACZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAADATAAAAADAAAAAAADADAAAAAAAAAADAAAAAAAAAAADAAAAAADAAAAAADAAAAAADAAAADAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADADAAAADAAAADAAAAA。。。H4nPQM0nrDRYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

-------------- エンド・バックアップ：

====
. ブートメニューで、 Normal Boot のオプションを選択します。
+
システムがブートし、「 Waiting for giveback... 」プロンプトが表示されます。

. パートナーコントローラにコンソールケーブルを接続し、「 admin 」としてログインします。
. storage failover show コマンドを使用して ' ターゲット・コントローラがギブバック可能な状態になっていることを確認します
. ギブバックを実行するには、「 storage failover giveback -fromnode local-only -cfo-aggregates true 」コマンドを使用して CFO アグリゲートのみをギブバックします。
+
** ディスク障害のためにコマンドが失敗した場合は、ディスクを物理的に取り外します。ただし、交換用のディスクを受け取るまでは、ディスクをスロットに残しておきます。
** CIFS セッションが開いているためにコマンドが失敗する場合は、 CIFS セッションを閉じる方法をお客様に確認してください。
+

NOTE: CIFS を終了原因すると、データが失われる可能性があります。

** パートナーの「準備が完了していません」が原因でコマンドが失敗した場合は、 NVMEM が同期されるまで 5 分待ちます。
** NDMP 、 SnapMirror 、または SnapVault のプロセスが原因でコマンドが失敗する場合は、そのプロセスを無効にします。詳細については、該当するドキュメントセンターを参照してください。


. ギブバックが完了したら 'storage failover show' および storage failover show-giveback コマンドを使用して ' フェイルオーバーとギブバックのステータスを確認します
+
CFO アグリゲート（ルートアグリゲートおよび CFO 形式のデータアグリゲート）のみが表示されます。

. コンソールケーブルをターゲットコントローラに接続します。
+
.. ONTAP 9.6 以降を実行している場合は、セキュリティキー管理ツールのオンボード同期を実行します。
.. 「 securitykey-manager onboard sync 」コマンドを実行し、プロンプトが表示されたらパスフレーズを入力します。
.. 「 securitykey-manager key query 」コマンドを入力して、オンボードキーマネージャに格納されているすべてのキーの詳細を表示し、すべての認証キーの「 restored 」列 = 「 yes / true 」であることを確認します。
+

NOTE: 「 Restored 」列が「 yes/true 」以外の場合は、カスタマサポートにお問い合わせください。

.. キーがクラスタ全体で同期されるまで 10 分待ちます。


. パートナーコントローラにコンソールケーブルを接続します。
. storage failover giveback -fromnode local コマンドを使用して、ターゲットコントローラをギブバックします。
. 「 storage failover show 」コマンドを使用して、ギブバックのステータスを確認します。このステータスは、レポートが完了してから 3 分後に表示されます。
+
20 分経ってもギブバックが完了しない場合は、カスタマーサポートにお問い合わせください。

. クラスタシェルプロンプトで、「 net int show -is-home false 」コマンドを入力し、ホームコントローラとポートにない論理インターフェイスを表示します。
+
いずれかのインターフェイスが「 false 」と表示されている場合は、「 net int revert 」コマンドを使用して、これらのインターフェイスをホームポートに戻します。

. コンソール・ケーブルをターゲット・コントローラに移動し 'version -v コマンドを実行して ONTAP のバージョンを確認します
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。




== ONTAP 9.6 以降を実行しているシステムで NSE / NVE をリストアする

.手順
. コンソールケーブルをターゲットコントローラに接続します。
. LOADER プロンプトで「 boot_ontap 」コマンドを使用して、コントローラをブートします。
. コンソールの出力を確認します。
+
|===


| * と表示されます | * 次に ... * 


 a| 
ログインプロンプト
 a| 
手順 7 に進みます。



 a| 
ギブバックを待っています
 a| 
.. パートナーコントローラにログインします。
.. storage failover show コマンドを使用して ' ターゲット・コントローラがギブバック可能な状態になっていることを確認します


|===
. コンソール・ケーブルをパートナー・コントローラに移動し ' storage failover giveback -fromnode local-only CFO -aggregates true local コマンドを使用してターゲット・コントローラ・ストレージをギブバックします
+
** ディスク障害のためにコマンドが失敗した場合は、ディスクを物理的に取り外します。ただし、交換用のディスクを受け取るまでは、ディスクをスロットに残しておきます。
** CIFS セッションが開いているためにコマンドが失敗する場合は、 CIFS セッションを閉じる方法をお客様に確認してください。
+

NOTE: CIFS を終了原因すると、データが失われる可能性があります。

** パートナーの「準備が完了していません」が原因でコマンドが失敗した場合は、 NVMEM が同期されるまで 5 分待ちます。
** NDMP 、 SnapMirror 、または SnapVault のプロセスが原因でコマンドが失敗する場合は、そのプロセスを無効にします。詳細については、該当するドキュメントセンターを参照してください。


. 3 分待ってから、「 storage failover show 」コマンドを使用してフェイルオーバーステータスを確認します。
. クラスタシェルプロンプトで、「 net int show -is-home false 」コマンドを入力し、ホームコントローラとポートにない論理インターフェイスを表示します。
+
いずれかのインターフェイスが「 false 」と表示されている場合は、「 net int revert 」コマンドを使用して、これらのインターフェイスをホームポートに戻します。

. コンソール・ケーブルをターゲット・コントローラに移動し 'version -v コマンドを実行して ONTAP のバージョンを確認します
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。
. クラスタシェルプロンプトで「 storage encryption disk show 」を使用して出力を確認します。
. 「 securitykey-manager key query 」コマンドを使用して、キー管理サーバに格納されている認証キーのキー ID を表示します。
+
** リストアされたカラム = 'yes/true' の場合は ' 終了し ' 交換プロセスを完了することができます
** 「 Key Manager type 」 = 「 external 」および「 restored 」列 = 「 yes / true 」以外の場合は、「 securitykey-manager external restore 」コマンドを使用して認証キーのキー ID をリストアします。
+

NOTE: コマンドが失敗した場合は、カスタマーサポートにお問い合わせください。

** 「 Key Manager type 」 = 「 onboard 」で「 restored 」列 = 「 yes / true 」以外の場合は、「 securitykey-manager onboard sync 」コマンドを使用して、 Key Manager タイプを再同期します。
+
すべての認証キーに対して 'restored`column=yes/true' を確認するには 'securitykey-manager key query` コマンドを使用します



. パートナーコントローラにコンソールケーブルを接続します。
. storage failover giveback -fromnode local コマンドを使用して、コントローラをギブバックします。
. 「 storage failover modify -node local-auto-giveback true 」コマンドを使用して自動ギブバックを無効にした場合は、自動ギブバックをリストアします。

