---
permalink: c190/bootmedia-shutdown.html 
sidebar: sidebar 
keywords: aff c190, shut down the controller, manual, manual boot recovery 
summary: 暗号化チェックを完了した後、 AFF C190システム上の障害のあるコントローラをシャットダウンします。AFF C190システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= コントローラをシャットダウンします。 AFF C190
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
暗号化チェックを完了した後、 AFF C190システム上の障害のあるコントローラをシャットダウンします。この手順には、コントローラを LOADER プロンプトに移動し、参照用にブート環境変数をキャプチャし、ブート メディアの交換のためにコントローラを準備することが含まれます。

AFF C190システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

NVE タスクまたは NSE タスクが完了したら、障害のあるコントローラをシャットダウンする必要があります。

.手順
. 障害のあるコントローラに LOADER プロンプトを表示します。
+
[cols="1,2"]
|===
| 障害のあるコントローラが表示された場合 | 作業 


 a| 
LOADER プロンプト
 a| 
コントローラモジュールの取り外しに進みます。



 a| 
ギブバックを待機しています
 a| 
Ctrl キーを押しながら C キーを押し ' プロンプトが表示されたら y と入力します



 a| 
システムプロンプトまたはパスワードプロンプト（システムパスワードの入力）
 a| 
正常なコントローラから障害のあるコントローラをテイクオーバーまたは停止します。 storage failover takeover -ofnode impaired_node_name

障害のあるコントローラに「 Waiting for giveback... 」と表示されたら、 Ctrl+C キーを押し、「 y 」と入力します。

|===
. LOADER プロンプトで「 printenv 」と入力し、すべてのブート環境変数をキャプチャします。出力をログファイルに保存します。
+

NOTE: ブートデバイスが壊れているか機能していない場合、このコマンドは機能しない可能性があります。


