---
permalink: c190/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: AFF c190, nondisruptive, disruptive, replace the boot media, manual, manual boot recovery 
summary: AFF C190システムでのブート メディアの交換について説明し、さまざまな交換方法を理解します。AFF C190システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= AFF C190システムにおける手動ブートメディアリカバリの要件を確認する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF C190システムでのブート メディアの交換について説明し、さまざまな交換方法を理解します。ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリ ブート イメージ ファイルが格納されます。ネットワーク構成に応じて、無停止交換（HA ペアをネットワークに接続）または停止交換（2 回の再起動が必要）のいずれかを実行できます。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
AFF C190システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

「 image_xxx.tgz 」ファイルを格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

* 無停止または停止を伴う方法でブートメディアを交換する場合は、 var ファイルシステムをリストアする必要があります。
+
** 無停止で交換する場合は、 HA ペアをネットワークに接続して var ファイルシステムをリストアする必要があります。
** 停止を伴う交換の場合、 var ファイルシステムをリストアするためにネットワーク接続は必要ありませんが、リブートが 2 回必要です。


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。



