---
permalink: a700/bootmedia-2n-mcc-switchback.html 
sidebar: sidebar 
keywords: aff a700, metrocluster, switchback, manual, manual boot recovery 
summary: '2 ノードMetroCluster構成で FRU の交換が完了したら、 MetroClusterスイッチバック操作を実行できます。これにより、構成は通常の動作状態に戻り、以前障害が発生していたサイトの同期元のストレージ仮想マシン (SVM) がアクティブになり、ローカル ディスク プールからデータを提供するようになります。AFF A700システムは、手動のブート メディア リカバリ手順のみをサポートします。' 
---
= 2ノードMetroCluster構成におけるアグリゲートのスイッチバック - AFF A700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブート メディアの交換が完了したら、 MetroClusterスイッチバック操作を実行します。AFF A700システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

このタスクでは、環境の 2 ノード MetroCluster 構成のみを実行します。

.手順
. すべてのノードの状態が「 enabled 」であることを確認します。 MetroCluster node show
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. すべての SVM で再同期が完了したことを確認します。「 MetroCluster vserver show 」
. 修復処理によって実行される LIF の自動移行が正常に完了したことを確認します。 MetroCluster check lif show
. サバイバークラスタ内の任意のノードから MetroCluster switchback コマンドを使用して、スイッチバックを実行します。
. スイッチバック処理が完了したことを確認します MetroCluster show
+
クラスタの状態が waiting-for-switchback の場合は、スイッチバック処理がまだ実行中です。

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
クラスタが「 normal 」状態のとき、スイッチバック処理は完了しています。

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
スイッチバックが完了するまでに時間がかかる場合は、「 MetroCluster config-replication resync-status show 」コマンドを使用することで、進行中のベースラインのステータスを確認できます。

. SnapMirror 構成または SnapVault 構成があれば、再確立します。

