---
permalink: a700/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, replace, boot, media, primary, secondary, image, disruptive, nondisruptive, manual, manual boot recovery 
summary: AFF A700システムでのブート メディアの交換について説明し、さまざまな交換方法を理解します。AFF A700システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= AFF A700 システムのブートメディアの交換について
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A700システムでのブート メディアの交換について説明し、さまざまな交換方法を理解します。ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリ ブート イメージ ファイルが格納されます。ネットワーク構成に応じて、無停止交換 (内部 e0S 接続を使用) または無停止交換 (2 回の再起動が必要) のいずれかを実行できます。

AFF A700システムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
「 image_xxx.tgz 」を格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

また ' この手順で後で使用するために 'image_xxx.tgz ファイルを USB フラッシュドライブにコピーする必要があります

* ブート・メディアを交換するための無停止かつ停止を伴う方法では 'var' ファイル・システムをリストアする必要があります
+
** 無停止交換の場合 'HA ペアはネットワークに接続して 'var' ファイル・システムをリストアする必要はありません単一シャーシ内の HA ペアには内部 e0S 接続があり ' これを使用して 'var'config をそれらの間で転送します
** 停止を伴う交換の場合 'var' ファイル・システムをリストアするためにネットワーク接続は必要ありませんが ' 再起動が 2 回必要です


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* 以下の手順のコマンドを正しいノードに適用することが重要です。
+
** impaired_node は、保守を実行しているノードです。
** Healthy node_name は、障害が発生したノードの HA パートナーです。



