---
permalink: fas-70-90/chassis-replace-complete-system-restore-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, verify and set HA state, complete the replacement process 
summary: コントローラを再起動し、システムの健全性を確認し、故障した部品をNetAppに返送して、FAS70 および FAS90 シャーシ交換手順の最終ステップを完了します。 
---
= シャーシ交換を完了 - FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラを再起動し、システムの健全性を確認し、故障した部品をNetAppに返送して、FAS70 および FAS90 シャーシ交換手順の最終ステップを完了します。



== ステップ1: コントローラを起動し、システムの健全性を確認する

コントローラが再起動したら、 ONTAPを起動し、コントローラを戻して、ストレージ システムの健全性を確認します。

.手順
. コンソールの出力を確認します。
+
.. コントローラがブートしてLoaderプロンプトが表示されたら、コマンドを使用してコントローラをリブートし `boot_ontap`ます。
.. リブート後にコンソールにと表示された場合 `waiting for giveback`は、パートナーコントローラにログインし、コマンドを使用して交換したコントローラのギブバックの準備が完了していることを確認します `storage failover show`。


. ギブバックを実行します。
+
.. パートナーコントローラにコンソールケーブルを接続します。
.. 障害コントローラのストレージをギブバックして、障害コントローラを通常動作に戻します。 `storage failover giveback -ofnode _impaired_node_name_`
.. 自動ギブバックが無効になっている場合は、再度有効にします。 `storage failover modify -node _impaired_node_name_ -auto-giveback _true_`
.. AutoSupportが有効になっている場合は、ケースの自動作成をリストアまたは抑制解除します。 `system node autosupport invoke -node * -type all -message MAINT=END`


. ギブバックが完了したら、 https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"]ストレージ システムの健全性を確認し、発生した問題を修正します。




== 手順2：故障した部品をNetAppに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
