---
permalink: fas-70-90/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: fas70, fas90, replace the chassis 
summary: FAS70 または FAS90 システムのシャーシを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが適切に機能していることを確認すること、 ONTAPのローカル管理者の認証情報、適切な交換用シャーシ、および必要なツールがあることを確認することが含まれます。 
---
= シャーシ交換の要件 - FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70 または FAS90 システムのシャーシを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが適切に機能していることを確認すること、 ONTAPのローカル管理者の認証情報、適切な交換用シャーシ、および必要なツールがあることを確認することが含まれます。

シャーシは、ファン、コントローラー/CPU ユニット、NVRAM12、システム管理モジュール、I/O カードとブランキング モジュール、PSU などのすべてのシステム コンポーネントを収容する物理シャーシです。

次の要件を確認します。

* システムの他のすべてのコンポーネントが正常に機能していることを確認します。正常に機能していない場合は、に連絡してサポートを受けてください http://mysupport.netapp.com/["ネットアップサポート"^]
* ONTAPのローカル管理者のクレデンシャルがない場合は、そのクレデンシャルを取得します。
* 交換に必要な工具と機器が揃っていることを確認します。
* シャーシの交換手順は、システムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、ファン、コントローラ モジュール、NVRAM12、システム管理モジュール、I/O カードとブランキング モジュール、および PSU を新しいシャーシに移動し、交換用シャーシがNetAppの新しいコンポーネントであることを前提として書かれています。


.次の手順
シャーシの交換要件を確認したら、を行う必要がありますlink:chassis-replace-prepare.html["シャーシを交換する準備"]。
