---
permalink: fas-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: fas70, fas90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 論理インターフェイス（LIF）がホームポートに報告していることを確認し、クラスタの健全性チェックを実行してから、障害が発生したパーツをNetAppに戻して、FAS70またはFAS90コントローラの交換手順の最後の手順を完了します。 
---
= コントローラ交換後の処理- FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A1Kシステムのコントローラ交換を完了するには、まずNetAppストレージ暗号化設定を復元します（必要な場合）。次に、論理インターフェイス（LIF）がホームポートにレポートしていることを確認し、クラスタの健全性チェックを実行します。最後に、故障した部品をNetAppに返送してください。



== 手順1：LIFを確認してクラスタの健全性を確認する

交換用ノードを使用可能な状態に戻す前に、論理インターフェイスがホームポートにあることを確認し、クラスタの健常性を確認して、自動ギブバックをリセットしてください。

.手順
. 論理インターフェイスがホームサーバとポートに報告されていることを確認します。「 network interface show -is-home false 」
+
いずれかの論理インターフェイスがfalseと表示された場合は、それらをホームポートにリバートします。 `network interface revert -vserver * -lif *`

. クラスタの健全性を確認します。詳細については、技術情報の記事を参照して https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAP でスクリプトを使用してクラスタの健全性チェックを実行する方法"^] ください。
. 自動ギブバックを無効にした場合は、再度有効にします。「 storage failover modify -node local-auto-giveback true 」




== 手順2：故障した部品をNetAppに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
