---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: 必要な機器と、プラットフォームとシェルフの持ち上げに関する注意事項を確認します。 
---
= 設置要件- FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70またはFAS90ストレージ・システムおよびストレージ・シェルフに必要な機器と、持ち上げに関する注意事項を確認します。



== 設置に必要な機器

FAS70またはFAS90ストレージ・システムを設置するには、次の機器および工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* NS224ストレージシェルフIDを設定するためのペーパークリップまたはボールペン
* No.2 プラスドライバ




== 吊り上げ時の注意事項

FAS70およびFAS90ストレージシステム、NS224ストレージシェルフ、およびDS460Cストレージシェルフは重量があります。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== FAS70オヨヒFAS90ストレエシシステム

FAS70またはFAS90ストレージ・システムの重量は最大28.5kg（62.83ポンド）になることがあります。システムを持ち上げるには、2人で作業するか、油圧リフトを使用します。

image::../media/drw_a1k_weight_caution_ieops-1698.svg[FAS70およびFAS90の持ち上げに関する注意アイコン]



=== NS224シェルフ

NS224ストレージシェルフの重量は最大30.29kg（66.78ポンド）です。ストレージシェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224の持ち上げに関する注意事項]



=== DS460Cシェルフ

DS460Cシェルフの重量は最大181.1kg（360.4ポンド）です。収納棚を持ち上げるには、最大5人で持ち上げるか、油圧リフトを使用します。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460Cの持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]
* https://hwu.netapp.com["NetApp Hardware Universe の略"^]


.次の手順
ハードウェア要件を確認したら、link:install-prepare.html["FAS70またはFAS90ストレージ・システムの設置の準備"]
