---
sidebar: sidebar 
permalink: fas-70-90/install-requirements.html 
keywords: fas70, fas90, install, setup, cautions 
summary: 必要な機器と、プラットフォームとシェルフの持ち上げに関する注意事項を確認します。 
---
= 設置要件- FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70またはFAS90ストレージ・システムおよびストレージ・シェルフに必要な機器と、持ち上げに関する注意事項を確認します。



== 設置に必要な機器

ストレージシステムを設置するには、次の機器および工具が必要です。

* ストレージシステムを設定するためのWebブラウザへのアクセス
* 静電放電（ESD）ストラップ
* 懐中電灯
* USB /シリアル接続を備えたラップトップまたはコンソール
* No.2 プラスドライバ




== 吊り上げ時の注意事項

ストレージシステムやシェルフは重い。これらのアイテムを持ち上げたり移動したりするときは、注意してください。



=== ストレージシステムノオモミ

ストレージシステムを移動または持ち上げるときは、必要な予防措置を講じてください。

FAS70またはFAS90ストレージ・システムの重量は最大28.5kg（62.83ポンド）になることがあります。システムを持ち上げるには、2人で作業するか、油圧リフトを使用します。

image::../media/drw_a1k_weight_caution_ieops-1698.svg[FAS70およびFAS90の持ち上げに関する注意アイコン]



=== シェルフの重量

シェルフを移動または持ち上げるときは、必要な予防措置を講じてください。

NS224シェルフの重量は最大30.29kg（66.78ポンド）です。シェルフを持ち上げるには、2人で作業するか、油圧リフトを使用します。シェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）をシェルフに保管してください。

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 NSM100の持ち上げに関する注意事項]

DS460Cシェルフの重量は最大181.1kg（260.4ポンド）です。ストレージシェルフを持ち上げるには、最大5人または油圧リフトが必要になる場合があります。ストレージシェルフの重量がバランスを崩さないように、すべてのコンポーネント（前面と背面の両方）を保管してください。

image::../media/drw_ds460c_weight_warning_ieops-1932.svg[DS460Cの持ち上げに関する注意事項]

.関連情報
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["安全に関する情報と規制に関する通知"^]


.次の手順
ハードウェア要件を確認したら、link:install-prepare.html["FAS70またはFAS90ストレージ・システムの設置の準備"]
