---
permalink: fas-70-90/install-hardware.html 
sidebar: sidebar 
keywords: fas70, fas90, install hardware, telco rack 
summary: キャビネットまたはTelcoラックにストレージシステムを設置します。 
---
= ハードウェアの設置- FAS70およびFAS90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS70またはFAS90ストレージ・システムの設置の準備が完了したら、システムのハードウェアを設置します。まず、レールキットを取り付けます。次に、キャビネットまたはTelcoラックにプラットフォームを設置して固定します。

キャビネットにデータが事前に格納されている場合は、この手順をスキップします。

.作業を開始する前に
* レールキットに手順書が同梱されていることを確認します。
* ストレージシステムとシェルフの重量に関連する安全上の問題に注意してください。
* ストレージ・システム内の通気は'ベゼルまたはエンド・キャップが取り付けられている前面から入り'ポートが取り付けられている背面から排出されます


.手順
. キットに付属の手順書に従って、ストレージシステムとシェルフのレールキットを必要に応じて設置します。
. キャビネットまたはTelcoラックにストレージシステムを設置して固定します。
+
.. キャビネットまたはTelcoラックの中央にあるレールにストレージシステムを配置し、ストレージシステムを下から支えて所定の位置にスライドさせます。
.. 付属の取り付けネジを使用して、ストレージシステムをキャビネットまたはTelcoラックに固定します。


. ベゼルをストレージシステムの前面に取り付けます。
. ケーブルマネジメントデバイスをストレージシステムの背面に接続します。
+
image::../media/drw_affa1k_install_cable_mgmt_ieops-1697.svg[ケーブルマネジメントデバイスの取り付け]

. 必要に応じてシェルフを設置して固定します。
+
.. シェルフの背面をレールに合わせ、シェルフを下から支えてキャビネットまたはTelcoラックに挿入します。
+
複数のシェルフを設置する場合は、最初のシェルフをコントローラの真上に配置します。2台目のシェルフをコントローラの真下に置きます。シェルフを追加する場合は、このパターンを繰り返します。

.. 付属の取り付けネジを使用して、シェルフをキャビネットまたはTelcoラックに固定します。
+
.次の手順
FAS70またはFAS90ストレージ・システムのハードウェアの設置が完了したら、次の作業を行いlink:install-cable.html["FAS70またはFAS90ストレージ・システムのハードウェアをケーブル接続します。"]ます。




