---
permalink: asa900/bootmedia_replace_overview.html 
sidebar: sidebar 
keywords: ASA A900 
summary: ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。 
---
= ブートメディアの交換- ASA A900
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。

「 image_xxx.tgz 」ファイルを格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

また ' この手順で後で使用するために 'image_xxx.tgz ファイルを USB フラッシュドライブにコピーする必要があります

* ブート・メディアを交換するための無停止かつ停止を伴う方法では 'var' ファイル・システムをリストアする必要があります
+
** 無停止交換の場合 'HA ペアはネットワークに接続して 'var' ファイル・システムをリストアする必要はありません単一シャーシ内の HA ペアには内部 e0S 接続があり ' これを使用して 'var'config をそれらの間で転送します
** 停止を伴う交換の場合 'var' ファイル・システムをリストアするためにネットワーク接続は必要ありませんが ' 再起動が 2 回必要です


* 障害が発生したコンポーネントは、NetAppから受け取った交換用FRUコンポーネントと交換する必要があります。
* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。



