---
permalink: asa900/index.html 
sidebar: sidebar 
keywords: asa A900 maintenance, maintenance, repairing asa A900, repairing asa A900, replace asa A900 components, replace asa A900 components 
summary: ASA A900ハードウェアのメンテナンス 
---
= ASA A900ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A900ストレージシステムでは、次のコンポーネントに対してメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== DCPM を実行します

DCPM（デステージコントローラ電源モジュール）には、NVRAM11バッテリが搭載されています。



== ファン

ファンによってコントローラが冷却されます。



== I/O モジュール

I/Oモジュール（入出力モジュール）は、コントローラと、コントローラとデータを交換する必要があるさまざまなデバイスやシステムとの間の仲介役として機能するハードウェアコンポーネントです。



== LED USB

LED USB モジュールは、コンソールポートおよびシステムステータスへの接続を提供します。



== NVRAM

 The NVRAM module (Non-Volatile Random Access Memory) allows the controller to retain data across power cycles or system reboots.


== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
