---
permalink: asa-r2-70-90/bootmedia-recovery-image-boot-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, boot the recovery image 
summary: 自動ブートリカバリプロセスを使用して、パートナーコントローラからブートメディア上のイメージをリストアできます。 
---
= 自動ブートリカバリ- ASA A70およびASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブートメディアが破損した場合は、パートナーノードからONTAPイメージをリストアします。

.このタスクについて
ノードのブートメディアが破損すると、ブートプロセスがLoaderプロンプトで停止し、ブートエラーメッセージが表示されます。

これらのブートエラーメッセージが表示された場合は、パートナーノードからONTAPイメージをリストアする必要があります。

.ブートエラーメッセージの例を表示します。
[%collapsible]
====
....
Can't find primary boot device u0a.0
Can't find backup boot device u0a.1
ACPI RSDP Found at 0x777fe014

Starting AUTOBOOT press Ctrl-C to abort...
Could not load fat://boot0/X86_64/freebsd/image1/kernel: Device not found

ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/Linux/image1/vmlinuz (boot0, fat)
ERROR: Error booting OS on: 'boot0' file: fat://boot0/X86_64/freebsd/image1/kernel (boot0, fat)

Autoboot of PRIMARY image failed. Device not found (-6)
LOADER-A>
....
====
.手順
. Loaderプロンプトで、次のコマンドを入力します。
+
`boot_recovery -partner`

+
画面に次のメッセージが表示されます。

+
`Starting boot media recovery (BMR) process. Press Ctrl-C to abort…`

. Loaderでローカルクラスタポートが設定され、パートナーノードから実行されるため、ブートメディアのリカバリプロセスを監視し `netboot`ます。
+
ネットブートの実行中は `Starting BMR`、メッセージが表示されます。

. 暗号化方式に応じて、シングルノード構成に一致するオプションを選択します。
+
[role="tabbed-block"]
====
.暗号化なし
--
暗号化が検出されなかった場合は、キー管理を必要とせずにブートメディアのリカバリプロセスが続行されます。

パートナーノードからバックアップ設定、envファイル、mdb、およびrdbがリストアされる間、リカバリプロセスを引き続き監視します。

リカバリプロセスが完了すると、ノードがリブートします。次のメッセージは、リカバリが成功したことを示します。

....

varfs_backup_restore: update checksum for varfs.tgz
varfs_backup_restore: restore using /cfcard/x86_64/freebsd/oldvarfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: Rebooting to load the new varfs
.
Terminated
varfs_backup_restore: bootarg.abandon_varfs is set! Skipping /var backup.

....
--
.オンボードキーマネージャ（ OKM ）
--
オンボードキーマネージャ（OKM）が検出されると、次のプロンプトが表示されます。

....
key manager is configured.
Entering Bootmenu Option 10...

This option must be used only in disaster recovery procedures. Are you sure? (y or n):
....
.. ブートメニューオプションのプロンプトで、と入力して、 `Y`ブートメディアリカバリオプションの使用を確定します。
.. プロンプトが表示されたらオンボードキーマネージャのパスフレーズを入力し、確認のためにもう一度パスフレーズを入力します。
+
.パスフレーズのプロンプトの例を表示します。
[%collapsible]
=====
....
Enter the passphrase for onboard key management:
Enter the passphrase again to confirm:
Enter the backup data:
TmV0QXBwIEtleSBCbG9iAAECAAAEAAAAcAEAAAAAAAA3yR6UAAAAACEAAAAAAAAA
QAAAAAAAAACJz1u2AAAAAPX84XY5AU0p4Jcb9t8wiwOZoqyJPJ4L6/j5FHJ9yj/w
RVDO1sZB1E4HO79/zYc82nBwtiHaSPWCbkCrMWuQQDsiAAAAAAAAACgAAAAAAAAA
3WTh7gAAAAAAAAAAAAAAAAIAAAAAAAgAZJEIWvdeHr5RCAvHGclo+wAAAAAAAAAA
IgAAAAAAAAAoAAAAAAAAAEOTcR0AAAAAAAAAAAAAAAACAAAAAAAJAGr3tJA/LRzU
QRHwv+1aWvAAAAAAAAAAACQAAAAAAAAAgAAAAAAAAABHVFpxAAAAAHUgdVq0EKNp
.
.
.
.
....
=====
.. パートナーノードからバックアップ設定、envファイル、mdb、およびrdbがリストアされる間、リカバリプロセスを引き続き監視します。
+
リカバリプロセスが完了すると、ノードがリブートします。次のメッセージは、リカバリが成功したことを示します。

+
....
Trying to recover keymanager secrets....
Setting recovery material for the onboard key manager
Recovery secrets set successfully
Trying to delete any existing km_onboard.wkeydb file.

Successfully recovered keymanager secrets.
....


--
.外部キーマネージャ（ EKM ）
--
EKMが設定されている場合は、次のプロンプトが表示されます。

....
Error when fetching key manager config from partner <IP>: 28

Has key manager been configured on this system? {y|n}
....
.. EKMが設定されている場合はと入力します `Y`。
+
....
key manager is configured.
Entering Bootmenu Option 11...
....
+
セットアップ時に最初に使用されたEKM設定の入力を求められます。

.. プロンプトが表示されたら、各EKM設定を入力します。
.. クラスタUUIDとキーストアUUIDの属性が正しいことを確認します。
+
*** パートナーノードで、次のコマンドを使用してクラスタUUIDを取得します。
+
`cluster identity show`

*** パートナーノードで、次のコマンドを使用してキーストアUUIDを取得します。
+
`vserver show -type admin`

+
`key-manager keystore show -vserver <nodename>`

*** パートナーノードを使用できない場合は、Mroot-AKキーを使用してUUIDを取得します。
+
**** [Cluster UUID]に次のコマンドを入力します。
+
`x-NETAPP-ClusterName: <cluster name>`

**** キーストアUUIDとして、次のコマンドを入力します。
+
`x-NETAPP-KeyUsage: MROOT-AK`





.. プロンプトが表示されたら、キーストアUUIDとクラスタUUIDの値を入力します。
.. キーが正常にリストアされたかどうかに応じて、次のいずれかの操作を実行します。
+
*** キーが正常にリストアされると、リカバリプロセスが続行され、ノードがリブートされます。手順4に進みます。
*** キーのリストアに失敗すると、システムが停止し、エラーメッセージと警告メッセージが表示されます。リカバリプロセスを再実行します。
+
.キーリカバリのエラーおよび警告メッセージの例を示します。
[%collapsible]
=====
....

ERROR: kmip_init: halting this system with encrypted mroot...

WARNING: kmip_init: authentication keys might not be available.

System cannot connect to key managers.

ERROR: kmip_init: halting this system with encrypted mroot...

Terminated

Uptime: 11m32s

System halting...

LOADER-B>
....
=====




--
====


. ノードがリブートしたら、システムがオンラインに戻って動作可能になったことを確認して、ブートメディアのリカバリが成功したことを確認します。

