---
permalink: asa-r2-70-90/bootmedia-encryption-preshutdown-checks.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, pre-shutdown checks for onboard encryption keys 
summary: 障害のあるコントローラをシャットダウンしてオンボード暗号化キーのステータスを確認する前に、障害のあるコントローラのステータスを確認し、自動ギブバックを無効にし、システムで実行されている ONTAP のバージョンを確認する必要があります。 
---
= 暗号化キーのサポートとステータスの確認- ASA A70およびASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
障害のあるコントローラをシャットダウンする前に、使用しているONTAPのバージョンがNetApp Volume Encryption（NVE）をサポートしているかどうか、およびキー管理システムが適切に設定されているかどうかを確認してください。



== 手順1：使用しているONTAPのバージョンが暗号化をサポートしているかどうかを確認する

ONTAPのバージョンでNetApp Volume Encryption（NVE）がサポートされているかどうかを確認します。この情報は、正しいONTAPイメージをダウンロードするために重要です。

. 次のコマンドを実行して、ONTAPのバージョンが暗号化をサポートしているかどうかを確認します。
+
`version -v`

+
出力にが含まれている場合、 `1Ono-DARE`クラスタのバージョンではNVEがサポートされていません。

. ご使用のシステムでNVEがサポートされているかどうかに応じて、次のいずれかを実行します。
+
** NVEがサポートされている場合は、NetAppボリューム暗号化を使用するONTAPイメージをダウンロードします。
** NVEがサポートされない場合は、NetAppボリューム暗号化なしのONTAPイメージ*をダウンロードします。






== 手順2：コントローラを安全にシャットダウンできるかどうかを確認する

コントローラを安全にシャットダウンするには、まずオンボードキーマネージャ（OKM）と外部キーマネージャ（EKM）がアクティブになっているかを確認します。次に、使用しているキー管理ツールを確認し、適切なキー情報を表示して、認証キーのステータスに基づいて操作を実行します。

. システムで有効になっているキー管理ツールを確認します。
+
[cols="1a,2a"]
|===
| キー管理ツールのタイプ | 実行する手順 


 a| 
外部キーマネージャ（ EKM ）
 a| 
次のコマンドを実行して、システムでEKMが有効になっているかどうかを確認します。

`security key-manager show key store`

EKMが有効になっている場合は `external`、が出力に表示されます。



 a| 
オンボードキーマネージャ（ OKM ）
 a| 
ノードで実行されているONTAPのバージョンに基づいて次のいずれかのコマンドを実行し、OKMがシステムで有効になっているかどうかを確認します。

** ONTAP 9 .14.1以降の場合は、次のコマンドを入力します。
+
`security key-manager keystore show`

+
OKMが有効になっている場合は、 `OKM`がコマンド出力に表示されます。

** ONTAP 9 .13.1以前の場合は、次のコマンドを入力します。
+
`security key-manager show-key-store`

+
OKMが有効になっている場合は、 `onboard`がコマンド出力に表示されます。



|===
. 次のクエリコマンドを入力して、キー管理ツールの認証キーのステータスを表示します。
+
`security key-manager key query`

. キー管理ツールの列の値が出力されていることを確認します `Restored`。
+
この列は、キー管理ツール（EKMまたはOKM）の認証キーがリストアされたかどうかを示します。

+
** Restored列の値がtrueの場合、キーは適切にリストアされ、コントローラのシャットダウンを安全に実行できます。
** 値がtrue以外の場合、キーはリストアされていません。EKMとOKMのどちらを使用しているかに応じて、追加の手順（キーのリストアまたは同期）を実行する必要があります。


. EKMとOKMのどちらを使用しているかに応じて、次のいずれかのオプションを選択し、列に表示される出力値に応じて適切な手順を実行し `Restored`ます。
+
[role="tabbed-block"]
====
.EKM
--
列に表示された出力値に応じて `Restored`、該当する手順を実行します。

[cols="1a,2a"]
|===
| 列の出力値 `Restored` | 実行する手順 


 a| 
`true`
 a| 
障害のあるコントローラを安全にシャットダウンできます。にアクセスします。



 a| 
それ以外のすべて `true`
 a| 
.. 次のコマンドを使用して、外部キー管理の認証キーをクラスタ内のすべてのノードにリストアします。
+
`security key-manager external restore`

+
コマンドが失敗する場合は、にお問い合わせください http://mysupport.netapp.com/["ネットアップサポート"^]。

.. コマンドを入力して、すべての認証キーの `_security key-manager key query_`列にと表示されている `true`ことを確認します `Restored`。
+
すべての認証キーがの場合は `true`、障害のあるコントローラを安全にシャットダウンできます。にアクセスします。



|===
--
.オクム
--
列に表示された出力値に応じて `Restored`、該当する手順を実行します。

[cols="1a,2a"]
|===
| 列の出力値 `Restored` | 実行する手順 


 a| 
`true`
 a| 
OKM情報を手動でバックアップします。

.. と入力してadvancedモードに切り替え `set -priv advanced`、プロンプトが表示されたらと入力します `Y`。
.. 次のコマンドを入力して、キー管理情報を表示します。
+
`security key-manager onboard show-backup`

.. バックアップ情報の内容を別のファイルまたはログファイルにコピーします。
+
これは、災害時にOKMを手動でリカバリしなければならない場合に必要になります。

.. 障害のあるコントローラを安全にシャットダウンできます。にアクセスします。




 a| 
それ以外のすべて `true`
 a| 
.. onboard security key-manager syncコマンドを入力します。
+
`security key-manager onboard sync`

.. プロンプトが表示されたら、32文字のオンボードキー管理のパスフレーズを英数字で入力します。
+
パスフレーズを入力できない場合は、にお問い合わせください http://mysupport.netapp.com/["ネットアップサポート"^]。

.. すべての認証キーの列にと表示されている `true`ことを確認し `Restored`ます。
+
`security key-manager key query`

.. タイプが表示されていることを確認し `Key Manager` `onboard`、OKM情報を手動でバックアップします。
.. 次のコマンドを入力して、キー管理バックアップ情報を表示します。
+
`security key-manager onboard show-backup`

.. バックアップ情報の内容を別のファイルまたはログファイルにコピーします。
+
これは、災害時にOKMを手動でリカバリしなければならない場合に必要になります。

.. 障害のあるコントローラを安全にシャットダウンできます。にアクセスします。


|===
--
====

