---
permalink: asa-r2-70-90/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, replace the boot media 
summary: ASA A70またはA90システムのブートメディアを交換する前に、交換が成功するために必要な要件を満たしていることを確認してください。 
---
= ブートメディアの交換要件- ASA A70およびASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A70 またはASA A90 システムのブートメディアを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、適切な交換用ブートメディアがあること、障害が発生したコントローラのクラスタポートが正常に動作していることを確認すること、オンボードキーマネージャ (OKM) または外部キーマネージャ (EKM) が有効になっているかどうかを確認することが含まれます。

次の要件を確認します。

* 障害が発生したブートメディアを、NetAppから受け取った交換用ブートメディアと交換する必要があります。
* クラスタポートは、自動ブートリカバリプロセス中に2つのコントローラ間の通信に使用されます。障害が発生したコントローラのクラスタポートが正常に動作していることを確認してください。
* OKM の場合、クラスター全体のパスフレーズとバックアップ データも必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/servers.cfg
** /cfcard/kmip/certs/client.crt
** /cfcard/kmip/certs/client.key
** /cfcard/kmip/certs/CA.pem


* 障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。
+
** _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
** _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。




.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["コントローラをシャットダウン"]
