---
permalink: asa-r2-70-90/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: コントローラのHA構成がアクティブで、ASA A70またはASA A90ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。 
---
= システム構成のリストアと確認（ASA A70およびASA A90）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラのHA構成がアクティブで、ASA A70またはASA A90ストレージシステムで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。

システムをサービス状態に戻す前に、HA 構成設定とディスク リストを確認してください。

.手順
. メンテナンスモードでブートします。
+
`boot_ontap maint`

. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。

. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。
. すべてのコンポーネントが同じ状態になっていることを確認し `HA`ます。
+
`ha-config show`

+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. コントローラモジュールの表示されたシステム状態がシステム構成と一致しない場合は、 `HA`コントローラーモジュールの状態:
+
`ha-config modify controller ha`

+
HAの状態には次のいずれかの値を指定できます。

+
** 「 HA 」
** `mcc` （サポートされていません）
** `mccip`（ASAシステムではサポートされません）
** `non-ha` （サポートされていません）


. 設定が変更されたことを確認します。
+
`ha-config show`

. アダプタがすべてのディスクへのパスをリストしていることを確認します。 `storage show disk -p`
+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. 保守モードを終了します :halt

