---
permalink: asa-r2-70-90/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa r2 a70, a90, prerequisite, replace the controller module 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラの交換要件- ASA A70およびASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラの交換手順の要件を確認し、使用しているONTAPオペレーティングシステムのバージョンに適した手順を選択する必要があります。

* すべてのドライブシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールは、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* ブートデバイスはシステムの背面に取り付けられたシステム管理モジュールに配置されているため、コントローラモジュールの交換時にブートデバイスを移動する必要はありません。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。


* コントローラのコンソール出力を必ずテキストログファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。


