---
permalink: asa-r2-70-90/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: asa r2 a70, asa r2 a90, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'システムを完全な状態にリストアするには、LIFを確認し、クラスタの健常性を確認して、障害が発生したパーツをNetAppに戻す必要があります。RMA番号を確認する場合や、交換手順についてサポートが必要な場合は、テクニカルサポートにお問い合わせください。にアクセスするか、日本国内サポート用電話番号：国内フリーダイヤル0066-33-123-265または0066-33-821-274（国際フリーフォン800-800-80-800も使用可能）までご連絡ください。 https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]' 
---
= コントローラ交換後の処理- ASA A70とASA A90
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A70 または ASA A90 システムのコントローラ交換を完了するには、まず NetApp Storage Encryption の設定を復元します（必要な場合）。次に、論理インターフェイス（LIF）がホームポートにレポートしていることを確認し、クラスタの健全性チェックを実行します。最後に、故障した部品を NetApp に返送してください。



== 手順1：LIFを確認してクラスタの健全性を確認する

交換用ノードを使用可能な状態に戻す前に、論理インターフェイスがホームポートにあることを確認し、クラスタの健常性を確認して、自動ギブバックをリセットしてください。

.手順
. 論理インターフェイスがホーム サーバーとポートにレポートしていることを確認します。
+
`network interface show -is-home false`

+
論理インターフェースが false としてリストされている場合は、それらをホーム ポートに戻します。

+
`network interface revert -vserver * -lif *`

. クラスターの健全性を確認します。参照 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAP でスクリプトを使用してクラスタの健全性チェックを実行する方法"^]KB 記事。
. 自動ギブバックを無効にした場合は、再度有効にします。
+
`storage failover modify -node local -auto-giveback true`





== 手順2：故障した部品をNetAppに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
