---
permalink: c800/drive-replace.html 
sidebar: sidebar 
keywords: aff c800, replace the drives 
summary: ドライブの交換は、ドライブで障害が発生したことを示す警告メッセージがプラットフォームからシステムコンソールに記録された場合に必要になります。さらに、オペレータ用ディスプレイパネルの障害 LED と、障害が発生したドライブの障害 LED の両方が点灯します。 
---
= SSDドライブを交換してください- AFF C800
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
障害が発生したSSDドライブは、I/Oの実行中に無停止で交換できます。

ドライブで障害が発生すると、どのドライブで障害が発生したかを示す警告メッセージがシステムコンソールに記録されます。さらに、オペレータ用ディスプレイパネルの障害 LED と、障害が発生したドライブの障害 LED の両方が点灯します。

.作業を開始する前に
* ドライブを交換する前に、ベストプラクティスに従って、最新バージョンの Disk Qualification Package （ DQP ）をインストールします。
* システムコンソールから「 storage disk show -broken 」コマンドを実行して、障害が発生したディスクドライブを特定してください。
+
障害が発生したドライブが障害ドライブのリストに表示されます。表示されない場合は、少し待ってからもう一度コマンドを実行してください。

+

NOTE: 障害ドライブのリストにドライブが表示されるまでに数時間かかることがあります。

* SED 認証が有効になっているかどうかを確認します。
+
ディスクの交換方法は、ディスクドライブの使用方法によって異なります。SED 認証が有効になっている場合は、に記載されている SED の交換手順を使用する必要があります https://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-nve/home.html["ONTAP 9 ネットアップ暗号化パワーガイド"]。SED の交換前後に行う必要のある作業についても説明しています。

* 交換用ドライブがプラットフォームでサポートされていることを確認してください。を参照してください https://hwu.netapp.com["NetApp Hardware Universe の略"]。
* システムのその他のコンポーネントがすべて正常に動作していることを確認します。問題がある場合は、必ずテクニカルサポートにお問い合わせください。


.このタスクについて
最新のファームウェアバージョンでない新しいドライブのドライブファームウェアは自動的に（無停止で）更新されます。

複数のディスクドライブを交換する場合は、ストレージシステムが新しいディスクの存在を認識できるようにするために、障害が発生した各ディスクドライブを取り外してから交換用ディスクドライブを挿入するまで70秒待機する必要があります。

.手順
. 交換用ドライブのドライブ所有権を手動で割り当てる場合は、ドライブの自動割り当て交換用ドライブが有効になっている場合は無効にする必要があります
+

NOTE: ドライブ所有権を手動で割り当てたあと、この手順の以降の手順で自動ドライブ割り当てを再度有効にします。

+
.. 自動ドライブ割り当てが有効になっているかどうかを確認します。「 storage disk option show
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+
自動ドライブ割り当てが有効になっている場合は ' 各コントローラモジュールの Auto Assign 列に on と表示されます

.. 自動ドライブ割り当てが有効になっている場合は無効にします。「 storage disk option modify -node node_name -autoassign off
+
両方のコントローラモジュールで自動ドライブ割り当てを無効にする必要があります。



. 自身の適切な接地対策を行います
. 障害ドライブを物理的に特定します。
+
ドライブで障害が発生すると、システムコンソールに、障害が発生したドライブを示す警告メッセージが記録されます。また、ドライブシェルフのオペレータディスプレイパネルにある警告（黄色） LED と障害が発生したドライブが点灯します。

+

NOTE: 障害が発生したドライブのアクティビティ（緑） LED は点灯する（点灯）ことがあります。点灯している（点灯）はドライブに電力が供給されていることを示しますが、点滅しては I/O アクティビティを示します。障害が発生したドライブには I/O アクティビティはありません。

. 障害ドライブを取り外します。
+
.. ドライブの前面にあるリリースボタンを押して、カムハンドルを開きます。
.. カムハンドルをつかみ、ドライブをもう一方の手で支えながら、ドライブをシェルフから引き出します。


. 交換用ドライブは、 70 秒以上待ってから挿入してください。
+
これにより、ドライブが取り外されたことがシステムで認識されます。

. 交換用ドライブを挿入します。
+
.. カムハンドルを開いた状態で、両手で交換用ドライブを挿入します。
.. ドライブが停止するまで押します。
.. ドライブがミッドプレーンに完全に収まり、カチッという音がして固定されるまで、カムハンドルを閉じます。
+
カムハンドルは、ドライブの前面に揃うようにゆっくりと閉じてください。



. ドライブのアクティビティ（緑） LED が点灯していることを確認します。
+
ドライブのアクティビティ LED が点灯している場合は、ドライブに電力が供給されています。ドライブのアクティビティ LED が点滅しているときは、ドライブに電力が供給されていて、 I/O が実行中です。ドライブファームウェアが自動的に更新されている場合は、 LED が点滅します。

. 別のドライブを交換する場合は、手順 3~7 を繰り返します。
. 手順 1 でドライブの自動割り当てを無効にした場合は、ドライブ所有権を手動で割り当ててから、必要に応じてドライブの自動割り当てを再度有効にします。
+
.. 所有権が未設定のドライブをすべて表示します。「 storage disk show -container-type unassigned 」
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

.. 各ドライブを割り当てます。 `storage disk assign -disk disk_name -owner node_name`
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+
ワイルドカード文字を使用すると、一度に複数のドライブを割り当てることができます。

.. 必要に応じて自動ドライブ割り当てを再度有効にします。「 storage disk option modify -node node_name -autoassign on 」
+
両方のコントローラモジュールで自動ドライブ割り当てを再度有効にする必要があります。



. 障害のある部品は、キットに付属する RMA 指示書に従ってネットアップに返却してください。
+
テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]RMA 番号を確認する場合や、交換用手順にサポートが必要な場合は、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。


