---
permalink: c800/overview.html 
sidebar: sidebar 
keywords: AFF C800 specifications, AFF C800 specs, NetApp AFF C800, AFF C800 hardware 
summary: AFF C800ストレージシステムの主な仕様 
---
= AFF C800の主な仕様
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以下はAFF C800の厳選された仕様です。訪問 https://hwu.netapp.com["NetApp Hardware Universe の略"^]AFF C800 の仕様の完全なリストについては、(HWU) を参照してください。このページは、単一の高可用性ペアを反映しています。



=== AFF C800の主な仕様

プラットフォーム構成: AFF C800シングルシャーシ HA ペア

最大生容量: 7.3680 PB

メモリ: 1280.0000 GB

フォームファクター: 2 つの HA コントローラと 48 個のドライブ スロットを備えた 4U シャーシ

ONTAPバージョン: b_startONTAP: 9.16.1P2b_end

PCIe拡張スロット: 10

最小ONTAPバージョン: ONTAP 9.10.1P15



=== スケールアウトの最大値

|===


| タイプ | HA ペア | 物理容量 | 最大メモリ 


| NAS | 12 | 88.4 PB / 78.5 PiB | 15360 GB 


| SAN | 6 | 44.2 PB / 39.3 PiB | 7680 GB 


| HAペア |  | 7.4 PB / 6.5 PiB | 1280.0000 
|===


=== IO



==== オンボードIO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 4 
|===


==== 合計 IO

|===


| プロトコル | ポート 


| イーサネット 100 Gbps | 20 


| イーサネット 25 Gbps | 16 


| イーサネット 10 Gbps | 32 


| FC 32 Gbps | 32 


| NVMe/FC 32Gbps | 32 


|  | 0 


|  | 0 
|===


==== 管理ポート

|===


| プロトコル | ポート 


| イーサネット 1 Gbps | 4 


| RS-232 115 Kbps | 4 


| USB 12 Mbps | 4 
|===


=== ストレージネットワークのサポート

CIFS、FC、iSCSI、NFS v3、NFS v4.0、NFS v4.1、NFS v4.2、NFSv3/RDMA、NFSv4/RDMA、NVMe/FC、NVMe/TCP、S3、NAS 付き S3、SMB 2.0、SMB 2.1、SMB 2.x、SMB 3.0、SMB 3.1、SMB 3.1.1、



=== システム環境仕様

* 標準電力: 6626 BTU/時
* 最悪の場合の電力: 8417 BTU/時
* 重量: 132.5ポンド/60.1kg
* 高さ: 4U
* 幅: 19インチ IEC ラック準拠 (17.6インチ 44.7 cm)
* 奥行き: 34.5インチ (ケーブル管理ブラケット付き 36.6インチ)
* 動作温度/高度/湿度: 5°C ～ 40°C (41°F ～ 104°F) (標高 3048m、10000 フィート)、相対湿度 8% ～ 90% (結露なし)
* 非動作時温度/湿度: -40°C ～ 70°C (-40°F ～ 158°F)、高度 12,192m (40,000 フィート) まで<br/>相対湿度 10% ～ 95%、結露なし、元の容器内
* 音響ノイズ：表示音響出力（LwAd）：8.0；br／音圧（LpAm）（傍観者位置）：62.8 dB




=== コンプライアンス

* 認証 EMC/EMI: AMCA、FCC、ICES、KC、モロッコ、VCCI
* 安全性認証: BIS、CB、CSA、G_K_U-SoR、IRAM、NOM、NRCS、SONCAP、TBS
* 認証 安全性/EMC/EMI: EAC、UKRSEPRO
* 認証 安全性/EMC/EMI/RoHS: BSMI、CE DoC、UKCA DoC
* 規格 EMC/EMI: BS-EN-55024、BS-EN55035、CISPR 32、EN55022、EN55024、EN55032、EN55035、EN61000-3-2、EN61000-3-3、FCC Part 15 Class A、ICES-003、KS C 9832、KS C 9835
* 安全規格：ANSI/UL60950-1、ANSI/UL62368-1、BS-EN62368-1、CAN/CSA C22.2 No. 60950-1、CAN/CSA C22.2 No. 62368-1、CNS 14336、EN60825-1、EN62368-1、IEC 62368-1、IEC60950-1、IS 13252（パート1）




=== 高可用性

イーサネット ベースのベースボード管理コントローラ (BMC) およびONTAP管理インターフェイス、冗長ホットスワップ可能なコントローラ、冗長ホットスワップ可能な電源装置。

 [//] 2025-10-15 ontap-systems-internal/issues/1357