---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, guide, storage, controllers, administrators, ontap, ha, high, availability 
summary: このガイドでは、 HA ペアのストレージコントローラを新しいコントローラにアップグレードする方法について説明します。 
---
= アグリゲートの再配置ガイドを使用するかどうかを決定します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このマニュアルでは、 HA ペアのストレージコントローラを新しいコントローラにアップグレードし、既存のデータとディスクはすべて維持する方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

このマニュアルは、次のような状況で使用することを想定しています。

* ONTAP 9.8 を実行している。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。
* MetroCluster 構成をアップグレードする場合は、 4 ノード以上の FC 構成であり、すべてのノードで ONTAP 9.8 を実行しています。


MetroCluster IP 設定のアップグレードについては、を参照してください link:http://ie-docs.rtp.openeng.netapp.com/ontap-9_chowchow/topic/com.netapp.doc.dot-mcc-upgrade/home.html["『 MetroCluster アップグレード、移行、および拡張ガイド』"^]。


NOTE: この手順では、 NetApp Storage Encryption （ NSE ）および NetApp Volume Encryption （ NVE ）を使用できます。

次の表に、コントローラのアップグレードでサポートされるモデルマトリックスを示します。

|===
| 古いコントローラ | 交換用コントローラ 


| FAS8020 、 FAS8040 、 FAS8060 、 FAS8080 | FAS8200 、 FAS8300 、 FAS8700 、 FAS9000 


| AFF8020 、 AFF8040 、 AFF8060 、 AFF8080 | AFF A300 、 AFF A400 、 AFF A700 、 AFF A800 * 


| FAS8200 | FAS8700 、 FAS9000 、 FAS8300 


| AFF A300 | AFF A700 、 AFF A800 * 、 AFF A400 
|===

NOTE: コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。

* A800 システムに必要な追加手順については、セクションの「 A800 」を参照している手順を参照してください link:setting_the_fc_or_uta_uta2_configuration_on_node3.html#step23["ノード 3 の UTA / UTA2 ポートを確認して設定し、手順 23 を実行します"]または 。


コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を使用してください link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["『 Controller Hardware Upgrade Express Guide 』を参照してください"] 代わりに、を参照してください  ONTAP 9 製品ドキュメントにアクセスするには、以下の手順を実行
