---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/ensuring_that_the_new_controllers_are_set_up_correctly.html 
keywords: ensure, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: 正しく設定されるようにするには、 HA ペアを有効にする必要があります。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
正しく設定されるようにするには、 HA ペアを有効にする必要があります。さらに、 node3 と node4 が相互のストレージにアクセスできること、およびクラスタ内の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、 node3 が node1 のアグリゲートを所有しており、 node4 が node2 のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認する必要があります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. 次のコマンドを使用して、ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. 次のコマンドを使用して、 node3 と node4 が同じクラスタに属していることを確認します。出力を確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node3 と node4 が相互のストレージにアクセスできることを確認します。出力を確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを使用して、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していない場合は、次のコマンドを使用してデータ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. 次のコマンドを使用して、 node3 が node1 のアグリゲートを所有していること、および node4 が node2 のアグリゲートを所有していることを確認します。
+
'storage aggregate show-owner-name<node3 >`

+
「 storage aggregate show-owner-name <node4 > 」という形式で指定します

. 次のコマンドを使用して、オフラインになっているボリュームがないかどうかを確認します。
+
volume show -node <node3 > -state offline`

+
volume show -node <node4 > -state offline`

. オフラインになっているボリュームがある場合は、セクションで取得したオフラインボリュームのリストと比較します link:preparing_the_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]必要に応じて、次のコマンドを使用して、ボリュームごとに 1 回、オフラインボリュームをオンラインにします。
+
'volume online -vserver <vserver-name> -volume <volume_name>`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
'system license add - license-code <license_code, license_code, license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
「 system license delete -serial -number <node-serial_number> -package <license_package> 」という 2 つのライセンスがあります

+
** 次のコマンドを使用して、期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 次のコマンドを使用して、使用していないライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
「 system license delete -serial-number <node1 serial number> -package * 」という名前になります

+
「 system license delete -serial-number <node2 serial number> -package * 」のように表示されます

+
次の出力が表示されます。

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
すべてのパッケージを削除するには 'y' を入力します



. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
の出力と、でキャプチャした出力を比較することもできます link:preparing_the_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

. 構成に NetApp Storage Encryption （ NSE ）を使用していた場合、「 setenv. bootarg.storageencryption.support 」コマンドを「 true 」に設定するには、「 kmip.init.maxwait>` variable 」を「 off 」に設定します（手順 27 ）。次のコマンドを使用して、変数をリセットする必要があります。
+
「 diag 」のコマンドは、 systemshell -node <nodename> command sudo kenv -u -p kmip.init.maxwait` です

. 両方のノードで次のコマンドを使用して SP を設定します。
+
「 system service-processor network modify -node <node_name > 」のように指定します

+
を参照してください link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/home.html["システムアドミニストレーションリファレンス"] SP およびの詳細については、を参照してください  「 system service-processor network modify 」コマンドの詳細については、を参照してください。

. 新しいノードの 1 つで次の操作を実行します。
+
.. 次のコマンドを使用して advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. 次のコマンドを入力します。
+
「 storage failover modify -node <node_name > -CIFS-NDO -duration default | medium | low 」

+
*** システムのワークロードが 50% ～ 75% の場合は、「 m edium 」と入力します。
*** システムのワークロードが 75% ～ 100% の場合は 'low' と入力します


.. 次のコマンドを使用して、 admin レベルに戻ります。
+
「特権管理者」

.. システムをリブートして、変更が有効になっていることを確認します。


. 新しいノードにスイッチレスクラスタをセットアップする場合は、ネットアップサポートサイトの「 2 ノードスイッチレスクラスタへの移行」の手順に従ってください。


ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、セクションを完了します link:setting_up_storage_encryption_on_the_new_controller_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の項を実行します 。
