---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/getting_an_ip_address_of_an_external_key_management_server_for_storage_encryption.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: アップグレード後は、すぐにストレージ暗号化を設定する必要があります。 
---
= ストレージ暗号化用の外部キー管理サーバの IP アドレスを取得します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アップグレード後は、すぐにストレージ暗号化を設定し、クラスタ全体の認証キーを確立して、以前のノードレベルの認証キーを置き換える必要があります。

.手順
. 次のコマンドを使用して、キー管理サーバとの通信に必要なクライアントとサーバのセキュアソケットレイヤ（ SSL ）証明書をインストールします。
+
「セキュリティ証明書のインストール」

. 各ノードで次のコマンドを使用して、すべてのノードでストレージ暗号化を設定します。
+
「セキュリティキーマネージャの設定」

. 次のコマンドを使用して、各キー管理サーバの IP アドレスを追加します。
+
「セキュリティキーマネージャの追加」

. 次のコマンドを使用して、クラスタ内のすべてのノードで同じキー管理サーバが設定され使用可能になっていることを確認します。
+
「 securitykey-manager show -status 」

. 次のコマンドを使用して、クラスタ全体の新しい認証キーを作成します。
+
「 securitykey-manager create-key 」を選択します

. 新しい認証キー ID をメモします。
. 次のコマンドを使用して、すべての自己暗号化ドライブのキーを新しい認証キーに変更します。
+
「 storage encryption disk modify -disk * -data-key-id <authentication_key_id>` 」





=== KMIP サーバを使用して認証を管理します

ONTAP 9.8 では、 Key Management Interoperability Protocol （ KMIP ）サーバを使用して認証キーを管理できます。

.手順
. 次のコマンドを使用して、新しいコントローラを追加します。
+
「 securitykey-manager setup -node <new_controller_name>` 」のように指定します

. 次のコマンドを使用して、キー管理ツールを追加します。
+
「 securitykey-manager-add <key_manager_server_ip_address >` 」

. 次のコマンドを使用して、キー管理サーバが設定され、クラスタ内のすべてのノードから使用できることを確認します。
+
「 securitykey-manager show -status 」

. 次のコマンドを使用して、リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
「 securitykey-manager restore -node <new_controller_name>` 」のように指定します

. 次のコマンドを使用して、すべての自己暗号化ディスクのキーを新しい認証キーに変更します。
+
'storage encryption disk modify -disk * [-data-key-id nonMSID AK

. 連邦情報処理標準（ FIPS ）を使用する場合は、次のコマンドを使用して、すべての自己暗号化ディスクのキーを新しい認証キーに変更します。
+
「 storage encryption disk * modify -disk * [-fips-key-id nonAK 」」





=== オンボードキーマネージャを使用してストレージ暗号化を管理します

OKM は暗号キーを管理できます。OKM を使用する場合は、アップグレードを開始する前にパスフレーズとバックアップ資料を記録しておく必要があります。

.手順
. パスフレーズを安全な場所に保存します。
. リカバリ用のバックアップを作成します。次のコマンドを実行して出力を保存します。
+
「 key-manager onboard show-backup 」を選択します





=== SnapMrerror 関係の休止（オプション）

交換手順を進める前に、すべての SnapMirror 関係が休止状態になっていることを確認する必要があります。休止された SnapMirror 関係は、リブート後およびフェイルオーバー後も休止状態のままです。

.手順
. 次のコマンドを使用して、デスティネーションクラスタの SnapMirror 関係のステータスを確認します。
+
「 Snapmirror show 」のように表示されます

+

NOTE: このステータスが「 Transferring 」の場合は、次のコマンドを使用して転送を中止する必要があります。「 snapmirror abort -destination-path vserver <vserver name> 」

+
SnapMirror 関係が Transferring 状態でない場合は、中止は失敗します。

. 次のコマンドを使用して、クラスタ間のすべての関係を休止します。
+
'snapmirror quiesce -destination-path vserver <vserver name> 」を指定します


