---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: ARL を使用して ONTAP 9.8 を実行しているコントローラのペアをアップグレードできるかどうかを確認します。 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用して ONTAP 9.8 を実行しているコントローラのペアをアップグレードできるかどうかは、プラットフォーム、および元のコントローラと交換用コントローラの両方の構成によって異なります。



==== ARL のアップグレードがサポートされます

ARL 手順 for ONTAP 9.8 を使用してノードのペアをアップグレードする場合は、 ARL が元のコントローラと交換用コントローラで実行可能であることを確認する必要があります。

元のシステムでサポートされるすべての定義済みアグリゲートのサイズとディスク数を確認する必要があります。次に、サポートされるアグリゲートサイズとディスク数を、新しいシステムでサポートされるアグリゲートサイズとディスク数と比較する必要があります。この情報は、で確認できます link:https://hwu.netapp.com["Hardware Universe"]。新しいシステムでサポートされるアグリゲートサイズとディスク数は、元のシステムでサポートされるアグリゲートサイズとディスク数以上であることが必要です。

元のコントローラを交換したときに、新しいノードが既存のノードとクラスタの一部になることができるかどうかは、クラスタ混在ルールで検証する必要があります。クラスタ混在ルールの詳細については、を参照してください link:https://hwu.netapp.com["Hardware Universe"]。


NOTE: 内蔵ドライブをサポートするシステム（ FAS2700 または AFF A250 など）をアップグレードする場合でも内蔵ドライブがないときは、手順の in_using アグリゲートの再配置を使用してコントローラハードウェア _ を手動でアップグレードしてください。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



==== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



==== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
を参照してください link:https://hwu.netapp.com["Hardware Universe"] ディスクサポート情報については、を参照してください。

* 内蔵ドライブを搭載したエントリレベルのコントローラ。たとえば、 FAS 2500 などです。
+
内蔵ドライブを搭載したエントリレベルのコントローラをアップグレードする場合は、手順の volume_in を移動して、 clustered Data ONTAP を実行するノードのペアをアップグレードするを参照してください link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["『 Controller Hardware Upgrade Express Guide 』を参照してください"]。





==== トラブルシューティング

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshooting_overview.html["トラブルシューティング"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策が見つからない場合は、テクニカルサポートにお問い合わせください。
