---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/installing_and_booting_node3.html 
keywords: installing, booting, node3, ontap 
summary: ノード 3 をラックに設置し、ノード 1 の接続をノード 3 に転送し、ノード 3 をブートして、 ONTAP をインストールする必要があります。 
---
= node3 をインストールしてブートします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 3 をラックに設置し、ノード 1 の接続をノード 3 に転送し、ノード 3 をブートして、 ONTAP をインストールする必要があります。そのあと、このセクションで説明するように、ノード 1 のスペアディスク、ルートボリュームに属するディスク、およびその前の手順でノード 2 に再配置されなかったルート以外のアグリゲートを再割り当てする必要があります。

再配置処理はこのフェーズの開始時に一時停止されます。このプロセスはほとんど自動化されており、処理は一時停止してステータスを確認できます。この処理は手動で再開する必要があります。また、 SAN LIF がノード 3 に正常に移動したことを確認する必要があります。

ノード 1 にインストールされている ONTAP 9 のバージョンが異なる場合は、ノード 3 をネットブートする必要があります。node3 のインストールが完了したら、 Web サーバに保存されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:preparing_for_netboot.html["ネットブートを準備"]。

.重要
* ストレージアレイに接続されている V シリーズシステム、またはストレージアレイに接続された FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、を完了する必要があります <<step1,手順 1.>> から <<step21,手順 21>>をクリックしてから、このセクションの指示に従います link:setting_the_fc_or_uta_uta2_configuration_on_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および  必要に応じて、メンテナンスモードでコマンドを入力します。その後、このセクションに戻ってからを使用して再開する必要があります <<step23,手順 23>>。
* ストレージディスクが搭載されたシステムをアップグレードする場合は、このセクション全体を完了して、にアクセスする必要があります link:setting_the_fc_or_uta_uta2_configuration_on_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および  セクションで、クラスタ・プロンプトでコマンドを入力します。


.手順
. [[step1] ノード 3 のラックスペースがあることを確認します。
+
ノード 1 とノード 2 が別々のシャーシに搭載されている場合は、ノード 3 をノード 1 と同じラックの場所に設置できます。ただし、 node1 が node2 の同じシャーシに設置されている場合は、 node3 を専用のラックスペースに配置する必要があります。その場合は、 node1 の場所に近い場所に配置することを推奨します。

. [[step2] ノードモデルの * 設置およびセットアップ手順 * に従って、ラックにノード 3 をインストールします。
+

NOTE: 両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 と node3 をシャーシに設置します。そうしないと、ノードをブートしたときにノードがデュアルシャーシ構成と同じように動作し、 node4 をブートした場合、ノード間のインターコネクトは稼働しません。

. [[step3]] ケーブルノード 3 を接続し、ノード 1 からノード 3 に接続を移動します。
+
『セットアップガイド』またはを使用して、次の配線を行います link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 仮想化インストール要件およびリファレンスガイド"] node3 プラットフォームについて、該当するディスクシェルフガイド、およびを参照してください ：

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカードまたはクラスタインターコネクトケーブルの接続を node1 から node3 に移動する必要はない場合があります。MetroCluster 構成の場合、 FC-VI ケーブルの接続を node1 から node3 に移動する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. [[step4]] ノード 3 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 もリブートします。ただし、 node4 のブートはあとで破棄することができます。

+

NOTE: node3 をブートすると、次の警告メッセージが表示される場合があります。

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
....
. [[step5] 」という警告メッセージがに表示される場合 <<step4,手順 4>>を使用して、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

NOTE: * 遅延をオーバーライドしないでください * 。 * バッテリーの充電に失敗すると、データが失われるおそれがあります * 。を参照してください link:preparing_for_netboot.html["ネットブートを準備"]。



. [[step6] 次のいずれかの操作を選択して、ネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。アップグレードの実行中にデータ LIF IP を使用しないでください。データ LIF が停止する可能性があります。

+
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで次のコマンドを使用して、自動的に接続を設定します。 ifconfig e0M -auto 


| 実行されていません | ブート環境プロンプトで次のコマンドを使用して、接続を手動で設定します。 ifconfig e0M -addr= <filer_addr> -mask= <netmask> -gw= <gateway> -dns= <dns_addr> domain= <dns_domain> `<filer_addr>`<netmask>` はストレージシステムのネットワークマスクです。「 <gateway>` 」は、ストレージシステムのゲートウェイです。「 <dns_addr> 」は、ネットワーク上のネームサーバの IP アドレスです。このパラメータはオプションです。「 <dns_domain> 」は、 Domain Name Service （ DNS ；ドメインネームサービス）ドメイン名です。このパラメータはオプションです。* 注 * ：インターフェイスによっては、他のパラメータが必要になる場合があります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。 
|===
. [[step7] node3 でネットブートを実行します。
+
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| その他すべてのシステム | netboot\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
「 <path_the_web-accessible_directory> 」は、「 <ONTAP_version>_image.tgz 」をダウンロードした場所を指します link:preparing_for_netboot.html["ネットブートを準備"]。

+

NOTE: トランクを中断しないでください。

. [[step8]] ブートメニューからオプション [(7) 新しいソフトウェアを最初にインストールする ] を選択します
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+

NOTE: 次のメッセージは無視してください 'This 手順 is not supported for Non-Disruptive Upgrade on an HA pair'コントローラのアップグレードではなく、 ONTAP による環境の無停止アップグレードも記録されています。新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境 All ONTAP リリース

. [[step9]] 手順を続行するかどうかを確認するメッセージが表示された場合は、「 y 」と入力し、パッケージのプロンプトが表示されたら URL を入力します。
+
http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` にアクセスします

. [[step10] コントローラモジュールをリブートするには、次の手順を実行します。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
バックアップ設定を今すぐ復元しますか ? {y|n}`

.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
' 新しくインストールしたソフトウェアの使用を開始するには ' ノードを再起動する必要があります今すぐリブートしますか？{y|n}`

+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. [[step11]] ブートメニューからメンテナンスモード「 5 」を選択し、起動を続行するように求めるプロンプトが表示されたら「 y 」と入力します。
. [[step12]] 次のコマンドを使用して、コントローラとシャーシが HA として設定されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

. [[step13]] コントローラとシャーシが HA として設定されていない場合は、次のコマンドを使用して構成を修正します。
+
「 ha-config modify controller 」を参照してください

+
HA 構成変更シャーシ HA

+
MetroCluster 構成の場合は、次のコマンドを使用してコントローラとシャーシを変更します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. [[step14]] 次のコマンドを使用して、メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境のプロンプトで Ctrl+C を押し、 AUTOBOOT を中断します。

. [[step15]] node2 で、次のコマンドを使用してシステムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. [step16]] on node3 で、ブート環境のプロンプトで次のコマンドを使用して日付を確認します。
+
「日付」

. [[step17]] 必要に応じて、次のコマンドを使用して、 node3 の日付を設定します。
+
'Set date <mm/dd/yyyy>`

. [step18]] on node3 で、ブート環境のプロンプトで次のコマンドを使用して時間を確認します。
+
「時間」

. [[step19]] 必要に応じて、次のコマンドを使用して、 node3 の時間を設定します。
+
時刻を設定します

. [[step20]] 必要に応じて、次のコマンドを使用して、 node3 にパートナーシステム ID を設定します。
+
'setenv partner-sysid <node2 _sysid>`

+
.. 設定を保存します。
+
'aveenv



. [step2]] 新しいノードのブートローダーで 'partner-sysid' パラメータを設定する必要がありますnode3 の場合、「 partner-sysid 」は node2 のものである必要があります。次のコマンドを使用して 'partner-sysid' の node3 を確認します
+
printenv partner-sysid

. [[step22]] 次のいずれかの操作を実行します。
+
|===
| システムの状態 | 説明 


| ディスクがあり、バックエンドストレージがない | に進みます <<step23,手順 23>> 


| は、 V シリーズシステム、または FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムです  a| 
.. セクションに移動します link:setting_the_fc_or_uta_uta2_configuration_on_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"] をクリックし、このセクションのサブセクションを完了します。
.. このセクションに戻って、から始めて残りの手順を実行します <<step23,手順 23>>。


* 重要 * ： V シリーズまたは FlexArray 仮想化ソフトウェアで ONTAP をブートする前に、オンボード FC ポート、 CNA オンボードポート、 CNA カードを再設定する必要があります。

|===
. [[step23]] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
システムにテープ SAN がある場合は、イニシエータをゾーニングする必要があります。必要に応じて、を参照してオンボードポートをイニシエータに変更します link:setting_the_fc_or_uta_uta2_configuration_on_node3.html#configure-fc-ports-on-node3["ノード 3 で FC ポートを設定しています"]。ゾーニングの詳細な手順については、ストレージアレイとゾーニングに関するドキュメントを参照してください。

. [[step24]] ストレージアレイに FC イニシエータポートを新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. [[step25]] ストレージアレイ上のアレイ LUN に関連付けられたホストまたはボリュームグループで、 World Wide Port Name （ WWPN ）値を変更します。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. [[step26]] スイッチベースのゾーニングを使用する構成の場合は、ゾーニングを調整して新しい WWPN 値を反映します。
. [[step27]] NetApp Storage Encryption （ NSE ）がこの構成で使用されている場合、「 setenvarg.storageencryption.support 」コマンドは「 true 」に設定する必要があります。「 kmip.init.maxwait` 」変数は、 node1 構成のロード後にブートループが発生しないように「 off 」に設定する必要があります。
+
'etenv bootarg.storageencryption.support true

+
'etenv kmip.init.maxwait off

. [[step28]] 次のコマンドを使用して、ブートメニューからノードをブートします。
+
「 boot_ontap menu

+
FC または UTA / UTA2 設定がない場合は、を実行します link:setting_the_fc_or_uta_uta2_configuration_on_node3.html#step15["ノード 3 の手順 15 で UTA / UTA2 ポートを確認して設定します"] ノード 3 がノード 1 のディスクを認識できるようにします。

. [step29] FlexArray 仮想化ソフトウェアがストレージアレイに接続されている MetroCluster 構成、 V シリーズシステム、およびシステムについて、ノードに接続されているディスクを検出するために、ノード 3 の FC ポートまたは UTA / UTA2 ポートを設定する必要があります。このタスクを完了するには、セクションに進んでください link:setting_the_fc_or_uta_uta2_configuration_on_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"]。

