---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/installing_and_booting_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: ノード 4 をラックに設置し、ノード 2 の接続をノード 4 に転送し、ブートノード 4 をブートして、 ONTAP をインストールする必要があります。 
---
= ノード 4 をインストールしてブートします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 4 をラックに設置し、ノード 2 の接続をノード 4 に転送し、ノード 4 をブートして、 ONTAP をインストールする必要があります。次に、このセクションで説明するように、ノード 2 のスペアディスク、ルートボリュームに属するディスク、およびプロセスの前にノード 3 に再配置されなかったルート以外のアグリゲートを再割り当てする必要があります。

再配置処理はこのフェーズの開始時に一時停止されます。このプロセスはほとんどが自動化されており、処理は一時停止してステータスを確認できます。この処理は手動で再開する必要があります。

node2 に同じバージョンの ONTAP 9 がインストールされていない場合は、 node4 をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに格納されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:preparing_for_netboot.html["ネットブートを準備"]。

.重要
* ストレージアレイに接続されている V シリーズシステム、またはストレージアレイに接続されている FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、これで完了です <<Step1,手順 1.>> から <<Step21,手順 21>>をクリックしてから、このセクションの指示に従ってください link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"] およびへ 、保守モードでコマンドを入力します。その後、このセクションに戻ってからを使用して再開する必要があります <<Step23,手順 23>>。
* ただし、ストレージディスクが搭載されたシステムをアップグレードする場合は、このセクション全体を完了してから、に進む必要があります link:setting_the_fc_or_uta_uta2_configuration_on_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"]クラスタ・プロンプトでコマンドを入力します。


.手順
. [ 手順 1] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 が node2 とは別のシャーシにある場合は、 node3 と同じ場所に node4 を配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. ノード 4 をケーブル接続します。 node2 から node4 に接続を移動します。
+
『 Installation and Setup Instructions 』またはの手順に従って、次の接続をケーブル接続します link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.vs-irrg/home.html["FlexArray 仮想化インストール要件およびリファレンスガイド"] ノード 4 のプラットフォームの場合は、該当するディスクシェルフガイドおよびを参照してください ：

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカード / FC-VI カードまたはインターコネクト / FC-VI ケーブルの接続を node2 から node4 に移動する必要はありません。MetroCluster 構成の場合は、 FC-VI ケーブルの接続を node2 から node4 に移動する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. ノード 4 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+

NOTE: node4 をブートすると、次の警告メッセージが表示される場合があります。

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.  When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 手順 4 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+
.注意：この遅延は無視しないでください。バッテリの充電に失敗すると、データが失われる可能性があります。

NOTE: を参照してください link:preparing_for_netboot.html["ネットブートを準備"]。



. 次のいずれかを実行してネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。アップグレードの実行中にデータ LIF IP を使用しないでください。データ LIF が停止する可能性があります。

+
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで次のコマンドを使用して、自動的に接続を設定します。 ifconfig e0M -auto 


| 実行されていません | ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。 ifconfig e0M -addr= <filer_addr> -mask= <netmask> -gw= <gateway> -dns= <dns_addr> domain= <dns_domain> `<filer_addr>`<netmask>` はストレージシステムのネットワークマスクです。「 <gateway>` 」は、ストレージシステムのゲートウェイです。「 <dns_addr> 」は、ネットワーク上のネームサーバの IP アドレスです。このパラメータはオプションです。「 <dns_domain> 」は DNS ドメイン名です。このパラメータはオプションです。* 注 * ：インターフェイスによっては、他のパラメータが必要になる場合があります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。 
|===
. ノード 4 でネットブートを実行します。
+
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://<web_server_ip/path_to_web-accessible_directory>/netboot/kernel` 


| その他すべてのシステム | netboot\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` 
|===
+
「 <path_the_web-accessible_directory> 」は、手順 1 の「 <ONTAP_version>_image.tgz 」をダウンロードした場所に配置する必要があります link:preparing_for_netboot.html["ネットブートを準備"]。

+

NOTE: トランクを中断しないでください。

. 起動メニューからオプション（ 7 ） Install new software first （新しいソフトウェアを最初にインストール）を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+

NOTE: 次のメッセージは無視してください 'This 手順 is not supported for Non-Disruptive Upgrade on an HA pair'コントローラのアップグレードではなく、 ONTAP による環境の無停止アップグレードも記録されています。新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境 All ONTAP リリース

. 手順を続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力し、パッケージの入力を求められたら URL を入力します。
+
http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` にアクセスします

. 次の手順を実行してコントローラモジュールをリブートします。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. ブート・メニューからメンテナンス・モード「 5 」を選択し、ブートを続行するように求めるプロンプトが表示されたら「 y 」と入力します。
. 次のコマンドを使用して、コントローラとシャーシが HA として構成されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

. コントローラとシャーシが HA として構成されていない場合は、次のコマンドを使用して構成を修正します。
+
「 ha-config modify controller 」を参照してください

+
HA 構成変更シャーシ HA

+
MetroCluster 構成の場合は、次のコマンドを使用してコントローラとシャーシを変更します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. 次のコマンドを使用してメンテナンスモードを終了します。
+
「 halt 」

+
ブート環境のプロンプトで Ctrl+C を押し、 AUTOBOOT を中断します。

. [[Step15]] ノード 3 で、次のコマンドを使用して、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. node4 で、ブート環境のプロンプトで次のコマンドを使用して日付を確認します。
+
「日付」

. 必要に応じて、次のコマンドを使用して node4 に日付を設定します。
+
'Set date <mm/dd/yyyy>`

. node4 で、ブート環境のプロンプトで次のコマンドを使用して時間を確認します。
+
「時間」

. 必要に応じて、次のコマンドを使用して node4 に時間を設定します。
+
時刻を設定します

. 必要に応じて、次のコマンドを使用して、 node4 にパートナーシステム ID を設定します。
+
'setenv partner-sysid <node2 _sysid>`

+
.. 設定を保存します。
+
'aveenv



. [Step2]] 新しいノードのブートローダーでは、「 partner-sysid 」パラメータを設定する必要があります。node4 の場合、「 partner-sysid 」は node3 のものでなければなりません。次のコマンドを使用して 'partner-sysid' の node3 を確認します
+
printenv partner-sysid

. 次のいずれかを実行します。
+
|===
| システムの状態 | 作業 


| ディスクがあり、バックエンドストレージがない | に進みます <<Step23,手順 23>>。 


| は、 V シリーズシステム、または FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムです  a| 
.. セクションに移動します link:setting_the_fc_or_uta_uta2_configuration_on_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"] をクリックし、このセクションのサブセクションを完了します。
.. このセクションに戻って、から始めて残りの手順を実行します <<Step23,手順 23>>。


* 重要 * ： V シリーズまたは FlexArray 仮想化ソフトウェアで ONTAP をブートする前に、オンボード FC ポート、 CNA オンボードポート、 CNA カードを再設定する必要があります。

|===
. [[Step23]] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
システムにテープ SAN がある場合は、イニシエータをゾーニングする必要があります。必要に応じて、を参照してオンボードポートをイニシエータに変更します link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"]。ゾーニングの詳細な手順については、ストレージアレイとゾーニングに関するドキュメントを参照してください。

. FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. ストレージアレイ上のアレイ LUN に関連付けられたホストまたはボリュームグループの World Wide Port Name （ WWPN ；ワールドワイドポート名）値を変更する。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. スイッチベースのゾーニングを使用している場合は、新しい WWPN 値が反映されるようにゾーニングを調整します。
. この構成で NetApp Storage Encryption （ NSE ）を使用している場合、ノード 1 の構成のロード後にブートループが発生しないようにするには、「 bootargen.storageencryption.support 」コマンドを「 true 」に設定し、「 kmip.init.maxwait` 」変数を「 off 」に設定する必要があります。
+
'etenv bootarg.storageencryption.support true

+
'etenv kmip.init.maxwait off

. 次のコマンドを使用して、ノードをブートメニューにブートします。
+
「 boot_ontap menu

+
FC または UTA / UTA2 設定がない場合は、を実行します link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#Step15["手順 15"] ノード 4 が node2 のディスクを認識できるようにします。

. MetroCluster 構成の場合、 V シリーズシステムおよび FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムノードに接続されているディスクを検出するためには、 node4 にある FC ポートまたは UTA / UTA2 ポートを設定して設定する必要があります。このタスクを完了するには、セクションに進んでください link:setting_the_fc_or_uta_uta2_configuration_on_node4.html["ノード 4 で FC または UTA / ut2 の設定を行います"]。

