---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/issues_that_can_arise_in_multiple_stages_of_the_procedure.html 
keywords: issues, arise, multiple, stages, procedure, ndac 
summary: 手順のさまざまな段階で問題が発生する可能性があります。 
---
= 手順の複数の段階で発生する可能性のある問題
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
手順のさまざまな段階で問題が発生する可能性があります。



== 予期しない「 storage failover show 」コマンドの出力が表示されます

手順の実行中に、すべてのデータアグリゲートをホストするノードがパニック状態になったり、誤ってリブートされたりした場合は、リブート、パニック状態、電源再投入の前後に「 storage failover show 」コマンドの出力が想定外に表示されることがあります。

ステージ 2 、ステージ 3 、ステージ 4 、またはステージ 5 の「 storage failover show 」コマンドの出力結果に予期しないものが表示されることがあります。

次の例は、すべてのデータアグリゲートをホストするノードでリブートやパニックが発生していない場合の「 storage failover show 」コマンドの出力を示しています。

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     false     Unknown
node2    node1     false     Node owns partner aggregates as part of the non-disruptive head upgrade procedure. Takeover is not possible: Storage failover is disabled.
....
次の例は、リブートまたはパニック後の「 storage failover show 」コマンドの出力例を示しています。

....
cluster::> storage failover show

                   Takeover
Node     Partner   Possible  State Description
-------  --------  --------- -----------------
node1    node2     -         Unknown
node2    node1    false      Waiting for node1, Partial giveback, Takeover is not possible: Storage failover is disabled
....
ノードが部分的なギブバック状態にあること、およびストレージフェイルオーバーが無効になっていることを示す出力が表示されますが、このメッセージは無視してもかまいません。

対処は不要です。ノードペアのアップグレード手順に進みます。
