---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: ノード 4 のネットワーク設定を確認したあと、ノード 3 からノード 4 にアグリゲートを再配置します。 
---
= node2 によって所有されているルート以外のアグリゲートと NAS データ LIF を、 node3 から node4 に移動します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 4 のネットワーク設定を確認し、ノード 3 からノード 4 にアグリゲートを再配置する前に、ノード 2 に現在ノード 3 に属する NAS データ LIF が、ノード 3 からノード 4 に再配置されていることを確認する必要があります。また、ノード 4 に SAN LIF が存在することも確認する必要があります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 4 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認します。

.手順
. 次のコマンドを使用して、再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. 次のコマンドを使用して、再配置処理を再開します。
+
「システムコントローラの交換が再開」

. システムは次のチェックを実行します。
+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、システムによって、 node2 によって所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node4 に再配置されます。リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. 次のコマンドを使用して、アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、取り外した LIF をリストアしてリバートします。次のコマンドを使用して、削除した LIF を表示します。
+
cluster controller -replacement network ヒエラー（クラスタコントローラ交換ネットワークが取り外されました） -interface show

+
LIF が削除された場合は、次のコマンドを使用してホームノードをノード 4 にリストアします。

+
クラスタ・コントローラ交換ネットワークが取り外されましたインタフェース・リストア -home-node

. 次のコマンドを使用して、処理を再開し、必要なポストチェックの実行をシステムに求めるプロンプトを表示します。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



