---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: ONTAP コマンドラインで次のコマンドを入力して、コントローラの交換プロセスを開始します。 
---
= ノードをアップグレードする準備をします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
<stdin> で未解決のディレクティブ : ../_include/ru_auto_prepare_nodes_upgrade_top_step_3.adoc[]

. [[step4]] システムコンソールのコントローラ交換用手順の指示に従って、次の一連のコマンドを実行します。
+
次のコマンドの出力を個別に実行して保存する必要があります。

+
** vserver services name-service dns show
** network interface show -curr-node <nodename> -role <cluster 、 intercluster 、 node-mgmt 、 cluster-mgmt 、 data >
** network port show -node <node_name > -type physical
** service-processor show -node * -instance の各コマンドを実行します
** network fcp adapter show -node <node_name >
** network port ifgrp show の設定
** system node show -instance -node <node_name >
** run -node <node_name >sysconfig
** storage aggregate show -node <node_name >
** volume show -node <node_name >
** storage array config show -switch <switch_name> のように表示されます
** system license show -owner <node_name >
** storage encryption disk show のコマンド
** security key-manager backup show のコマンドは
** security key-manager external show のコマンド
** security key-manager external show-status のこと
** reachability show-detailability





NOTE: オンボードキーマネージャ（ OKM ）を使用する NetApp Volume Encryption を使用している場合、キー管理ツールのパスフレーズを使用して、あとで手順でキー管理ツールの再同期を完了してください。

<stdin> で未解決のディレクティブ：： ./_include/ru_auto_correct_aggregate_owner.adoc[]

<stdin> で未解決のディレクティブ : ../_include/ru_auto_license.adoc[]
