---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/reboots_panics_or_power_cycles.html 
keywords: reboots, panics, power, cycles, node, crash 
summary: システムがクラッシュする場合–リブート、パニック状態、または電源の再投入が行われます。 
---
= リブート、パニック、電源再投入
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アップグレードの各段階で、システムがクラッシュする（リブート、パニック状態、または電源の再投入）場合があります。

これらの問題の解決策は、状況によって異なります。



== 事前チェックフェーズでのリブート、パニック、電源再投入



=== HA ペアを有効にして事前チェックフェーズの前にノード 1 またはノード 2 がクラッシュした場合

事前チェックフェーズの前にノード 1 またはノード 2 がクラッシュした場合は、再配置されたアグリゲートがなく、 HA ペア構成が有効なままになります。

テイクオーバーとギブバックは正常に実行されます。

.手順
. コンソールで、システムで発行された EMS メッセージを確認し、推奨される対処方法を実行します。
. ノードペアのアップグレード用手順に進みます。




== 最初のリソースリリースフェーズでリブート、パニック、電源再投入が発生した場合



=== HA ペアを有効にすると、リソースの最初のリリースフェーズでノード 1 がクラッシュします

一部またはすべてのアグリゲートがノード 1 からノード 2 に再配置されており、 HA ペアが有効なままです。node2 は、ノード 1 のルートボリュームと再配置されていないルート以外のアグリゲートをテイクオーバーします。

再配置されたアグリゲートの所有権は、ホーム所有者が変更されていないためにテイクオーバーされたルート以外のアグリゲートの所有権と同じになります。

node1 の状態が「 waiting for giveback 」になると、 node2 はノード 1 のルート以外のすべてのアグリゲートをギブバックします。

.手順
. ノード 1 がブートすると、ノード 1 のルート以外のすべてのアグリゲートがノード 1 に戻されます。次のコマンドを使用して、 node1 から node2 へのアグリゲートの手動での再配置を実行する必要があります。「 storage aggregate relocation start -node node1 -destination node2 -aggregate-list * -ndocontroller -upgrade true
. ノードペアのアップグレード用手順に進みます。




=== HA ペアを無効にすると、リソースの最初のリリースフェーズでノード 1 がクラッシュします

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 1 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== リソースの最初のリリースフェーズで HA ペアを有効にした状態で node2 に障害が発生する

ノード 1 の一部またはすべてのアグリゲートが node2 に再配置されています。HA ペアが有効になります。

ノード 1 で、ノード 2 のすべてのアグリゲートと、ノード 2 に再配置された独自のアグリゲートがテイクオーバーされます。ノード 2 がブートすると、アグリゲートの再配置が自動的に完了します。

.手順
. node2 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== リソースの最初のリリースフェーズと HA ペアの無効化後に、ノード 2 がクラッシュします

ノード 1 ではテイクオーバーが実行されません。

.手順
. node2 を起動します。
+
node2 のブート中に、すべてのアグリゲートでクライアントが停止します。

. 残りのノードペアのアップグレード用手順に進みます。




== 最初の検証フェーズでリブート、パニック、または電源の再投入が発生した場合



=== HA ペアを無効にして最初の検証フェーズで node2 がクラッシュします

HA ペアがすでに無効になっているため、ノード 2 のクラッシュ後にノード 3 はテイクオーバーしません。

.手順
. node2 を起動します。
+
node2 のブート中に、すべてのアグリゲートでクライアントが停止します。

. ノードペアのアップグレード用手順に進みます。




=== HA ペアを無効にして初回の検証フェーズでノード 3 がクラッシュした場合

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 3 を起動します。
. ノードペアのアップグレード用手順に進みます。




== 最初のリソース再取得フェーズでのリブート、パニック、電源再投入



=== アグリゲートの再配置中にリソースを再取得する最初のフェーズでノード 2 がクラッシュする

node2 の一部またはすべてのアグリゲートがノード 1 からノード 3 に再配置されています。node3 は、再配置されたアグリゲートからデータを提供します。HA ペアが無効になっているため、テイクオーバーはありません。

再配置されなかったアグリゲートのクライアントが停止しています。ノード 2 のブート時に、ノード 1 のアグリゲートがノード 3 に再配置されます。

.手順
. node2 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== アグリゲートの再配置中に、最初のリソースのリ回復フェーズでノード 3 がクラッシュする

node2 によるアグリゲートのノード 3 への再配置中にノード 3 がクラッシュした場合、ノード 3 のブート後も処理が続行されます。

node2 では残りのアグリゲートの処理が続行されますが、 node3 の起動中にすでに node3 に再配置されたアグリゲートでクライアントが停止する可能性があります。

.手順
. ノード 3 を起動します。
. コントローラのアップグレードに進みます。




== チェック後のフェーズでリブート、パニック、電源再投入が発生した場合



=== チェック後のフェーズで node2 または node3 がクラッシュする

HA ペアが無効になっているため、テイクオーバーは行われません。リブートしたノードに属するアグリゲートでクライアントが停止しています。

.手順
. ノードを起動します。
. ノードペアのアップグレード用手順に進みます。




== リソースの 2 つ目のリリースフェーズでリブート、パニック、電源の再投入が発生した場合



=== リソースの 2 つ目のリリースフェーズでノード 3 がクラッシュする

node2 によるアグリゲートの再配置中にノード 3 がクラッシュした場合、ノード 3 のブート後もタスクは続行されます。

node2 で残りのアグリゲートの処理は続行されますが、 node3 と node3 の独自のアグリゲートにすでに再配置されたアグリゲートでは、 node3 のブート中にクライアントが停止することがあります。

.手順
. ノード 3 を起動します。
. コントローラのアップグレード手順に進みます。




=== 2 番目のリソースリリースフェーズで node2 がクラッシュします

アグリゲートの再配置時にノード 2 がクラッシュした場合、ノード 2 はテイクオーバーされません。

ノード 3 は再配置されたアグリゲートを引き続き提供しますが、ノード 2 が所有するアグリゲートではクライアントの停止が発生します。

.手順
. node2 を起動します。
. コントローラのアップグレード手順に進みます。




== 2 回目の検証フェーズで、リブート、パニック、または電源の再投入が発生した場合



==== 2 回目の検証フェーズでノード 3 がクラッシュした場合

このフェーズで node3 がクラッシュした場合は、 HA ペアがすでに無効になっているため、テイクオーバーは実行されません。

node3 がリブートするまでは、すべてのアグリゲートのクライアントが停止します。

.手順
. ノード 3 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== 2 番目の検証フェーズ中にノード 4 がクラッシュした場合

このフェーズでノード 4 がクラッシュした場合は、テイクオーバーは実行されません。node3 は、アグリゲートからデータを提供します。

ノード 4 のリブートまでルート以外のアグリゲートがすでに再配置されています。

.手順
. ノード 4 を起動します。
. ノードペアのアップグレード用手順に進みます。

