---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/relocating_non-root_aggregates_and_nas_data_lifs_owned_by_node1_to_node2.html 
keywords: relocating, non-root, aggregates, nas, data, lif, node1, node2 
summary: ノード 1 をノード 3 に交換する前に、ルート以外のアグリゲートを移動する必要があります。 
---
= ノード 1 が所有するルート以外のアグリゲートと NAS データ LIF をノード 2 に再配置します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 1 をノード 3 に交換する前に、ルート以外のアグリゲートと NAS データ LIF をノード 1 からノード 2 に移動してから、ノード 1 のリソースをノード 3 に移動する必要があります。

この処理は、タスクの開始時にすでに一時停止されている必要があります。手動で再開する必要があります。

アグリゲートと LIF の移行が完了すると、検証のために処理が一時停止されます。この段階で、ルート以外のアグリゲートと SAN 以外のデータ LIF がすべて node3 に移行されているかどうかを確認する必要があります。


NOTE: アグリゲートおよび LIF のホーム所有者は変更されず、現在の所有者のみが変更されます。

.手順
. 次のコマンドを使用して、アグリゲートの再配置と NAS データ LIF の移動の処理を再開します。
+
「システムコントローラの交換が再開」

+
ルート以外のアグリゲートと NAS データ LIF はすべて、 node1 から node2 に移行されます。

+
処理が一時停止することで、ノード 1 のルート以外のアグリゲートと SAN 以外のデータ LIF がすべて node2 に移行されているかどうかを確認できます。

. 次のコマンドを使用して、アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

. 処理が中断されたまま、次のコマンドを使用して、ルート以外のすべてのアグリゲートが node2 上のそれぞれの状態でオンラインになっていることを確認します。
+
「 storage aggregate show -node <node2> -state online -root false 」のように表示されます

+
次の例は、 node2 のルート以外のアグリゲートがオンラインになっていることを示しています。

+
....
cluster::> storage aggregate show -node node2 state online -root false

Aggregate Size     Available Used% State  #Vols Nodes  RAID Status
aggr_1    744.9GB  744.8GB    0%   online   5   node2  raid_dp,normal
aggr_2    825.0GB  825.0GB    0%   online   1   node2  raid_dp,normal
2 entries were displayed.
....
+
アグリゲートがオフラインになった場合、または node2 で外部になった場合は、各アグリゲートに対して 1 回、 node2 で次のコマンドを使用してアグリゲートをオンラインにします。

+
「 storage aggregate online -aggregate <aggr_name>` 」という名前になります

. node2 で次のコマンドを使用し、出力を調べて、すべてのボリュームがオンラインであることを確認します。
+
volume show -node <node2> -state offline`

+
node2 上にオフラインのボリュームがある場合は、各ボリュームに対して 1 回、 node2 で次のコマンドを使用してオンラインにします。

+
'volume online -vserver <vserver-name> -volume <volume-name>`

+
このコマンドで使用する「 <vserver -name> 」は、前の volume show コマンドの出力に含まれています。

. LIF が 1 つでも停止している場合は、各 LIF に対して次のコマンドを実行して、 LIF の管理ステータスを「 up 」に設定します。
+
「 network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <nodename> -status-admin up 」という形式で指定します


