---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/relocating_failed_or_vetoed_aggregates.html 
keywords: relocating, failed, vetoed, aggregates, relocation, operation 
summary: いずれかのアグリゲートに再配置の失敗や再配置が拒否された場合は、アグリゲートを手動で再配置する必要があります。 
---
= 障害が発生したアグリゲートを再配置するか
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
いずれかのアグリゲートに再配置が失敗した場合、または拒否されている場合は、アグリゲートを手動で再配置するか、必要に応じて拒否またはデスティネーションのチェックを無視する必要があります。

エラーが原因で再配置処理が一時停止します。

.手順
. イベント管理システム（ EMS ）のログで、アグリゲートの再配置に失敗した理由や拒否された理由を確認します。
. 次のコマンドを使用して、障害が発生したアグリゲートまたは拒否されたアグリゲートを再配置
+
「 storage aggregate relocation start -node <node1> -destination <node2> aggregate-list <aggr_name> -nd-controller-upgrade true 」の形式で指定します

. プロンプトが表示されたら、「 y 」と入力します。
. 再配置は、次のいずれかの方法で強制的に実行できます。


[cols="35,65"]
|===
| オプション | 説明 


| 拒否チェックの無視 | 次のコマンドを使用します。「 storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggr_list> -nd-controller-upgrade true -override-vetoes true 」 


| デスティネーションチェックの無効化 | 次のコマンドを使用します。「 storage aggregate relocation start -node node1 -destination node2 -aggregate-list <aggr_list> -nd-controller-upgrade true -override-vetoes true -override-destination-checks true 」 
|===