---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: ノード 3 にオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードがある場合 
---
= ノード 3 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
<stdin> の未解決のディレクティブ： ./_include:./_include/ru_auto_set_fc_or_uta_confgig_node3_intro.adoc[]

* ノード 3 にオンボードの FC ポート、オンボードの UTA / UTA2 ポート、または UTA / UTA2 カードがなく、ストレージディスクを搭載したシステムをアップグレードする場合は、に進みます link:verify_node3_installation.html["ノード 3 のインストールを確認"] セクション。
* ただし、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載したストレージアレイを使用するシステムがある場合に、ノード 3 にオンボードの FC ポート、オンボードの UTA / UTA ポート、または UTA / UTA2 カードがない場合は、の項に戻って node3 を起動し、の項を再開します link:install_boot_node3.html#step23["手順 23"]。


<stdin> の未解決のディレクティブ： ./_include:./_include/ru_auto_set_fc_or_uta2_confgig_node3_choices.adoc[]

<stdin> の未解決のディレクティブ： ./_include/ru_auto_config_ports_node3_adoc[]

. [[auto_check3_step8] 次のいずれかの操作を実行します
+
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合は、セクションに進みます <<Check and configure UTA/UTA2 ports on node3>>。
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合は、このセクションを省略してください <<Check and configure UTA/UTA2 ports on node3>> をクリックして、セクションに移動します link:verify_node3_installation.html["ノード 3 のインストールを確認します"]。




| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合は、セクションに進みます <<Check and configure UTA/UTA2 ports on node3>>。
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合は、このセクションを省略してください <<Check and configure UTA/UTA2 ports on node3>> セクション「 _ インストール」に戻り、 node3 をブートしてから再開します link:install_boot_node3.html#step23["手順 23"]。


|===




== ノード 3 の UTA / UTA2 ポートを確認して設定してください

ノード 3 にオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードが搭載されている場合は、アップグレードしたシステムの使用方法によって、ポートの設定を確認し、場合によっては再設定する必要があります。

UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

FC にユニファイドターゲットアダプタ（ UTA / UTA2 ）ポートを使用する場合は、まずポートの設定を確認する必要があります。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

現在のポート設定を確認するには、「 ucadmin show 」コマンドを使用します。

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UTA2 モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、同じ 10GbE SFP+ インターフェイスを共有する NIC と FCoE のトラフィックを同時に処理でき、 FC ターゲットをサポートできます。

UTA / UTA2 ポートはアダプタまたはコントローラに搭載されている場合がありますが、次の構成になっています。ノード 3 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。

* コントローラを注文した UTA / UTA2 カードは、注文したパーソナリティを指定するために出荷前に設定されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、希望するパーソナリティを持つように出荷する前に設定されます。
+

WARNING: * 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがインストールされていて、ストレージアレイに接続されている場合は、このセクションのメンテナンスモードプロンプトでコマンドを入力します。UTA / UTA2 ポートを設定する場合は、メンテナンスモードにする必要があります。



.手順
. [[step1] node3 で次のコマンドを入力して、ポートが現在どのように設定されているかを確認します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 対処は不要です。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2] 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールと交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. [[step3]] 「 ucadmin show 」コマンドの出力を調べ、 UTA / UTA2 ポートに希望するパーソナリティがあるかどうかを確認します。
. [[step4]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| UTA / UTA2 ポート | 次に、 


| 希望するパーソナリティがない | に進みます <<auto_check3_step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<auto_check3_step13,手順 13>>。 
|===
. [[auto_check3_step5] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | に進みます <<auto_check3_step7,手順 7>> 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<auto_check3_step8,手順 8>>。 
|===
. [[step6] アダプタがイニシエータモードの場合、および UTA / UTA2 ポートがオンラインの場合は、 UTA / UTA2 ポートをオフラインにします。
+
「 storage disable adapter <adapter_name> 」

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check3_step7] 現在の構成が目的の用途に一致しない場合は、必要に応じて構成を変更します。
+
ucadmin modify -m fc | cna-t initiator | target <adapter_name> `

+
** 「 -m 」はパーソナリティ・モードで、「 fc 」または「 cna 」です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープドライブ、 FlexArray 仮想化システム、および MetroCluster 構成には、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。



. [[auto_check3_step8] 設定を確認します。
+
ucadmin show

. [[step9] 設定を確認します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例の出力は ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更され ' アダプタ「 2a 」および「 2b 」のモードが「 cna' 」に変更されていることを示しています

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[step10]] 次のいずれかのコマンドを入力して、各ポートに 1 回ずつターゲットポートをオンラインにします。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 network fcp adapter modify -node <node_name > -adapter <adapter_name> -state up 」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config <adapter_name> up' 
|===
. [[step11]] ポートをケーブル接続します。


. [[auto_check3_step12]] 次のいずれかの操作を実行します。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | に進みます link:verify_node3_installation.html["ノード 3 のインストールを確認します"]。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | section_Install および node3 のブートに戻り、で再開します link:install_boot_node3.html#step23["手順 23"]。 
|===
. [[auto_check3_step13]] メンテナンスモードを終了します。
+
「 halt 」

. [[step14]] ブートメニューへのノードのブート時に 'boot_ontap menu' を実行しますA800 にアップグレードする場合は、に進みます <<auto_check3_step23,手順 23>>。


. [auto9597_check_node3 _step15]] ノード 3 で、ブートメニューに移動し、 22-7 を使用して、非表示オプション「 boot_after_controller_replacement 」を選択します。プロンプトで、 node1 のディスクを node3 に再割り当てするには、次の例のように入力します。
+
....
LOADER-A> boot_ontap menu
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7) Print this secret List
(25/6) Force boot with multiple filesystem disks missing.
(25/7) Boot w/ disk labels forced to clean.
(29/7) Bypass media errors.
(44/4a) Zero disks if needed and create new flexible root volume.
(44/7) Assign all disks, Initialize all disks as SPARE, write DDR labels
.
<output truncated>
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes
.
<output truncated>
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
<output truncated>
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
<output truncated>
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
Login:
....
+

NOTE: 上記のコンソールの出力例では、アドバンストディスクパーティショニング（ ADP ）ディスクを使用するシステムの場合は ONTAP からパートナーノード名の入力を求められます。

. [[step16]] システムが「 no disks found 」というメッセージでリブートループに入ると、システムが FC または UTA/UTA2 ポートをターゲットモードにリセットしたためにディスクを認識できないことを示します。この問題を解決するには、に進みます <<auto_check3_step17,手順 17>> 終了： <<auto_check3_step22,手順 22>>をクリックするか、セクションに移動します link:verify_node3_installation.html["ノード 3 のインストールを確認します"]。
. [[auto_check3_step17]] autoboot 中に Ctrl + C を押して 'loader>` プロンプトでノードを停止します
. [[step18]] LOADER プロンプトで、メンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

. [[step19]] メンテナンスモードで、現在ターゲットモードになっている以前に設定されたすべてのイニシエータポートを表示します。
+
ucadmin show

+
ポートをイニシエータモードに戻します。

+
ucadmin modify -m fc -t initiator -f <adapter name> `

. [[step20]] ポートがイニシエータモードに変更されていることを確認します。
+
ucadmin show

. [[step2]] メンテナンスモードを終了します。
+
「 halt 」

. [auto_check3_step22]] LOADER プロンプトのブートアップ：
+
「 boot_ontap 」

+
これで、ブート時に以前に割り当てられていたすべてのディスクをノードで検出できるようになり、想定どおりにブートできるようになります。

. [[auto_check3_step23]] 外付けディスクがあるシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ AFF A800 システムなど）にアップグレードする場合は、 node1 アグリゲートをルートアグリゲートとして設定し、 node1 のルートアグリゲートからブートするようにします。ルート・アグリゲートを設定するには ' ブート・メニューからオプション 5 を選択して ' 保守モードに切り替えます
+

CAUTION: * ここに示す順序で以下の手順を実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。 *

+
次の手順は、 node3 を node1 のルートアグリゲートからブートするように設定します。

+
.. メンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

.. node1 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node1 アグリゲートのステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node1 アグリゲートをオンラインにします。
+
'aggr_online root_aggr_from_<node1>

.. node3 を元のルートアグリゲートからブートできないようにします。
+
aggr offline <root_aggr_on_node3>`

.. node1 ルートアグリゲートを、 node3 の新しいルートアグリゲートとして設定します。
+
「 aggr options aggr_from_<node1> root 」のように指定します

.. ノード 3 のルートアグリゲートがオフラインになっていること、およびノード 1 からテイクオーバーされたディスクのルートアグリゲートがオンラインになっていて root に設定されていることを確認します。
+
「 aggr status 」を入力します

+

NOTE: 前の手順を実行しないと、原因 node3 を内部ルートアグリゲートからブートするか、原因システムで新しいクラスタ構成が存在すると想定するか、あるいはクラスタ構成を特定するように求められる可能性があります。

+
次の例は、コマンドの出力を示しています。

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



