---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/setting_the_fc_or_uta_uta2_configuration_on_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary:  
---
= ノード 4 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 4 でオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードが使用されている場合は、残りの手順を完了する前に設定する必要があります。

完了する必要がある場合があります link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"]、 、または両方のセクション。


NOTE: ノード 4 にオンボードの FC ポート、オンボード UTA / UTA2 ポート、または UTA / UTA2 カードがなく、ストレージディスクが搭載されたシステムをアップグレードする場合は、に進みます link:verifying_the_node4_installation.html["ノード 4 のインストールを確認します"]。ただし、 V シリーズシステムを使用している場合や FlexArray 仮想化ソフトウェアを使用していて、ストレージアレイに接続している場合に、 node4 にはオンボードの FC ポート、オンボードの UTA / UTA2 ポート、 UTA / UTA2 カードがない場合は、に戻る必要があります  ステップ 22 でセクションを再開します。ノード 4 に十分なラックスペースがあることを確認してください。node4 が node2 とは別のシャーシにある場合は、 node3 と同じ場所に node4 を配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

.選択肢
* link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"]
* link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"]




== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:preparing_the_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"]。

* 重要 * ：ご使用のシステムにストレージ・ディスクがある場合は、クラスタ・プロンプトでこのセクションにコマンドを入力する必要があります。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムの場合は、このセクションのメンテナンスモードでコマンドを入力します。

.手順
. 次のいずれかを実行します。
+
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」コマンドを使用します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを使用します。 ucadmin show 
|===
+
システムには、システム上のすべての FC アダプタと統合ネットワークアダプタに関する情報が表示されます。

. ノード 4 の FC 設定とノード 1 から前に取得した設定を比較します。
. 次のいずれかを実行します。
+
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
次のいずれかのコマンドを使用して、必要に応じて node4 の FC ポートを変更します。

** ターゲットポートをプログラムする場合： ucadmin modify -m fc -t target <adapter>`
** イニシエータポートをプログラムするには、 ucadmin modify -m fc -t initiator <adapter> を使用します


`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 必要に応じて、次のいずれかのコマンドを使用して、 node4 の FC ポートを変更します。 ucadmin modify -m fc -t initiator -f <adapter_port_name> `-t` は、 FC4 タイプ、ターゲット、またはイニシエータです。* 注： FC ポートはイニシエータとしてプログラムする必要があります。 
|===
. 次のコマンドを使用してメンテナンスモードを終了します。
+
「 halt 」

. 次のコマンドを使用して、 LOADER プロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。
. 次のいずれかを実行します。
+
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
** このセクションをスキップして、に進みます link:verifying_the_node4_installation.html["ノード 4 のインストールを確認します"] ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合




| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
** に進みます link:setting_the_fc_or_uta_uta2_configuration_on_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"] ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合
** node4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合は、 section_Check をスキップして UTA / UTA2 ポートを設定し、 node4 に戻ってブートノードを再開します link:installing_and_booting_node4.html#step23["手順 23"]。


|===




== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードは FC イニシエータと FC ターゲットをサポートします。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。

* 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。ストレージアレイに接続された MetroCluster FC システム、 V シリーズシステム、または FlexArray 仮想化ソフトウェアを搭載したシステムがある場合、 UTA / UTA2 ポートを設定するにはメンテナンスモードにする必要があります。

.手順
. ノード 4 で次のいずれかのコマンドを使用して、ポートが現在どのように設定されているかを確認します。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. ucadmin show コマンドの出力結果を調べ、 UTA / UTA2 ポートが希望するパーソナリティに対応しているかどうかを確認します。
. 次のいずれかを実行します。
+
|===
| CNA ポートの状況 | 次に、 


| 希望するパーソナリティがない | に進みます <<Step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<Step13,手順 13>>。 
|===
. [[Step5] 次のいずれかの操作を行います。
+
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | に進みます <<Step7,手順 7>> 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<Step8,手順 8>>。 
|===
. アダプタがイニシエータモードで UTA / UTA2 ポートがオンラインの場合は、次のコマンドを使用して UTA / UTA2 ポートをオフラインにします。
+
「 storage disable adapter <adapter_name> 」

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[Step7] 現在の設定が目的の使用方法と一致しない場合は、必要に応じて次のコマンドを使用して設定を変更します。
+
ucadmin modify -m fc | cna-t initiator | target <adapter_name> `

+
** 「 -m' 」はパーソナリティ・モードである FC または 10 GbE UTA です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープドライブ、 FlexArray 仮想化システム、および MetroCluster 構成には、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。



. [[Step8] 次のコマンドを使用して設定を確認します。
+
ucadmin show

. 次のいずれかのコマンドを使用して設定を確認します。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例の出力は ' アダプタ 1b の FC4 タイプがイニシエータに変更され ' アダプタ 2a および 2b のモードが CNA に変更されていることを示しています

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 次のいずれかのコマンドをポートごとに 1 回入力して、ターゲットポートをオンラインにします。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 network fcp adapter modify -node <node_name > -adapter <adapter_name> -state up 」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config <adapter_name> up' 
|===
. ポートをケーブル接続します。
. 次のいずれかを実行します。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | に進みます link:verifying_the_node4_installation.html["ノード 4 のインストールを確認します"]。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | に戻ります link:installing_and_booting_node3.html["node3 をインストールしてブートします"] ステップ 23 で再開します。 
|===
. [[Step13 、 Step 13]] 次のコマンドを使用してメンテナンスモードを終了します。
+
「 halt 」

. 次のコマンドを使用して、ノードをブートメニューにブートします。
+
「 boot_ontap menu

+
A800 にアップグレードする場合は、に進みます <<Step23,手順 23>>

. [[Step15]] ノード 4 でブートメニューに移動し、 22/7 を使用して非表示オプション「 boot_after_controller_replacement 」を選択します。プロンプトで node2 と入力し、次の例のように node2 のディスクを node4 に再割り当てします。
+
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to
restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure
you want to continue?: yes
.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:
<nodename of the node being replaced>
Changing sysid of node node2 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote
    key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a
boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
+

NOTE: 上記のコンソールの出力例では、アドバンストディスクパーティショニング（ ADP ）ディスクを使用するシステムの場合は ONTAP からパートナーノード名の入力を求められます。

. 「 no disks found 」というメッセージが表示されてシステムがリブートループに入ると、システムが FC ポートまたは UTA/UTA2 ポートをターゲットモードにリセットしたため、ディスクが認識されないことを示します。これを解決するには、に進みます <<Step17,手順 17>> 終了： <<Step22,手順 22>> または、セクションに移動します link:verifying_the_node4_installation.html["ノード 4 のインストールを確認します"]。
. [[Step17]] autoboot 中に Ctrl+C キーを押して 'loader>` プロンプトでノードを停止します
. LOADER プロンプトで、次のコマンドを使用してメンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

. 保守モードで次のコマンドを使用して、以前に設定したすべてのイニシエータポートをターゲットモードで表示します。
+
ucadmin show

+
次のコマンドを使用して、ポートをイニシエータモードに戻します。

+
ucadmin modify -m fc -t initiator -f <adapter name> `

. 次のコマンドを使用して、ポートがイニシエータモードに変更されたことを確認します。
+
ucadmin show

. 次のコマンドを使用してメンテナンスモードを終了します。
+
「 halt 」

. [[Step22]] ローダープロンプトで次のコマンドを使用して起動します。
+
「 boot_ontap 」

+
これで、ブート時に以前に割り当てられていたすべてのディスクをノードで検出できるようになり、想定どおりにブートできるようになります。

. [[Step23]] 外付けディスクのあるシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ AFF A800 システムなど）にアップグレードする場合は、ノード 2 のアグリゲートをルートアグリゲートとして設定して、ノード 2 のルートアグリゲートからノード 2 のノード 4 ノード 4 がブートするようにします。ルート・アグリゲートを設定するには ' ブート・メニューからオプション 5 を選択して ' 保守モードに切り替えます
+

WARNING: 次の手順を記載されている順序で実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。

+
次の手順では、 node4 に node2 のルートアグリゲートからブートするよう設定しています。

+
.. 次のコマンドを使用してメンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

.. 次のコマンドを使用して、 node2 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. 次のコマンドを使用して、 node2 アグリゲートのステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、次のコマンドを使用して node2 アグリゲートをオンラインにします。
+
'aggr_online root_aggr_from_<node2>] を選択します

.. 次のコマンドを使用して、 node4 に元のルートアグリゲートからブートされないようにします。
+
'aggr offline <root_aggr_on_node4 >`

.. 次のコマンドを使用して、 node2 のルートアグリゲートを node4 の新しいルートアグリゲートとして設定します。
+
「 aggr options aggr_from_<node2> root 」のように指定します

.. 次のコマンドを使用して、 node4 のルートアグリゲートがオフラインになっていること、 node2 から昇格されたディスクのルートアグリゲートがオンラインになっていること、および root に設定されていることを確認します。
+
「 aggr status 」を入力します

+

NOTE: 前の手順を実行しない場合は、原因 node4 から内部ルートアグリゲートをブートするか、原因システムが新しいクラスタ構成が存在すると想定するか、あるいはクラスタ構成を特定するように求められる可能性があります。

+
次の例は、コマンドの出力を示しています。



+
....
---------------------------------------------------------------------
Aggr State                       Status               Options
aggr 0_nst_fas8080_15 online     raid_dp, aggr        root, nosnap=on
                                 fast zeroed
                                 64-bit
aggr0 offline                    raid_dp, aggr        diskroot
                                 fast zeroed`
                                 64-bit
---------------------------------------------------------------------
....

