---
sidebar: upgrade-arl-auto-app_sidebar 
permalink: upgrade-arl-auto-app/using_aggregate_relocation_to_upgrade_controller_hardware_overview.html 
keywords: aggregate, relocation, upgrade, controller, hardware, ontap, non-root, arl, ha, high, availability 
summary: ONTAP 9.8 を実行しているノードのペアでは、コントローラハードウェアを無停止でアップグレードできます。 
---
= アグリゲートの再配置を使用してコントローラハードウェアをアップグレードする
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順全体を通じて少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。また、処理を続行する前に、データ論理インターフェイス（ LIF ）を移行し、新しいコントローラのネットワークポートをインターフェイスグループに割り当てます。


NOTE: このドキュメントでは、元のノードの名前は _node1_AND _node2 _ で、新しいノードの名前は _node3 _ と _node4 _ です。説明されている手順では、 node1 は node3 に置き換えられ、 node2 は node4 に置き換えられます。_node1_、 _node2 、 _node3 _ 、および _node4 _ という用語は、元のノードと新しいノードを区別するためだけに使用されます。手順を使用するときは、元のノードと新しいノードの実際の名前を置き換える必要があります。ただし実際には、ノードの名前は変更されません。 node3 には node1 という名前が付けられ、 node4 にはコントローラハードウェアのアップグレード後に node2 という名前が付けられます。本ドキュメントでは、 FlexArray 仮想化ソフトウェアを搭載した「 _systems 」という用語は、これらの新しいプラットフォームに属するシステムを意味します。V シリーズシステムという用語は、ストレージアレイに接続可能な独立したハードウェアシステムを指します



==== 重要

* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["ARL を使用したコントローラのアップグレードに関するガイドライン"] および  アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入され、使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアを以前に使用していた場合は、テクニカルサポートに問い合わせる必要があります。特に、コントローラが Data ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタでコントローラハードウェアをアップグレードできます。ただし、クラスタ内のハイアベイラビリティ（ HA ）ペアごとに手順を個別に実行する必要があります。
* この FlexArray システム、 V シリーズシステム、 AFF システム、および手順環境 FAS 仮想化ソフトウェアを搭載したシステムです。必要なライセンスがインストールされていれば、 ONTAP 9.5 以降にリリースされた FAS システムをストレージアレイに接続できます。既存の V シリーズシステムは、 ONTAP 9.5 でサポートされます。V シリーズのサポートマトリックスを参照してください link:https://hwu.netapp.com["Hardware Universe"] ストレージアレイモデルと V シリーズモデルに関する情報が表示されます。
* この手順環境システムは、 4 ノードの NetApp MetroCluster 構成以上を実行しています。MetroCluster 構成サイトは物理的に異なる場所に設置できるため、 HA ペアの場合は各 MetroCluster サイトでコントローラの自動アップグレードを個別に実行する必要があります。
* AFF A320 システムからアップグレードする場合は、ボリューム移動を使用してコントローラハードウェアをアップグレードするか、テクニカルサポートにお問い合わせください。ボリューム移動を行う場合は、を参照してください link:https://docs.netapp.com/platstor/topic/com.netapp.doc.hw-upgrade-controller/home.html["『 Controller Hardware Upgrade Express Guide 』を参照してください"]。

