---
permalink: fas9000/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, replace, boot, media, primary, secondary, image, disruptive, nondisruptive, manual, manual boot recovery 
summary: 'ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリのシステム (ブート イメージ) ファイル セットが保存されます。ネットワーク構成に応じて、無停止交換または停止交換のいずれかを実行できます。FAS9000システムは、手動のブート メディア回復手順のみをサポートします。' 
---
= ブートメディアの交換の概要- FAS9000
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ブート メディアには、システムの起動時に使用されるプライマリおよびセカンダリのシステム (ブート イメージ) ファイル セットが保存されます。FAS9000システムは、手動のブート メディア回復手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

ブートメディアには、システムがブート時に使用するシステムファイル（ブートイメージ）のプライマリセットとセカンダリセットが格納されています。ネットワーク構成に応じて、無停止または停止を伴う交換を実行できます。

「 image_xxx.tgz 」を格納できる適切な容量のストレージを搭載した、 FAT32 にフォーマットされた USB フラッシュドライブが必要です。

また ' この手順で後で使用するために 'image_xxx.tgz ファイルを USB フラッシュドライブにコピーする必要があります

* ブート・メディアを交換するための無停止かつ停止を伴う方法では 'var' ファイル・システムをリストアする必要があります
+
** 無停止交換の場合 'HA ペアはネットワークに接続して 'var' ファイル・システムをリストアする必要はありません単一シャーシ内の HA ペアには内部 e0S 接続があり ' これを使用して 'var'config をそれらの間で転送します
** 停止を伴う交換の場合 'var' ファイル・システムをリストアするためにネットワーク接続は必要ありませんが ' 再起動が 2 回必要です


* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* 以下の手順のコマンドを正しいノードに適用することが重要です。
+
** impaired_node は、保守を実行しているノードです。
** Healthy node_name は、障害が発生したノードの HA パートナーです。



