---
permalink: fas9000/controller-replace-overview.html 
sidebar: sidebar 
keywords: aff a700, fas9000, replace, controller, module, prerequisites, procedure 
summary: 交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。 
---
= コントローラモジュールの交換 - AFF A700 および FAS9000 の概要
:icons: font
:imagesdir: ../media/


[role="lead"]
交換用手順の前提条件を確認し、ご使用の ONTAP オペレーティングシステムのバージョンに適したバージョンを選択する必要があります。

* すべてのドライブシェルフが適切に動作している必要があります。
* FlexArray システムの場合や V_StorageAttach ライセンスのあるシステムの場合は、この手順を実行する前に、必要な追加の手順を参照する必要があります。
* システムが HA ペアに含まれている場合、正常なノードが交換するノードをテイクオーバーできる必要があります（この手順では「障害ノード」と呼びます）。
* MetroCluster 構成のシステムの場合は、を参照してください https://docs.netapp.com/us-en/ontap-metrocluster/disaster-recovery/concept_choosing_the_correct_recovery_procedure_parent_concept.html["正しいリカバリ手順の選択"] この手順の使用が必要かどうかを判断するには、次の手順を実行
+
使用する手順の場合は、 4 ノードまたは 8 ノードの MetroCluster 構成のノードのコントローラ交換手順は HA ペアの場合と同じであることに注意してください。障害が HA ペアに制限されているため、 MetroCluster 固有の手順は必要ありません。また、 storage failover コマンドを使用すると、交換時に無停止操作を行うことができます。

* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* コントローラモジュールを、同じモデルタイプのコントローラモジュールと交換する必要があります。コントローラモジュールを交換するだけでは、システムをアップグレードすることはできません。
* この手順の一部としてドライブやドライブシェルフを変更することはできません。
* この手順では、ブートデバイスを障害ノードから _replacement _ node に移動して、 _replacement _ node は古いコントローラモジュールと同じバージョンの ONTAP でブートします。
* これらの手順のコマンドを正しいシステムに適用することが重要です。
+
** impaired_node は、交換するノードです。
** replacement _node は、障害ノードと交換する新しいノードです。
** healthy_node はサバイバーノードです。


* ノードのコンソール出力を必ずテキストファイルにキャプチャする必要があります。
+
これにより、手順の記録が作成され、交換プロセス中に発生する可能性のある問題をトラブルシューティングすることができます。


