---
permalink: fas9000/x91148a-modules-with-open-slots-add.html 
sidebar: sidebar 
keywords: aff a700, fas9000, ass, x91148a, module, open, slots, nic, storage 
summary: システムの空のモジュールスロットに、 100GbE NIC または NS224 ストレージシェルフのストレージモジュールとして X91148A モジュールを追加できます。 
---
= オープンスロットを備えた AFF A700 に X91148A モジュールを追加する - AFF A700 および FAS9000
:icons: font
:imagesdir: ../media/


[role="lead"]
システムの空のモジュールスロットに、 100GbE NIC または NS224 ストレージシェルフのストレージモジュールとして X91148A モジュールを追加できます。

* システムで ONTAP 9.8 以降が実行されている必要があります。
* X91148A モジュールを無停止で追加するには、ターゲットコントローラをテイクオーバーし、ターゲットスロットのブランクカバーを取り外してモジュールを追加し、ターゲットコントローラをギブバックする必要があります。
* システムに使用可能な空きスロットが 1 つ以上必要です。
* 複数のスロットが使用可能な場合は、 Hardware Universe で X91148A モジュールのスロット優先順位のマトリックスに従ってモジュールをインストールします。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"]

* X91148A モジュールをストレージモジュールとして追加する場合は ' モジュールスロット 3 または 7 を取り付ける必要があります
* X91148A モジュールを 100GbE NIC として追加する場合は、任意の空きスロットを使用できます。ただし、デフォルトでは、スロット 3 と 7 がストレージスロットとして設定されます。これらのスロットをネットワークスロットとして使用し、 NS224 シェルフを追加しない場合は、「 storage port modify -node name __ port_port name_-mode network 」コマンドでネットワーク用のスロットを変更する必要があります。ネットワーク用に X91148A モジュールで使用できるその他のスロットについては、 Hardware Universe を参照してください。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"]

* システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、必ずテクニカルサポートにお問い合わせください。




== オプション 1 ：オープンスロットを持つシステムで、 NIC モジュールとして X91148A モジュールを追加する

[role="lead"]
スロットが開いているシステムで、 X91148A モジュールを NIC モジュールとして追加するには、特定の手順に従う必要があります。

.手順
. コントローラ A をシャットダウンします。
+
.. 自動ギブバックを無効にします。「 storage failover modify -node local-auto-giveback false 」
.. ターゲットノードをテイクオーバーします。「 storage failover takeover -ofnode _target_node_name _ 」
+
テイクオーバーが完了すると、コンソール接続でノードが LOADER プロンプトに表示されます。



. 接地対策がまだの場合は、自身で適切に実施します。
. ターゲットスロットのブランクカバーを取り外します。
+
.. 文字と数字が記載されたカムボタンを押し下げます。
.. カムラッチを下に回転させて水平にします。
.. ブランキングカバーを取り外す。


. X91148A モジュールをインストールします
+
.. X91148A モジュールをスロットの端に合わせます
.. X91148A モジュールをスロットに差し込み ' 文字と数字が記載された I/O カムラッチが I/O カムピンにかみ合うようにします
.. I/O カムラッチを上に押してモジュールを所定の位置にロックします。


. モジュールをデータスイッチにケーブル接続します。
. コントローラ A を再起動します。「 boot_ontap 」
. パートナーノードからノードをギブバックします。「 storage failover giveback -ofnode target_node_name _
. 自動ギブバックを無効にした場合は、有効にします。「 storage failover modify -node local-auto-giveback true 」
. コントローラ B について、上記の手順を繰り返します




== オプション 2 ：オープンスロットを持つシステムで、 X91148A モジュールをストレージモジュールとして追加する

[role="lead"]
オープン・スロットがあるシステムで X91148A モジュールをストレージ・モジュールとして追加するには ' 特定の手順に従う必要があります

* この手順は、スロット 3 または 7 が開いていることを前提としています。


.手順
. コントローラ A をシャットダウンします。
+
.. 自動ギブバックを無効にします。「 storage failover modify -node local-auto-giveback false 」
.. ターゲットノードをテイクオーバーします。「 storage failover takeover -ofnode target_node_name 」
+
テイクオーバーが完了すると、コンソール接続でノードが LOADER プロンプトに表示されます。



. 接地対策がまだの場合は、自身で適切に実施します。
. ターゲットスロットのブランクカバーを取り外します。
+
.. 文字と数字が記載されたカムボタンを押し下げます。
.. カムラッチを下に回転させて水平にします。
.. ブランキングカバーを取り外す。


. X91148A モジュールをスロット 3 に取り付けます
+
.. X91148A モジュールをスロットの端に合わせます
.. X91148A モジュールをスロットに差し込み ' 文字と数字が記載された I/O カムラッチが I/O カムピンにかみ合うようにします
.. I/O カムラッチを上に押してモジュールを所定の位置にロックします。
.. ストレージ用に 2 つ目の X91148A モジュールを取り付ける場合は、スロット 7 のモジュールに対してこの手順を繰り返します。


. コントローラ A を再起動します。「 boot_ontap 」
. パートナーノードからノードをギブバックします。「 storage failover giveback -ofnode target_node_name
. 自動ギブバックを無効にした場合は、有効にします。「 storage failover modify -node local-auto-giveback true 」
. コントローラ B について、上記の手順を繰り返します
. の説明に従って、 NS224 シェルフを設置してケーブル接続します https://docs.netapp.com/us-en/ontap-systems/ns224/hot-add-shelf.html["NS224 シェルフをホットアドします"]。

