---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: ASA A20、ASA A30、またはASA A50ストレージシステムのブートメディアを交換する前に、交換を成功させるために必要な要件と考慮事項を満たしていることを確認してください。具体的には、適切な交換用ブートメディアがあること、障害のあるコントローラのe0S（e0Mレンチ）ポートに障害がないこと、オンボードキーマネージャ（OKM）と外部キーマネージャ（EKM）のどちらが有効になっているかを確認します。 
---
= ブートメディアの交換要件- ASA A20、ASA A30、およびASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、ASA A30、またはASA A50ストレージシステムのブートメディアを交換する前に、交換を成功させるために必要な要件と考慮事項を満たしていることを確認してください。具体的には、適切な交換用ブートメディアがあること、障害のあるコントローラのe0S（e0Mレンチ）ポートに障害がないこと、オンボードキーマネージャ（OKM）と外部キーマネージャ（EKM）のどちらが有効になっているかを確認します。



== 要件

* 障害が発生したコンポーネントは、NetAppから受け取ったものと同じ容量の交換用FRUコンポーネントと交換する必要があります。
* 障害のあるコントローラのe0S（e0Mレンチ）ポートを障害状態にすることはできません。
+
e0Sポートは自動ブートリカバリに使用されます。

* 次のいずれかの方法でオンボードキーマネージャ（OKM）または永遠キーマネージャ（EKM）が設定されているかどうかを確認します。
+
** OKMまたはEKMが有効になっているかどうかは、システム管理者に確認してください。
** OKMが有効になっているかどうかを確認するには、を使用し `security key-manager onboard show`ます。
** EKMが有効になっているかどうかを確認するには、を使用し `security key-manager external show`ます。


* OKMを使用するには、OKMパスフレーズファイルの内容が必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。






== 考慮事項

* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。


* 該当するプラットフォームの物理的な位置を特定するために、必要に応じてプラットフォームシャーシロケーション（青色）LEDを点灯できます。SSHを使用してBMCにログインし、コマンドを入力し `system location-led _on_`ます。
+
プラットフォームシャーシにはロケーションLEDが3つあります。1つはオペレータ用ディスプレイパネルに、もう1つは各コントローラにあります。ロケーションLEDは30分間点灯したままになります。

+
無効にするには、コマンドを入力し `system location-led _off_`ます。LEDが点灯しているか消灯しているかが不明な場合は、コマンドを入力してLEDの状態を確認できます `system location-led show`。



.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["障害のあるコントローラをシャットダウン"]
