---
permalink: asa-r2-a20-30-50/bootmedia-replace-requirements-bmr.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace the boot media 
summary: ASA A20、ASA A30、またはASA A50ストレージシステムのブートメディアを交換する前に、交換を成功させるために必要な要件と考慮事項を満たしていることを確認してください。これには、正しい交換用ブートメディアを使用しているかの確認、障害が発生したコントローラのe0Mポートが正常に動作しているかの確認、およびオンボードキーマネージャまたは外部キーマネージャが有効になっているかどうかの確認が含まれます。 
---
= ASA A20、ASA A30、またはASA A50システムにおける自動ブートメディアリカバリの要件を確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、 ASA A30、またはASA A50ストレージシステムのブートメディアを交換する前に、交換を正常に行うために必要な要件と考慮事項を満たしていることを確認してください。これには、正しい交換用ブート メディアがあることを確認すること、障害のあるコントローラの e0M (レンチ) ポートが正常に動作していることを確認すること、オンボード キー マネージャ (OKM) または外部キー マネージャ (EKM) が有効になっているかどうかを確認することが含まれます。

次の要件を確認します。

[NOTE]
====
NetApp では、この手順を実行する際には、作業対象のデバイスでコンソールログを有効にし、以下の操作を行うことを強くお勧めします。

* メンテナンス中はAutoSupportを有効にしておいてください。これにより、問題が発生した場合にNetAppサポートが診断情報を受信できるようになります。
* すべてのCLIセッションのセッションログを有効にします。これにより、メンテナンス作業中に実行されたすべてのコマンドとシステム出力の完全な記録が作成されます。セッションログを有効にする方法については、 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_configure_PuTTY_for_optimal_connectivity_to_ONTAP_systems["ONTAP システムへの最適な接続のために PuTTY を設定する方法"^]を参照してください。


====
* 障害が発生したコンポーネントは、NetAppから受け取ったものと同じ容量の交換用FRUコンポーネントと交換する必要があります。
* 障害のあるコントローラのe0Sインターフェース（e0Mレンチポート）に故障がないことを確認します。
+
e0M ポートは、自動ブート回復プロセス中に 2 つのコントローラー間で通信するために使用されます。

* OKM の場合、クラスター全体のパスフレーズとバックアップ データも必要です。
* EKMの場合は、パートナーノードから次のファイルのコピーが必要です。
+
** /cfcard/kmip/ servers.cfgファイル。
** /cfcard/kmip/certs/client.crtファイル。
** /cfcard/kmip/certs/client.keyファイル。
** /cfcard/kmip/certs/CA.pemファイル。


* 障害のあるブート メディアを交換するときは、正しいコントローラにコマンドを適用することが重要です。
+
** _障害のあるコントローラー_ は、メンテナンスを実行しているコントローラーです。
** _正常なコントローラ_ は、障害のあるコントローラの HA パートナーです。




.次の手順
ブートメディアの要件を確認したら、link:bootmedia-shutdown-bmr.html["障害のあるコントローラをシャットダウン"]
