---
permalink: asa-r2-a20-30-50/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: ASA A20、ASA A30、またはASA A50のストレージシステムでコントローラのHA構成がアクティブで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。 
---
= システム構成のリストアと確認（ASA A20、ASA A30、およびASA A50）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、ASA A30、またはASA A50のストレージシステムでコントローラのHA構成がアクティブで正常に機能していることを確認し、システムのアダプタにディスクへのすべてのパスがリストされていることを確認します。



== 手順1：HA構成を確認する

コントローラの状態を確認し、必要に応じてストレージシステム構成に合わせて更新する必要があります `HA`。

. メンテナンスモードでブートします。
+
`boot_ontap maint`

+
.. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。



. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。
. すべてのコンポーネントが同じ状態になっていることを確認し `HA`ます。
+
`ha-config show`

+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. 表示されたコントローラのシステム状態がストレージシステム構成と一致しない場合は、コントローラの状態を設定し `HA`ます。
+
`ha-config modify controller ha`

+
HAの状態には次のいずれかの値を指定できます。

+
** 「 HA 」
** `mcc` （サポートされていません）
** `mccip`（ASAシステムではサポートされません）
** `non-ha` （サポートされていません）


. 設定が変更されたことを確認します。
+
`ha-config show`





== 手順2：ディスクリストを確認する

. アダプタにすべてのディスクへのパスがリストされていることを確認します。
+
`storage show disk -p`

+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. メンテナンスモードを終了します。
+
`halt`



.次の手順
システム構成を復元して確認したら、を実行する必要がありlink:controller-replace-recable-reassign-disks.html["コントローラをギブバック"]ます。
