---
permalink: asa-r2-a20-30-50/controller-replace-requirements.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, prerequisite, replace the controller module 
summary: ASA A20、 ASA A30、またはASA A50 ストレージ システムのコントローラを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラーがあることを確認すること、コントローラーのコンソール出力をテキスト ログ ファイルに保存することが含まれます。 
---
= コントローラの交換要件- ASA A20、ASA A30、ASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、 ASA A30、またはASA A50 ストレージ システムのコントローラを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることを確認すること、正しい交換用コントローラーがあることを確認すること、コントローラーのコンソール出力をテキスト ログ ファイルに保存することが含まれます。

コントローラの交換手順に関する要件と考慮事項を確認しておく必要があります。



== 要件

* すべてのシェルフが適切に動作している必要があります。
* 正常なコントローラは、交換するコントローラをテイクオーバーできる必要があります（この手順 では「障害のあるコントローラ」と呼びます）。
* コントローラを同じモデルタイプのコントローラと交換する必要があります。コントローラを交換するだけではシステムをアップグレードできません。
* この手順では、ドライブやシェルフを変更することはできません。
* コントローラのコンソール出力を必ずテキストログファイルにキャプチャする必要があります。
+
コンソール出力には、交換プロセスで発生する可能性がある問題のトラブルシューティングに使用できる手順が記録されています。





== 考慮事項

* この手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、交換するコントローラです。
** replacement _controller は、障害のあるコントローラを交換する新しいコントローラです。
** healthy_controller はサバイバーコントローラです。




.次の手順
障害のあるコントローラの交換要件を確認したら、を行う必要がありますlink:controller-replace-shutdown.html["障害のあるコントローラをシャットダウン"]。
