---
permalink: asa-r2-a20-30-50/index.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50 maintenance, maintenance, repairing a70 asa a90,  replace a70 asa a90 components 
summary: ASA A20、ASA A30、およびASA A50ハードウェアのメンテナンス 
---
= ASA A20、ASA A30、およびASA A50ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、ASA A30、またはASA A50ストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



== ファン

ファンによってコントローラが冷却されます。



== NVDIMM

NVDIMM（不揮発性デュアルインラインメモリモジュール）は、揮発性メモリから不揮発性ストレージへのデータ転送を管理し、停電やシステムのシャットダウン時にもデータの整合性を維持します。



== NVDIMM バッテリ

NVDIMMバッテリは、NVDIMMモジュールへの電力を維持する役割を果たします。



== PCIe カード

PCIe（Peripheral Component Interconnect Express）カードは、マザーボードのPCIeスロットに接続する拡張カードです。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
