---
permalink: asa-r2-a20-30-50/io-module-overview.html 
sidebar: sidebar 
keywords: asa a20, asa a30, asa a50, replace io module, io module add, io module hotswap 
summary: ASA A20、 ASA A30、およびASA A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードしたり、故障したモジュールに対処したりする際には、I/Oモジュールの追加、ホットスワップ、または交換が不可欠です。 
---
= I/O モジュールのメンテナンスの概要 - ASA A20、 ASA A30、およびASA A50
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA A20、 ASA A30、およびASA A50ストレージシステムは、I/Oモジュールの拡張または交換を柔軟に行えるため、ネットワーク接続性とパフォーマンスを向上できます。ネットワーク機能をアップグレードしたり、故障したモジュールに対処したりする際には、I/Oモジュールの追加、ホットスワップ、または交換が不可欠です。

ストレージシステム内の故障したI/Oモジュールは、同じタイプのI/Oモジュール、または異なるタイプのI/Oモジュールと交換できます。ストレージシステムが特定の要件を満たしている場合は、クラスタとHA I/Oモジュールをホットスワップできます。また、空きスロットがあるストレージシステムにI/Oモジュールを追加することもできます。

* link:io-module-add.html["I/Oモジュールの追加"]
+
I/Oモジュールを追加すると、冗長性が向上し、1つのI/Oモジュールに障害が発生してもストレージシステムが動作し続けるようになります。

* link:io-module-hotswap.html["I/O モジュールのホット スワップ"]
+
特定のI/Oモジュールを同等のI/Oモジュールとホット スワップすることで、ストレージシステムを最適な動作状態に復元できます。ホット スワップは、手動でテイクオーバーを実行することなく実行できます。

+
この手順を使用するには、ストレージ システムでONTAP 9.17.1 以降が実行されており、特定のシステム要件を満たしている必要があります。

* link:io-module-replace.html["I/Oモジュールの交換"]
+
障害が発生したI/Oモジュールを交換すると、ストレージシステムを最適な動作状態に戻すことができます。


