---
permalink: asa-c250/chassis-replace-requirements.html 
sidebar: sidebar 
keywords: asa c250, replace the chassis 
summary: ASA C250システムのシャーシを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることの確認、ONTAPのローカル管理者クレデンシャルがあることの確認、正しい交換用シャーシ、および必要なツールが含まれます。 
---
= シャーシ交換の要件 - ASA C250
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C250システムのシャーシを交換する前に、交換を正常に行うために必要な要件を満たしていることを確認してください。これには、システム内の他のすべてのコンポーネントが正常に機能していることの確認、ONTAPのローカル管理者クレデンシャルがあることの確認、正しい交換用シャーシ、および必要なツールが含まれます。

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。

次の要件を確認します。

* システムの他のすべてのコンポーネントが正常に機能していることを確認します。正常に機能していない場合は、に連絡してサポートを受けてください http://mysupport.netapp.com/["ネットアップサポート"^]
* ONTAPのローカル管理者のクレデンシャルがない場合は、そのクレデンシャルを取得します。
* 交換に必要な工具と機器が揃っていることを確認します。
* シャーシの交換手順は、システムでサポートされるすべてのバージョンのONTAPで使用できます。
* シャーシの交換手順は、ベゼル、NVMeドライブ、およびコントローラモジュールを新しいシャーシに移動することを前提としています。また、交換用シャーシはNetAppの新しいコンポーネントであることを前提としています。
* シャーシの交換手順はシステムの停止を伴います。2 ノードクラスタではサービスが完全に停止し、マルチノードクラスタでは部分的に停止します。


.次の手順
要件を確認した後、link:chassis-replace-prepare.html["シャーシを交換する準備"] 。
