---
permalink: asa-c250/maintain-overview.html 
sidebar: sidebar 
keywords: asa C250 maintenance, maintenance, repairing C250, repairing asa C250, replace asa C250 components, replace asa C250 components 
summary: ASA C250ハードウェアのメンテナンス 
---
= ASA C250ハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA C250 ストレージ システムのハードウェアをメンテナンスして、長期的な信頼性と最適なパフォーマンスを確保します。故障したコンポーネントの交換などの定期的なメンテナンス タスクを実行すると、ダウンタイムやデータ損失を防ぐことができます。

メンテナンス手順では、ASA C250ストレージシステムがONTAP環境のストレージ ノードとしてすでに導入されていることを前提としています。



== システムコンホオネント

ASA C250ストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。

[cols="25,65"]
|===


 a| 
link:bootmedia-replace-workflow-bmr.html["ブートメディア - 自動回復"]
 a| 
ブートメディアには、ストレージシステムが起動に使用するONTAPイメージファイルのプライマリセットとセカンダリセットが格納されます。自動リカバリ中に、システムはパートナーノードからブートイメージを取得し、適切なブートメニューオプションを自動的に実行して、交換用ブートメディアにイメージをインストールします。自動ブートメディアリカバリプロセスは、ONTAP 9.18.1以降でのみサポートされます。ストレージシステムで以前のバージョンのONTAPを実行している場合は、link:bootmedia-replace-workflow.html["手動ブート回復手順"]を使用してください。



 a| 
link:bootmedia-replace-workflow.html["ブートメディア - 手動リカバリ"]
 a| 
ブートメディアには、ストレージ システムが起動に使用する ONTAP イメージ ファイルのプライマリとセカンダリのセットが格納されます。手動リカバリでは、USB ドライブからストレージ システムを起動し、ファイル システムのイメージと構成を手動で復元します。ストレージ システムが ONTAP 9.18.1 以降を実行している場合は、link:bootmedia-replace-workflow-bmr.html["自動ブート回復手順"]を使用します。



 a| 
link:chassis-replace-workflow.html["シャーシ"]
 a| 
シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



 a| 
link:controller-replace-workflow.html["コントローラ"]
 a| 
コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



 a| 
link:dimm-replace.html["DIMM"]
 a| 
メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



 a| 
link:drive-replace.html["ドライブ"]
 a| 
ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



 a| 
link:fan-replace.html["ファン"]
 a| 
ファンによってコントローラが冷却されます。



 a| 
link:mezzanine-replace.html["メザニンカード"]
 a| 
メザニンカードは、別のプラグインカードに直接接続するプリント回路基板です。



 a| 
link:nvmem-nvram-battery-replace.html["NVMEM バッテリ"]
 a| 
NVMEM バッテリーは、AC 電源に障害が発生した場合にキャッシュされたデータを保持する役割を果たします。



 a| 
link:power-supply-replace.html["電源装置"]
 a| 
電源装置は、コントローラシェルフに電源の冗長性を提供します。



 a| 
link:rtc-battery-replace.html["リアルタイムクロックバッテリ"]
 a| 
リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。

|===