---
permalink: ns224/change-shelf-id.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, change, shelf, id, system, ontap, unown, spare, offline, aggregate, change an ns224 drive shelf id 
summary: ONTAP がまだ実行されていない場合や、シェルフをシステムにケーブル接続する前にホットアドする場合は、システムのシェルフ ID を変更できます。また、 ONTAP が実行中で、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーである場合にも、シェルフ ID を変更できます \ （コントローラモジュールがデータを提供可能です \ ）。 
---
= シェルフ ID - NS224 シェルフを変更します
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP がまだ実行されていない場合や、シェルフをシステムにケーブル接続する前にホットアドする場合は、システムのシェルフ ID を変更できます。また、 ONTAP が実行中（コントローラモジュールがデータを提供可能）の場合でも、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーである場合にはシェルフ ID を変更できます。

.作業を開始する前に
* ONTAP が実行中（コントローラモジュールがデータを提供可能）の場合は、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーであることを確認しておく必要があります。
+
「 storage disk show -shelf_shelf_number _ 」コマンドを使用すると、ドライブの状態を確認できます。Container Type 列の出力に 'sare 'srep' または broken と表示されます（ドライブに障害が発生している場合）さらに 'Container Name' および Owner カラムにはダッシュが表示されます

* 片側をまっすぐに伸ばしたペーパークリップ、または細い先端のボールペンが必要です。
+
ペーパークリップまたはボールペンを使用して、 LED の右側にある小さな穴からシェルフ ID ボタンにオペレータディスプレイパネル（ ODP ）からアクセスします。



.このタスクについて
* 有効なシェルフ ID は 00~99 です。
* シェルフ ID は HA ペア内で一意である必要があります。
* シェルフ ID を有効にするには、シェルフの電源を再投入する必要があります（両方の電源コードを抜き、適切な時間を待ってから再度接続します）。
+
電源コードを再接続するまでの待機時間は、この手順の後半で説明するように、 ONTAP の状態によって異なります。

+

NOTE: NS224 シェルフの電源装置には電源スイッチはありません。



.手順
. シェルフの電源がオンになっていない場合はオンにします。
+
電源コードをシェルフに接続して電源コード固定クリップで所定の位置に固定してから、耐障害性を確保するためにそれぞれ別々の電源に接続します。

. 左側のエンドキャップを取り外して、 LED の右側にある小さな穴の位置を確認します。
. シェルフ ID の最初の番号を変更します。
+
.. ペーパークリップまたはボールペンを小さな穴に差し込みます。
.. デジタルディスプレイの 1 桁目の数字が点滅するまでボタンを押し続け、ボタンを放します。
+
点滅するまでに最大 15 秒かかる場合があります。これにより、シェルフ ID プログラミングモードがアクティブになります。

+

NOTE: ID の点滅に 15 秒以上かかる場合は、ボタンをもう一度押し続けてください。

.. 目的の番号になるまで、ボタンを押してから離します（ 0 ～ 9 ）。
+
各プレスおよびリリース時間は、 1 秒ほど短くすることができます。

+
1 桁目の数字は点滅し続けます。



. シェルフ ID の 2 番目の番号を変更します。
+
.. デジタルディスプレイの 2 桁目の数字が点滅するまで、ボタンを押し続けます。
+
数字が点滅するまでに最大 3 秒かかる場合があります。

+
デジタルディスプレイの 1 桁目の数字の点滅が停止します。

.. 目的の番号になるまで、ボタンを押してから離します（ 0 ～ 9 ）。
+
2 桁目の数字は点滅し続けます。



. 2 桁目の数字が点滅しなくなるまでボタンを押し続けて、目的の番号をロックしてプログラミングモードを終了します。
+
点滅が停止するまでに最大 3 秒かかる場合があります。

+
デジタルディスプレイの両方の番号が点滅し始め、約 5 秒後に ODP の黄色の LED が点灯して保留中のシェルフ ID がまだ有効になっていないことを警告します。

. シェルフの電源を再投入し、シェルフ ID を有効にします。
+
シェルフの両方の電源装置から電源コードを抜き、適切な時間待機してから、シェルフの電源装置に接続し直して、電源の再投入を完了する必要があります。

+
電源コードが接続されるとすぐに、電源装置の電源がオンになります。LED が緑色に点灯します。

+
** ONTAP が実行されていない場合、または（まだシステムにケーブルが接続されていない）シェルフをホットアドする場合は、少なくとも 10 秒待ちます。
** ONTAP が実行中（コントローラからデータを提供可能）で、シェルフ内のすべてのドライブが所有されていないか、スペアであるか、オフラインのアグリゲートのメンバーである場合は、少なくとも 70 秒待ちます。
+
この間に、 ONTAP は古いシェルフアドレスを削除し、新しいシェルフアドレスのコピーを更新します。



. 左側のエンドキャップを取り付けます。

