---
permalink: ns224/hot-remove-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, drive, aggregate, ha, pair, serving, data, i/o, hot-remove an ns224 
summary: ドライブからアグリゲートを削除した NS224 ドライブシェルフは、 HA ペア内でデータを提供中（ I/O が実行中）にホットリムーブできます。 
---
= シェルフ / NS224 シェルフのホットリムーブ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ドライブからアグリゲートを削除した NS224 ドライブシェルフは、 HA ペア内で稼働中でデータを提供中（ I/O が実行中）の場合にホットリムーブできます。

.作業を開始する前に
* HA ペアをテイクオーバー状態にすることはできません。
* 取り外すシェルフのドライブ（ドライブはスペアである必要があります）からすべてのアグリゲートを削除しておく必要があります。
+

NOTE: この手順を取り外すシェルフにアグリゲートが含まれた状態で実行しようとすると、システムでエラーが発生し、複数のディスクがパニック状態になることがあります。

+
「 storage aggregate offline -aggregate _aggregate-name _ 」コマンドを実行し、「 storage aggregate delete -aggregate _aggregate-name _ 」コマンドを実行します。

* システムがシステムキャビネットに付属していた場合は、プラスドライバを使用して、シェルフをキャビネットの背面に固定しているネジを外します。


.このタスクについて
* 複数のシェルフをホットリムーブする場合は、シェルフを一度に 1 台ずつ取り外します。
* * ベストプラクティス： * 取り外すシェルフのドライブからアグリゲートを削除したあとに、ドライブの所有権を削除することを推奨します。
+
所有権情報を削除したスペアドライブは、必要に応じて別のノードに適切に統合できます。

+
ドライブの所有権を削除するための手順は、ディスクとアグリゲートのコンテンツに含まれています。

+
https://docs.netapp.com/us-en/ontap/disks-aggregates/index.html["ディスクとアグリゲートの概要"^]




NOTE: 手順では、自動ドライブ割り当てを無効にする必要があります。自動ドライブ割り当ては、この手順の最後（シェルフのホットリムーブ後）で再度有効にします。

* 影響を受けるシェルフの物理的な位置を特定するために、必要に応じてシェルフのロケーション（青色の） LED を点灯できます。「 storage shelf location -led modify -shelf-name _shelf_name _led-status on
+
該当するシェルフの「 _shelf_name_ 」がわからない場合は、「 storage shelf show 」コマンドを実行します。

+
シェルフにはロケーション LED が 3 つあります。オペレータ用ディスプレイパネルに 1 つと、各 NSM モジュールに 1 つずつです。ロケーション LED は 30 分間点灯します。点灯を中止するには、同じコマンドを off オプションに変更して入力します。

* 専用でない RoCE 対応ポート（コントローラ上、 RoCE 対応の PCIe カード上、両方の組み合わせ、または I/O モジュール上）からシェルフを取り外したあと、それらのポートをネットワーク用に再設定することができます。
+

NOTE: HA ペアで ONTAP 9.6 のバージョンを実行している場合は、コントローラを 1 つずつリブートする必要があります。HA ペアで ONTAP 9.7 以降が実行されている場合は、一方または両方のコントローラがメンテナンスモードでないかぎり、コントローラをリブートする必要はありません。この手順では、どちらのコントローラもメンテナンスモードでないことを前提としています。



.手順
. 自身の適切な接地対策を行います
. 取り外すシェルフのドライブにアグリゲートがないこと（スペアであること）、および所有権が削除されていることを確認します。
+
.. 次のコマンドを入力して、取り外すシェルフにあるすべてのドライブの一覧を表示します。「 storage disk show -shelf_shelf_number
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

.. 出力をチェックし、ドライブにアグリゲートがないことを確認します。
+
アグリゲートのないドライブの場合 ' Container Name 列にダッシュが表示されます

.. の出力をチェックし、ドライブから所有権が削除されていることを確認します。
+
所有権のないドライブの場合は '[Owner] 列にダッシュが表示されます

+

NOTE: 障害が発生したドライブがある場合は ' Container Type 列に broken と表示されます障害が発生したドライブには所有権がありません。

+
次の出力は、取り外すシェルフ（シェルフ 2 ）のドライブが、シェルフを取り外すための正しい状態にあることを示しています。アグリゲートはすべてのドライブから削除されているため、各ドライブの「 Container Name 」列にダッシュが表示されます。所有権もすべてのドライブから削除されるため ' 各ドライブの [Owner] 列にダッシュが表示されます



+
[listing]
----
cluster1::> storage disk show -shelf 2

           Usable           Disk     Container   Container
Disk         Size Shelf Bay Type     Type        Name       Owner
-------- -------- ----- --- ------   ----------- ---------- ---------
...
2.2.4           -     2   4 SSD-NVM  spare                -         -
2.2.5           -     2   5 SSD-NVM  spare                -         -
2.2.6           -     2   6 SSD-NVM  broken               -         -
2.2.7           -     2   7 SSD-NVM  spare                -         -
...
----
. 取り外すシェルフの物理的な場所を確認します。
. 取り外すシェルフからケーブルを外します。
+
.. AC電源装置の場合は電源コード固定クリップを開き、DC電源装置の場合は2本の蝶ネジを外して、電源装置から電源コードを抜きます。
+
電源装置には電源スイッチはありません。

.. ストレージケーブルを（シェルフからコントローラへ）外します。


. ラックまたはキャビネットからシェルフを物理的に取り外します。
+

NOTE: フル装備の NS224 シェルフの重量は最大 30.29kg （ 66.78 ポンド）になるため、シェルフを持ち上げるときは 2 人で行うか油圧リフトを使用してください。シェルフの重量を軽くするために、シェルフコンポーネントを（シェルフの前面または背面から）取り外さないでください。シェルフの重量が不均衡になります。

+

NOTE: システムをキャビネットに設置していた場合は、最初にシェルフを背面の保守用ネジに固定している 2 本のプラスネジを外す必要があります。このネジは、下部 NSM モジュールのシェルフ内壁にあります。このネジにアクセスするには、両方の NSM モジュールを取り外す必要があります。

. 複数のシェルフを取り外す場合は、手順 2~5 を繰り返します。
+
それ以外の場合は、次の手順に進みます。

. ドライブから所有権を削除する際に自動ドライブ割り当てを無効にした場合は、再度有効にします。「 storage disk option modify -autoassign on 」
+
このコマンドは両方のコントローラモジュールで実行します。

. 次の手順を実行すると、非専用 RoCE 対応ポートをネットワーク用に再設定できます。
+
それ以外の場合は、この手順を使用します。

+
.. 現在ストレージ用に設定されている専用でないポートの名前を確認します。「 storage port show 」
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+

NOTE: ストレージ用に設定されている専用でないポートは、次のように出力に表示されます。 HA ペアで ONTAP 9.8 以降が実行されている場合、非専用ポートの列に「 storage 」と表示されます。HA ペアが ONTAP 9.7 または 9.6 を実行している場合は ' 専用でないポートは 'Is dedicated ？に false と表示されます 列には、「有効」列も表示されます。

.. HA ペアで実行している ONTAP のバージョンに応じて、次の手順を実行します。
+
[cols="1,2"]
|===
| HA ペアの実行中 | 作業 


 a| 
ONTAP 9.8 以降
 a| 
... 1 つ目のコントローラモジュールで、ネットワーク用に専用でないポートを再設定します。「 storage port modify -node name_-port_port name_-mode network 」
+
再設定するポートごとにこのコマンドを実行する必要があります。

... 上記の手順を繰り返して、 2 台目のコントローラモジュールのポートを再設定します。
... 手順 8c に進み、すべてのポートが変更されたことを確認します。




 a| 
ONTAP 9.7
 a| 
... 1 つ目のコントローラモジュールで、ネットワーク用に専用でないポートを再設定します。「 storage port disable -node name_-port_port name_` 」
+
再設定するポートごとにこのコマンドを実行する必要があります。

... 上記の手順を繰り返して、 2 台目のコントローラモジュールのポートを再設定します。
... 手順 8c に進み、すべてのポートが変更されたことを確認します。




 a| 
ONTAP 9.6 のバージョン
 a| 
... 1 つ目のコントローラモジュールで、 RoCE 対応ポートをネットワーク用に再設定します。「 storage port disable -node name_-port_port name_`
+
再設定するポートごとにこのコマンドを実行する必要があります。

... コントローラモジュールをリブートし、ポートの変更を有効にします。
+
「システム・ノードの再起動 - Node_node name -- reason_reason_ 再起動時

+

NOTE: リブートが完了してから次の手順に進む必要があります。リブートには最大 15 分かかる場合があります。

... 2 つ目のコントローラモジュールのポートを再設定するには、最初の手順（ A ）を繰り返します。
... 2 台目のコントローラをリブートしてポートの変更を有効にし、 2 つ目の手順（ b ）を繰り返します。
... 手順 8c に進み、すべてのポートが変更されたことを確認します。


|===
.. 両方のコントローラモジュールの専用でないポートがネットワーク用に再設定されていることを確認します。「 storage port show 」
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+
HA ペアで ONTAP 9.8 以降が実行されている場合、非専用ポートの「モード」列に「ネットワーク」と表示されます。

+
HA ペアが ONTAP 9.7 または 9.6 を実行している場合は ' 専用でないポートは 'Is dedicated ？に false と表示されます 列には、「 State 」列に「 disabled 」と表示されます。




