---
permalink: ns224/hot-add-asa-prepare-a30-50.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, asa systems, preparation, roce, asa a30, asa a50 
summary: RoCE対応I/Oモジュールをインストールしてポートを設定し、既存のシェルフのケーブルを再配線して自動ドライブ割り当てを無効にすることで、NS224シェルフをホットアドするためのASA A30またはA50システムを準備します。 
---
= ASA A30またはASA A50システムにNS224シェルフをホットアドする準備をしてください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RoCE対応のストレージポートが十分にあることを確認し、それらをストレージ用に設定し、スロットの冗長性を確保するために既存のシェルフの配線を変更し、自動ドライブ割り当てを無効にして、ASA A30またはA50システムにNS224シェルフをホットアドする準備をします。



== RoCE 対応 I/O モジュールをインストールする

システムがRoCE対応のPCIeカードまたはI/Oモジュールの使用をサポートしている場合、HAペアには、ホットアドするシェルフの数をサポートするのに十分なRoCE対応イーサネットポートが備わっている必要があります。

.手順
. ホットアドするシェルフごとに、各コントローラにRoCE対応ポートが2つあることを確認します。
+
これらのポートは、コントローラ上、RoCE対応PCIeカード上、両方の組み合わせ、またはシステムでサポートされているRoCE対応I/Oモジュール上に配置できます。

. HAペアに十分なRoCE対応ポートがない場合は、システムでサポートされている適切なコントローラスロットに、追加のPCIeカードまたはI/Oモジュールを取り付けてください。
+
.. お使いのシステムに適したコントローラースロットを特定してください。 https://hwu.netapp.com["NetApp Hardware Universe の略"^]を参照してください。
.. PCIeカードまたはI/Oモジュールの取り付け手順については、システムのマニュアルを参照してください。






== ストレージ用のRoCE対応ポートの設定

一部のシステムでは、RoCE対応のPCIeカードまたはI/Oモジュールを対応するコントローラスロットにインストールすると、RoCE対応ポートは自動的にストレージ用途にデフォルト設定されます。ただし、ストレージ用途向けにポートが正しく設定されていることを確認するために、この手順を完了する必要があります。

ストレージ用途向けに非専用RoCE対応ポートを設定する手順は、システムを停止させることなく実行できます。コントローラーの片方または両方がメンテナンスモードになっていない限り、コントローラーを再起動する必要はありません。この手順は、どちらのコントローラもメンテナンスモードになっていないことを前提としています。

今後、ストレージ用ポートをネットワーク用ポートに変更する必要がある場合は、以下のコマンドを使用してください `storage port modify -node _node_name_ -port _port_name_ -mode network`。

.手順
. 各コントローラに、RoCE対応の追加PCIeカードまたはI/Oモジュールが取り付けられていることを確認してください。
. SSHまたはシリアルコンソールポートを使用してクラスタにログインします。
. HA ペアの非専用ポートがストレージ用に構成されていることを確認するには、次のコマンドを入力します `storage port show`。
+
コマンドの出力は、ONTAPのバージョンによって異なります。

+
** **ONTAP 9.8以降：**ストレージ用に構成された非専用ポートは、 `Mode`列に `storage`と表示されます。ストレージ用に構成されていないポートは、 `Mode`列に `network`と表示されます。
** **ONTAP 9.7：**ストレージ用に構成された非専用ポートは、 `Is Dedicated?`列に `false`を表示し、 `State`列に `enabled`を表示します。ストレージ用に構成されていないポートは、 `Is Dedicated?`列に `false`を表示し、 `State`列に `disabled`を表示します。


. 非専用ポートがストレージ用途に設定されている場合、この手順は完了です。それ以外の場合は、次の手順を実行してポートを設定します。
. いずれかのコントローラ上で、非専用ポートをストレージ用として設定します。設定するポートごとに、該当するコマンドを繰り返す必要があります。
+
[cols="1,3"]
|===
| HA ペアの実行中 | 使用するコマンド 


 a| 
ONTAP 9.8 以降
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 2 番目のコントローラーに対して前の手順を繰り返します。
. 両方のコントローラの非専用ポートがストレージ用に構成されていることを確認するには、次のコマンドを入力します `storage port show`。
+
コマンドの出力は、ONTAPのバージョンによって異なります。

+
** **ONTAP 9.8以降：**ストレージ用に構成された非専用ポートは、 `Mode`列に `storage`を表示します。
** **ONTAP 9.7：**ストレージ用に構成された非専用ポートは、 `Is Dedicated?`列に `false`を、 `State`列に `enabled`を表示します。






== 既存のシェルフを再接続

A30、C30、A50、またはC60 HAペアに2つ目のシェルフをホットアドする場合、各コントローラのスロット3とスロット1にあるRoCE対応I/Oモジュール間で、最初のシェルフのケーブルを再配線する必要があります。

この手順では、既存のシェルフが各コントローラのスロット3にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

.手順
. 各コントローラのスロット3とスロット1のRoCE対応I/Oモジュール全体で最初のシェルフを再配線します。
+
.. コントローラAで、ケーブルをスロット3のポートb（e3b）からスロット1のポートb（e1b）に移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します


. 再接続されたシェルフがを使用して正しくケーブル接続されていることを確認します https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
ケーブル接続エラーが発生した場合は、表示される対処方法に従ってください。





== 自動ドライブ割り当ての無効化

ドライブ所有権を手動で割り当てる必要があるかどうかがわからない場合や、ご使用のストレージシステムのドライブ所有権の自動割り当てポリシーについて理解する場合は、に進みます https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["ディスク所有権の自動割り当てについて"^]。

.手順
. 自動ドライブ割り当てが有効になっているかどうかを確認します。「 storage disk option show
+
このコマンドはどちらのノードでも入力できます。

+
自動ドライブ割り当てが有効になっている場合、出力の各ノードの `Auto Assign`列に `on`が表示されます。

. 自動ドライブ割り当てが有効になっている場合は無効にします。「 storage disk option modify -node _node_name -autoassign off
+
自動ドライブ割り当ては両方のノードで無効にする必要があります。



.次の手順
link:hot-add-asa-install.html["シェルフを取り付ける"]に進みます。
