---
permalink: ns224/prepare-hot-add-shelf.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, hot-add, ha, pair, requirement, preparation, applicable, complete, drive, hot-add an ns224 drive shelf 
summary: HA ペアが一定の要件を満たし、 HA ペアに適用可能な準備作業が完了したら、 NS224 ドライブシェルフをホットアドできます。 
---
= ホットアドNS224シェルフの準備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NS224シェルフをホットアドする前に、HAペアに該当する準備作業を完了してください。

適切な準備作業が完了したら、に進みます link:prepare-hot-add-shelf.html["ホットアド用のシェルフの設置"]。



== RoCE対応PCIeカードまたはI/Oモジュールの取り付け

プラットフォームモデルでRoCE対応のPCIeカードまたはI/Oモジュールの使用がサポートされている場合は、ホットアドするシェルフの数に対応できる十分な数のRoCE対応イーサネットポートがHAペアに必要です。

.手順
. ホットアドするシェルフごとに、各コントローラにRoCE対応ポートが2つあることを確認します。
+
この 2 つのポートは、コントローラ、 RoCE 対応の PCIe カード、両方の組み合わせ、または RoCE 対応の I/O モジュール上のポートで、プラットフォームモデルに対応しています。

. HAペアに十分な数のRoCE対応ポートがない場合は、プラットフォームモデルのサポートに従って、追加のPCIeカードまたはI/Oモジュールを正しいコントローラスロットに取り付けます。
+
.. プラットフォームモデルに適したコントローラスロットを特定します。を参照してください https://hwu.netapp.com["NetApp Hardware Universe の略"^]
.. PCIeカードまたはI/Oモジュールの取り付け手順については、プラットフォームモデルのマニュアルを参照してください。






== ストレージ用のRoCE対応ポートの設定

HAペアに専用ではないRoCE対応イーサネットポートを使用してNS224シェルフをホットアドする場合は、（ネットワーク用ではなく）ストレージ用にポートを設定する必要があります。

.作業を開始する前に
* 追加のRoCE対応PCIeカードまたはI/Oモジュールが各コントローラに取り付けられていることを確認します。


.このタスクについて
* 一部のプラットフォームモデルでは、RoCE対応PCIeカードまたはI/Oモジュールがコントローラのサポートされているスロットに搭載されている場合、ポートは（ネットワークではなく）自動的にストレージ使用にデフォルト設定されます。 ただし、次の手順を実行して、RoCE対応ポートがストレージ用に設定されていることを確認することを推奨します。
* HA ペア手順内の、専用でない RoCE 対応ポートがストレージ用に設定されていない場合は、無停止でそのポートを設定できます。一方または両方のコントローラがメンテナンスモードの場合を除き、コントローラをリブートする必要はありません。この手順では、どちらのコントローラもメンテナンスモードでないことを前提としています。
* 今後、ポートをストレージ用途からネットワーク用途に変更する必要がある場合は、コマンドを入力し `storage port modify -node _node_name_ -port _port_name_ -mode network`ます。


.手順
. SSHまたはシリアルコンソールポートを使用してクラスタにログインします。
. 次のコマンドを入力して、HAペアの専用以外のポートがストレージ用に設定されているかどうかを確認します。
+
`storage port show`

+
** HA ペアで ONTAP 9.8 以降が実行されている場合は、非専用ポートの「モード」列に「ストレージ」と表示されます。
** HAペアでONTAP 9.7を実行している場合は `Is Dedicated?`、列にと表示されている非専用ポートも `State`列にと表示され `false`ます `enabled`。
+
[NOTE]
====
専用でないポートがストレージ用に設定されていない場合、コマンド出力には次のように表示されます。

*** HA ペアで ONTAP 9.8 以降が実行されている場合、非専用ポートの「モード」列に「ネットワーク」と表示されます。
*** HAペアでONTAP 9.7を実行している場合は `Is Dedicated?``、列にと表示されている非専用ポートも `State`列にと表示され `false`ます `disabled`。


====


. 専用でないポートがストレージ用に設定されている場合、この手順を使用します。
+
それ以外の場合は、手順 4~7 を実行してポートを設定する必要があります。

. いずれかのコントローラで、ストレージ用に専用でないポートを設定します。
+
設定するポートごとに、該当するコマンドを繰り返す必要があります。

+
[cols="1,3"]
|===
| HA ペアの実行中 | 使用するコマンド 


 a| 
ONTAP 9.8 以降
 a| 
`storage port modify -node _node_name_ -port _port_name_ -mode storage`



 a| 
ONTAP 9.7
 a| 
`storage port enable -node _node_name_ -port _port_name_`

|===
. 2台目のコントローラについて手順4を繰り返します。
. 両方のコントローラの非専用ポートがストレージ用に設定されていることを確認します。 `storage port show`
+
** HA ペアで ONTAP 9.8 以降が実行されている場合は、非専用ポートの「モード」列に「ストレージ」と表示されます。
** HAペアでONTAP 9.7を実行している場合は `Is Dedicated?`、列にと表示されている非専用ポートも `State`列にと表示され `false`ます `enabled`。






== 既存のシェルフを再接続

プラットフォームモデルによっては、シェルフをホットアドする前に、（追加のRoCE対応PCIeカードまたはI/Oモジュールを取り付けたあとに）既存のシェルフを別 々 のスロットの2セットのポートに再接続して、スロット障害に対する耐障害性を確保しなければならない場合があります。

.作業を開始する前に
* 追加のRoCE対応PCIeカードまたはI/Oモジュールが各コントローラに取り付けられていることを確認します。
* 取り付けたRoCE対応PCIeカードまたはI/Oモジュールの非専用ポートが、ストレージ用に設定されていることを確認します。


.このタスクについて
* マルチパス HA 接続を使用しているシェルフでは、ポート接続の再接続によって無停止の手順が使用されます。
* この手順の実行中もシェルフへの接続を維持するために、ケーブルを一度に1本ずつ外します。
+

NOTE: ケーブルを移動する場合、あるポートからケーブルを外して別のポートに接続するまでの待機時間は不要です。

* 必要に応じて、で使用しているプラットフォームモデルのシェルフのケーブル配線図を参照して link:cable-overview-hot-add-shelf.html["ホットアドのケーブル接続の概要"]ください。


.手順
. プラットフォームモデルに応じて、異なるスロットにある2組のRoCE対応ポートを使用して、既存のシェルフの接続をケーブル接続し直します。


[role="tabbed-block"]
====
.AFF A1K用
--
2番目のシェルフまたは4番目のシェルフをホットアドする場合は、次のいずれかを実行します。


NOTE: AFF A1K HAペアを使用していて、3番目のシェルフをホットアドし、3番目または4番目のRoCE対応I/Oモジュールを各コントローラに取り付ける場合、3番目のシェルフは3番目または3番目および4番目のI/Oモジュールにのみケーブル接続されます。既存のシェルフをケーブルで再接続する必要はありません。

* 2台目のシェルフをホットアドする場合は、各コントローラのスロット11とスロット10のRoCE対応I/Oモジュールで最初のシェルフにケーブルを再接続します。
+
この手順では、既存のシェルフが各コントローラのスロット11にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

+
.. コントローラ A で、スロット 11 のポート b （ e11b ）からスロット 10 のポート b （ e10b ）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します


* 4台目のシェルフをホットアドする場合は、各コントローラのスロット9とスロット8のRoCE対応I/Oモジュールで3台目のシェルフにケーブルを再接続します。
+
この手順では、3台目のシェルフが各コントローラのスロット9にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

+
.. コントローラ A で、スロット 9 のポート b （ e9b ）からスロット 8 のポート b （ e8b ）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します




--
.AFF A70、AFF A90、またはAFF C80
--
2台目のシェルフをホットアドする場合は、各コントローラのスロット11とスロット8のRoCE対応I/Oモジュールで1台目のシェルフにケーブルを再接続します。

この手順では、既存のシェルフが各コントローラのスロット11にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

. コントローラ A で、スロット 11 のポート b （ e11b ）からスロット 8 のポート b （ e8b ）にケーブルを移動します。
. コントローラ B についても、同じケーブルの移動を繰り返します


--
.AFF A800またはAFF C800
--
2台目のシェルフをホットアドする場合は、各コントローラのスロット5とスロット3にある2組のRoCE対応ポートで1台目のシェルフをケーブル接続し直します。

手順は、既存のシェルフが各コントローラのスロット 5 にある RoCE 対応 PCIe カードにケーブル接続されていることを前提としています。

. コントローラ A で、スロット 5 のポート b （ e5b ）からスロット 3 のポート b （ e3b ）にケーブルを移動します。
. コントローラ B についても、同じケーブルの移動を繰り返します


--
.AFF A700
--
2台目のシェルフをホットアドする場合は、各コントローラのスロット3とスロット7にある2組のRoCE対応ポートで1台目のシェルフをケーブル接続し直します。

手順は、既存のシェルフが各コントローラのスロット 3 にある RoCE 対応 I/O モジュールにケーブル接続されていることを前提としています。

. コントローラ A で、スロット 3 のポート b （ e3b ）からスロット 7 のポート b （ e7b ）にケーブルを移動します。
. コントローラ B についても、同じケーブルの移動を繰り返します


--
.AFF A400またはAFF C400
--
2台目のシェルフをホットアドする場合は、プラットフォームモデルに応じて、次のいずれかを実行します。

* AFF A400の場合：
+
各コントローラの2組のRoCE対応ポート（オンボードe0c / e0d、スロット5）で最初のシェルフにケーブルを再接続します。

+
この手順では、既存のシェルフが各コントローラのRoCE対応オンボードポートe0c/e0dにケーブル接続されていると仮定します。

+
.. コントローラ A で、ポート e0d からスロット 5 のポート b （ e5b ）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します


* AFF C400の場合：
+
各コントローラのスロット4とスロット5の2組のRoCE対応ポートで、最初のシェルフにケーブルを再接続します。

+
この手順では、既存のシェルフが各コントローラのスロット4にあるRoCE対応ポートにケーブル接続されていることを前提としています。

+
.. コントローラAで、スロット4のポートa（e4a）からスロット5のポートb（e5b）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します




--
.AFF A900 の略
--
2番目のシェルフまたは4番目のシェルフをホットアドする場合は、次のいずれかを実行します。

* 2台目のシェルフをホットアドする場合は、各コントローラのスロット2とスロット10のRoCE対応I/Oモジュールで最初のシェルフにケーブルを再接続します。
+
この手順では、既存のシェルフが各コントローラのスロット2にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

+
.. コントローラ A で、スロット 2 のポート b （ e2b ）からスロット 10 のポート b （ e10b ）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します


* 4台目のシェルフをホットアドする場合は、各コントローラのスロット1とスロット11のRoCE対応I/Oモジュールで3台目のシェルフにケーブルを再接続します。
+
この手順では、3台目のシェルフが各コントローラのスロット1にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

+
.. コントローラ A で、スロット 1 のポート b （ e1b ）からスロット 11 のポート b （ e11b ）にケーブルを移動します。
.. コントローラ B についても、同じケーブルの移動を繰り返します




--
.AFF A30、AFF C30、AFF A50、またはAFF C60
--
2台目のシェルフをホットアドする場合は、各コントローラのスロット3とスロット1のRoCE対応I/Oモジュールで最初のシェルフにケーブルを再接続します。

この手順では、既存のシェルフが各コントローラのスロット3にあるRoCE対応I/Oモジュールにケーブル接続されていることを前提としています。

. コントローラ A で、スロット 3 のポート b （ e3b ）からスロット 1 のポート b （ e1b ）にケーブルを移動します。
. コントローラ B についても、同じケーブルの移動を繰り返します


--
====
. 再接続されたシェルフがを使用して正しくケーブル接続されていることを確認します https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["Active IQ Config Advisor"^]。
+
ケーブル接続エラーが発生した場合は、表示される対処方法に従ってください。





== 自動ドライブ割り当ての無効化

ホットアドするNS224シェルフのドライブ所有権を手動で割り当てる場合は、自動ドライブ割り当てを無効にする必要があります（有効になっている場合）。

ドライブ所有権を手動で割り当てる必要があるかどうかがわからない場合や、ご使用のストレージシステムのドライブ所有権の自動割り当てポリシーについて理解する場合は、に進みます https://docs.netapp.com/us-en/ontap/disks-aggregates/disk-autoassignment-policy-concept.html["ディスク所有権の自動割り当てについて"^]。

.手順
. 自動ドライブ割り当てが有効になっているかどうかを確認します。「 storage disk option show
+
このコマンドはどちらのノードでも入力できます。

+
自動ドライブ割り当てが有効になっている場合は、各ノードの列にと表示されます `on` `Auto Assign` 。

. 自動ドライブ割り当てが有効になっている場合は無効にします。「 storage disk option modify -node _node_name -autoassign off
+
自動ドライブ割り当ては両方のノードで無効にする必要があります。


