---
permalink: ns224/service-replace-boot-media.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, boot, media, run, ontap, nvme, module, nsm, firmware, version, nondisruptive, i/o 
summary: ONTAP 9.7 以降を実行している HA ペアの NS224 ドライブシェルフでブートメディアに障害が発生した場合、またはシェルフで NVMe シェルフモジュール（ NSM ）ファームウェアバージョン 1.1x 以降が実行されている場合は、ブートメディアを交換できます。ブートメディアの交換は、ドライブシェルフの電源をオンにした状態で、 I/O を実行中のまま、無停止で実行できます。 
---
= ブートメディア -NS224 シェルフを交換してください
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.7 以降を実行している HA ペアの NS224 ドライブシェルフでブートメディアに障害が発生した場合、またはシェルフで NVMe シェルフモジュール（ NSM ）ファームウェアバージョン 1.1x 以降が実行されている場合は、ブートメディアを交換できます。ブートメディアの交換は、ドライブシェルフの電源をオンにした状態で、 I/O を実行中のまま、無停止で実行できます。

.作業を開始する前に
* サポートされる最小バージョンの NSM ファームウェアがある HA ペアで ONTAP 9.7 以降が実行されているか、または ONTAP 9.6 のバージョンと NSM ファームウェアバージョン 1.1x 以降が実行されている必要があります。
+
いずれかのコントローラのコンソールで「 storage shelf show module 」コマンドを入力して、シェルフの NSM ファームウェアのバージョンを確認できます。

+
[NOTE]
====
NSM ファームウェアバージョン 1.1x 以降を実行していないシェルフでは、ブートメディアを交換できません。 NSM モジュールを交換する必要があります。

link:service-replace-nsm100.html["NSM モジュール - NS224 シェルフを交換してください"^]

====
* No.1 プラスドライバが必要です。
+
ブートメディアをボードに固定するネジには No.1 プラスドライバが必要です。別のタイプのドライバを使用すると、ネジを外すことができます。

* 障害が発生した FRU （ターゲット NSM モジュール）を搭載した NSM モジュールを取り外す際にシェルフが接続を維持できるように、シェルフのパートナー NSM モジュールが稼働し、正しくケーブル接続されている必要があります。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"^]

* システムのその他のコンポーネントがすべて正常に動作している必要があります。


.このタスクについて
* ブートメディアを交換すると、シェルフのパートナー NSM モジュールのブートイメージが交換用ブートメディアに自動的にコピーされます。
+
この処理には最大 5 分かかることがあります。

* NVMe シェルフモジュール（ NSM ）を取り外したあと、少なくとも 70 秒待ってから取り付けるようにしてください。
+
これにより、 ONTAP が NSM の削除イベントを処理するのに十分な時間がかかります。

* * ベストプラクティス： FRU コンポーネントを交換する前に、お使いのシステムの NVMe シェルフモジュール（ NSM ）ファームウェアとドライブファームウェアを最新バージョンにしておくことを推奨します。
+
[NOTE]
====
ファームウェアをシェルフおよびそのコンポーネントに対応しないバージョンにリバートしないでください。

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"^]

====
* 影響を受けるシェルフの物理的な位置を特定するために、必要に応じてシェルフのロケーション（青色の） LED を点灯できます。「 storage shelf location -led modify -shelf-name _shelf_name _led-status on
+
該当するシェルフの「 _shelf_name_ 」がわからない場合は、「 storage shelf show 」コマンドを実行します。

+
シェルフにはロケーション LED が 3 つあります。オペレータ用ディスプレイパネルに 1 つと、各 NSM モジュールに 1 つずつです。ロケーション LED は 30 分間点灯します。同じコマンドを「 off 」オプションを使用して入力すると、これらのコマンドを無効にできます。

* ブートメディアを交換したら、キットに付属する RMA 指示書に従って、障害のある部品をネットアップに返却します。
+
RMA 番号を確認する場合や、交換用手順に関するその他のサポートが必要な場合は、テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]にアクセスするか、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。

* 次のビデオまたは記載された手順に従って、ブートメディアを交換します。
+
https://netapp.hosted.panopto.com/Panopto/Pages/Embed.aspx?id=20ed85f9-1f80-4e0e-9219-ab4600070d8a["NS224 ドライブシェルフのブートメディアを交換する"^]



.手順
. 自身の適切な接地対策を行います
. 交換する FRU が搭載されている NSM モジュールからケーブルを外します。
+
.. 電源コード固定クリップを開き、電源装置から電源コードを抜きます。
+
電源装置には電源スイッチはありません。

.. NSM モジュールのポートからストレージケーブルを外します。
+
各ケーブルが接続されている NSM モジュールのポートをメモしてください。この手順の後半で NSM モジュールを再び取り付けるときに、同じポートにケーブルを再接続します。



. シェルフから NSM モジュールを取り外します。
+
.. NSM モジュールの両側にあるラッチの穴に人さし指を入れます。
+

NOTE: 下部の NSM モジュールを取り外す際に下部のレールが邪魔になってラッチに手が届きにくい場合は、（腕を交差させて）内側から穴に人さし指を入れてください。

.. ラッチ上部にあるオレンジ色のタブを親指で押し下げます。
+
ラッチが持ち上がり、シェルフのラッチピンが解除されます。

.. NSM モジュールを 3 分の 1 ほどシェルフからゆっくりと引き出し、 NSM モジュールの側面を両手で持って、平らで安定した場所に置きます。
+
NSM モジュールを引き出すと、ラッチのアームが NSM モジュールの外に引き出され、すべて引き出された位置で固定されます。



. NSM モジュールのカバーの取り付けネジを緩めてカバーを開きます。
. 障害が発生したブートメディアの物理的な場所を特定し
+
ブートメディアは、電源装置とは反対のシェルフシャーシの壁に沿って配置されています。ボード上のブートメディアスロットの横にあるブートメディア警告（黄色） LED が点灯します。

+

NOTE: シェルフから NSM モジュールを取り外したあと、 LED が 10 分間点灯したままになります。

. ブートメディアを交換します。
+
.. No.1 プラスドライバを使用して、ブートメディアの下部（ノッチ付き）をボードに固定しているネジを慎重に取り外します。
.. ノッチ付き端を少し上に回転させ、ソケットから外れるまでゆっくりと手前に引き出して、ブートメディアを取り外します。
+
ブートメディアは、親指と人差し指で端のノッチに置くことで保持できます

.. 静電気防止用バッグからブートメディアを取り出します。
.. 交換用ブートメディアが正しい向きでソケットに完全に装着されるまで、ソケットにゆっくりと押し込みます。
+
ブートメディアは、親指と人差し指で端のノッチに置くことで保持できますヒートシンクの側面が上向きになっていることを確認します。

+
正しく装着され、ブートメディアをブートすると、ネジでまだ固定されていないため、ブートメディアのノッチ付きの端がボードから斜めになります。

.. ブートメディアのノッチ付きの端を挿入してそっと押し下げ、ドライバでネジを締めてブートメディアを所定の位置に固定します。
+

NOTE: ネジはブートメディアを所定の位置に固定できるだけで締めすぎないように締めます。



. NSM モジュールのカバーを閉じ、取り付けネジを締めます。
. NSM モジュールをシェルフに再び取り付けます。
+
.. ラッチのアームがすべて引き出された位置で固定されていることを確認します。
.. NSM モジュールの重量がシェルフによって完全に支えられるまで、両手でゆっくりと NSM モジュールをシェルフにスライドさせます。
.. NSM モジュールをシェルフの奥（シェルフの背面から約 1.27cm ）に止まるまで押し込みます。
+
（ラッチのアームの）穴の手前にあるオレンジ色のタブに親指を置くと、 NSM モジュールを押し込むことができます。

.. NSM モジュールの両側にあるラッチの穴に人さし指を入れます。
+

NOTE: 下部の NSM モジュールを挿入する際に下部のレールが邪魔になってラッチに手が届きにくい場合は、（腕を交差させて）内側から穴に人さし指を入れてください。

.. ラッチ上部にあるオレンジ色のタブを親指で押し下げます。
.. ラッチが止まるまでゆっくりと押し込みます。
.. ラッチの上部から親指を離し、ラッチが完全に固定されるまで押し続けます。
+
NSM モジュールをシェルフに完全に挿入し、シェルフの端と同一平面になるようにしてください。



. NSM モジュールにケーブルを再接続します。
+
.. ストレージケーブルを同じ 2 つの NSM モジュールのポートに再接続します。
+
ケーブルは、コネクタのプルタブを上に向けて挿入します。ケーブルを正しく挿入すると、カチッという音がして所定の位置に収まります。

.. 電源装置に電源コードを再接続し、電源コード固定クリップを使用して電源コードを固定します。
+
電源装置が正常に動作している場合は、 LED が緑色に点灯します。

+
また、両方の NSM モジュールのポートの LNK （緑） LED が点灯します。LNK LED が点灯しない場合は、ケーブルを取り付け直します。



. 障害が発生したブートメディアを搭載した NSM モジュールおよびシェルフのオペレータ用ディスプレイパネルにある警告（黄色） LED が点灯していないことを確認します。
+
警告 LED が消灯するまで 5 ~ 10 分かかることがあります。NSM モジュールをリブートし、ブートメディアイメージのコピーが完了するまでにかかる時間です。

+
障害 LED が点灯したままの場合は、ブートメディアが正しく装着されていないか、別の問題がある可能性があるため、テクニカルサポートにお問い合わせください。

. Active IQ Config Advisor を実行して、 NSM モジュールが正しくケーブル接続されていることを確認します。
+
ケーブル接続エラーが発生した場合は、表示される対処方法に従ってください。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"^]


