---
permalink: ns224/service-replace-power-supply.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, fail, power, supply, nondisruptive, drive, i/o, progress, hot-swap, hot-swap a power supply 
summary: 電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中には、障害が発生した電源装置を無停止で交換できます。 
---
= 電源装置のホットスワップ - NS224 シェルフ
:icons: font
:imagesdir: ../media/


[role="lead"]
電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中には、障害が発生した電源装置を無停止で交換できます。

.このタスクについて
* 複数の電源装置を交換する場合は、シェルフの電源を維持するために、一度に 1 つずつ交換する必要があります。
* * ベストプラクティス： * NSM モジュールを取り外してから 2 分以内に電源装置を交換することを推奨します。
+
2 分を超えてもシェルフは機能しますが、電源装置が交換されるまでデグレード状態の電源装置に関するメッセージが ONTAP からコンソールに送信されます。

* * ベストプラクティス： FRU コンポーネントを交換する前に、お使いのシステムの NVMe シェルフモジュール（ NSM ）ファームウェアとドライブファームウェアを最新バージョンにしておくことを推奨します。
+
[NOTE]
====
ファームウェアをシェルフおよびそのコンポーネントに対応しないバージョンにリバートしないでください。

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"^]

====
* 影響を受けるシェルフの物理的な位置を特定するために、必要に応じてシェルフのロケーション（青色の） LED を点灯できます。「 storage shelf location -led modify -shelf-name _shelf_name _led-status on
+
該当するシェルフの「 shelf_name 」がわからない場合は、「 storage shelf show 」コマンドを実行します。

+
シェルフにはロケーション LED が 3 つあります。オペレータ用ディスプレイパネルに 1 つと、各 NSM モジュールに 1 つずつです。ロケーション LED は 30 分間点灯します。点灯を中止するには、同じコマンドを off オプションに変更して入力します。

* 交換用電源装置を開封したら、障害が発生した電源装置を返送するときのために、梱包材はすべて保管しておいてください。
+
RMA 番号を確認する場合や、交換用手順に関するその他のサポートが必要な場合は、テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]にアクセスするか、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。

* 次のビデオまたは記載された手順に従って、電源装置を交換します。
+
https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=5794da63-99aa-425a-825f-aa86002f154d["NS224 ドライブシェルフの電源装置のホットスワップ"^]



.手順
. 自身の適切な接地対策を行います
. 障害が発生した電源装置を物理的に特定します。
+
障害が発生した電源装置を示す警告メッセージがシステムコンソールに記録されます。また、シェルフのオペレータ用ディスプレイパネルの警告（黄色） LED が点灯し、障害が発生した電源装置の 2 色 LED が赤色に点灯します。

. 電源コード固定クリップを開き、電源装置から電源コードを抜きます。
+
電源装置には電源スイッチはありません。

. 障害が発生した電源装置を取り外します。
+
.. カムハンドルを開いた状態（水平位置）まで回転させ、つかみます。
.. 青色のタブを親指で押して、ロックを解除します。
.. もう一方の手で支えながら、電源装置を NSM モジュールから引き出します。


. 交換用電源装置を挿入します。
+
.. 電源装置の端を両手で支えながら、 NSM モジュールの開口部に合わせます。
.. カチッという音がしてロックが所定の位置に収まるまで、電源装置を NSM モジュールにそっと押し込みます。
+

NOTE: 力を入れすぎないように注意してください。内部コネクタが破損することがあります。

.. カムハンドルを回して閉じた位置にします。


. 電源コードを電源装置に接続し、電源コード固定クリップを使用して電源コードを固定します。
+
電源装置が正常に動作している場合は、 LED が緑色に点灯します。


