---
permalink: ns224/service-replace-drive.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, fail, replace, drive, nondisruptive, i/o, hot-swap, hot-swap a drive 
summary: 電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中は、障害が発生したドライブを無停止で交換できます。 
---
= ドライブをホットスワップします - NS224 シェルフ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中は、障害が発生したドライブを無停止で交換できます。

.作業を開始する前に
* 取り付けるドライブが NS224 シェルフでサポートされている必要があります。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

* SED 認証が有効になっている場合は、 ONTAP のドキュメントに記載されている SED の交換手順を使用する必要があります。
+
ONTAP のドキュメントには、 SED の交換前と交換後に実行する必要がある手順も記載されています。

+
https://docs.netapp.com/us-en/ontap/encryption-at-rest/index.html["CLI での NetApp Encryption の概要"^]

* システムのその他のコンポーネントがすべて正常に動作している必要があります。問題がある場合は、テクニカルサポートにお問い合わせください。
* 取り外すドライブで障害が発生していることを確認します。
+
「 storage disk show -broken 」コマンドを実行して、ドライブが障害状態であることを確認できます。障害が発生したドライブが障害ドライブのリストに表示されます。表示されない場合は、少し待ってからもう一度コマンドを実行してください。

+

NOTE: ドライブのタイプと容量によっては、障害ドライブのリストに表示されるまでに数時間かかることがあります。



.このタスクについて
* * ベストプラクティス：ドライブをホットスワップする前に、 Disk Qualification Package （ DQP ）の最新バージョンをインストールしておくことを推奨します。
+
DQP の最新バージョンをインストールしておくと、新しく認定されたドライブがシステムで認識されて使用できるようになります。これにより、ドライブの情報が最新でない場合に表示されるシステムイベントメッセージを回避できるほか、ドライブが認識されないために発生するドライブのパーティショニングを回避できます。さらに、ドライブのファームウェアが最新でない場合も、通知で知ることができます。

+
https://mysupport.netapp.com/NOW/download/tools/diskqual/["ネットアップのダウンロード： Disk Qualification Package"^]

* * ベストプラクティス： FRU コンポーネントを交換する前に、お使いのシステムの NVMe シェルフモジュール（ NSM ）ファームウェアとドライブファームウェアを最新バージョンにしておくことを推奨します。
+
[NOTE]
====
ファームウェアをシェルフおよびそのコンポーネントに対応しないバージョンにリバートしないでください。

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"^]

====
* 最新のファームウェアバージョンでない新しいドライブのドライブファームウェアは自動的に（無停止で）更新されます。
+

NOTE: ドライブファームウェアは 2 分ごとにチェックされます。

* 影響を受けるシェルフの物理的な位置を特定するために、必要に応じてシェルフのロケーション（青色の） LED を点灯できます。「 storage shelf location -led modify -shelf-name _shelf_name _led-status on
+
該当するシェルフの「 _shelf_name_ 」がわからない場合は、「 storage shelf show 」コマンドを実行します。

+
シェルフにはロケーション LED が 3 つあります。オペレータ用ディスプレイパネルに 1 つと、各 NSM モジュールに 1 つずつです。ロケーション LED は 30 分間点灯します。同じコマンドを「 off 」オプションを使用して入力すると、これらのコマンドを無効にできます。

* 交換用ドライブを開封したら、障害が発生したドライブを返送するときのために、梱包材はすべて保管しておいてください。
+
RMA 番号を確認する場合や、交換用手順に関するその他のサポートが必要な場合は、テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]にアクセスするか、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。

* 次のビデオでは、ドライブのホットスワップ手順の物理的な取り外しと取り付けの部分の概要を示します。
+
https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=733011a7-e03a-41b0-8723-aa840133bf25["NS224 ドライブシェルフ内のドライブのホットスワップ"^]



.手順
. 交換用ドライブのドライブ所有権を手動で割り当てる場合は、ドライブの自動割り当てを無効にする必要があります。
+

NOTE: シェルフ内のドライブが HA ペアの両方のコントローラモジュールで所有されている場合は、ドライブ所有権を手動で割り当てる必要があります。

+

NOTE: ドライブ所有権を手動で割り当てたあと、この手順の以降の手順で自動ドライブ割り当てを再度有効にします。

+
.. 自動ドライブ割り当てが有効になっているかどうかを確認します。「 storage disk option show
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+
自動ドライブ割り当てが有効になっている場合は、各コントローラモジュールの Auto Assign 列に on と表示されます。

.. 自動ドライブ割り当てが有効になっている場合は無効にします。「 storage disk option modify -node node_name -autoassign off
+
両方のコントローラモジュールで自動ドライブ割り当てを無効にする必要があります。



. 自身の適切な接地対策を行います
. 障害ドライブを物理的に特定します。
+
ドライブで障害が発生すると、システムコンソールに、障害が発生したドライブを示す警告メッセージが記録されます。また、ドライブシェルフのオペレータディスプレイパネルにある警告（黄色） LED と障害が発生したドライブが点灯します。

+

NOTE: 障害が発生したドライブのアクティビティ（緑） LED は点灯する（点灯）ことがあります。点灯している（点灯）はドライブに電力が供給されていることを示しますが、点滅しては I/O アクティビティを示します。障害が発生したドライブには I/O アクティビティはありません。

. 障害ドライブを取り外します。
+
.. ドライブの前面にあるリリースボタンを押して、カムハンドルを開きます。
.. カムハンドルをつかみ、ドライブをもう一方の手で支えながら、ドライブをシェルフから引き出します。


. 交換用ドライブは、 70 秒以上待ってから挿入してください。
+
これにより、ドライブが取り外されたことがシステムで認識されます。

. 交換用ドライブを挿入します。
+
.. カムハンドルを開いた状態で、両手で交換用ドライブを挿入します。
.. ドライブが停止するまで押します。
.. ドライブがミッドプレーンに完全に収まり、カチッという音がして固定されるまで、カムハンドルを閉じます。
+
カムハンドルは、ドライブの前面に揃うようにゆっくりと閉じてください。



. ドライブのアクティビティ（緑） LED が点灯していることを確認します。
+
ドライブのアクティビティ LED が点灯している場合は、ドライブに電力が供給されています。ドライブのアクティビティ LED が点滅しているときは、ドライブに電力が供給されていて、 I/O が実行中です。ドライブファームウェアが自動的に更新されている場合は、 LED が点滅します。

. 別のドライブを交換する場合は、手順 3~7 を繰り返します。
. 手順 1 で自動ドライブ割り当てを無効にした場合は、ドライブ所有権を手動で割り当ててから、必要に応じて自動ドライブ割り当てを再度有効にします。
+
.. 所有権が未設定のドライブをすべて表示します。「 storage disk show -container-type unassigned 」
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

.. 各ドライブを割り当てます。「 storage disk assign -disk disk_name -owner owner_name 」
+
このコマンドは、どちらのコントローラモジュールでも入力できます。

+
ワイルドカード文字を使用すると、一度に複数のドライブを割り当てることができます。

.. 必要に応じて自動ドライブ割り当てを再度有効にします。「 storage disk option modify -node node_name -autoassign on 」
+
両方のコントローラモジュールで自動ドライブ割り当てを再度有効にする必要があります。




