---
permalink: ns224/service-replace-dimm.html 
sidebar: sidebar 
keywords: ns224, shelves, shelf, ns224 shelves, replace, nondisruptive, dimm, i/o, replace a dimm 
summary: 電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中は、障害が発生した DIMM を無停止で交換できます。 
---
= DIMM-NS224 シェルフを交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
電源がオンになっている NS224 ドライブシェルフおよび I/O の実行中は、障害が発生した DIMM を無停止で交換できます。

.作業を開始する前に
* 障害が発生した FRU （ターゲット NSM モジュール）を搭載した NSM モジュールを取り外す際にシェルフが接続を維持できるように、シェルフのパートナー NSM モジュールが稼働し、正しくケーブル接続されている必要があります。
+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"^]

* 他の 3 つの DIMM を含め、システム内のその他すべてのコンポーネントが正常に動作している必要があります。


.このタスクについて
* NVMe シェルフモジュール（ NSM ）を取り外したあと、少なくとも 70 秒待ってから取り付けるようにしてください。
+
これにより、 ONTAP が NSM の削除イベントを処理するのに十分な時間がかかります。

* * ベストプラクティス： FRU コンポーネントを交換する前に、お使いのシステムの NVMe シェルフモジュール（ NSM ）ファームウェアとドライブファームウェアを最新バージョンにしておくことを推奨します。
+
[NOTE]
====
ファームウェアをシェルフおよびそのコンポーネントに対応しないバージョンにリバートしないでください。

https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["ネットアップのダウンロード：ディスクシェルフファームウェア"^]

https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["ネットアップのダウンロード：ディスクドライブファームウェア"^]

====
* 影響を受けるシェルフの物理的な位置を特定するために、必要に応じてシェルフのロケーション（青色の） LED を点灯できます。「 storage shelf location -led modify -shelf-name _shelf_name _led-status on
+
該当するシェルフの「 _shelf_name_ 」がわからない場合は、「 storage shelf show 」コマンドを実行します。

+
シェルフにはロケーション LED が 3 つあります。オペレータ用ディスプレイパネルに 1 つと、各 NSM モジュールに 1 つずつです。ロケーション LED は 30 分間点灯します。同じコマンドを「 off 」オプションを使用して入力すると、これらのコマンドを無効にできます。

* 交換用 DIMM を開封したら、障害が発生した DIMM を返送するときのために、すべての梱包材を保管しておいてください。
+
RMA 番号を確認する場合や、交換用手順に関するその他のサポートが必要な場合は、テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"^]にアクセスするか、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。

* 次のビデオまたは記載された手順に従って、 DIMM を交換します。
+
https://netapp.hosted.panopto.com/Panopto/Pages/embed.aspx?id=eef28b10-ed93-4aa7-bfce-aa86002f20a2["NS224 ドライブシェルフの DIMM の交換"^]



.手順
. 自身の適切な接地対策を行います
. 交換する FRU が搭載されている NSM モジュールからケーブルを外します。
+
.. 電源コード固定クリップを開き、電源装置から電源コードを抜きます。
+
電源装置には電源スイッチはありません。

.. NSM モジュールのポートからストレージケーブルを外します。
+
各ケーブルが接続されている NSM モジュールのポートをメモしてください。この手順の後半で NSM モジュールを再び取り付けるときに、同じポートにケーブルを再接続します。



. シェルフから NSM モジュールを取り外します。
+
.. NSM モジュールの両側にあるラッチの穴に人さし指を入れます。
+

NOTE: 下部の NSM モジュールを取り外す際に下部のレールが邪魔になってラッチに手が届きにくい場合は、（腕を交差させて）内側から穴に人さし指を入れてください。

.. ラッチ上部にあるオレンジ色のタブを親指で押し下げます。
+
ラッチが持ち上がり、シェルフのラッチピンが解除されます。

.. NSM モジュールを 3 分の 1 ほどシェルフからゆっくりと引き出し、 NSM モジュールの側面を両手で持って、平らで安定した場所に置きます。
+
NSM モジュールを引き出すと、ラッチのアームが NSM モジュールの外に引き出され、すべて引き出された位置で固定されます。



. NSM モジュールのカバーの取り付けネジを緩めてカバーを開きます。
+
NSM モジュールカバーの FRU ラベルには、 NSM モジュールの中央にある、ヒートシンクの両側にある 4 つの DIMM の位置が示されています。

. 障害のある DIMM を物理的に特定します。
+
DIMM に障害が発生すると、システムコンソールに、障害が発生した DIMM を示す警告メッセージが記録されます。また、ボード上の DIMM スロットの横にある DIMM 警告（黄色） LED が点灯します。

+

NOTE: 障害のある DIMM の LED は、シェルフから NSM モジュールを取り外したあと 10 分間点灯したままになります。

. 障害のある DIMM を交換します。
+
.. 交換用 DIMM を同じ向きで挿入できるように、スロット内の DIMM の向きをメモします。
.. DIMM スロットの両端にあるツメをゆっくり押し開いて DIMM をスロットから外し、そのまま持ち上げてスロットから取り出します。
+

NOTE: DIMM 回路基板のコンポーネントに力が加わらないように、 DIMM の両端を慎重に持ちます。

+
イジェクタタブは開いたままです。

.. 交換用 DIMM を静電気防止用の梱包バッグから取り出します。
.. DIMM の両端を持ち、スロットに DIMM を垂直に挿入します。
+
DIMM の下部のピンの間にある切り欠きを、スロットの突起と揃える必要があります。

+
DIMM をスロットに正しく挿入するにはある程度の力が必要です。DIMM が正しく挿入されていない場合は、再度取り付けます

.. DIMM の両端のノッチにツメがかかるまで、 DIMM の上部を慎重にしっかり押し込みます。


. NSM モジュールのカバーを閉じ、取り付けネジを締めます。
. NSM モジュールをシェルフに再び取り付けます。
+
.. ラッチのアームがすべて引き出された位置で固定されていることを確認します。
.. NSM モジュールの重量がシェルフによって完全に支えられるまで、両手でゆっくりと NSM モジュールをシェルフにスライドさせます。
.. NSM モジュールをシェルフの奥（シェルフの背面から約 1.27cm ）に止まるまで押し込みます。
+
（ラッチのアームの）穴の手前にあるオレンジ色のタブに親指を置くと、 NSM モジュールを押し込むことができます。

.. NSM モジュールの両側にあるラッチの穴に人さし指を入れます。
+

NOTE: 下部の NSM モジュールを挿入する際に下部のレールが邪魔になってラッチに手が届きにくい場合は、（腕を交差させて）内側から穴に人さし指を入れてください。

.. ラッチ上部にあるオレンジ色のタブを親指で押し下げます。
.. ラッチが止まるまでゆっくりと押し込みます。
.. ラッチの上部から親指を離し、ラッチが完全に固定されるまで押し続けます。
+
NSM モジュールをシェルフに完全に挿入し、シェルフの端と同一平面になるようにしてください。



. NSM モジュールにケーブルを再接続します。
+
.. ストレージケーブルを同じ 2 つの NSM モジュールのポートに再接続します。
+
ケーブルは、コネクタのプルタブを上に向けて挿入します。ケーブルを正しく挿入すると、カチッという音がして所定の位置に収まります。

.. 電源装置に電源コードを再接続し、電源コード固定クリップを使用して電源コードを固定します。
+
電源装置が正常に動作している場合は、 LED が緑色に点灯します。

+
また、両方の NSM モジュールのポートの LNK （緑） LED が点灯します。LNK LED が点灯しない場合は、ケーブルを取り付け直します。



. 障害が発生した DIMM が搭載された NSM モジュールおよびシェルフのオペレータ用ディスプレイパネルにある警告（黄色） LED が点灯していないことを確認します。
+
NSM モジュールがリブートし、 DIMM 問題が検出されなくなったあとに、 NSM モジュールの警告 LED が消灯します。この処理には、 3~5 分かかることがあります。

. Active IQ Config Advisor を実行して、 NSM モジュールが正しくケーブル接続されていることを確認します。
+
ケーブル接続エラーが発生した場合は、表示される対処方法に従ってください。

+
https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ネットアップのダウンロード： Config Advisor"^]


