---
permalink: fas8300/chassis-replace-move-hardware.html 
sidebar: sidebar 
keywords: fas8300, fas8700, shut, chassis, controller, replace, remove, swap, verify, install, power, supply, metrocluster, aggregates, replacement, process, equipment, rack, ha, state, system 
summary: ファン、ハードドライブ、およびコントローラモジュールを障害のあるシャーシから新しいシャーシに移動し、装置ラックまたはシステムキャビネットの障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシと交換します。 
---
= ハードウェア - FAS8300 と FAS8700 を移動して交換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ファン、ハードドライブ、およびコントローラモジュールを障害のあるシャーシから新しいシャーシに移動し、装置ラックまたはシステムキャビネットの障害のあるシャーシを、障害のあるシャーシと同じモデルの新しいシャーシと交換します。



== 手順 1 ：コントローラモジュールを取り外す

シャーシを交換するには、古いシャーシからコントローラモジュールを取り外す必要があります。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. 電源ケーブル固定クリップを外し、電源装置からケーブルを抜きます。
. ケーブルマネジメントデバイスに接続しているケーブルをまとめているフックとループストラップを緩め、システムケーブルと SFP をコントローラモジュールから外し（必要な場合）、どのケーブルが何に接続されていたかを記録します。
+
ケーブルはケーブルマネジメントデバイスに収めたままにします。これにより、ケーブルマネジメントデバイスを取り付け直すときに、ケーブルを整理する必要がありません。

. ケーブルマネジメントデバイスをコントローラモジュールの右側と左側から取り外し、脇に置きます。
. 両方のロックラッチを押し下げ、両方のラッチを同時に下方向に回転させます。
+
コントローラモジュールがシャーシから少し引き出されます。

. コントローラモジュールをシャーシから引き出します。
+
このとき、空いている手でコントローラモジュールの底面を支えてください。

. コントローラモジュールを安全な場所に置いておきます。シャーシ内の他のコントローラモジュールについて、上記の手順を繰り返します。




== 手順 2 ：ファンを移動します

シャーシを交換するときにファンモジュールを交換用シャーシに移動するには、特定の順序でタスクを実行する必要があります。

.手順
. 接地対策がまだの場合は、自身で適切に実施します。
. （必要な場合）両手でベゼルの両側の開口部を持ち、手前に引いてシャーシフレームのボールスタッドからベゼルを外します。
. ファンモジュールのカムハンドルのリリースラッチを押し下げ、カムハンドルを下に回転させます。
+
ファンモジュールがシャーシから少し離れた場所に移動します。

. ファンモジュールをシャーシから引き出します。このとき、ファンモジュールがシャーシから落下しないように、必ず空いている手で支えてください。
+

CAUTION: ファンモジュールは奥行きがないので、シャーシから突然落下してけがをすることがないように、必ず空いている手でファンモジュールの底面を支えてください。

. ファンモジュールを脇へ置きます。
. 残りのファンモジュールに対して上記の手順を繰り返します。
. 交換用シャーシの開口部にファンモジュールを合わせ、スライドさせながらシャーシに挿入します。
. ファンモジュールのカムハンドルをしっかり押して、シャーシに完全に装着されるようにします。
+
ファンモジュールが完全に装着されると、カムハンドルが少し持ち上がります。

. カムハンドルを閉じる位置まで上げ、カムハンドルのリリースラッチがカチッという音を立ててロックされたことを確認します。
. 残りのファンモジュールに対して上記の手順を繰り返します。




== 手順 3 ：装置ラックまたはシステムキャビネット内のシャーシを交換する

交換用シャーシを設置するには、装置ラックまたはシステムキャビネットから既存のシャーシを取り外す必要があります。

.手順
. シャーシ取り付けポイントからネジを外します。
. 古いシャーシをシステムキャビネットまたは装置ラックのラックレールからスライドさせて取り出し、脇に置きます。
. 接地対策がまだの場合は、自身で適切に実施します。
. 交換用シャーシを、システムキャビネットまたは装置ラックのラックレールに沿って挿入して、装置ラックまたはシステムキャビネットに設置します。この作業は 2 人で行ってください。
. シャーシをスライドさせて装置ラックまたはシステムキャビネットに完全に挿入します。
. 古いシャーシから取り外したネジを使用して、シャーシの前面を装置ラックまたはシステムキャビネットに固定します。
. まだベゼルを取り付けていない場合は、取り付けます。




== 手順 4 ：コントローラモジュールを取り付ける

新しいシャーシにコントローラモジュールを取り付けたら、ブートする必要があります。

2 台のコントローラモジュールを同じシャーシに搭載する HA ペアでは、シャーシへの設置が完了すると同時にリブートが試行されるため、コントローラモジュールの取り付け順序が特に重要です。

.手順
. コントローラモジュールの端をシャーシの開口部に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

NOTE: 指示があるまでコントローラモジュールをシャーシに完全に挿入しないでください。

. コンソールとコントローラモジュールを再度ケーブル接続し、管理ポートを再接続します。
. コントローラモジュールの取り付けを完了します。
+
.. 電源装置に電源コードを接続し、電源ケーブルロックカラーを再度取り付けてから、電源装置を電源に接続します。
.. ロックラッチを使用し、ロックラッチが持ち上がるまで、コントローラモジュールをシャーシにしっかりと押し込みます。
+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをスライドしてシャーシに挿入する際に力を入れすぎないでください。

.. コントローラモジュールをシャーシに完全に挿入するために、ロックラッチを上に回転させ、ロックピンが外れるように傾けてコントローラをそっと奥まで押し込んだら、ロックラッチをロックされるまで下げます。
+
コントローラモジュールは、シャーシに完全に装着されるとすぐにブートを開始します。ブートプロセスを中断できるように準備しておきます。

.. ケーブルマネジメントデバイスをまだ取り付けていない場合は、取り付け直します。
.. 通常のブート・プロセスを中断し 'Ctrl+C キーを押して LOADER でブートします
+

NOTE: システムがブートメニューで停止した場合は、 LOADER でブートするオプションを選択します。

.. LOADER プロンプトで「 bye 」と入力して、 PCIe カードおよびその他のコンポーネントを再初期化します。
.. Ctrl+C キーを押して、ブート・プロセスを中断し、 LOADER プロンプトでブートします。
+
システムがブートメニューで停止した場合は、 LOADER でブートするオプションを選択します。



. 同じ手順を繰り返して、 2 台目のコントローラを新しいシャーシに取り付けます。

