---
permalink: fas8300/controller-replace-restore-system-rma.html 
sidebar: sidebar 
keywords: fas8300, fas8700, how to restore NetApp Storage Encryption, how to complete the replacement process 
summary: 'システムを完全に動作状態に戻すには、 NetApp Storage Encryption の構成をリストアし（必要な場合）、新しいコントローラのライセンスをインストールし、障害のある部品をネットアップに返却する必要があります。これについては、キットに付属する RMA 指示書を参照してください。テクニカルサポートにお問い合わせください https://mysupport.netapp.com/site/global/dashboard["ネットアップサポート"]RMA 番号を確認する場合や、交換用手順にサポートが必要な場合は、日本国内サポート用電話番号：国内フリーダイヤル 0066-33-123-265 または 0066-33-821-274 （国際フリーフォン 800-800-80-800 も使用可能）までご連絡ください。' 
---
= システムのリストアを完了します - FAS8300 および FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
システムを完全に動作状態に戻すには、 NetApp Storage Encryption の構成をリストアし（必要な場合）、新しいコントローラのライセンスをインストールし、障害のある部品をネットアップに返却する必要があります。これについては、キットに付属する RMA 指示書を参照してください。



== 手順 1 ：交換用コントローラのライセンスを ONTAP にインストールする

障害ノードが標準（ノードロック）ライセンスを必要とする ONTAP 機能を使用していた場合は、 _replacement node に新しいライセンスをインストールする必要があります。標準ライセンスを使用する機能では、クラスタ内の各ノードにその機能用のキーが必要です。

.このタスクについて
ライセンスキーをインストールするまでの間も、標準ライセンスを必要とする機能を _replacement _node から引き続き使用できます。ただし、該当する機能のライセンスがクラスタ内でその障害ノードにしかなかった場合、機能の設定を変更することはできません。

また、ライセンスされていない機能をノードで使用するとライセンス契約に違反する可能性があるため、できるだけ早く _replacement にライセンスキーをインストールする必要があります。

.作業を開始する前に
ライセンスキーは 28 文字の形式です。

ライセンスキーは 90 日間の猶予期間中にインストールする必要があります。この猶予期間を過ぎると、古いライセンスはすべて無効になります。有効なライセンスキーをインストールしたら、 24 時間以内にすべてのキーをインストールする必要があります。


NOTE: システムで最初にONTAP 9 .10.1以降を実行していた場合は、に記載されている手順を使用してください https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/Post_Motherboard_Replacement_Process_to_update_Licensing_on_a_AFF_FAS_system#Internal_Notes^["マザーボードの交換後プロセスを実行して、AFF / FASシステムのライセンスを更新"]。システムの最初のONTAPリリースが不明な場合は、を参照してくださいlink:https://hwu.netapp.com["NetApp Hardware Universe の略"^]。

.手順
. 新しいライセンスキーが必要な場合は、で交換用ライセンスキーを取得します https://mysupport.netapp.com/site/global/dashboard["ネットアップサポートサイト"] [ ソフトウェアライセンス ] の [ マイサポート ] セクションで、
+

NOTE: 必要な新しいライセンスキーが自動的に生成され、 E メールで送信されます。ライセンスキーが記載された E メールが 30 日以内に届かないは、テクニカルサポートにお問い合わせください。

. 各ライセンスキーをインストールします :+system license add-license-code license-key, license-key...+`
. 必要に応じて、古いライセンスを削除します。
+
.. 使用されていないライセンスを確認してください : 「 license clean-up-unused -simulate 」
.. リストが正しい場合は、未使用のライセンス「 license clean-up-unused 」を削除します






== 手順2：LIFを確認してシリアル番号を登録する

replacement _node を使用可能な状態に戻す前に、 LIF がホームポートにあることを確認し、 AutoSupport が有効になっている場合は _replacement _node のシリアル番号を登録して、自動ギブバックをリセットする必要があります。

.手順
. 論理インターフェイスがホームサーバとポートに報告されていることを確認します。「 network interface show -is-home false 」
+
いずれかのLIFがfalseと表示された場合は、ホームポートにリバートします。 `network interface revert -vserver * -lif *`

. システムのシリアル番号をネットアップサポートに登録します。
+
** AutoSupport が有効になっている場合は、 AutoSupport メッセージを送信してシリアル番号を登録します。
** AutoSupport が有効になっていない場合は、を呼び出します https://mysupport.netapp.com["ネットアップサポート"] をクリックしてシリアル番号を登録します。


. クラスタの健全性を確認します。詳細については、技術情報の記事を参照して https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_perform_a_cluster_health_check_with_a_script_in_ONTAP["ONTAP でスクリプトを使用してクラスタの健全性チェックを実行する方法"^] ください。
. AutoSupportのメンテナンス時間がトリガーされた場合は、を使用して終了します `system node autosupport invoke -node * -type all -message MAINT=END` コマンドを実行します
. 自動ギブバックを無効にした場合は、再度有効にします。「 storage failover modify -node local-auto-giveback true 」




== 手順 3 ： 2 ノード MetroCluster 構成でアグリゲートをスイッチバックする

このタスクでは、環境の 2 ノード MetroCluster 構成のみを実行します。

.手順
. すべてのノードの状態が「 enabled 」であることを確認します。 MetroCluster node show
+
[listing]
----
cluster_B::>  metrocluster node show

DR                           Configuration  DR
Group Cluster Node           State          Mirroring Mode
----- ------- -------------- -------------- --------- --------------------
1     cluster_A
              controller_A_1 configured     enabled   heal roots completed
      cluster_B
              controller_B_1 configured     enabled   waiting for switchback recovery
2 entries were displayed.
----
. すべての SVM で再同期が完了したことを確認します。「 MetroCluster vserver show 」
. 修復処理によって実行される LIF の自動移行が正常に完了したことを確認します。 MetroCluster check lif show
. サバイバークラスタ内の任意のノードから MetroCluster switchback コマンドを使用して、スイッチバックを実行します。
. スイッチバック処理が完了したことを確認します MetroCluster show
+
クラスタの状態が waiting-for-switchback の場合は、スイッチバック処理がまだ実行中です。

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured       	switchover
Remote: cluster_A configured       	waiting-for-switchback
----
+
クラスタが「 normal 」状態のとき、スイッチバック処理は完了しています。

+
[listing]
----
cluster_B::> metrocluster show
Cluster              Configuration State    Mode
--------------------	------------------- 	---------
 Local: cluster_B configured      		normal
Remote: cluster_A configured      		normal
----
+
スイッチバックが完了するまでに時間がかかる場合は、「 MetroCluster config-replication resync-status show 」コマンドを使用することで、進行中のベースラインのステータスを確認できます。

. SnapMirror 構成または SnapVault 構成があれば、再確立します。




== 手順 4 ：障害が発生したパーツをネットアップに返却する

障害が発生したパーツは、キットに付属のRMA指示書に従ってNetAppに返却してください。 https://mysupport.netapp.com/site/info/rma["パーツの返品と交換"]詳細については、ページを参照してください。
