---
permalink: fas8300/controller-replace-system-config-restore-and-verify.html 
sidebar: sidebar 
keywords: fas8300, fas8700, restore and verify the system configuration, verify and set the ha state of the controller module 
summary: コントローラの HA 構成がアクティブで、FAS8300 および FAS8700 ストレージシステムで正しく機能していることを確認し、システムのストレージポートにディスクへのすべてのパスがリストされていることを確認してください。 
---
= システム構成をリストアして検証します。 FAS8300 と FAS8700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
コントローラの HA 構成がアクティブで、FAS8300 および FAS8700 ストレージシステムで正しく機能していることを確認し、システムのストレージポートにディスクへのすべてのパスがリストされていることを確認してください。

システムをサービス状態に戻す前に、HA 構成設定とディスク リストを確認してください。

.手順
. メンテナンスモードでブートします。
+
`boot_ontap maint`

. 「_Continue with boot？_」と表示されたら、と入力します `y`。
+
「_System ID mismatch_warning」というメッセージが表示された場合は、と入力します `y`。

. 表示内容を入力し `sysconfig -v`てキャプチャします。
+

NOTE: personality mismatch_customer supportと表示された場合

.  `sysconfig -v`の出力で、アダプタカードの情報を交換用コントローラのカードおよび場所と比較します。
. すべてのコンポーネントが同じ状態になっていることを確認し `HA`ます。
+
`ha-config show`

+
HA 状態はすべてのコンポーネントで同じになっているはずです。

. コントローラモジュールの表示されたシステム状態がシステム構成と一致しない場合は、 `HA`コントローラーモジュールの状態:
+
`ha-config modify controller _ha-state_`

+
HAの状態には次のいずれかの値を指定できます。

+
** 「 HA 」
** 「 mcc 」
** 「 mcc-2n 」
** 「 MCCIP 」
** 「 non-ha 」


. 設定が変更されたことを確認します。
+
`ha-config show`

. アダプタがすべてのディスクへのパスをリストしていることを確認します。 `storage show disk -p`
+
問題が発生した場合は、ケーブル接続を確認し、ケーブルを抜き差しします。

. 保守モードを終了します :halt


.次の手順
FAS8300およびFAS8700システムのシステム構成を復元して検証したら、link:controller-replace-recable-reassign-disks.html["コントローラをギブバック"]する必要があります。
