---
permalink: a700s/bootmedia-replace-overview.html 
sidebar: sidebar 
keywords: aff a700s, aff, a700s, primary, boot, media, store, ontap, image, system, restore, primary, media, secondary, usb, flash, drive, replace, replace the boot media, manual, manual boot recovery 
summary: AFF A700sシステムでのブート メディアの交換について学習し、リカバリ方法を理解します。AFF A700sシステムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。 
---
= ブートメディアの交換の概要 - AFF A700s
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A700sシステムでのブート メディアの交換について学習し、リカバリ方法を理解します。プライマリ ブート メディアには、システムの起動時に使用されるONTAPブート イメージが保存されます。セカンダリ ブート メディアのONTAPイメージを使用して、または必要に応じて FAT32 にフォーマットされた USB フラッシュ ドライブから、プライマリ ブート メディア イメージを復元できます。

AFF A700sシステムは、手動のブート メディア リカバリ手順のみをサポートします。自動ブート メディア リカバリはサポートされていません。

セカンダリブートメディアに障害が発生した場合、または image.tgz ファイルがない場合は、 USB フラッシュドライブを使用してプライマリブートメディアをリストアする必要があります。ドライブは FAT32 にフォーマットされており、 image.tgz ファイルを格納できる容量のストレージが必要です。

* 交換プロセスでは、 var ファイルシステムをセカンダリブートメディアまたは USB フラッシュドライブからプライマリブートメディアにリストアします。
* 障害が発生したコンポーネントは、プロバイダから受け取った交換用 FRU コンポーネントと交換する必要があります。
* これらの手順のコマンドを正しいコントローラに適用することが重要です。
+
** impaired_controller は、メンテナンスを実行しているコントローラです。
** healthy_controller は、障害のあるコントローラの HA パートナーです。




プライマリブートメディアが取り付けられていて正常な状態でセカンダリブートメディアを交換する必要がある場合は、NetAppサポートに連絡して技術情報アーティクルを記載して https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_replace_the_secondary_boot_device_of_an_a700s["AFF A700sのセカンダリブートデバイスの交換方法"^] ください。
