---
permalink: a700s/index.html 
sidebar: sidebar 
keywords: aff A700s maintenance, maintenance, repairing A700s, repairing aff A700s, replace aff A700s components, replace aff A700s components 
summary: ASA A700sハードウェアのメンテナンス 
---
= AFF A700sハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A700sストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。



== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



== ファン

ファンによってコントローラが冷却されます。



== NVRAM バッテリ

NVRAMバッテリは、NVRAMモジュールへの電力を維持する役割を果たします。



== NVRAM

 The NVRAM module (Non-Volatile Random Access Memory) allows the controller to retain data across power cycles or system reboots.


== PCIe カード

PCIe（Peripheral Component Interconnect Express）カードは、マザーボードのPCIeスロットに接続する拡張カードです。



== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
