---
permalink: a700s/maintain-overview.html 
sidebar: sidebar 
keywords: a700s maintenance, maintenance, repairing a700s, repairing a700s, replace a700s components, replace a700s components 
summary: AFF A700sハードウェアのメンテナンス 
---
= AFF A700sハードウェアのメンテナンス
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A700sストレージシステムでは、次のコンポーネントのメンテナンス手順を実行できます。



[[boot-media]]
== ブートメディア

ブートメディアには、システムがブート時に使用するブートイメージファイルのプライマリセットとセカンダリセットが格納されています。



[[chassis]]
== シャーシ

シャーシは、コントローラ/CPUユニット、電源装置、I/Oなど、すべてのコントローラコンポーネントを収容する物理エンクロージャです。



[[controller]]
== コントローラ

コントローラは、ボード、ファームウェア、ソフトウェアで構成されます。ドライブを制御し、ONTAP機能を実装します。



[[dimm]]
== DIMM

メモリサイズが異なる場合や DIMM に障害がある場合は、 DIMM （デュアルインラインメモリモジュール）を交換する必要があります。



[[drive]]
== ドライブ

ドライブは、データの物理ストレージメディアとして使用されるデバイスです。



[[fan]]
== ファン

ファンによってコントローラが冷却されます。



[[nvram-battery]]
== NVRAM バッテリ

バッテリはコントローラに付属しており、AC電源に障害が発生した場合にバックアップ電源を供給します。



[[nvram-module]]
== NVRAMモシユウル

電源障害が発生した場合、NVRAMモジュール（不揮発性ランダムアクセスメモリ）はキャッシュデータを保持します。



[[pcie-card]]
== PCIe カード

PCIe（Peripheral Component Interconnect Express）カードは、マザーボードのPCIeスロットに接続する拡張カードです。



[[power-supply]]
== 電源装置

電源装置は、コントローラシェルフに電源の冗長性を提供します。



[[real-time-clock-battery]]
== リアルタイムクロックバッテリ

リアルタイムクロックバッテリは、電源がオフの場合にシステムの日付と時刻の情報を保持します。
